### ISSUE TITLE
Converting Kramdown::Converter::TOC output to HTML

### ISSUE THREAD

**Issue by jashank** [gettalong/kramdown#108]
I've captured a `Kramdown::Document` instance, and `@document.to_toc` works a charm from the same Document that I subsequently convert to HTML.  What I'd like, though, is a HTML-rendered version of the TOC.  What's the best way to go about doing this?

Additionally, I note that `Kramdown::Converter::Html` appears to reinvent the wheel on this conversion, and doesn't have an "ideal" utility method to convert a `Kramdown::Converter::TOC` to HTML. Is it worthwhile writing a replacement for either the current `generate_toc_tree` with a new mechanism that harvests data in the same way `Kramdown::Converter::TOC` does (and thus moving the TOC magic to be there only), or adding a utility mechanism to `Kramdown::Converter::TOC` that makes it a tad easier to manipulate, as a general solution to this problem?

**Comment by adipasquale** [comment]
👋 hello thanks @gettalong for the great lib. If anyone ends up on this issue here is my hacky code to do this:

```rb
def table_of_contents_html
  kramdown_elt_to_list_html(kramdown_doc.to_toc)
end

def kramdown_elt_to_list_html(elt)
  return nil if elt.children.empty?

  "<ol>\n#{elt.children.map { kramdown_elt_to_list_item_html(_1) }.join("\n")}\n</ol>\n"
end

def kramdown_elt_to_list_item_html(elt)
  "<li><a href='##{elt.attr[:id]}'>#{elt.value.options[:raw_text]}</a>#{kramdown_elt_to_list_html(elt)}</li>"
end
```
