### ISSUE TITLE
Not all HTML entities are supported

### ISSUE THREAD

**Issue by tomer** [gettalong/kramdown#114]
I am using Jekyll with kramdown. While redcrapt supported all the HTML entities I've used, I've found that kramdown doesn't support some of my entities, and instead is just escaping the ampersand character. 

I'm using a known [and documented](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references) entities, which should be supported. I guess that if I'll replace the entity keyword with its numerical location it will work, but it is far less readable for who will read the unparsed document. 

test.md

``` markdown

---

---
&quot; Hello World &pi; &rlm; &amp; & &quot;
```

_config.yml

``` yml
markdown: kramdown
```

result:

``` html
<p>" Hello World π &amp;rlm; &amp; &amp; "</p>
```

Expected result:

``` html
<p>" Hello World π &rlm; &amp; &amp; "</p>
```

(or replace &rlm with U+200F which I'm not really fan of…)

https://gist.github.com/tomer/9703168

**Comment by siman-man** [comment]
I think there are a lot of entities not yet supported.

* [GitHub Flavored Markdown Spec - Entity references](https://github.github.com/gfm/#entity-references)
* [CommonMark Spec - Entity references](http://spec.commonmark.org/0.27/#entity-references)

In these specifications, https://html.spec.whatwg.org/entities.json is referred to

However, `ENTITY_TABLE` defined in [entities.rb](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/utils/entities.rb)  doesn't supported many of entities compared with [that](https://html.spec.whatwg.org/entities.json).

---

For example

```ruby
require 'kramdown'

text =<<-HTML
&Abreve; &Acy; &Afr; &Amacr; &And;
HTML

puts Kramdown::Document.new(text).to_html
```

expect

```html
<p>Ă А 𝔄 Ā ⩓</p>
```

actual

```html
<p>&amp;Abreve; &amp;Acy; &amp;Afr; &amp;Amacr; &amp;And;</p>
```

**Comment by gettalong** [comment]
@siman-man All HTML4 entity references should be supported. However, I didn't find any W3C HTML5 entity reference table. The WhatWG spec you referenced doesn't seem to be official.
