### ISSUE TITLE
Enhancement request - Creating links that open in new tab/window

### ISSUE THREAD

**Issue by ApsOps** [gettalong/kramdown#122]
I feel there should be a provision to create links that open in a new tab/window.
Basically this.   `target=“_blank”` but without writing HTML code.

`<a href="http://example.com/" target="_blank">Hello, world!</a>`

**Comment by benjam1n** [comment]
Is there a easy way to make all link have target="_blank" or do I have to do manual parsing?

**Comment by gettalong** [comment]
You will need to either postprocess the resulting HTML (or adapt the HTML converter) or change the respective nodes in the AST created after parsing.

**Comment by Booligoosh** [comment]
@benjam1n 
```
---
---
// make all links open in new tab
var links = document.getElementsByTagName('a');
for (var i = 0; i < links.length; i++){
    var parser = document.createElement('a');
    parser.href = links[i].href;
    links[i].target="blank";
}
```

**Comment by Simon-Tang** [comment]
Could the `{:target="_blank"}` info be added to the documentation at https://kramdown.gettalong.org/syntax.html#links-and-images?

**Comment by gettalong** [comment]
@Simon-Tang I'm not sure what you mean. The IALs can be applied to any span element and any key-value pair can be used, so using `{:target="_blank"}` naturally works.

**Comment by jeffreysbrother** [comment]
Adding this IAL to a markdown link has the effect of breaking the syntax highlighting in Atom. Has anyone else encountered this?

**Comment by Simon-Tang** [comment]
@jeffreysbrother Looks like something that won't be resolved anytime soon with the GitHub flavoured markdown package - https://github.com/atom/language-gfm/issues/44#issuecomment-111044333 has a hack/workaround.

**Comment by jeffreysbrother** [comment]
Good to know!

Actually, I was just able resolve this (somewhat, for my limited purposes) by installing the language-markdown package and placing HTML links directly into the markdown file. Seems to work fine so far. (I'm using this in a Jekyll website, just in case anyone is curious).
