### ISSUE TITLE
Writing a Custom Converter?

### ISSUE THREAD

**Issue by brycefisher** [gettalong/kramdown#126]
My ultimate goal is to change the way Kramdown parses markdown links within Jekyll. I opened a [pull request](https://github.com/gettalong/kramdown/pull/124) that does exactly what I want, but I was told that this kind of work should go into a custom converter. 

I've spent some time googling custom kramdown converters, and I still have questions:
1. Should I extend the Karmdown parser and override the method I want to alter?
2. Does my custom converter need to become a gem?
3. To integrate with Jekyll, should I be following the directions in their documentation labeled ["User Defined Parser"](http://jekyllrb.com/docs/extras/#user-defined)?

Thanks for your help!!

**Comment by Booligoosh** [comment]
Here is how you can override Kramdown converters in Jekyll:
```yml
# _config.yml

markdown: MyCustomProcessor
```
```ruby
# _plugins/markdown.rb

class Kramdown::Converter::Html
  # You can override any function from this page:
  # https://kramdown.gettalong.org/rdoc/Kramdown/Converter/Html.html
  def convert_a(el, indent)
    # Override the code for turning links into HTML here.
  end
end

class Jekyll::Converters::Markdown::MyCustomProcessor
  def initialize(config)
    require 'kramdown'
    @config = config
  rescue LoadError
    STDERR.puts 'You are missing a library required for Markdown. Please run:'
    STDERR.puts '  $ [sudo] gem install kramdown'
    raise FatalException.new("Missing dependency: kramdown")
  end

  def convert(content)
    Kramdown::Document.new(content, {
      # Your Kramdown settings here
    }).to_html
  end
end
```
Let me know if that makes sense. I'm doing a similar thing with images to add `loading="lazy"` to `<img>` tags.

**Comment by idmyn** [comment]
For anybody else finding this in the future, I struggled getting the above solution to work but found success just adding this to a file (name doesn't matter) in `_plugins_`. No change needed to my `_config`!

```ruby
class Kramdown::Converter::Html
  # You can override any function from this page:
  # https://kramdown.gettalong.org/rdoc/Kramdown/Converter/Html.html
  def footnote_content()
    ""
  end
end
```

**Comment by Booligoosh** [comment]
Good point! Think I ended up doing that too, sorry I forgot to update here

**Comment by msangel** [comment]
It was hard and I even had to clone one of your repositories for digging.
For future readers, for those who migrate from github pages.
Plugin load disabled for github pages.  It disabled on the source level, so if you use `github-pages` as dependencies instead of `jekyll`  - it not going to work.
Also, default jekyll is not setting `post` layout as default for all posts.

**Comment by nathangibson** [comment]
I'm trying to change the footnote handling and tried what was suggested above by @idmyn in https://github.com/gettalong/kramdown/issues/126#issuecomment-811703555

But when I do that copying exactly the code from Kramdown footnote_content I get an error "uninitialized constant Kramdown::Converter::Html::Element (NameError)"

From what I can find for this error there is probably an include or require statement I need to use but I'm not sure what exactly. Here is the code. 

```
class Kramdown::Converter::Html

    # File lib/kramdown/converter/html.rb, line 487

    def footnote_content
        ol = Element.new(:ol)
        ol.attr['start'] = @footnote_start if @footnote_start != 1
        i = 0
        backlink_text = escape_html(@options[:footnote_backlink], :text)
        while i < @footnotes.length
          name, data, _, repeat = *@footnotes[i]
          li = Element.new(:li, nil, 'id' => "fn:#{name}", 'role' => 'doc-endnote')
          li.children = Marshal.load(Marshal.dump(data.children))

          para = nil
          if li.children.last.type == :p || @options[:footnote_backlink_inline]
            parent = li
            while !parent.children.empty? && ![:p, :header].include?(parent.children.last.type)
              parent = parent.children.last
            end
            para = parent.children.last
            insert_space = true
          end

          unless para
            li.children << (para = Element.new(:p))
            insert_space = false
          end

          unless @options[:footnote_backlink].empty?
            nbsp = entity_to_str(ENTITY_NBSP)
            value = sprintf(FOOTNOTE_BACKLINK_FMT, (insert_space ? nbsp : ''), name, backlink_text)
            para.children << Element.new(:raw, value)
            (1..repeat).each do |index|
              value = sprintf(FOOTNOTE_BACKLINK_FMT, nbsp, "#{name}:#{index}",
                              "#{backlink_text}<sup>#{index + 1}</sup>")
              para.children << Element.new(:raw, value)
            end
          end

          ol.children << Element.new(:raw, convert(li, 4))
          i += 1
        end
        if ol.children.empty?
          ''
        else
          format_as_indented_block_html('div', {class: "footnotes", role: "doc-endnotes"}, convert(ol, 2), 0)
        end
    end
end
```

**Comment by gettalong** [comment]
@nathangibson The `Element` class lives here `Kramdown::Element` and needs to be required using `require 'kramdown/element'`. So try using `Kramdown::Element` instead of just `Element`.

**Comment by nathangibson** [comment]
@gettalong Thanks! I replaced all instances of `Element` in my file with `Kramdown::Element` and added `require 'kramdown/element'`. I no longer get the error.
