### ISSUE TITLE
Pipes inside image alt text lead to unwanted table output

### ISSUE THREAD

**Issue by kleinfreund** [gettalong/kramdown#135]
The following...

```
![What | is | wrong](/img.jpg)
```

outputs this:

```
<table>
  <tbody>
    <tr>
      <td>![What</td>
      <td>is</td>
      <td>wrong](/img.jpg)</td>
    </tr>
  </tbody>
</table>
```

This is unexpected. Inside an image alt text/link text shouldn't be any markup.

**Comment by gettalong** [comment]
@whuwangyong See https://github.com/gettalong/kramdown/issues/431#issuecomment-1086223572
