### ISSUE TITLE
Center text in kramdown

### ISSUE THREAD

**Issue by TheChymera** [gettalong/kramdown#145]
hi, some markdown flavour I used before moving to kramdown (I think rdiscount) had a really nice and handy centering feature where you could use 

``` markdown
-> text <-
```

 to center text. Is there any chance of having this in kramdown as well?

**Comment by aug-riedinger** [comment]
I would be in favor of adding the 
```
-> text <-
```
feature. Why not making the language more powerful after all?

**Comment by gettalong** [comment]
Changing the parser in this way would not be backwards-compatible and therefore isn't done.

It also seems to be a rather specific, one-of-a-kind syntax. And using an ALD together with IALs is not really much more to write:

~~~
{:center: style="text-align: center"}

text
{:center}
~~~

This gives you:

~~~ html
<p style="text-align: center">text</p>
~~~

The ALD needs to be defined only once and can then be used everywhere.

**Comment by aug-riedinger** [comment]
I understand the backward compatibility thing. I did not know about the ALD thing either. 

I would support the `-> text <-` syntax, not to write the shortest code possible, but to stick to the markdown philosophy which is to write inline code being graphically as readable as possible for:
1. everyone's readability 
2. non-developpers to not-being afraid of editing/creating those files themselves

The ALD thing could be considered as readable, but isn't as simple to use as `-> text <-`. And I really think that's what makes Markdown language so great. If it were only for developpers, we could definitely write html.

I am not a kramdown contributor so obviously I can't influence more than that to the final decision, but those were my final 2 cents.

**Comment by gettalong** [comment]
@aug-riedinger Markdown was built using markup that was already commonly used, for example in text e-mail messages. Gruber explicitly stated that for more complex or one-off tasks one has to fall back to HTML. kramdown added markup for some very *commonly* used constructs.

I would argue that for such a very specific task it would not be good to add a separate markup:

1. First: A person who has never seen it could easily misinterpret it as "highlight this part", and not as center that part.

2. Next: What if I want to center a heading/blockquote and not a paragraph?

3. Third: How would this construct handle a paragraph spanning multiple lines?

4. And: What about the problem with the image @TheChymera pointed out?

All the above can easily and recognizably be handled the way I pointed out. Additionally, the markup to center is defined by the user and not the HTML converter, so it can easily be changed by the user. How would this be done with the new syntax?

Everyone can contribute to kramdown and with your comments on this issue you already have - thank you! However, sometimes I have to decide against the wishes of someone.

ps. Another reason for not adding many new markup syntax extensions is that each and every extension slows done the parser, even if the markup is not used 99.99% percent of the time. So I'm very careful in this regard.

**Comment by aug-riedinger** [comment]
Got it.

Interesting to think that there is no perfect Markdown implementation but an implementation for the need of each user. Maybe the *best* markdown implementation would be a modular one, where each user can select the features he would like to include, depending on his constraints (speed, readability, feature-completeness etc.)

In my case, I'm using Kramdown for a jekyll blog, which means performance is not a concern, but I would like all my collaborators to be able to create a new `post.md` file so they can customize it as much as possible before any technical intervention.

**Comment by kpym** [comment]
I agree with two things : 
- Text alignment (left, right, center, justify) is very useful thing. You can check almost any wysywig editor have next to bold and italic the text alignment.
- This should be done in a backward compatible way.

My proposition is to do 
- `{:<}` = left align (default ?)
- `{:>}` = right align
- `{:><}` = center align
- `{:<>}` = justify (default ?)

So `{:>}` is just a shortcut to `{: style="text-align: right"}` for paragraphs, but it could be a shortcut to `{: style="float:right"}` for other block elements or for images.

The question is how to implements `{:><}`? May be for most of the bloack elements `{: style="text-align: center"}` will be ok, but for images one possibility is to make it equal to `{: style="display:block; margin-left:auto; margin-right: auto;"}`.

As we can see it is not obvious what should be the interpretation of some of this alignments in some situations, but this is not a reason to not implement them in the obvious cases and to try to make them work in a more consistent as possible way in other situations.

NOTES: 
- We can't define this shortcuts now by `{:><: style="text-align: center"}`.
- These shortcuts are very close to what [textile](http://redcloth.org/hobix.com/textile/quick.html) use.
- There is a shortcut for id (`{:#id}`) and class (`{: .class}`), but in a strange way, there is no shortcut for style. May be `{:{text-align: center}}` could be a shortcut for `{: style="text-align: center"}` ?

**Comment by gettalong** [comment]
I think that it would be better to let the user decide how to center his blocks. He could mark blocks with a special IAL like `{:center}` and define it like he wants, for example `{:center: style="text-align: center"}`.

**Comment by mkamensky** [comment]
One point in favour of the alignment syntax is that it is neutral with respect to the output language. The IAL solution works only for html, as far as I understand

**Comment by gettalong** [comment]
@mkamensky The IAL could also be used by other converters, it currently just isn't.
