### ISSUE TITLE
Table syntax

### ISSUE THREAD

**Issue by tgherzog** [gettalong/kramdown#151]
Is it possible to make the recognized table syntax a bit more stringent? I was very surprised when Kramdown interpreted this as two embedded tables.

```
* Home page: [old](old-homepage.png) | [new](http://data.worldbank.org)
* [Local country pages](local.html)
* [Data catalog improvements](http://datacatalog.worldbank.org)
* Topic pages: [old](http://data.worldbank.org/topic/education) | [new](education-topic.png)
```

I personally prefer Markdown Extra's approach, which I believe requires a header declaration. Perhaps that could be a configuration option.

**Comment by azu** [comment]
[GitHub Pages only support](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0) kramdown.
I'v met this issue again...

**Comment by mzlogin** [comment]
+1, this puzzling me after GitHub Pages only support kramdown.

**Comment by IanMitchell** [comment]
I also ran into this with a `[Link | Text](...)` link in a post. Isn't this a bug rather than a syntax change / new option? I wouldn't expect Kramdown to parse that as a table and warp the entire paragraph

**Comment by gettalong** [comment]
It seems to be a bug but it is actually a very bad decision on my part... I should have never allowed tables without leading pipe characters...

**Comment by IanMitchell** [comment]
Is this maybe related to #323 - perhaps just disable additional parsing in links? That'd probably be a bigger change than a bugfix though, and I'm not sure how spec compliant it'd be

**Comment by gettalong** [comment]
@IanMitchell No, #323 is not related.

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1
