### ISSUE TITLE
Suggestions for `<span>` and `<div>` markup (2.0.0): double guillemets?

### ISSUE THREAD

**Issue by Vaguery** [gettalong/kramdown#160]
[fixed to reverse stupid span/block mistake in example]

For some time I've been using a modified preprocessor to insert `<span>` and `<div>` markup before passing the results on to kramdown, mainly so I can apply the kramdown tag and id `{}` more accurately.

The syntax I've been using in my preprocessing step is 2x single and double guillemets

```
««This is a _div_ ‹‹with a `span` inside it.››»»
```

Which renders to

```
<div>This is a _div_ <span>with a `span` inside it.</span></div>
```

(which my preprocessing step passes on to kramdown)

I'm wondering if you have plans for kramdown 2.0.0 markup covering `span` and `div` besides pure html, and if so whether this syntax might be appropriate. On the US keyboard, `«»` are`opt-\` and `opt-shift-\` respectively, and `‹›` are `opt-shift-3` and `opt-shift-4`, respectively.

I also don't really know whether these are as readily available on other international keyboards.

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1

**Comment by gettalong** [comment]
General block (`div`) and span syntax is available with the spiritual successor of kramdown: https://github.com/gettalong/versadok
