### ISSUE TITLE
Colon in Attributes List Definitions needed?

### ISSUE THREAD

**Issue by mb21** [gettalong/kramdown#176]
In an effort to expand on CommonMark, we've [discussed generic attributes](http://talk.commonmark.org/t/consistent-attribute-syntax/272/) and I've come up with a proposal for an [extended spec](http://mb21.github.io/stmd/spec.html#attributes). Any feedback is welcome.

Kramdown [supports attributes](http://kramdown.gettalong.org/syntax.html#attribute-list-definitions) on a lot of elements with `{: key=val}` and I understand that the colon is needed when declaring and using a set of attributes separately. However, it isn't when you don't use references. So I was wondering whether you would consider making the colon (`:`) optional in order to make the `{key=val}` syntax universal across Kramdown, [Pandoc](http://johnmacfarlane.net/pandoc/README.html#extension-header_attributes) and [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/#spe-attr).

**Comment by shicks** [comment]
Is it possible to reconsider this?  This is an important incompatibility between Kramdown and several other Markdown engines, and if there were a consensus then CommonMark could possibly make progress on actually standardizing it.

**Comment by shicks** [comment]
Note also that it's not just the colon that's different - it's the placement as well.  Kramdown expects the IAL to precede the element it affects, whereas Pandoc, HoExtDown, and Markdown Extra expect their attribute lists to follow the heading/code block.

**Comment by gettalong** [comment]
@shicks IALs in kramdown can be placed before *and* after a block level element.
