### ISSUE TITLE
Creating <span> instead of <code>?

### ISSUE THREAD

**Issue by dg-ratiodata** [gettalong/kramdown#182]
Why are you generating a `<code>`-element instead of a `<span>` element [here](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/html.rb#L261)?

**Comment by gettalong** [comment]
I have updated the documentation to include information on how to implement syntax highlighters.

**Comment by dg-ratiodata** [comment]
Thank you. :+1:
