### ISSUE TITLE
Docs should better explain inline option use

### ISSUE THREAD

**Issue by Vaguery** [gettalong/kramdown#190]
I'd like to see a big, highlighted introduction on almost every page of the [documentation site](http://kramdown.gettalong.org) that explains how to set kramdown options _within the document_, not just as a quick mention as the very last thing in the very last section of [this](http://kramdown.gettalong.org/quickref.html#extensions).

At least five or six times in the years I've been working with kramdown, either I or a colleague has tried to Google something like "how do I set coderay options from within a kramdown document?" and failed.

The docs are excellent in general, but this _very important and useful_ thing is awful to try to find. It's easy to find out how to set them programmatically; just nearly impossible to find them for inline control.

If the site's repo is online, I would be happy to revise them and send a pull request.

**Comment by gettalong** [comment]
I updated the documentation on the options page to show how options can be set in different ways. Will go online with the next release.

**Comment by Vaguery** [comment]
Thank you! Didn't realize I'd let this slip.

**Comment by gettalong** [comment]
No problem :)
