### ISSUE TITLE
Option to add IDs to the TOC entries

### ISSUE THREAD

**Issue by cirosantilli** [gettalong/kramdown#195]
Input:

```md
-a 
{:toc}

# h1
## h2
```

Desired TOC:

```
ul
    li
        a href='#h1' id='toc-h1'
        ul
             li
                 a href='#h2' id='toc-h2'
```

The new feature would be adding the `id` on the anchors.

Application: I want to add a link next to each header back to it's TOC entry.

Users can of course hit the `Home` key to go back up. But you often want to go back to the current header to see what is going on around it, and when you have many headers it is difficult to find it.

This would be uber awesome together with: https://github.com/gettalong/kramdown/issues/188 , and maybe a way to automatically generate the links up.

**Comment by gettalong** [comment]
Adding the ID to the HTML `<a>` elements should be no problem, will do this.

**Comment by gettalong** [comment]
This is now implemented!

**Comment by cirosantilli** [comment]
Yay, thanks!
