### ISSUE TITLE
"The encoding of the source text is not valid!"

### ISSUE THREAD

**Issue by shevegen** [gettalong/kramdown#196]
:89:in `adapt_source': The encoding of the source text is not valid! (RuntimeError)

Could this error become more explicit?

My file is US-ASCII. Can Kramdown also tell what encoding would be valid, or at least also tell me the specific encoding in case such an error arises? The current error message is not ideal, it does not tell me what to do when I encounter such an error or how to proceed, and I don't feel confident enough to dig into the Kramdown source.

Thanks.

**Comment by darthschmoo** [comment]
I just bumped into this, and was led here by the Googles.  I reopened it as a UTF8 file and saved it, which fixed everything.  But before I did, I ran `file` on it and got:

book/chapter0011.markdown: Non-ISO extended-ASCII English text, with very long lines, with CRLF line terminators

I don't know if that helps at all.  Would it be a good idea for kramdown to just silently convert in these instances?

**Comment by gettalong** [comment]
The problem with silently converting is that we don't know the source encoding. Ruby takes the encoding it uses for input from the system. So when the system encoding is, e.g. ISO-8859-1, it assumes that all input is in this encoding. If it is not, Ruby has no built-in way of determining the encoding and interpreting the bytes correctly as characters.

**Comment by gettalong** [comment]
The new error message would be "The source text contains invalid characters for the used encoding US-ASCII" - is this more helpful?

So I can print the encoding that Ruby assumes the source text is in but I cannot print what would be a valid encoding.

**Comment by darthschmoo** [comment]
I like it!  I suppose with UTF-8 as common as it is, you might suggest it as a possible alternative.  But whatever.  This message will definitely get people looking in the right direction.

**Comment by gettalong** [comment]
I think that suggesting an alternative that might also not work is not so a good idea.

But thank you for the feedback!
