### ISSUE TITLE
Add an option to support CommonMark or support it by default

### ISSUE THREAD

**Issue by cirosantilli** [gettalong/kramdown#197]
You can check incompatibilities with:

```
./test/spec_tests.py --program kramdown
```

The problem is that now their normalization is broken so too many tests fail, so I'll keep a list of actual discrepancies here until the normalization gets fixed:
- invalid entity not converted to `U+FFFD` https://github.com/jgm/CommonMark/blob/b28c97c9b8af266d4f12deb5febcf28807d9f5c6/spec.txt#L4080

**Comment by cup** [comment]
For anyone using GitHub Pages, you can simply add this to `_config.yml`:

~~~
markdown: CommonMarkGhPages
~~~

you dont even have to declare the plugin in `_config.yml` as its activated by
default:

http://github.com/github/pages-gem/blob/fb5c3f2/lib/github-pages/plugins.rb#L9

reference:

http://github.com/github/jekyll-commonmark-ghpages

**Comment by cup** [comment]
https://github.com/gettalong/kramdown/issues/197
https://github.com/github/pages-gem/issues/605
https://github.com/jekyll/jekyll/issues/7417
