### ISSUE TITLE
Allow images without alt attribute

### ISSUE THREAD

**Issue by winniehell** [gettalong/kramdown#198]
Current behavior for images with missing alt attribute is:
<pre>
$ kramdown -ihtml -okramdown &lt;&lt;&lt;'&lt;img src=""/>'
/var/lib/gems/1.9.1/gems/kramdown-1.5.0/lib/kramdown/converter/kramdown.rb:289:in `convert_img': undefined method `gsub' for nil:NilClass (NoMethodError)
	from /var/lib/gems/1.9.1/gems/kramdown-1.5.0/lib/kramdown/converter/kramdown.rb:32:in `convert'
	from /var/lib/gems/1.9.1/gems/kramdown-1.5.0/lib/kramdown/converter/kramdown.rb:59:in `block in inner'
	from /var/lib/gems/1.9.1/gems/kramdown-1.5.0/lib/kramdown/converter/kramdown.rb:52:in `each'
	from /var/lib/gems/1.9.1/gems/kramdown-1.5.0/lib/kramdown/converter/kramdown.rb:52:in `each_with_index'
	from /var/lib/gems/1.9.1/gems/kramdown-1.5.0/lib/kramdown/converter/kramdown.rb:52:in `inner'
	from /var/lib/gems/1.9.1/gems/kramdown-1.5.0/lib/kramdown/converter/kramdown.rb:361:in `convert_root'
	from /var/lib/gems/1.9.1/gems/kramdown-1.5.0/lib/kramdown/converter/kramdown.rb:32:in `convert'
	from /var/lib/gems/1.9.1/gems/kramdown-1.5.0/lib/kramdown/converter/base.rb:104:in `convert'
	from /var/lib/gems/1.9.1/gems/kramdown-1.5.0/lib/kramdown/document.rb:120:in `method_missing'
	from /var/lib/gems/1.9.1/gems/kramdown-1.5.0/bin/kramdown:61:in `block in <top (required)>'
	from /var/lib/gems/1.9.1/gems/kramdown-1.5.0/bin/kramdown:61:in `each'
	from /var/lib/gems/1.9.1/gems/kramdown-1.5.0/bin/kramdown:61:in `<top (required)>'
	from /usr/local/bin/kramdown:23:in `load'
	from /usr/local/bin/kramdown:23:in `<main>'
</pre>
whereas
<pre>
$ kramdown -ihtml -okramdown &lt;&lt;&lt;'&lt;img src="" alt=""/>'
![]()
</pre>
works perfectly fine.

Please consider treating missing alt attributes as empty.

**Comment by gettalong** [comment]
Fixed this.

**Comment by winniehell** [comment]
Thank you! :+1:
