### ISSUE TITLE
Remove trailing spaces in paragraph text

### ISSUE THREAD

**Issue by winniehell** [gettalong/kramdown#200]
The [syntax definition](http://kramdown.gettalong.org/syntax.html#paragraphs) claims that
> Leading and trailing spaces will be stripped from the paragraph text.

However this seems not to be the case:
```
$ kramdown <<< 'foo    '
<p>foo    </p>
```

**Comment by gettalong** [comment]
Fixed it!

**Comment by winniehell** [comment]
Awesome! :+1:
