### ISSUE TITLE
Detect duplicate HTML attributes

### ISSUE THREAD

**Issue by winniehell** [gettalong/kramdown#201]
Current behavior is that duplicate attributes in HTML tags overwrite previous values:
```
$ kramdown -ihtml -okramdown <<<'<a href="a" href="b">c</a>'
[c](b)
$ kramdown -ihtml -okramdown <<<'<img src="a" src="b" alt="c" alt="d"/>'
![d](b)
```

I would at least expect a warning in such a case.

**Comment by gettalong** [comment]
When an HTML attribute is overwritten, a warning will now be generated.
