### ISSUE TITLE
Support entity conversion for HTML input

### ISSUE THREAD

**Issue by winniehell** [gettalong/kramdown#202]
The flag `--entity-output` seems to have no effect for HTML input:
```
$ kramdown -ihtml -okramdown --entity-output ':as_char' <<<'&quot;'
&quot; 
$ kramdown -ihtml -ohtml --entity-output ':as_char' <<<'&quot;'
&quot;
```
whereas it works as expected for Markdown input:
```
$ kramdown -ikramdown -okramdown --entity-output ':as_char' <<<'&quot;'
"
$ kramdown -ikramdown -ohtml --entity-output ':as_char' <<<'&quot;'
<p>"</p>
```

**Comment by gettalong** [comment]
The HTML parser expects to be parsing one or more top level HTML elements, so if you change `&quot;` to `<p>&quot;</p>` you will get the correct output.

**Comment by winniehell** [comment]
I see, thank you for the clarification. :mortar_board:
