### ISSUE TITLE
Can't seem to apply an IAL to a code block in kramdown

### ISSUE THREAD

**Issue by maxim** [gettalong/kramdown#207]
When doing something like this, the class wouldn't appear on the resulting `<pre>`.

    ~~~ruby
    …code…
    ~~~
    {:.foo}

**Comment by gettalong** [comment]
I think this should work, have you tried the latest version of kramdown?

**Comment by maxim** [comment]
I was surprised myself. I'm on 1.5.0, and the class just stays "highlight", no additional class appears. Here's a pic, disregard the text, it's horse ebooks ipsum.

![kramdown-pre-bug](https://cloud.githubusercontent.com/assets/7758/5895551/fab2d826-a4f0-11e4-9288-23908ce95dc3.png)

**Comment by gettalong** [comment]
Which options are you using?

When I run your example through the `kramdown --syntax-highlighter nil`, I get the following result:

~~~ html
<pre class="foo"><code class="language-ruby">…code…
</code></pre>
~~~

**Comment by gettalong** [comment]
I'm sorry but I still can't reproduce the problem.

Please provide a working example that shows the problem and I will re-open this issue.
