### ISSUE TITLE
Alternate {:footnotes} behavior

### ISSUE THREAD

**Issue by Tuckie** [gettalong/kramdown#208]
I'm currently working with some long form markdown, and I was wondering if it would be possible to have an option for alternate `{:footnotes}` behavior (originally introduced [here](https://github.com/gettalong/kramdown/commit/8efa9c30c45014442970d5976dd0e0005682edf3))?

What I would like is `{:footnotes}` (on a list, of course) to display the footnotes thus far, and reset all footnote variables.  This would allow one to place footnotes for a section / chapter of the text, rather than having them so far removed from the original material.

**Comment by gettalong** [comment]
I don't think that this is easily possible with the current code - I will have a look at it.

What you could do is split the document into several standalone documents, render them and then concatenate the result together.

**Comment by Tuckie** [comment]
Thank you for taking a look! 

I'm currently using this with [middleman](https://middlemanapp.com/), so I hope we can come up with a way that doesn't require custom render helpers for every page.

**Comment by Tuckie** [comment]
I was thinking about how to tackle this after looking through the code... 

I believe that the main issue would be determining how to group footnotes before we know how the {:footnote} sections break the footnotes up.  I would suggest pushing the @footnote* variables into a corresponding array every time we encounter a new {:footnote}. Then we just iterate through the array(s) to insert each footnote section during `convert_root`.

The other issue that jumps out would searching through the other sections to resolve name (ID) conflicts (but I imagine we would do this the same way we increment headers)

**Comment by gettalong** [comment]
I'm open for a pull request!

Yes, every time a list with `{:footnotes}` is encountered, its location needs to be stored and all footnotes encountered so far associated with it. Footnote numbering would be continuous, though.

Also, entries after the last list with `{:footnotes}` must not be forgotten and should probably be added to the last footnotes location.

**Comment by Tuckie** [comment]
Valid point on the ending footnotes.  I'll probably tackle this in the next month.

**Comment by larissa** [comment]
@Tuckie are you still working on this? I'd like to give it a go.

**Comment by Tuckie** [comment]
@larissa I have not yet had a chance to start.  Thank you for checking!

**Comment by arthurattwell** [comment]
+1 This would be a very useful feature.

I use Jekyll to generate book content for print/web/epub, and with all footnotes gathered in one place, I can't use markdown footnotes for footnotes that should appear on the same page as the footnote reference.

This enhancement would let me use `{:footnotes}` to place and float footnotes on a particular page. 

A simpler alternative for my use case might be a kramdown option that creates a footnote list element wherever footnote text appears in the markdown, rather than collecting them at the end of the document.

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1
