### ISSUE TITLE
Embedding codeblocks in lists

### ISSUE THREAD

**Issue by wooboxsam** [gettalong/kramdown#209]
In the documentation it states that you have to indent code 1 tab or 4 spaces.

But it gets really hairy in lists. In fact, it takes exactly 1 tab and 2 spaces extra for it to work. Take the following examples:

	- list item
	- another listitem
		- 
			  2tabs2spaces
				3tabs

Generates:
![image](https://cloud.githubusercontent.com/assets/4369001/5785790/0205d37a-9d90-11e4-934b-67de020b07ac.png)

If you remove the space from the dash after another listitem, then it doesn't even put the following lines in a codeblock at all. The ~~~ syntax does not work either.

Also, doing it to the first list item in an unordered list will wrap the `listitem` (and all subsequent list item text) in a p tag. But this doesn't happen if you indent a codeblock for the 2nd or later items in a list.

All of this seems to make no sense, and actually none of it is documented anywhere that I can find. Are you not supposed to be able to add code blocks within li elements? the backtick syntax does work but if I want multiple lines then it doesn't generate work as nicely.

**Comment by gettalong** [comment]
Please read the syntax documentation for lists because you need to take the list indentation into account.

For example, the following list has an indentation of 2 spaces, so the code block needs to be indented 6 spaces:

~~~
* list with a follow-up indentation of 2 spaces
  (because of the asterisk and space at the beginning of the line)

  paragraph that belongs to list item indented 2 spaces

      Code block belonging to list item indented 6 spaces
~~~

**Comment by nasht00** [comment]
@gettalong 
I don't know if this is the same issue,
Take a look at this blog post: http://idratherbewriting.com/2016/02/21/bug-with-kramdown-and-rouge-with-github-pages/

I am having the exact same issue described there, but not in GitHub Pages (in a standdalone Jekyll site).
Is it a separate bug? Should I open one? Or is this unrelated to kramdowm?

Thanks

**Comment by gettalong** [comment]
See my answer at tomjohnson1492/kramdowntest#1 - it is basically the same problem. As far as I can tell the wrong indentation is used and therefore you get the wrong result.

**Comment by geraldb** [comment]
@nasht00  FYI: This might help. I've updated the example with the help of Thomas Leitner - the kramdown developer. It works!

All you have to fix is your indentation e.g. use three spaces max. for your code block (for level 1) and 3+4 e.g. 7 spaces max. for your code block (for level 2) and so on. See the sample [source](http://planetjekyll.github.io/sandbox-syntax-highlighter/lists.html) and [rendered with GitHub Pages](https://github.com/planetjekyll/sandbox-syntax-highlighter/blob/gh-pages/lists.md). Cheers.
