### ISSUE TITLE
Support starting numbered lists with arbitrary number

### ISSUE THREAD

**Issue by winniehell** [gettalong/kramdown#211]
Allow numbered lists to have a defined offset like [in CommonMark](http://spec.commonmark.org/dingus.html?text=5.%20one%0A1.%20two).

Current output:

```
$ kramdown --output kramdown <<< '5.  five
6.  six'

1.  five
2.  six
```

Expected:

```
$ kramdown --output kramdown <<< '5.  five
6.  six'

5.  five
6.  six
```

Especially useful in quotes:

```
$ kramdown --output kramdown <<< '> 42.  Question

What is it?'
```

should really be

```
> 42.  Question

What is it?
```

**Comment by gettalong** [comment]
Thanks for the issue. However, since this will change the output and probably break some documents, this can't be done in the 1.x release and has to wait for the 2.x release.

**Comment by winniehell** [comment]
@gettalong 2.x would be great :+1:

**Comment by Phrogz** [comment]
+1 particularly for inline quoted responses. When someone writes: 

    Some questions:

    1. How big are your shoes?
    2. Can a bullet ricochet off an armadillo?

And I respond with a quoting system that prefixes the input with `>`, and inject my responses:

    > 1. how big are your shoes
    
    Normal sized

    > 2. Can a bullet ricochet off an armadillo?

    [Apparently, yes.](http://www.bbc.com/news/world-us-canada-33748027)

The result is undesirable.

> 1. how big are your shoes
   
Normal sized

> 2. Can a bullet ricochet off an armadillo?

[Apparently, yes.](http://www.bbc.com/news/world-us-canada-33748027)

My workaround hack is to wrap the quoted list items in backticks to preserve the typed value.

**Comment by e9t** [comment]
:+1:

**Comment by chimericdream** [comment]
Another option that I just found is to use an IAL declaration before the list. I was looking for this exact feature and was sad (at first) to learn that it isn't supported. However, the following works as desired:

```
{:start="3"}
1. test
1. test
1. test
```

Output:
```
3. test
4. test
5. test
```

Tested with this online Kramdown editor: https://kramdown.herokuapp.com/

This doesn't solve the problem for the average user who doesn't know much markdown, but it's a workaround for people using Kramdown in cases like Jekyll sites and whatnot.

**Comment by winniehell** [comment]
@chimericdream That is awesome, thank you very much! :+1: 

However for quoting multiple list entries, this is a lot of overhead:

```markdown
> {:start="42"}     
> 42. Question

Nobody knows!

> {:start="2016"}
> 2016. Current Year        

YOLO
```

**Comment by chimericdream** [comment]
> However for quoting multiple list entries, this is a lot of overhead:

@winniehell I completely agree. I think it'd be awesome to have this baked into Kramdown core so that the list starts at the number of the first bullet. But for bloggers and power users, it's good to know that there is a fairly straightforward workaround until Kramdown 2.0 is final.

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1

**Comment by cup** [comment]
@gettalong again, not sure why this was closed when this issue still hasnt been
fixed. Here is a workaround for any interested. Just add to your `default.html`
or similar:

~~~js
document.querySelectorAll('ol a').forEach(z =>
   z.closest('ol').start = z.getAttribute('href')
);
~~~

http://github.com/cup/umber/tree/master/javascript/kramup

**Comment by gettalong** [comment]
@cup There is nothing to fix here. It currently works as designed and this issue talks about changing the design which would be a breaking change.

**Comment by cup** [comment]
For anyone using GitHub Pages, you can simply add this to `_config.yml`:

~~~
markdown: CommonMarkGhPages
~~~

you dont even have to declare the plugin in `_config.yml` as its activated by
default:

http://github.com/github/pages-gem/blob/fb5c3f2/lib/github-pages/plugins.rb#L9

reference:

http://github.com/github/jekyll-commonmark-ghpages
