### ISSUE TITLE
Nested HTML elements with markdown="1"

### ISSUE THREAD

**Issue by tkrotoff** [gettalong/kramdown#213]
- Works:
```HTML
<div markdown="1">
   My text with **markdown** syntax
</div>
```
generates:
```HTML
<div>
  <p>My text with <strong>markdown</strong> syntax</p>
</div>
```

- Does not work:
```HTML
<div>
  <div markdown="1">
     My text with **markdown** syntax
  </div>
</div>
```
generates:
```HTML
<div>
  <div>
    <pre><code> My text with **markdown** syntax
</code></pre>
  </div>
</div>
```
expected:
```HTML
<div>
  <div>
    <p>My text with <strong>markdown</strong> syntax</p>
  </div>
</div>
```

**Comment by gettalong** [comment]
It works as expected. A `<div>` tag contains block elements and your text is indented by four spaces, therefore it is a codeblock.

If you want it to be a paragraph, don't indent it.

**Comment by tkrotoff** [comment]
Oops, sorry for the bad report: i'm so used to GFM '```' syntax and forgot you can get 'pre' using 4 spaces. I guess since Markdown inside HTML is kind of hackish, there is no way to keep the code indented without producing a code block.
