### ISSUE TITLE
Rouge support will not accept custom formatter

### ISSUE THREAD

**Issue by BackOrder** [gettalong/kramdown#214]
Syntax highlighting using Rouge has ```::Rouge::Formatters::HTML.new(opts)``` formatter embedded into the code, not allowing the use of a **custom formatter**. It would be great to be able to pass a custom formatter as an option to the syntax highlighter.

**CASE STUDY**
I am using custom classes for Kramdown and Rouge to allow rendering in http://shoesrb.com/ to replace the old manual. Those classes generate methods that Shoes can interpret to create GUI elements according to the markdown. 

For example, **\*\*This is in bold.**** is transformed into **para(strong("This is in bold."))**. Rouge may determine it is a literal string and return, say, a color of value **#336633**, which would in turn be translated into **para(strong("This is in bold."), :stroke => "#336633")**.

The current solution involves copying the code from *Kramdown::Converter::SyntaxHighlighter::Rouge.call* and replace the formatter with my custom formatter.

**REFERENCE**
https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/syntax_highlighter/rouge.rb#L31

**Comment by gettalong** [comment]
So what you are saying is that you want a key like `:formatter` that can be passed to the `syntax_highlighter_opts` option and which is then used instead of the standard HTML formatter?

Something like:

~~~ruby
formatter = (opts.delete(:formatter) || ::Rouge::Formatters::HTML).new(opts)
~~~

**Comment by BackOrder** [comment]
Yes, exactly. 

```ruby
:syntax_highlighter_opts => { :formatter => Kramdown::Rouge::Formatters::MyCustomFormatter }
```

**Comment by gettalong** [comment]
Okay, I think that can be done. Initially I had reservations because of possible code injections but specifying a constant is only doable by setting the option in Ruby and not via the `{::options}` extension, so that should be no problem.

**Comment by gettalong** [comment]
Done!

**Comment by BackOrder** [comment]
Excellent, thanks! I am looking forward using this feature.
