### ISSUE TITLE
Test for html input

### ISSUE THREAD

**Issue by winniehell** [gettalong/kramdown#216]
I tried to write a test for html input and Markdown output&mdash;as you (@gettalong) described in #206&mdash;by adding two files `dummy.htmlinput` and `dummy.text`:
https://github.com/winniehell/kramdown/compare/test-suite-sandbox

Yet the resulting build fails:
https://travis-ci.org/winniehell/kramdown/builds/49637465

It tries to call the following methods:
* `dummy_htmlinput_to_html`
* `dummy_text_to_html`
* `dummy_text_to_kramdown_to_html`

As I understood [your comment](https://github.com/gettalong/kramdown/pull/206#issuecomment-72997174) it should not call any of those since there is no `dummy.html`. Did I get anything wrong?

**Comment by gettalong** [comment]
No, I'm sorry, it is my fault. It seems that I missed some places in the test code when I introduced the '.htmlinput' notion. I have updated the test code and pushed the changes. Please try again now!

By the way: There is a typo in your text file, it should read "dummy text".

**Comment by winniehell** [comment]
Thank you for the effort! Now indeed those failing methods are no longer called but unfortunately it seems like the conversion html to Markdown is called neither:
https://travis-ci.org/winniehell/kramdown/builds/49867907

I left the typo in the test file to provoke exactly one failing test:
https://github.com/winniehell/kramdown/compare/test-suite-sandbox

**Comment by gettalong** [comment]
Sorry, I'm not at my best currently it seems. The test code is grown code and I should really refactor it someday now...

I have now changed some things and this works now with your test suite sandbox.

**Comment by winniehell** [comment]
Yep, fixed :sparkles: - thank you!

**Comment by winniehell** [comment]
May I suggest that once you refactor the test code you reverse the logic such that it lists the files to test instead of the excluded files? At least for me that would be a lot less confusing... :+1:

**Comment by gettalong** [comment]
The thing is that doing it this way one can add test cases without changing the test code itself. The test code only needs to be changed if an added test case won't work in some circumstances.
