### ISSUE TITLE
Is hard_wrap working?

### ISSUE THREAD

**Issue by firedev** [gettalong/kramdown#217]
Given:
```ruby
Kramdown::Document.new("a\nb", hard_wrap: true).to_html
```
I would expect:
```ruby
"<p>a<br>b</p>\n"
```

Instead:
```ruby
"<p>a\nb</p>\n"
```

Please advise.

**Comment by gettalong** [comment]
The hard_wrap option is only used by the GFM parser, not the standard kramdown parser. I will update the options page so that this is made clearer.

**Comment by gettalong** [comment]
Done!

**Comment by firedev** [comment]
Sorry me again, I don't understand, how can I use it then? This is what I have:

```ruby
Kramdown::Document.new(text, hard_wrap: true).to_html
```

**Comment by gettalong** [comment]
You have to tell kramdown that the input is not in the kramdown format but in the GFM format:

~~~ ruby
Kramdown::Document.new(text, input: 'GFM', hard_wrap: true).to_html
~~~

**Comment by firedev** [comment]
Thank you! That did it.
