### ISSUE TITLE
New (?) bug rendering divs next to paragraphs?

### ISSUE THREAD

**Issue by Vaguery** [gettalong/kramdown#220]
I just noticed (while chasing down a new Nokogiri bug) that a bunch of old blog posts are not rendering correctly. There are two symptoms, apparently:

- a `<div>` that appears without a newline right before it is not recognized, and comes out HTML escaped inside its surrounding block
- a `<div>` with any attribute at all is not recognized unless it is preceded by TWO newlines

[Here's a gist showing the behavior](https://gist.github.com/Vaguery/f145dcbb418aca05383c)

Amusingly, github parses the source correctly. View "RAW" to see the problem.

**Comment by gettalong** [comment]
Examples 4 and 6 have to fail because the `<div>` tags appear inside the paragraph, and this is not allowed.

Example 7 should not fail. It is similar to 5 which is parsed correctly. So this has to do with the attribute probably.

**Comment by gettalong** [comment]
I have found the problem and this will be fixed in the next release.

Please also note that when using "parse_block_html" that the closing tag needs to be on a separate line!

**Comment by Vaguery** [comment]
Confused about the `<div>` tags appearing "inside" the paragraph. Those examples are concertedly correctly by the github parser, and there is no (explicit) requirement for a `<div>` to start on a new line.

Indeed, these examples were converted correctly (as a paragraph followed by a `div`) by `kramdown` a few months ago.

**Comment by gettalong** [comment]
Okay, I will use `git bisect` to see if kramdown's behaviour changed and will let you know!

**Comment by gettalong** [comment]
kramdown has functioned this way since 2009, so this is not new behaviour.

However, if you can find an example where kramdown acted differently, please share it!

**Comment by Vaguery** [comment]
My mistake! Apparently it's the behavior of other renderers (github, for example), and I got confused.

**Comment by gettalong** [comment]
No problem :) Thank you for reporting!
