### ISSUE TITLE
Reference link id doesn't render when it contains ä

### ISSUE THREAD

**Issue by davidsilvasmith** [gettalong/kramdown#221]
I ran into an issue where reference links didn't render when the link id contained ä in [Jekyll](https://github.com/jekyll/jekyll/issues/3448).

Markdown showing the issue:

    [Risto Pietilä]: https://twitter.com/ristopietila
    [Risto Pietila]: https://twitter.com/ristopietila
    [Risto Pietilä] - does not render as an a tag.
    [Risto Pietilä][Risto] - renders as an a tag

**Comment by gettalong** [comment]
I'm sorry but I need a complete example for the failure, I cannot reproduce it.

See the following working example:

~~~text
[Risto Pietilä]: https://twitter.com/ristopietila

this is [Risto Pietilä] test                             
~~~

Result:

~~~html
<p>this is <a href="https://twitter.com/ristopietila">Risto Pietilä</a> test</p>
~~~
