### ISSUE TITLE
Final `\n` should be swallowed in fenced code blocks?

### ISSUE THREAD

**Issue by nybblr** [gettalong/kramdown#223]
It looks like this line: https://github.com/gettalong/kramdown/blob/9d1e2766ace22d227707825cdafb9f2e0b3cf797/lib/kramdown/parser/gfm.rb#L50

...does not swallow the last linebreak before the fence. e.g.

    ```ruby
    puts "Hello"
    ```

...parses out `puts "Hello"\n`. However, it seems Rouge (maybe CodeRay as well?) expects the last `\n` to be chomped off. Since it isn't, the following output is produced:

```html
<pre class="highlight"><code><span class="nb">puts</span> <span class="s2">"Hello"</span>
</code></pre>
```

While some browsers are forgiving of that extra line break, I think it should be outputting:

```html
<pre class="highlight"><code><span class="nb">puts</span> <span class="s2">"Hello"</span></code></pre>
```

Should Kramdown be swallowing the extra linebreak?

**Comment by gettalong** [comment]
I don't think so. When you have a code snippet like

    ~~~
    puts :hello
    ~~~

you have a line break at the end of the line and since a codeblock should be used verbatim, the trailing EOL character is used.

Also have a look at http://johnmacfarlane.net/babelmark2/?normalize=1&text=++++testline - you will find that most Markdown libraries do the same.

**Comment by nybblr** [comment]
![screencapture-johnmacfarlane-net-babelmark2](https://cloud.githubusercontent.com/assets/794113/6316940/447ffd60-ba06-11e4-9040-b0ce3934632e.png)

I note that many of the "best" markdown implementations (Pandoc and Maruku notably, and Marked) all consider the trailing EOL irrelevant, while some of those which disagree seem to be niche implementations (which might include the extra linebreak only out of lazy implementation). The three with the most weight to me are RedCarpet, RDiscount, and PHP Markdown. So to me, it looks about even whether it's "standard" to include an extra EOL or not.

From a strict HTML perspective, the extra linebreak can be interpreted in a `<pre>` tag as a literal linebreak, and thus make the `<pre>` tag one line too tall. So from my understanding, the extra linebreak could break things?

Thanks for putting up with yak shaving!

**Comment by gettalong** [comment]
Can you show me an example where the extra line break is a problem? I haven't seen any.

**Comment by aldanor** [comment]
The simplest example of where a trailing line break *is* a problem – automatic line-numbering: http://jsfiddle.net/g8zwu9fr/

This is exactly what Kramdown outputs when given a fenced code block like this:

    ~~~ python
    print 'foo'
    print 'bar'
    ~~~

**Comment by gettalong** [comment]
Actually, that is not a real example since the output is changed if you look at the HTML in the "Result" box. It contains additional `<span>` elements that weren't in the source.

**Comment by aldanor** [comment]
My point was -- this is a real-world example where the extra newline in `<code>` does make a difference because another library may depend on it when injecting additional elements. And since there's currently no way to tell Kramdown "please, don't insert this trailing linebreak" it may become quite painful to fix it.

Hypothetically, if there was a config option (`trim_code_block`?) which would force Kramdown to always trim the extra newline in fenced code blocks, that would be just perfect.

**Comment by gettalong** [comment]
Okay but when another library depends on it, it is not kramdown's problem per se since kramdown can't anticipate every library's needs. It is possible that another library needs that trailing newline...

**Comment by aldanor** [comment]
But that's my point exactly. If you are writing HTML manually, then you're to choose whether you want that trailing newline or not. Kramdown makes that choice for you when rendering fenced code blocks, following the "browsers don't care about" reasoning, and unconditionally inserts a trailing newline -- however there are libraries (e.g. client-side syntax highlighting) that may care about it, hence having an option to turn it on/off might make sense?

**Comment by rbanks54** [comment]
Just as a note, I'm finding that in Edge, the trailing new line is being rendered by the browser, making the code block a line too long.

**Comment by gettalong** [comment]
@rbanks54 I downloaded a free VM from Microsoft (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) to test with Edge and the two `<pre>` tags in the following HTML page render completely the same:

~~~ html
<style>
pre {border: 1px solid black}
</style>

<pre><code>test
</code></pre>

<pre><code>test</code></pre>
~~~

**Comment by rbanks54** [comment]
@gettalong Yeah, I've been chasing it up further. It's looking like it's a CSS handling difference between browsers, not the hanging new line on it's own. So while the new line triggers the behaviour difference, I think leaving the HTML rendering as is is fine. I'll see if I can get a concise repro and then get in touch with the Edge team.
