### ISSUE TITLE
CDATA wrapping shows up in "TeX source" of MathJax elements

### ISSUE THREAD

**Issue by jethrogb** [gettalong/kramdown#224]
As a result of the discussion in commit 512b00a6 and the discussion here: https://groups.google.com/forum/#!topic/mathjax-users/AS6swTZzyWY MathJax jax's are always wrapped with CDATA. This does not look pretty when you select "Show Math As ▸ TeX Commands" from the MathJax context menu: the CDATA stuff shows up.

From that mathjax-users discussion we learn: "in HTML, script tags are automatically CDATA, so it is not  needed there, and in XHTML, the browser handles CDATA itself, so MathJax doesn't have to."

The current converter produces something that is compatible with both HTML XHTML but does not look good.

I propose to add a processing option that lets you force the conversion to be explicitly HTML- or XHTML-compatible:
```ruby
      wraptype = converter.options[:math_engine_opts] && converter.options[:math_engine_opts][:wrap] || :compatible
      case wraptype
        when :html
          text = el.value
        when :xhtml
          text = "<![CDATA[#{el.value}]]>"
        else
          text = (el.value =~ /<|&/ ? "% <![CDATA[\n#{el.value} %]]>" : el.value)
      end
```

You can now set an option like ```:math_engine_opts => { :wrap => :html }```.

**Comment by gettalong** [comment]
It is correct that the CDATA wrapping is showing up when viewing the source. However, one can clearly see that it is a LaTeX comment and can therefore be ignored.

I would rather not change the converter to output either HTML or XHTML (this would probably lead to many more changes that are not really beneficial). If you have specific requirements for your output, please create a custom converter based on the HTML converter that fulfills your need.
