### ISSUE TITLE
Coderay Synxtaxhighlight is broken

### ISSUE THREAD

**Issue by commel** [gettalong/kramdown#227]
I am using Kramdown 1.5.0 and have both kramdown and coderay gems installed in my Rails application.

When the markup contains code that should be syntax highlighted it will fail with:

```ruby
ActionView::Template::Error (wrong constant name ::Kramdown::Converter::SyntaxHighlighter::Coderay):
```

When I switch to Kramdown 1.4.2 it works again. In the Rails Console i cannot access the module. Only Kramdown::Converter is available.

**Comment by gettalong** [comment]
This is a Rails error, not a kramdown error. Please try without Rails, i.e. just with `irb`. If it still fails, I will re-open.
