### ISSUE TITLE
UTF-8 support for Markdown-to-HTML via cli

### ISSUE THREAD

**Issue by uaqben** [gettalong/kramdown#229]
I am trying to export a Markdown document to HTML using kramdown (1.5.0) directly from the command line. Unfortunately it garbles up some characters – to give an example:

`Gestació, interpretació i revisió del text`

I run:

 `kramdown text.md > text.html`

I get:

`<p>GestaciÃ³, interpretaciÃ³ i revisiÃ³ del text</p>`

I've looked at the kramdown documentation but can't find any `--flag` pertaining to character encoding that I could use.

Also, I've tried setting the `text.md` to both `utf-8 no BOM` & `utf-8 with BOM`, to no avail.

Is the above behavior normal/expected? or what am I doing wrong?

Note: The same version of kramdown, when used by Jekyll (2.5.3), parses the Markdown text fine, ie. the HTML renders fine. I've tried looking at how Jekyll calls kramdown – but haven't been able to find much I can put to use (or know how to use).

**Comment by gettalong** [comment]
The most probable cause of this problem is that the Ruby interpreter uses another encoding than the file itself. kramdown just takes the input in whatever encoding it is in (specified via the system locale or by an explicit `ruby -E...` parameter) and converts it.

To change the used encoding run the kramdown binary like this: `ruby -EENCODING -s kramdown ...`, for example: `ruby -EUTF-8 -s kramdown test.md`.

**Comment by uaqben** [comment]
Thanks! I now see that the encoding was actually fine. The problem was that the html output lacked a `<header>` specifying `utf-8`, thus when viewed in a browser it was garbled.

I'd like to use the `--template=ARG`flag, so as to set:

``<html><head><meta charset="utf-8"></head>``

However, I haven't been able to find a reference template file for markdown... could you point me to one?

**Comment by gettalong** [comment]
Have a look at `data/kramdown/document.html` for the sample template that ships with kramdown.

**Comment by uaqben** [comment]
Perfect – Thanks !

**Comment by spetrosi** [comment]
> The most probable cause of this problem is that the Ruby interpreter uses another encoding than the file itself. kramdown just takes the input in whatever encoding it is in (specified via the system locale or by an explicit `ruby -E...` parameter) and converts it.
> 
> To change the used encoding run the kramdown binary like this: `ruby -EENCODING -s kramdown ...`, for example: `ruby -EUTF-8 -s kramdown test.md`.
Hello @gettalong, I know this conversation happened 6 years ago, but I see you are still around in this repo.

When running kramdown from a Linux CLI as  you suggested, kramdown fails to find the GFM parser extention:
```
ruby --encoding=UTF-8 -s usr/bin/kramdown --extension parser-gfm --input GFM --output html postfix/README.md
Traceback (most recent call last):
	3: from /usr/bin/kramdown:23:in `<main>'
	2: from /usr/bin/kramdown:23:in `load'
	1: from /usr/share/gems/gems/kramdown-2.1.0/bin/kramdown:124:in `<top (required)>'
/usr/share/gems/gems/kramdown-2.1.0/bin/kramdown:124:in `read': No such file or directory @ rb_sysopen - parser-gfm (Errno::ENOENT)
```

While when I run just kramdown without `ruby`  it just works, in these two cases
```
kramdown --extension parser-gfm --input GFM --output html postfix/README.md >> postfix/README.html
/usr/bin/kramdown --extension parser-gfm --input GFM --output html postfix/README.md >> postfix/README.html 
```
I think I need to somehow point ruby to the `parser-gfm` kramdown extention, but I do not know why. Are you able to help with this?

Thanks in advance.

**Comment by gettalong** [comment]
@spetrosi No problem, I would have also recommended the `-S` switch.
