### ISSUE TITLE
Kramdown warning - method redefined

### ISSUE THREAD

**Issue by shevegen** [gettalong/kramdown#230]
Hi,

Not sure this is worthy to report, as it is just a warning.

  /usr/lib/ruby/gems/2.1.0/gems/kramdown-1.5.0/lib/kramdown/utils/configurable.rb:30: warning: method redefined; discarding old configurables/usr/lib/ruby/gems/2.1.0/gems/kramdown-1.5.0/lib/kramdown/utils/configurable.rb:30: warning: previous definition of configurables was here

It seems a method is redefined, perhaps the code structure could be arranged to not have to redefine said method? Thanks for reading and considering, kramdown and markdown rocks!

**Comment by gettalong** [comment]
Thanks for that! I have corrected it.
