### ISSUE TITLE
Add data-label to HTML table cells

### ISSUE THREAD

**Issue by fluffypony** [gettalong/kramdown#232]
I've been fiddling with adding this to the table parser and then the HTML converter, but my Ruby is terrible, and so I feel it prudent to add this as an issue and beg for some assistance;)

Basically, because tables suck for responsive layouts we use a responsive table system based on [Kelly Cook's work](http://kellycook.github.io/responsive-tables/). When screen resolution is too small to display the table it falls back to horizontal layout (analogous to the way mysql's CLI displays the results of a `SELECT` statement when terminated with `\G` instead of a semi-colon). So a normal table:

Head1 | Head2 | Head3
--- | --- | ---
Stuff | Goes | Here
More | Stuff | Here

then gets displayed as so:

|  |
| ---- |
| **Head1:** Stuff<br>**Head2:** Goes<br>**Head3**: Here |
| **Head1:** More<br>**Head2:** Stuff<br>**Head3**: Here |

(ignore that top row, had to put in a fake header to get it to display properly)

The way this works in the HTML is that each `<td>` has a `data-label` attribute, which in Kramdown would ideally be based on the `<thead>` values (so no `thead`, no `data-label`). I imagine that this would also be optional, as it may not provide value to everyone (although it is a markedly better solution, in my opinion, than Bootstrap's horizontal scroll for responsive tables).

We're in the process of moving from Markdown to Kramdown as the parser on the Monero Forum software, so we'll hack php-markdown to do this in the meantime (see [this thread](https://forum.getmonero.org/1/news-announcements-and-editorials/196/editorial-submultiples-of-monero), for instance, which would benefit from it).

**Comment by gettalong** [comment]
I don't think that you need to modify the parser. Just write a custom converter based on the HTML converter that modifies how the table cells are output by `#convert_td` (see https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/html.rb#L213).

**Comment by hzy916** [comment]
Hello, I am using data-label to make responsive tables in small screens, however, my table has images, do u have any idea about how to use data-label to represent images? Thank you. 

The following is my html code:
<table>
 
  <thead>
    <tr>
      <th scope="col">
        <a href="http://www.petessentials.ie/" target="_blank">
            <img class="brandImage1" src="https://www.pawtrails.ie/wp-content/uploads/2018/01/pet-essentials-logo.jpg">
          </a>

          </th>
      <th scope="col">  
        <a id="macroom" href="https://www.facebook.com/juliespetshop/" target="_blank">
            <strong>Macroom Pet Shop</strong>
          </a>
       </th>
      <th scope="col"> 
        <a href="http://www.westcorkpetstore.net/" target="_blank">
            <img class="brandImage2" src="https://www.pawtrails.ie/wp-content/uploads/2018/01/potty-fish.jpg">
          </a>
          </th>
      <th scope="col">  
        <a id="slinky" href="https://www.goldenpages.ie/slinkys-pet-shop-mitchelstown/" target="_blank">
             <strong>Slinkys Pet Shop</strong>
         </a> 
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td data-label="Pet Essentials"> 
        <img class="locationIcon" src="http://pawtrails.ie/wp-content/uploads/2018/01/maps-and-flags.png">
                  <p>Unit 9 Kilnagleary Business Park,</p>
                  <p>Carrigaline, Co. Cork</p> 
      </td>
      
      <td data-label="Macroom Pet Shop">  
        <img class="locationIcon" src="http://pawtrails.ie/wp-content/uploads/2018/01/maps-and-flags.png">
        <p>3 Main St Macroom</p>
        <p>Co. Cork</p>
      </td>
      
      <td data-label="Potty Fish">  
        <img class="locationIcon" src="http://pawtrails.ie/wp-content/uploads/2018/01/maps-and-flags.png">
       <p>Baldwin St, Ballinwillin,</p>
        <p>Bandon, Co. Cork</p>
            </td>
   
          
      <td data-label=" Slinkys Pet Shop">
        <img class="locationIcon" src="http://pawtrails.ie/wp-content/uploads/2018/01/maps-and-flags.png">
                  <p>Baldwin St, Ballinwillin,</p>
                  <p>Mitchelstown, Co. Cork</p>
                  </td>
    </tr>
 

  </tbody>
</table>

The following is the css code:
body {
  font-family: "Open Sans", sans-serif;
  line-height: 1.25;
}
table {
  border: 1px solid #ccc;
  border-collapse: collapse;
  margin: 0;
  padding: 0;
  width: 100%;
  table-layout: fixed;

}
table caption {
  font-size: 1.5em;
  margin: .5em 0 .75em;
}
table tr {
  background: #f8f8f8;
  border: 1px solid #ddd;
  padding: .35em;
}
table th,
table td {
  padding: .625em;
  text-align: center;
}
table th {
  font-size: .85em;
  letter-spacing: .1em;
  text-transform: uppercase;
}
@media screen and (max-width: 600px) {
  table {
    border: 0;
  }
  table caption {
    font-size: 1.3em;
  }
  table thead {
    border: none;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
  }
  table tr {
    border-bottom: 3px solid #ddd;
    display: block;
    margin-bottom: .625em;
  }
  table td {
    border-bottom: 1px solid #ddd;
    display: block;
    font-size: .8em;
    text-align: right;
  }
  table td:before {
    /*
    * aria-label has no advantage, it won't be read inside a table
    content: attr(aria-label);
    */
    content: attr(data-label);
    float: left;
    font-weight: bold;
 
  }
  table td:last-child {
    border-bottom: 0;
  }
}


/**********/
#macroom{
  color:#A52A2A;
  font-size: 20px;
  letter-spacing: 1px;
}
#slinky{
  color:#000000;
  font-size: 20px;
  letter-spacing: 1px;
}
.brandImage1{
    margin-top:15px;
    margin-bottom:15px;
    height:60px;
    text-align: center;
    border-radius: 5px 5px 5px 5px;
    overflow: hidden;
    border-right-color: #aaa;
    box-shadow: 0 2px 18px 0 rgba(0,0,0,0.3);
  }
  .brandImage2{
    height:60px;
    width:150px;
    text-align: center;
    border-radius: 5px 5px 5px 5px;
    overflow: hidden;
    border-right-color: #aaa;
    box-shadow: 0 2px 18px 0 rgba(0,0,0,0.3);
  }
.locationIcon{
  width:30px;
}

  table, th, td {
      background-color: #fff;
      border-radius: 1px 1px 1px 1px;
      overflow: hidden;
      border-width: 1px;
      border-color: #f4f4f4;
      box-shadow: 6px 6px 18px 0 rgba(0,0,0,0.3);
      text-align: center;
}

Currently, it will become text in small screens, but I want to use the images like big screens? Any help is greatly appreciated, Thank you so much.

**Comment by hzy916** [comment]
https://codepen.io/steph2020/pen/EQjyxr
This is the link to my table on codepen. Thank you

**Comment by arslanahmedawan** [comment]
```
<style>
  body {
    font-family: arial;
  }
  table {
    border: 1px solid #ccc;
    width: 100%;
    margin:0;
    padding:0;
    border-collapse: collapse;
    border-spacing: 0;
  }
  table tr {
    border: 1px solid #ddd;
    padding: 5px;
  }
  table th, table td {
    padding: 10px;
    text-align: center;
  }
  table th {
    text-transform: uppercase;
    font-size: 14px;
    letter-spacing: 1px;
  }
  @media screen and (max-width: 600px) {
    table {
      border: 0;
    }
    table thead {
      display: none;
    }
    table tr {
      margin-bottom: 10px;
      display: block;
      border-bottom: 2px solid #ddd;
    }
    table td {
      display: block;
      text-align: right;
      font-size: 13px;
      border-bottom: 1px dotted #ccc;
    }
    table td:last-child {
      border-bottom: 0;
    }
    table td:before {
      content: attr(data-label);
      float: left;
      text-transform: uppercase;
      font-weight: bold;
    }
  }
</style>
<table>
  <thead>
    <tr>
      <th>Country</th>
      <th>Name</th>
      <th>Field</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td data-label="Country">Pakistan</td>
      <td data-label="Name">Arslan Ahmed Awan</td>
      <td data-label="Field">Software Engineering</td>
    </tr>
    <tr>
      <td data-label="Country">Pakistan</td>
      <td data-label="Name">Arslan Ahmed Awan</td>
      <td data-label="Field">Software Engineering</td>
    </tr>
  </tbody>
</table>
```

**Good Luck**
