### ISSUE TITLE
Too much white space

### ISSUE THREAD

**Issue by noiseunion** [gettalong/kramdown#233]
I am using Kramdown to generate some developer docs.  My code blocks are rendering out of whack and I am can not figure out where things are going crazy.  I am using the "GFM" input parser and Coderay for syntax highlighting.  

The first line is properly placed, but then all of the following lines end up being pushed way over to the right.  Anyone dealt with this before?  At first I thought it was a CSS issue, but I have removed ALL of the CSS and I still have the same problem.  The HTML rendered ends up with a bunch of extra white-space for each line.

**Comment by gettalong** [comment]
Please show us an example of the problem (raw input text and wrong HTML output)!

**Comment by noiseunion** [comment]
Hey @gettalong, sorry for the late reply here.  See below:

The markdown is a code block that should render like this below:

```ruby
# app/models/advisors/user.rb

module Advisors
  class User < ::Ofi::User
    include Ofi::BitwiseEnums

    bitwise_enum  :login_status,
                  :must_reset_password,
                  :must_accept_terms_and_conditions,
                  :must_create_security_questions
  end
end
```

Instead, I get rendering like this:

![screen shot 2015-03-09 at 9 23 05 am](https://cloud.githubusercontent.com/assets/173789/6557837/cc184b40-c63d-11e4-8147-8dff387ac089.png)

When you look at the underlying HTML you will see all sorts of extra white space in the HTML:
```html
<pre><span style="color:#777"># app/models/advisors/user.rb</span>
              
 <span style="color:#080;font-weight:bold">module</span> <span style="color:#B06;font-weight:bold">Advisors</span>
                <span style="color:#080;font-weight:bold">class</span> <span style="color:#B06;font-weight:bold">User</span> &lt; ::<span style="color:#036;font-weight:bold">Ofi</span>::<span style="color:#036;font-weight:bold">User</span>
                  include <span style="color:#036;font-weight:bold">Ofi</span>::<span style="color:#036;font-weight:bold">BitwiseEnums</span>
              
                  bitwise_enum  <span style="color:#A60">:login_status</span>,
                                <span style="color:#A60">:must_reset_password</span>,
                                <span style="color:#A60">:must_accept_terms_and_conditions</span>,
                                <span style="color:#A60">:must_create_security_questions</span>
                <span style="color:#080;font-weight:bold">end</span>
              <span style="color:#080;font-weight:bold">end</span>
              
              </pre>
```

I am seeing the same result in both FireFox and Chrome.  At first I thought it was an issue with the CSS for the page, however I get the same results when rendering with no CSS.  

Any help you can provide is appreciated.

**Comment by gettalong** [comment]
Thanks for the documents! One more thing: If you run your sample source text through the kramdown binary using the same options as you are using otherwise, is the output correct?

**Comment by noiseunion** [comment]
I will give that a shot in a little bit here and let you know.

**Comment by noiseunion** [comment]
Here is a line from a code block after running it through the binary:

   before_process <span style="color:#A60">:set_visitor_id</span>

Here is what comes through in Chrome for that same line:


                  before_process <span style="color:#A60">:set_visitor_id</span>

**Comment by noiseunion** [comment]
No styling, but here is the binary output pulled in to chrome directly:

The #process method has a before and after callback that can be used to perform actions accordingly. To use the callbacks, reference them in your form object just as you would an ActiveModel callback.

```html
 1# app/forms/advisors/registration_form.rb
 2
 3module Advisors
 4  class RegistrationForm < Ofi::FormObject::Base
 5    before_process :set_visitor_id
 6    after_process :load_advisor
 7
 8    attr_reader :visitor_id, :user
 9
10    # code has been removed to keep this example simple.
11
12    ## Methods ------------------------------------------
13
14    private # -------------------------------------------
15
16    def set_visitor_id
17      @visitor_id = Thread.current[:visitor_id]
18
19      if @visitor_id.nil?
20        @visitor_id = Ofi::VisitorService.get_new_id
21      else
22        existing_user = Advisors::UserFetchService.fetch_by_visitor_id @visitor_id
23        @visitor_id = Ofi::VisitorService.get_new_id if existing_user.present?
24      end
25    end
26
27    def load_advisor
28      @user = Advisors::UserFetchService.fetch_by_visitor_id @visitor_id
29    end
30
31    def persist
32      Advisors::UserRegistrationService.register! @visitor_id, self
33    end
34  end
35end
36
```

**Comment by noiseunion** [comment]
looks a lot better.

**Comment by gettalong** [comment]
Thanks for all the effort, however, I need an input file that I can run through the kramdown binary that exhibits this strange behavior. Otherwise I cannot look for the cause.

**Comment by noiseunion** [comment]
https://gist.github.com/noiseunion/d5c2eb09d33bff434bf1

**Comment by noiseunion** [comment]
if it is at all helpful, I am using Kramdown v1.6.0

**Comment by gettalong** [comment]
I get the following result which seems right (i.e. no spaces):

~~~
bash$ kramdown -i GFM /tmp/sample.md 
<!-- app/views/ofi/developer/docs/markdown/ofi_model_base_class.md -->

<h1 id="ofimodel">Ofi::Model</h1>

<p>This is a base class that should be used moving forward as the base for any models that are not backed by a database.  This base class provides basic Active Model features and will be extended with additional features as they are needed.</p>

<p>This base class will give a consistent “standard” that can be used for all non-persistent models created in the application.</p>

<div class="highlighter-coderay"><div class="CodeRay">
  <div class="code"><pre><span class="line-numbers"> <a href="#n1" name="n1">1</a></span><span style="color:#777"># app/models/my_model.rb</span>
<span class="line-numbers"> <a href="#n2" name="n2">2</a></span>
<span class="line-numbers"> <a href="#n3" name="n3">3</a></span><span style="color:#080;font-weight:bold">class</span> <span style="color:#B06;font-weight:bold">MyModel</span> &lt; <span style="color:#036;font-weight:bold">Ofi</span>::<span style="color:#036;font-weight:bold">Model</span>
<span class="line-numbers"> <a href="#n4" name="n4">4</a></span>
<span class="line-numbers"> <a href="#n5" name="n5">5</a></span>  attr_accessor <span style="color:#A60">:my_field1</span>,
<span class="line-numbers"> <a href="#n6" name="n6">6</a></span>                <span style="color:#A60">:my_field2</span>,
<span class="line-numbers"> <a href="#n7" name="n7">7</a></span>                ...
<span class="line-numbers"> <a href="#n8" name="n8">8</a></span>
<span class="line-numbers"> <a href="#n9" name="n9">9</a></span><span style="color:#080;font-weight:bold">end</span>
</pre></div>
</div>
</div>
~~~

Which options are you using?

**Comment by noiseunion** [comment]
yeah that is what I get as well when I run it through the command line.  I am seeing different results when I run it and view the result in Chrome.

**Comment by noiseunion** [comment]
This is what is running in my controller:

```ruby
markdown = File.open("#{ path }.md", hard_wrap: true) { |file| file.read }
@document = Kramdown::Document.new markdown, input: "GFM", coderay_line_numbers: nil
```

The in the view I am doing this:

```ruby
= @document.to_html.html_safe
```

**Comment by gettalong** [comment]
As far as I know, there is no `hard_wrap: true` option for `File.open`. However, there is one for kramdown.

When I run the sample Markdown file with the options you use I get the following which is the correct result:

~~~
bash$  kramdown -i GFM /tmp/sample.md --coderay-line-numbers=nil --hard-wrap
<!-- app/views/ofi/developer/docs/markdown/ofi_model_base_class.md -->

<h1 id="ofimodel">Ofi::Model</h1>

<p>This is a base class that should be used moving forward as the base for any models that are not backed by a database.  This base class provides basic Active Model features and will be extended with additional features as they are needed.</p>

<p>This base class will give a consistent “standard” that can be used for all non-persistent models created in the application.</p>

<div class="highlighter-coderay"><div class="CodeRay">
  <div class="code"><pre><span style="color:#777"># app/models/my_model.rb</span>

<span style="color:#080;font-weight:bold">class</span> <span style="color:#B06;font-weight:bold">MyModel</span> &lt; <span style="color:#036;font-weight:bold">Ofi</span>::<span style="color:#036;font-weight:bold">Model</span>

  attr_accessor <span style="color:#A60">:my_field1</span>,
                <span style="color:#A60">:my_field2</span>,
                ...

<span style="color:#080;font-weight:bold">end</span>
</pre></div>
</div>
</div>
~~~

This means that the problem has in all probability nothing to do with kramdown.

**Comment by noiseunion** [comment]
You are correct, the hard_wrap was in the wrong place.  That said, yes...everything appears to work great when using the binary.  I am getting expected output that way.  Using the Kramdown::Document.new in my controller however, is consistently wrong.  Even on a page with NO css it is wrong.

This is the output using the following:
```
$ kramdown -i GFM sample.md --hard-wrap > sample.html
```
![screen shot 2015-03-12 at 9 49 49 am](https://cloud.githubusercontent.com/assets/173789/6621582/0ce82648-c89d-11e4-9063-7e094b625783.png)

This is what I get when using:
```ruby
markdown = File.open('sample.md') { |f| f.read }
@document = Kramdown::Document.new markdown, input: "GFM", hard_wrap: true
```

Again, there is NO CSS on either page.  Both pages were loaded into the exact same Chrome browser.  This definitely feels like an issue with Kramdown.  It is inconsistent.  Did you try running the code within the context of a Rails/Sinatra view?

**Comment by noiseunion** [comment]
ok, i have narrowed this down to as soon as the HTML output is rendered in a valid HTML doc, then the code block goes whacky.  Viewing the HTML created by kramdown works fine, until you embed it into a valid HTML doc.  Not sure why that is making a difference.

Thanks for the help.

**Comment by gettalong** [comment]
I'm sorry but I can't reproduce the problem. If you run

~~~ shell
kramdown -i GFM sample.md --coderay-line-numbers=nil --hard-wrap --template document > sample.html
~~~

you will get a full valid HTML document that correctly displays the codeblock.

Running in the context of a Rails/Sinatra view is of no concern to me, if there *is* a problem, it is most likely their fault.

I'm not sure I can help you with the problem without further information...

**Comment by hugopeixoto** [comment]
I was having a similar problem, when using markdown and haml, in nanoc.
My problem was that I was using a layout in Haml, and yielding to the markdown template:

```haml
%body
  #content
    = yield
````

Haml, when using `=`, reindents the string to match the current html indentation level. This screwed up my code blocks. I fixed it by using `~` instead of `=` (http://haml.info/docs/yardoc/file.REFERENCE.html#tilde). You might be running into a similar issue.
