### ISSUE TITLE
Be smart

### ISSUE THREAD

**Issue by penibelst** [gettalong/kramdown#235]
In https://github.com/jekyll/jekyll/pull/3566 I try to use kramdown’s smarty pants method. Redcarpet have a dedicated way:

```ruby
input = "I'm"
Redcarpet::Render::SmartyPants.render(input)
# => "I’m"
```

What is the method call in kramdown?

**Comment by gettalong** [comment]
"Smarty pants" substitutions are automatically done with kramdown - see http://kramdown.gettalong.org/syntax.html#typographic-symbols. There is no separate implementation. However, you could create a minimal parser based on the kramdown parser that only does the things you need (:typographic_syms, :smart_quotes).

**Comment by penibelst** [comment]
Minimal parser is exactly what I need. Thank you.
