### ISSUE TITLE
Location/line number not stored on nested raw html elements

### ISSUE THREAD

**Issue by mivok** [gettalong/kramdown#243]
Sample code:

```ruby
#!/usr/bin/env ruby
require 'kramdown'

text = <<EOF
<ul>
  <li>Test</li>
</ul>
EOF

doc = Kramdown::Document.new(text)
puts doc.root.children.inspect
```

which gives:

```ruby
[<kd:html_element "ul" {} {:category=>:block, :location=>1, :content_model=>:raw, :is_closed=>false [
  <kd:text "\n  " nil {:location=>1}>, <kd:html_element "li" {} {:category=>:block, :content_model=>:raw, :is_closed=>false} [
    <kd:text "Test" nil {:location=>nil}>]>, <kd:text "\n" nil {:location=>1}>]>]
```

There is no :location option on the nested li element.

As best as I can tell, this happens at https://github.com/gettalong/kramdown/blob/master/lib/kramdown/parser/html.rb#L153 where the arity of the handle_html_start_tag method is actually -1 (variable number of arguments, none required). Because of this, it tries to call the method without passing the line number in, resulting in no location being given for the li element.

Doing one of the following fixes the issue for me, but I'm not sure of the implications of either solution:

* Removing the default value of 'nil' from the handle_html_start_tag method at https://github.com/gettalong/kramdown/blob/master/lib/kramdown/parser/html.rb#L79
* Changing the check on line 153 to look for an arity of -1 instead of (or in addition to) 1.

**Comment by gettalong** [comment]
Option one is not backwards-compatible, so this won't work. But changing line 153 to look for `arity = 1 || arity < 0` will. I will have a second look at this to see if there would be another problem with this change.

**Comment by gettalong** [comment]
Thanks for reporting, this is fixed with the next release.
