### ISSUE TITLE
Reference links in headers add link reference/name to header ID

### ISSUE THREAD

**Issue by peter-kehl** [gettalong/kramdown#252]
Background: Not sure whether it's a good practice to have links in headers. However, I thought it useful e.g. linking to terms definition.

Problem: When using a reference link with local link text in a header, the reference name is added to the header ID:

~~~
# Add-ons for development of Selenese [scripts][script]

-- that becomes <h1 id="add-ons-for-development-of-selenese-scriptsscript">

Workaround:
# Add-ons for development of Selenese [scripts][script]
{:#add-ons-for-development-of-selenese-scripts}
~~~

**Comment by peter-kehl** [comment]
Related and a bigger problem:
TOC puts [linkReference] or [linkName][linkReference] in the header name listed in TOC for such headers.

**Comment by gettalong** [comment]
As for the first this is just how the automatic ID gets generated. If you don't like the auto-id you have to provide your own.

Could you provide an example for the second message? I don't know what you mean by it.

**Comment by peter-kehl** [comment]
Example for the second message:

~~~
# Add-ons for development of Selenese [scripts][script]

- That renders well as a header in the content (including the link). However, when I generate TOC using:

* TOC
{:toc}

then in TOC it will show '[scripts][script]' as a part of contents. HTML of that TOC part is:

<a href="#add-ons-for-development-of-selenese-scripts">Add-ons for development of Selenese [scripts][script]</a>
~~~

**Comment by gettalong** [comment]
Ah, okay. I will see what I can do!

**Comment by gettalong** [comment]
Can you try the following example using your tool chain:

~~~
# Add-ons for development of Selenese [scripts][script]

* TOC
{:toc}

[script]: test.html
~~~

This results in the following output, not showing both of the mentioned problems:

~~~ html
<h1 id="add-ons-for-development-of-selenese-scriptsscript">Add-ons for development of Selenese <a href="test.html">scripts</a></h1>

<ul id="markdown-toc">
  <li><a href="#add-ons-for-development-of-selenese-scriptsscript" id="markdown-toc-add-ons-for-development-of-selenese-scriptsscript">Add-ons for development of Selenese <a href="test.html">scripts</a></a></li>
</ul>
~~~

It seems to me that the Markdown text was just missing the link definition, you should have gotten a warning about that if you use the kramdown binary.

**Comment by gettalong** [comment]
@peter-kehl Regarding your first problem: There is actually any option that I forgot was available named 'auto_id_stripping' which does exactly what you want regarding the automatic ID generation.

Input:
~~~
{::options auto_id_stripping="true" /}

# Add-ons for development of Selenese [scripts][script]

[script]: test.html
~~~

Output:

~~~ html
<h1 id="add-ons-for-development-of-selenese-scripts">Add-ons for development of Selenese <a href="test.html">scripts</a></h1>
~~~

**Comment by peter-kehl** [comment]
Thank you.
