### ISSUE TITLE
Is it possible to use Latex labels in equations?

### ISSUE THREAD

**Issue by warmspringwinds** [gettalong/kramdown#255]
I was searching for this but didn't find how to do it.

For example I have an equation:

$$
\begin{equation} \label{softmax}
    p(C_k|\textbf{x}) = \frac{e^{~a_k(\textbf{x})}}{\sum_{j=1}^{K}e^{~a_j(\textbf{x})}}
\end{equation}
$$

And later on in the text I want to link it:
"and function $$\ref{softmax}$$"

Is it possible?

**Comment by gettalong** [comment]
It definitely doesn't work with the HTML converter but it might with the LaTeX converter - just tty it out.
