### ISSUE TITLE
LaTeX doesn't like \tt

### ISSUE THREAD

**Issue by richard101696** [gettalong/kramdown#257]
I'm a huge fan of kramdown, but I have a niggle ...

I'm using the Ruby gem for kramdown, 1.7.0.  When I use the backtick for URLs, e.g. `github.com`, this is converted by kramdown to the LaTeX \tt construction, i.e. {\tt github.com}.  This construction is deprecated, and I get the message

(scrartcl)              You should note, that in 1994 font command `\tt' has
(scrartcl)              been defined for compatiblitiy to Script 2.0 only.
(scrartcl)              Now, after two decades of LaTeX2e and NFSS2, you
(scrartcl)              shouldn't use such commands any longer and within
(scrartcl)              KOMA-Script usage of `\tt' is definitely deprecated.
(scrartcl)              See `fntguide.pdf' for more information about
(scrartcl)              recommended font commands.
(scrartcl)              Note also, that KOMA-Script will remove the definition
(scrartcl)              of `\tt' anytime until release of about version 3.20.
(scrartcl)              But for now, KOMA-Script will replace deprecated `\tt'
(scrartcl)              by `\normalfont \ttfamily ' on input line 453.

Could someone change the gem to use e.g. \texttt instead ?

Best wishes
Richard

**Comment by gettalong** [comment]
Thanks for the issue report! I will change the `\tt` beforee the next release.

**Comment by richard101696** [comment]
Hello Thomas

Thanks very much for dealing with this so promptly. 

Yours
R

✉---------------------
Richard Bland
Schiehallion
Smithy Loan
Dunblane
FK15 0HQ
