### ISSUE TITLE
Warning in kramdown 

### ISSUE THREAD

**Issue by shevegen** [gettalong/kramdown#258]
Hi,

I am getting two warnings in my apache log:

  lib/ruby/gems/2.2.0/gems/kramdown-1.6.0/lib/kramdown/utils/configurable.rb:30: warning: method redefined; discarding old configurables
  lib/ruby/gems/2.2.0/gems/kramdown-1.6.0/lib/kramdown/utils/configurable.rb:30: warning: previous definition of configurables was here

I use kramdown.

Do you think this warning could be changed? The redefined method in configurable.rb
could probably be reshuffled, or an "unless defined? configurables" or perhaps "unless self.respond_to? :configurables" could be added (unsure, I have no real experience with the internals of kramdown, sorry)

Thanks

**Comment by gettalong** [comment]
Please update to the newest version, this is already fixed.
