### ISSUE TITLE
Math expressions get evaluated too often

### ISSUE THREAD

**Issue by ckruse** [gettalong/kramdown#259]
Math expressions get evaluated even when escaped or within a nomarkdown block. These expressions get all evaluated:

~~~
\$\$e^x$$

\$\$e^x\$\$

{::nomarkdown}$$e^x$${:/}
~~~

I would expect that none of them get evaluated, according to the documentation. Am I wrong? I'm using kramdown 1.7.0

**Comment by gettalong** [comment]
Can you show me the sample input together with the current output and what you would expect?

When kramdown inline or block math statements are escaped, the raw input text is output. So whether this input text gets further evaluated or not by some other software is out of kramdown's hands.

**Comment by ckruse** [comment]
Ok, after I found some time I was able to debug the problem. It is mathjax additionally searching for `$$` expressions, not a kramdown bug. Sorry for the noise.
