### ISSUE TITLE
HTML5 fragments inside markdown content emits warnings for elements without body

### ISSUE THREAD

**Issue by gpakosz** [gettalong/kramdown#262]
Currently, the html parser expects XHTML content and will warn about non-self closing tags without body. E.g. `<img>` and `<br>` tags.

```ruby
if !closed && HTML_ELEMENTS_WITHOUT_BODY.include?(el.value)
  warning("The HTML tag '#{el.value}' on line #{line} cannot have any content - auto-closing it")
  closed = true
end
 ```
in [`lib/kramdown/parser/html.rb:89`](https://github.com/gettalong/kramdown/blob/2af9ef8cf0e2b9431c81f6d3dd920e9057ea2177/lib/kramdown/parser/html.rb#L89
)

Could we get rid of or have an option to disable that specific warning? I guess nowadays more and more people expect to be able to have fragments of HTML5 inside their markdown documents.

Thanks!

**Comment by gettalong** [comment]
Okay, I have removed the warning messages altogether.
