### ISSUE TITLE
Report errors rather than silently ignore

### ISSUE THREAD

**Issue by geertjanvdk** [gettalong/kramdown#263]
I have been debugging a problem with Jekyll, kramdown and Rouge last night. Using kramdown 1.7.0, I could not figure out why Rouge was not doing its magic. The configuration in Jekyll was sound.
So I went into kramdown and saw this:

```ruby
module Kramdown::Converter::SyntaxHighlighter
  module Rouge
    begin
      require 'rouge'

      # Highlighting via Rouge is available if this constant is +true+.
      AVAILABLE = true
    rescue LoadError, SyntaxError
      AVAILABLE = false  # :nodoc:
    end
```

I did put the `require 'rouge'` outside the begin/rescue and behold: Rouge can't be loaded.

I am only two weeks acquainted with Ruby, and my long Python coding learned me that having 'rouge.rb' as module name could clash with the gem 'rouge'. But that was not it.
The problem is actually with Bundle and $LOAD_PATH. This is not an issue of kramdown.

The above story is long, but it gives an idea of how novice, none-programmers users using kramdown with Jekyll (or any other project) would get frustrated and start throwing computers around.

I would strongly advice to not silently ignore LoadErrors. How is that best done, I don't know in Ruby world, but the following simple thing helps already a ton:

```ruby
    begin
      require 'rouge'

      # Highlighting via Rouge is available if this constant is +true+.
      AVAILABLE = true
    rescue LoadError, SyntaxError => e
      p "Failed loading rouge: #{e.message}"
      AVAILABLE = false  # :nodoc:
    end
```

I hope this helps others finding out why syntax highlighting ain't working. It's getting more important now kramdown and Rouge are close to be coming default in Jekyll 3.0.

**Comment by gettalong** [comment]
Thanks for the issue and your explanation!

If you have configured rouge as syntax highlighter and it is not available, kramdown generates a warning message (see [Kramdown::Converter::Base](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/base.rb#L209).

I'm sorry that you had this problem but it is up to the library/application using kramdown to use these warning messages, e.g. by displaying them to the user. If Jekyll doesn't do this, you should probably raise the problem with them.
