### ISSUE TITLE
Implement options for auto_id_stripping

### ISSUE THREAD

**Issue by chadpowers** [gettalong/kramdown#265]
I am working on using kramdown to generate html from markdown software documentation. `auto_id_stripping` is essential, yet it would add greater functionality to allow options rather than just `true` or `false`. This way you could choose whether to strip only images tags or code tags, etc. 

Currently `:auto_id_stripping => false` turns

``` md
## Header 1
## Header 2 ![with image][image_url]
## `Header 3`
```

into

``` html
<h2 id="header-1">Header 1</h2>
<h2 id="header-2-with-image">Header 2 <im ... ></h2>
<h2 id="header-3"><code>Header 3</code></h2>
```

`true` generates

``` html
<h2 id="header-1">Header 1</h2>
<h2 id="header-2">Header 2 <im ... ></h2>
<h2 id="section-#"><code>Header 3</code></h2>
```

This enhancement option would allow only stripping images or vice-versa...
i.e. `:auto_id_stripping => ["im"]`
would generate

``` html
<h2 id="header-1">Header 1</h2>
<h2 id="header-2">Header 2 <im ... ></h2>
<h2 id="header-3"><code>Header 3</code></h2>
```

This enhancement also aligns with the auto-id currently used by Github.

**Comment by gettalong** [comment]
I get different results for the text input:

~~~
## Header 1

## Header 2 ![with image][image_url]

## `Header 3`

[image_url]: test.jpg
~~~

auto_id_stripping set to false:

~~~ html
<h2 id="header-1">Header 1</h2>

<h2 id="header-2-with-imageimageurl">Header 2 <img src="test.jpg" alt="with image" /></h2>

<h2 id="header-3"><code>Header 3</code></h2>
~~~

auto_id_stripping set to true:

~~~ html
<h2 id="header-1">Header 1</h2>

<h2 id="header-2-">Header 2 <img src="test.jpg" alt="with image" /></h2>

<h2 id="section"><code>Header 3</code></h2>
~~~

Furthermore it is not clear what the proposed extension should *exactly* do with the header text for every possible kramdown span element.

The current implementation uses all text elements (note: no raw text elements!) for generating the ID.

Also note that the auto_id_stripping option is scheduled to be removed in 2.0, making it the default behavior.

**Comment by chadpowers** [comment]
Thank you for the quick response. So do you see any way to configure or add an option such that code tags are included in the id and image tags are not. This is how Github generates auto-ids, and I wanted to use the same markdown files that are correct for Github in my Jekyll (using kramdown) site.

**Comment by gettalong** [comment]
We would need a new value for the auto_id_stripping option. However, is using the contents of a code span really useful? Normally, the contents of a code span is text mixed with control/markup/syntax characters.

**Comment by chadpowers** [comment]
Agree. Yet I am trying to reproduce the way Github processes markdown for Jekyll. We have documentation with a header:
```
 ### `property.subproperty.value`
```
and the id on Github is `propertysubpropertyvalue`.

To maintain correctness of anchor tags on both the html and github markdown, I was hoping to be able to select which spans to include or not include... or just have default behavior in this case be that like Github.

**Comment by gettalong** [comment]
I understand your problem. However, this is how Markdown works without syntax specification, many things that look nearly the same but aren't. It won't get better until there is something that feels like Markdown but is officially something completely different (CommonMark is JAMS - just another Markdown syntax).

If you have a website built with Jekyll and kramdown, why does Github come into play?

For your specific case I would suggest overriding the `Kramdown::Parser::Kramdown#update_raw_header_text` method. Since the algorithm how Github generates a header ID isn't published (or is it?) there may be other cases where kramdown and GFM differ.

On a side note, now that I have written the abbreviation GFM: kramdown has a GFM parser which isn't bound strictly on how the kramdown parser works. So if this is something that the GFM parser should do (and *not* the main kramdown parser), I'm happy to change it there to make the GFM parser more compatible with how Github works (I'm sorry that this just popped into my mind, I always forget that there is a GFM parser inside the kramdown library ;-).

**Comment by chadpowers** [comment]
Github comes into play under my requirement to have the doc useable/readable on our repo and on the website. For example [this doc](https://github.com/gettalong/kramdown/blob/master/doc/index.page) (and all others) would be marked-up by Github with all the links and formatting correct (like the [README.md](https://github.com/gettalong/kramdown/blob/master/README.md)) _and_ Jekyll or similar static site generator would produce the correct html.

This dual locality is why the auto-id problem arises. So then yes, I think the GFM parser could change to make it more compatible with Github.

**Comment by gettalong** [comment]
Thanks for your explanations! Then I will implement this change in the GFM parser. Do you, by chance, know the exact algorithm Github uses to generate the ID value?

**Comment by chadpowers** [comment]
Thank you! I've been digging for awhile. Starting at https://github.com/github/markup, and then its use of https://github.com/jch/html-pipeline.
I believe the filter is the TableOfContentsFilter found [here](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb), but I haven't pinned down the exact algorithm.

**Comment by gettalong** [comment]
Thanks! It seems that they are using Nokogiri or something similar to parse the HTML and get all the text parts of the header. This should be replicable with kramdown. Will see what I can do.

**Comment by gettalong** [comment]
I have looked at this but didn't have time to implement it - pull requests are welcome!

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1
