### ISSUE TITLE
1.8.0 changelog?

### ISSUE THREAD

**Issue by saizai** [gettalong/kramdown#266]
Don't see anything on changelog / GH releases since 1.5.0. Would be nice to know tl;dr of what's changed w/out having to dig through commits.

**Comment by gettalong** [comment]
Have a look at http://kramdown.gettalong.org/news.html

**Comment by saizai** [comment]
Could this be included in the repo, if simply as a pointer in a changelog
file?

**Comment by gettalong** [comment]
Will think about it.

**Comment by gettalong** [comment]
I have adjusted the readme file to include a pointer to the mentioned link.
