### ISSUE TITLE
Rouge Highlighter Options

### ISSUE THREAD

**Issue by afontaine** [gettalong/kramdown#268]
According to the [docs](http://kramdown.gettalong.org/syntax_highlighter/rouge.html), you can only set `default_lang` and `formatter`, but [the code](https://github.com/gettalong/kramdown/blob/2af9ef8cf0e2b9431c81f6d3dd920e9057ea2177/lib/kramdown/converter/syntax_highlighter/rouge.rb#L25-L31) looks like I can pass in arbitrary Rouge options.

Can I pass in arbitrary Rouge options or am I missing a call that filters out invalid options?

**Comment by gettalong** [comment]
You are right, you can pass any options using the 'syntax_highlighter_opts' to the selected formatter. However, this was an unintended side effect but won't be changed. So I better document it - thanks!

**Comment by afontaine** [comment]
Awesome, thanks!

**Comment by gettalong** [comment]
I have added a note regarding the Rouge options.
