### ISSUE TITLE
Insert prefixes into auto TOC links

### ISSUE THREAD

**Issue by joelweeks** [gettalong/kramdown#269]
I'm using AngularJS ngRoute for link routing, which intercepts hashtag links. This causes problems with named anchors. Because named anchor links start with #, they do not resolve. There are evidently ways to resolve this on AngularJS end, but I'm not having any luck with this approach (nor is a developer looking at this issue).

I could fix this from the Kramdown side with a new option similar to auto_id_prefix, which could be inserted in each markdown file with the value of the AngularJS route.

Assuming this new option is called auto_toc_prefix, it would merely add the specified string ONLY to auto TOC links. These links would thus not work in vanilla HTML pages, but they could when combined with some other routing approach, such as AngularJS.

I can actually construct valid route links in the auto TOC with auto_id_prefix currently, but of course it also inserts these prefixes into the ID values, which does not work.

Example:

Normal named anchor in auto TOC:

```
<li><a href="#GET_employee">GET Employee</a>    <ul>
```

Modified version with AngularJS route, in this case the page is named _employee_:

```
 <li><a href="#/employee/#GET_employee">GET Employee</a>    <ul>
```

With new option the following in the Markdown would insert the correct prefix in auto TOC:
```
{::options auto_toc_prefix="employee/#" /}
```

**Comment by gettalong** [comment]
This option just doesn't make sense for kramdown. If you need this, please write a custom HTML converter that modifies the TOC to work as you like.
