### ISSUE TITLE
With an empty footnote backlink, superscript numerals nonetheless appear in reference list

### ISSUE THREAD

**Issue by kylebarbour** [gettalong/kramdown#270]
It is possible to suppress footnote backlinks by using:

    {::options footnote_backlink="" /}

However, when there are multiple references to a footnote, those superscripts still appear. For example, consider the following test case:

```kramdown
{::options footnote_backlink="" /}
Test sentence 1. [^ref] Test sentence 2. [^ref]

[^ref]:
    Reference.
```

This produces the following HTML output:

```html
<p>Test sentence 1. <sup id="fnref:ref"><a href="#fn:ref" class="footnote">1</a></sup> Test sentence 2. <sup id="fnref:ref:1"><a href="#fn:ref" class="footnote">1</a></sup></p>

<div class="footnotes">
  <ol>
    <li id="fn:ref">

      <p>Reference. <a href="#fnref:ref" class="reversefootnote"></a> <a href="#fnref:ref:1" class="reversefootnote"><sup>2</sup></a></p>
    </li>
  </ol>
</div>
```

which causes the footnote to have an undesired superscript 2 as well as additional undisplayed HTML. It would be nice to have the footnote backlink fully suppressible so that these don't need to be edited out in `sed`.

**Comment by gettalong** [comment]
Thanks, I will have a look at this and then decide.

**Comment by gettalong** [comment]
I have changed the implementation so that an empty `footnote_backlink` option will suppress the output of all backlinks.

**Comment by kylebarbour** [comment]
Thank you!
