### ISSUE TITLE
"include" syntax in the demo code is Interpreting somehow

### ISSUE THREAD

**Issue by kamlekar** [gettalong/kramdown#277]
I am using Kramdown markdown in Jekyll blog template for my site which is getting published on github from [here](http://github.com/kamlekar/kamlekar.github.io). 

In one of the `.md` files, I wrote a sample demo code which is something like this:

     {% include "_head.html" %}

After inserting this code in my post and running my site, I am getting "page build" error.

You can find the file [here](https://github.com/kamlekar/kamlekar.github.io/blob/master/_posts/2015-08-26-compiling-html-templates-to-html-pages.md).

Thanks in Advance.

**Comment by gettalong** [comment]
This doesn't seem to be a kramdown related question as you are asking regarding an error when running Jekyll. Please ask the Jekyll maintainers.
