### ISSUE TITLE
enable_coderay: false doesn't work when GFM enabled

### ISSUE THREAD

**Issue by jhalterman** [gettalong/kramdown#278]
Using kramdown 1.8.0. When I set `enable_coderay` to false with GFM enabled, coderay still highlights my fenced code blocks.

**Comment by jhalterman** [comment]
Found a workaround by setting `syntax_highlighter: none`. Fine for me.

**Comment by gettalong** [comment]
Yeah, the `enable_coderay` option is deprecated in favor of the more general `syntax_highlighter` option.
