### ISSUE TITLE
Code Fence does not work inside of inline html

### ISSUE THREAD

**Issue by f41c0r** [gettalong/kramdown#280]
According to the [markdown](https://daringfireball.net/projects/markdown/syntax#html) spec: 

"For any markup that is not covered by Markdown’s syntax, you simply use HTML itself. There’s no need to preface it or delimit it to indicate that you’re switching from Markdown to HTML; you just use the tags."

If the below behavior is intended, great, but based on the above quote, I am under the impression that this is a bug:

```markdown
<p>typing something `like` this</p>
```
renders to 
```html
<p>typing something `like` this</p>
```
instead of the behavior I expected, which would have been this:
```html
<p>typing something <code>like</code> this</p>
```
using kramdown 1.8.0 installed from ruby gems with ruby 2.2.0

**Comment by gettalong** [comment]
The markdown spec is mostly irrelevant for kramdown, and probably all other advanced implementations. See http://kramdown.gettalong.org/syntax.html#html-blocks instead. There you will find that block HTML tags are not parsed as kramdown markup by default. However, you can change that by adding a `markdown="1"` attribute.

So this is the intended behavior.
