### ISSUE TITLE
the '{{#}}' in the markdown

### ISSUE THREAD

**Issue by blueforest** [gettalong/kramdown#284]
I use kramdown in jeklly,now I meet a problem,I write a html code block in markdown,like this
```
<table class="table">
<tbody>
    <tr>
        {{#columns}}
            <td>{{.label}}</td>
        {{/columns}}
    </tr>
    {{#rows:rowIndex}}
        <tr>
            {{#columns:columnIndex}}
                <td>
                    {{rows[rowIndex][.field]}}
                </td>
            {{/columns}}
        </tr>
    {{/rows}}
</tbody>
</table>
```
but the code like this '{{#columns}}' dose not appear in the HTML,
<img width="131" alt="code" src="https://cloud.githubusercontent.com/assets/2793416/9808590/125a56d8-5893-11e5-9144-cece6d8d2040.png">
what is the problem here?

**Comment by gettalong** [comment]
Can you give more details? When I run the sample you provided through kramdown (by enclosing it in a fenced code block) I get the following result which seems right:

~~~ html
<pre><code>&lt;table class="table"&gt;
&lt;tbody&gt;
    &lt;tr&gt;
        {{#columns}}
            &lt;td&gt;{{.label}}&lt;/td&gt;
        {{/columns}}
    &lt;/tr&gt;
    {{#rows:rowIndex}}
        &lt;tr&gt;
            {{#columns:columnIndex}}
                &lt;td&gt;
                    {{rows[rowIndex][.field]}}
                &lt;/td&gt;
            {{/columns}}
        &lt;/tr&gt;
    {{/rows}}
&lt;/tbody&gt;
&lt;/table&gt;
</code></pre>
~~~

**Comment by gettalong** [comment]
@blueforest As I stated I can't reproduce your problem. If it still exists, I will re-open this issue.
