### ISSUE TITLE
Inline code broken with Rouge and line numbers

### ISSUE THREAD

**Issue by reitzig** [gettalong/kramdown#286]
I use kramdown with Rouge in my Jekyll site.

I notice that kramdown compiles inline code to `<code class="highlighter-rouge">inline code</code>` instead of simply `<code>...</code>`. While it would be nice to be able to turn off highlighting in inline code, no biggy.

When I set `line_numbers: true`, however, things get ugly: Rouge can or does not distinguish between inline and block code, and translates the inline code into a block with line numbers -- clearly not as intended!

(The created code looks broken beyond that, too.)

**Comment by gettalong** [comment]
Thanks for reporting this!

To mitigate the problem I have implemented the following changes:

* Globally enabling rouge as syntax highlighter and disabling span and/or block highlighting is now possible by using the new "disable" option.

* Options can now be set for both spans and blocks as well as only for spans or only for blocks. This enables you to turn on the line numbers for blocks but not for spans.

**Comment by tdbe** [comment]
> using the new "disable" option

> Options can now be set for both spans and blocks as well as only for spans or only for blocks

Could you please provide a usage example of what that syntax looks like?

All I understood is that you now have that capability and flexibility. But how exactly do I fix the inline code while having `line_numbers: true` on the code blocks?

**Comment by gettalong** [comment]
kramdown doesn't have a `_config.yml` file. You need to use the ['syntax_highligher_opts'](http://kramdown.gettalong.org/options.html#option-syntax-highlighter-opts) configuration option as described on the documentation page for the [rouge syntax highlighter](http://kramdown.gettalong.org/syntax_highlighter/rouge.html).

Where you set this option depends on how use kramdown, e.g. if you are using the binary, you would do something like the following:

~~~
kramdown --syntax-highlighter rouge --syntax-highlighter-opts "{span: {disable: true}}"
~~~

**Comment by tdbe** [comment]
Oh I see where you're coming from but I was referring to the OP's context, ie using Jekyll with github's builtin markdown compilers. But thanks for the docs links.

Githyb jekyll needs something [like this](http://hustlei.tk/2014/08/jekyll-dir-and-config.html) in a _config.yml:

`
kramdown:
  syntax_highlighter: rouge 
  syntax_highlighter_opts:
    default_lang: c
    block:
      line_numbers: true
      start_line: 1
    inline_theme: colorful
    wrap: true
`
But this^ is not quite working out. I'll have to figure out why and come back.

**Comment by gettalong** [comment]
Please ask the Jekyll team - thanks!
