### ISSUE TITLE
Enable longer dashes

### ISSUE THREAD

**Issue by reitzig** [gettalong/kramdown#287]
Currently, kramdown translates inline `--` and `---` to simple dashes.

It *could* translate them to `&ndash;` and `&mdash;`, respectively. That would be nice not only because it gives more flexibility to authors, but also because it would be consistent with LaTeX.

(FWIW, while certainly not all other Markdown compilers do this, I know that [pandoc does](http://pandoc.org/README.html#smart-punctuation).)

**Comment by gettalong** [comment]
kramdown already does this - see http://kramdown.gettalong.org/syntax.html#typographic-symbols

**Comment by reitzig** [comment]
I did not see this behaviour but retrying I do. Maybe I tried in a place where Jekyll did not actually markdownify. My bad, sorry for the inconvenience.
