### ISSUE TITLE
Problem rendering text between two horizontal rules 

### ISSUE THREAD

**Issue by julianofischer** [gettalong/kramdown#291]
Hi!
I am using kramdown 1.9.0.

The following should render the text with two horizontal rules, one above and another below the text.
    ---
    Text
    ---
    ***
    Text
    ***

However, the result is:

![captura_de_tela-3](https://github-cloud.s3.amazonaws.com/assets/158303/10565686/b4dd9886-75b5-11e5-9524-b7d2547fda96.png) 

That is, only the horizontal rule above the text is rendered and the text is succeeded by --- (or ***, both cases lead to the same behavior).

However, adding a blank line below text solves the "problem".

I do not know if it is a bug or a design option.
In the latter case, I apologize.
Thank you very much for your attention.

**Comment by gettalong** [comment]
Yes, this is intentional.
