### ISSUE TITLE
Relaxing Email/URL validation for autolinking?

### ISSUE THREAD

**Issue by erikse** [gettalong/kramdown#293]
Would it be possible to relax the validation of email addresses for autolinking? 

Even just simple non-alphanum characters like underscore seem to be disallowed in Ruby 2.x

* with underscore, no autolinking

```ruby
require 'kramdown'
=> true 

text = %{
$C
Email: <t_leitner@gmx.at>
$C
}
=> "\n$C\nEmail: <t_leitner@gmx.at>\n$C\n" 
 
Kramdown::Document.new(text).to_html
=> "\n<p>$C\nEmail: &lt;t_leitner@gmx.at&gt;\n$C</p>\n" 
```

*  without underscore, autolinking

```ruby
require 'kramdown'
=> true 

text = %{
$C
Email: <t.leitner@gmx.at>
$C
}
 => "\n$C\nEmail: <t.leitner@gmx.at>\n$C\n" 

Kramdown::Document.new(text).to_html
=> "\n<p>$C\nEmail: <a href=\"&#109;&#097;&#105;&#108;&#116;&#111;:&#116;&#046;&#108;&#101;&#105;&#116;&#110;&#101;&#114;&#064;&#103;&#109;&#120;&#046;&#097;&#116;\">&#116;&#046;&#108;&#101;&#105;&#116;&#110;&#101;&#114;&#064;&#103;&#109;&#120;&#046;&#097;&#116;</a>\n$C</p>\n" 
```

**Comment by gettalong** [comment]
In those cases you can prepend the protocol (ie. `<mailto:t_leitner@gmx.at>`) and it will work.

However, the underscore is definitely missing from the allowed characters for Ruby versions >= 1.9.0 in the protocol-less form - thanks for reporting!

Adding anything other than underscore would potentially break backwards-compatibility.

**Comment by erikse** [comment]
Thank you! Have been using ```<mailto: .. >``` prefix and that works, but nice to have the option without thanks for adding the underscore @gettalong

**Comment by benhyland** [comment]
Similarly, we ran into an issue with apostrophes in email links:

```ruby
=> "Email without apostrophe <foo@example.com>"
irb(main):019:0> Kramdown::Document.new(text).to_html
=> "<p>Email without apostrophe <a href=\"&#109;&#097;&#105;&#108;&#116;&#111;:&#102;&#111;&#111;&#064;&#101;&#120;&#097;&#109;&#112;&#108;&#101;&#046;&#099;&#111;&#109;\">&#102;&#111;&#111;&#064;&#101;&#120;&#097;&#109;&#112;&#108;&#101;&#046;&#099;&#111;&#109;</a></p>\n"
irb(main):020:0> text = "Email with apostrophe <fo'o@example.com>"
=> "Email with apostrophe <fo'o@example.com>"
irb(main):021:0> Kramdown::Document.new(text).to_html
=> "<p>Email with apostrophe &lt;fo’o@example.com&gt;</p>\n"
irb(main):022:0> text = "Email with apostrophe <mailto:fo'o@example.com>"
=> "Email with apostrophe <mailto:fo'o@example.com>"
irb(main):023:0> Kramdown::Document.new(text).to_html
=> "<p>Email with apostrophe <a href=\"&#109;&#097;&#105;&#108;&#116;&#111;:&#102;&#111;&#039;&#111;&#064;&#101;&#120;&#097;&#109;&#112;&#108;&#101;&#046;&#099;&#111;&#109;\">&#102;&#111;&#039;&#111;&#064;&#101;&#120;&#097;&#109;&#112;&#108;&#101;&#046;&#099;&#111;&#109;</a></p>\n"
```

Using `mailto` in the link works.
Apostrophe is valid in email addresses in the local part.
I didn't understand the reason to decide not to fix this in the previous example - can you explain any further?
Many thanks.

**Comment by erikse** [comment]
There seems to be some Ruby version dependency in the mailto autolinking, Ideally, the format of the mailto link would be agnostic of this, but maybe it's hard to write a regex that works across Ruby versions, eg.

https://github.com/gettalong/kramdown/blob/af7e0feb7a19a704c630c145535dbef9102871a8/lib/kramdown/parser/kramdown/autolink.rb#L14-L21

**Comment by gettalong** [comment]
@benhyland @erikse The shorthand version only works for the most common case, for everything else the full version including 'mailto:' has to be used.
