### ISSUE TITLE
MathJax display math 

### ISSUE THREAD

**Issue by s1ddok** [gettalong/kramdown#294]
Default MathJax uses $ for inline math and $$ for display math. But in kramdown we need to use $$ all the time, so all my math comes inline, which is crucially bad for me. How can I use display math but still be able to use kramdown?

**Comment by gettalong** [comment]
Could you provide a sample input, the wrong output kramdown gives and the output you would like to have? Because I don't really know what the problem seems to be...

**Comment by s1ddok** [comment]
Ok, it isn't a wrong output it is more like a general problem of how kramdown treats $$ and doesn't recognize $. 

Sometimes you want math to be inline, like so:
     ```%text% $inline math here$ %other text%```
That's how stock MathJax works and produce effect like so:
![example]
(https://i.gyazo.com/38f538b23a0eaf05926ae515f7c6733a.png)

And sometimes you want display math bahaviour.
In stock MathJax you would do:
```%some text% $$display math$$ %some text%```
And will receive this effect:
![example]
(https://i.gyazo.com/b66760f3acc3c992e37af3abbab538f6.png)

But becuase of kramdown only understands $$ and treat it as inline math all my math becomes inline.

I know, of course, that you can wrap something in html-block and tell kramdown to skip it during parsing, but it seems dirty and comlicated. Is there a way to make kramdown differ $ and $$?

**Comment by gettalong** [comment]
The reason why both inline and block math use `$$` is that you can't start another block inside a paragraph. So if you want to have inline math use

~~~
This is some text $$some=equation$$ followed by text.
~~~

and if you want to use a math block do this:

~~~
This is some text:

$$some=block-equation$$

Some other text here (just another paragraph)
$$

This is the way to write things like this when using kramdown. You can't compare this directly to writing HTML and MathJax.

**Comment by s1ddok** [comment]
I tried that! It doesn't seem to work. This code:
```something1

$$\lambda_i=\lambda_j$$

something```

Produces this:

![img]
(https://i.gyazo.com/b00dbba7701c9fb8840f1fe532fed334.png)

**Comment by gettalong** [comment]
This is the output from kramdown:

~~~ html
<p>something1</p>

<script type="math/tex; mode=display">\lambda_i=\lambda_j</script>

<p>something</p>
~~~

So it does what is expected. Which command did you use to convert the input to HTML?

**Comment by s1ddok** [comment]
Well, I get the following:
![img]
(https://i.gyazo.com/ffdc3ac49501bec417597e2661f8b552.png)

for this:
```
...
   $$\lambda_i=\lambda_j$$
something1

$$\lambda_i=\lambda_j$$

something

Тогда жорданова форма матрицы имеет вид
...
```

And it seems like all my results are string with ignored paragraphs. 

I've tried to add this to the top of my document
```
{::options hard_wrap="true" /}
```

How do I force kramdown respect my paragraphs?

**Comment by gettalong** [comment]
Your screenshot is from the inspector, you will need to show the source code, i.e. what kramdown *really* generated, so that I can say more. Ie. the source with the HTML code kramdown generated.

If you are using kramdown inside another library/application, make sure that the library/application doesn't interfere with kramdown.

**Comment by s1ddok** [comment]
Ok here is what I get, exactly as it apears in Atom editor.
``` html
<p class="right example1">
1. Пусть характеристический многочлен матрицы <script type="math/tex">A_\epsilon</script> имеет вид

<script type="math/tex">\phi(\lambda)=(-1)^3(\lambda-\lambda_1)(\lambda-\lambda_2)(\lambda-\lambda_3),</script>
где <script type="math/tex">\lambda_i=\lambda_j</script> <script type="math/tex">(i=j)</script>.
   <script type="math/tex">\lambda_i=\lambda_j</script>
something1

<script type="math/tex">\lambda_i=\lambda_j</script>

something

Тогда жорданова форма матрицы имеет вид
<script type="math/tex">% <![CDATA[
A_f=\left\{
\begin{array}{lll}
\lambda_1 & 0 & 0\\
0 & \lambda_2 & 0\\
0 & 0 & \lambda_3
\end{array}
\right\}. %]]></script>
 </p>
```

For this kramdown code:
```
<p class="right example1" markdown="1">
1. Пусть характеристический многочлен матрицы $$A_\epsilon$$ имеет вид

$$\phi(\lambda)=(-1)^3(\lambda-\lambda_1)(\lambda-\lambda_2)(\lambda-\lambda_3),$$
где $$\lambda_i=\lambda_j$$ $$(i=j)$$.
   $$\lambda_i=\lambda_j$$
something1

$$\lambda_i=\lambda_j$$

something

Тогда жорданова форма матрицы имеет вид
$$A_f=\left\{
\begin{array}{lll}
\lambda_1 & 0 & 0\\
0 & \lambda_2 & 0\\
0 & 0 & \lambda_3
\end{array}
\right\}.
 $$
 </p> 
```

**Comment by gettalong** [comment]
First, you shouldn't use a paragraph tag if you are gonna use block markup inside. Use a `<div>` or something, then the list in the first line and the block math is converted correctly.

**Comment by s1ddok** [comment]
Oh, my bad! Thanks!
