### ISSUE TITLE
gbk error when convert markdown to latex source

### ISSUE THREAD

**Issue by HereChen** [gettalong/kramdown#295]
excute (windows 7 x64, kramdown 1.9.0):
kramdown -o latex test.md >test.tex

error:
....
The source text contains invalid characters for the used encoding GBK
....

Do kramdown converter surpport GBK?
Thanks. :)

**Comment by gettalong** [comment]
Haven't tested it but should be no problem. Just make sure that the source text **does** contain only GBK characters!

If in doubt, please make the file available so that I can test it.
