### ISSUE TITLE
Global options for includes

### ISSUE THREAD

**Issue by s1ddok** [gettalong/kramdown#297]
I'm building my site using slate and kramdown. Is there a way to apply an option globally, I mean do it once in index.md and so it will affect every file in `includes`?

I dont like placing the same exact line in the beginning of every .md file :(

**Comment by gettalong** [comment]
If you are using kramdown via another tool, you have to ask the developers of this other tool how they support kramdown. For example, [webgen](http://webgen.gettalong.org) supports kramdown and global options.
