### ISSUE TITLE
<mark> treated as block tag

### ISSUE THREAD

**Issue by ndarville** [gettalong/kramdown#298]
Using <mark>Seems to have the result of removing `<p>` tags when writing in [Jekyll](https://github.com/hafniatimes/hafniatimes.github.io).

Markdown input:
```markdown
Lorem ipsum.

<mark>Test</mark>

<mark>Foobar</mark>
```

HTML output:
```html
<p>Lorem ipsum.</p>

<mark>Test</mark>

<mark>Foobar</mark>
```

```sh
$ bundle exec kramdown -v
1.9.0
```

I thought it might have to do with the tag being treated as an unknown tag or a block tag given the behaviour, but the main problem is that using `markdown=“1"` and `markdown="span"` doesn’t fix it either.

I take it this can’t be expected behaviour, at least if you can’t mitigate it with the `markdown` attribute. Or does is it “not working, as expected”, if you will? :)

I’ll be using `<span class="highlight">` for now, but that’s obviously not ideal for a number of reasons.

**Comment by gettalong** [comment]
Sorry, I don't fully understand the problem. The `<mark>` tag is not a valid HTML tag. Can you provide input, current output and expected output?

**Comment by ndarville** [comment]
Has it been [deprecated](http://www.w3.org/TR/html5/text-level-semantics.html#the-mark-element)?

**Comment by gettalong** [comment]
Ah, okay, didn't know that it was a HTML5 tag. Okay, so this is a span-level tag like `<b>`. And what is the exact problem?

**Comment by ndarville** [comment]
The rendered HTML is

```html
<p>Lorem ipsum.</p>

<mark>Test</mark>

<mark>Foobar</mark>
```

when it should be 

```html
<p>Lorem ipsum.</p>

<p><mark>Test</mark></p>

<p><mark>Foobar</mark></p>
```

```diff
- <mark>Test</mark>
+ <p><mark>Test</mark></p>

- <mark>Foobar</mark>
+ <p><mark>Foobar</mark></p>
```

**Comment by gettalong** [comment]
Okay, that should be easy to fix - thanks for the bug report!

**Comment by ndarville** [comment]
No problem, appreciate the fast reply!

**Comment by ndarville** [comment]
:+1:
