### ISSUE TITLE
Admonition Support

### ISSUE THREAD

**Issue by dcode** [gettalong/kramdown#300]
Python Markdown is one of the only markdown implementations that provide [admonition](https://pythonhosted.org/Markdown/extensions/admonition.html) support. I'd like to see this in kramdown as well. I was looking to start using Kramdown in Jekyll or maybe in some direct tooling to build PDF documents via LaTeX.

The HTML render is trivial and could just take the existing work from Python Markdown:

```
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>You should note that the title will be automatically capitalized.</p>
</div>
```

And for LaTeX either take the [DB2LaTeX transform](http://db2latex.sourceforge.net/reference/rn05re53.html) or the [ASCIIdoc transform](https://github.com/asciidoctor/asciidoctor-latex/blob/7a26dd019df5ad818de9d2918b88942e38b19da9/data/asciidoc_tex_macros.tex) 

```
\admonition{WARNING}{Watch out for dragons!}
```

The LaTeX environment like this would make it simple to adjust using LaTeX styling.

**Rationale**: Lots of authors are migrating to using Markdown for writing technical documentation and books. I love using Markdown for general documentation, but more detailed technical documentation often needs additional features. Others have worked around this using embedded HTML, but that gets awfully verbose and means the author has to keep track to make sure every usage is presented exactly the same. Additionally, if one wishes to render LaTeX from the same source, they're out of luck.

Thanks! :grinning:

**Comment by gettalong** [comment]
For this to work the syntax would need to be changed which cannot be done in 1.x, only in 2.x.

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1

**Comment by deeplow** [comment]
@gettalong any update on this?

**Comment by gettalong** [comment]
@deeplow No, not really. I rather hesitant to add new syntax features due to backwards compatibility. However, admonition support could easily be added via a new custom parser if you need it sooner than later.

**Comment by deeplow** [comment]
I see. Thanks for the reply @gettalong. 

>  However, admonition support could easily be added via a new custom parser if you need it sooner than later.

Thanks for the suggestion. It may be worth considering. I am not too familiar with ruby, though. Is this a matter of extending [the base class](https://kramdown.gettalong.org/rdoc/Kramdown/Parser/Base.html) to add the extra functionality or should it be based on another class?

**Comment by gettalong** [comment]
I would not extend the base class since that doesn't contain any parsing functionality itself but the kramdown parser itself. Have a look at the `parser-gfm` implementation at https://github.com/kramdown/parser-gfm/blob/master/lib/kramdown/parser/gfm.rb to see an example. You can probably take that and modify it to your needs.

**Comment by gettalong** [comment]
Admonitions can be done via extension in VersaDok, the spiritual successor to kramdown: https://github.com/gettalong/versadok
