### ISSUE TITLE
Remove HTML Tags converter doesn't remove HTML tags

### ISSUE THREAD

**Issue by jsdalton** [gettalong/kramdown#301]
The RemoveHtmlTags converter just doesn't seem to work:

```
> require 'kramdown'
=> true
> doc = ::Kramdown::Document.new('<h1>This is a <b>real</b> header</h1>', input: 'html')
=> <KD:Document: options={:template=>"", :auto_ids=>true, :auto_id_stripping=>false, :auto_id_prefix=>"", :transliterated_header_ids=>false, :parse_block_html=>false, :parse_span_html=>true, :html_to_native=>false, :link_defs=>{}, :footnote_nr=>1, :enable_coderay=>true, :coderay_wrap=>:div, :coderay_line_numbers=>:inline, :coderay_line_number_start=>1, :coderay_tab_width=>8, :coderay_bold_every=>10, :coderay_css=>:style, :coderay_default_lang=>nil, :entity_output=>:as_char, :toc_levels=>[1, 2, 3, 4, 5, 6], :line_width=>72, :latex_headers=>["section", "subsection", "subsubsection", "paragraph", "subparagraph", "subparagraph"], :smart_quotes=>["lsquo", "rsquo", "ldquo", "rdquo"], :remove_block_html_tags=>true, :remove_span_html_tags=>false, :header_offset=>0, :hard_wrap=>true, :syntax_highlighter=>:coderay, :syntax_highlighter_opts=>{}, :math_engine=>:mathjax, :math_engine_opts=>{}, :footnote_backlink=>"&#8617;", :input=>"html"} root=<kd:root nil {:encoding=>#<Encoding:UTF-8>, :location=>1, :options=>{}, :abbrev_defs=>{}, :abbrev_attr=>{}} [<kd:header {} {:level=>1, :raw_text=>"This is a real header"} [<kd:text "This is a " nil>, <kd:strong {} [<kd:text "real" nil>]>, <kd:text " header" nil>]>]> warnings=[]>
> doc.to_remove_html_tags
=> <kd:root nil {:encoding=>#<Encoding:UTF-8>, :location=>1, :options=>{}, :abbrev_defs=>{}, :abbrev_attr=>{}} [<kd:header {} {:level=>1, :raw_text=>"This is a real header"} [<kd:text "This is a " nil>, <kd:strong {} [<kd:text "real" nil>]>, <kd:text " header" nil>]>]>
> doc.to_html
=> "<h1 id=\"this-is-a-real-header\">This is a <strong>real</strong> header</h1>\n"
```

So it does appear to be correctly parsing the input HTML, as can be seen in the KD:Document object that gets outputted.

Digging in to the code of the remove html converter, I'm looking at this line here:

https://github.com/gettalong/kramdown/blob/REL_1_9_0/lib/kramdown/converter/remove_html_tags.rb#L40

There appears to be some logic which identifies block level elements:

```
(@options[:remove_block_html_tags] && children[index].options[:category] == :block)
```

However, the parser itself, when ingesting the HTML, does not appear to be assigning a `:category` option to the `Element`, so that bit of logic is coming up blank.

Interestingly there's a class method `self.category` located here:

https://github.com/gettalong/kramdown/blob/REL_1_9_0/lib/kramdown/element.rb#L512

That *does* in fact correctly identify a block level element. Continuing from the irb session above:

```
> element = doc.root.children[0]
=> <kd:header {} {:level=>1, :raw_text=>"This is a real header"} [<kd:text "This is a " nil>, <kd:strong {} [<kd:text "real" nil>]>, <kd:text " header" nil>]>
irb(main):009:0> ::Kramdown::Element.category(element)
=> :block 
```

... but this method is not used by the Remove HTML Tags converter.

Not sure if this is a bug or maybe I'm using this library incorrectly, but I could find no examples in the documentation or around the web that showed how to use this converter properly with a correct result.

**Comment by gettalong** [comment]
The "remove HTML converter" removes HTML tags from the input, i.e. elements of type 'html_element'.

If you use the HTML parser as input parser, all HTML elements that kramdown understands are automatically converted to their native representation. Therefore no HTML tags are removed in your example because there are none.
