### ISSUE TITLE
URLs are not autolinked in GFM mode

### ISSUE THREAD

**Issue by benbalter** [gettalong/kramdown#306]
Per https://help.github.com/articles/autolinked-references-and-urls/#urls, in GFM, URLs should automatically become links, even when not wrapped in `<` and `>`.
## Steps to reproduce

`Link http://example.com`
## Expected

`Link <a href="http://example.com">http://example.com>
## Actual

`Link http://example.com`

**Comment by gettalong** [comment]
Thanks for pointing this out but without the inside knowledge of what GFM **actually** supports I can't properly implement this.

**Comment by benbalter** [comment]
> without the inside knowledge of what GFM actually supports I can't properly implement this.

Did a little digging, and it looks like [the autolink filter in HTML pipeline](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/autolink_filter.rb), uses [Rinku](https://github.com/vmg/rinku), a Ruby gem which implements autolinking. It'd be an additional dependency, so its your call, but maybe make it an optional dependency that autolinks if present?

**Comment by gettalong** [comment]
I would accept a pull request with Rinku being an optional dependency for kramdown. However, it should then be mentioned in kramdown's GFM docs that Rinku has to be installed for the GFM parser to work correctly.

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1

**Comment by zhengjia** [comment]
I attempted to fix this in https://github.com/gettalong/kramdown/pull/528. Hopefully someone can finish it off or work on a better fix.

**Comment by cup** [comment]
https://github.com/gettalong/kramdown/issues/306
https://github.com/gettalong/kramdown/issues/490
https://github.com/gettalong/kramdown/pull/528

**Comment by cup** [comment]
@gettalong why was this closed if it was not fixed?

**Comment by gettalong** [comment]
@cup See [my comment above](https://github.com/gettalong/kramdown/issues/306#issuecomment-258595190)

**Comment by cup** [comment]
I saw it before I posted mine. Can we please reopen the issue until it is actually fixed. Or is this a won't fix issue

**Comment by gettalong** [comment]
If someone is actively working on a fix, we can re-open. All open pull requests/issues that need actions from contributers are tracked through the dedicated project.

**Comment by cup** [comment]
That project is just a collection of issues. Creating the project doesn't change the convention of closing issues when they are actually fixed, and shouldn't. By this issue being closed it gives the impression that it's either fixed or won't fix, neither of which are true.

What is disconcerting is that GFM already supports this as does red carpet, but only kramdown is supported for GitHub pages. So you have to write different markdown in this regard.

Please consider reopening thank you.

**Comment by gettalong** [comment]
The reason for having the project is to collect all issues needing work done by contributors. Once somebody works on such an issue I'm glad to reopen it. But until then these issues just clobber the issue tracker.

As for the issue at hand: As indicated by the label, pull requests for resolving this feature requests are welcome!

**Comment by cup** [comment]
ok. i disagree with your methods but this is your repo.

cheers.

**Comment by cup** [comment]
Here is a workaround for any interested. Just add to your `default.html` or
similar:

~~~js
document.querySelectorAll('p, li').forEach(b => {
   let k = b.innerHTML;
   if (RegExp('^https?://').test(k))
   {
      let z = document.createElement('a');
      z.href = z.textContent = k;
      b.firstChild.replaceWith(z);
   }
});
~~~

http://github.com/cup/umber/tree/master/javascript/autolink

**Comment by cup** [comment]
For anyone using GitHub Pages, you can simply add this to `_config.yml`:

~~~
markdown: CommonMarkGhPages
commonmark:
   extensions:
   - autolink
~~~

you dont even have to declare the plugin in `_config.yml` as its activated by
default:

http://github.com/github/pages-gem/blob/fb5c3f2/lib/github-pages/plugins.rb#L9

reference:

http://github.com/github/jekyll-commonmark-ghpages

**Comment by gettalong** [comment]
@benbalter The GFM parser has been extracted from the main kramdown distribution. If this issue should be resolved, please create a ticket at https://github.com/kramdown/parser-gfm/issues since I can't transfer this issue there. Thank you!
