### ISSUE TITLE
Unordered list containing number with trailing dot

### ISSUE THREAD

**Issue by Brixy** [gettalong/kramdown#309]
Hi!

Not sure, whether this is intended.

```
- 11. Februar
- 12. Februar
```

results in:

```
<ul>
<li><ol>
<li>Februar</li>
</ol></li>
<li><ol>
<li>Februar</li>
</ol></li>
</ul>
```

Pandoc result:

```
<ul>
<li><ol start="11" style="list-style-type: decimal">
<li>Februar</li>
</ol></li>
<li><ol start="12" style="list-style-type: decimal">
<li>Februar</li>
</ol></li>
</ul>
```

This would also be ok:

```
<ul>
<li><p>11. Februar</p></li>
<li><p>12. Februar</p></li>
</ul>
```

Of course, you can use escapes like `- 11\. Feburar`.

Thank you!

**Comment by gettalong** [comment]
As your example points out, the Pandoc result is basically the same as kramdown's result, i.e. nested ordered lists are created. *And* this is exactly what should happen in kramdown as the content of a list item are block level elements.

If you don't want the nested list, you have to escape the dot, i.e. `* 11\. Februar`.
