### ISSUE TITLE
GIs and attribute names in embedded xml are converted to lower case

### ISSUE THREAD

**Issue by cabo** [gettalong/kramdown#310]
I haven't fully analyzed this, but I note that kramdown is less useful with embedded XML as all GIs (element names) and attribute names are converted to lower case.  Quite a few authors of XML schemas think these can only be considered profeSsiOnal wHen thEy uSe a loT of CamelCase.

**Comment by gettalong** [comment]
Thanks for the observation - since XML tags/attribute names are case-sensitive this is actually unwanted behavior.

I originally thought only of HTML tags/attribute names and those are case-insensitive, so this is definitely a bug to be fixed.

**Comment by gettalong** [comment]
This will take a bit of tinkering since HTML is case-insensitive. So the HTML tags need  to be parsed case-insensitive and the XML ones case sensitive.

**Comment by gettalong** [comment]
@cabo The fix for this is in the repository and will be in the next version due later today.
