### ISSUE TITLE
Docs installation issue

### ISSUE THREAD

**Issue by zaufi** [gettalong/kramdown#314]
Hi,

trying 

    ruby setup.rb install --prefix=`pwd`/installed

I've found no documentation  installed. Is there a proper way to install syntax related docs?

**Comment by gettalong** [comment]
Which docs do you mean?

If you install kramdown via Rubygems you can generate the API docs (either as HTML or for `ri`). However, the syntax specification is part of the website in the `doc/` subdirectory and is never automatically built. You can do that by running `webgen` (`gem install webgen`) in the kramdown source directory.

**Comment by zaufi** [comment]
Yes, I meant to build syntax specification (as a part of Gentoo ebuild process) for offline reading...

**Comment by gettalong** [comment]
@zaufi  Okay. As I said the syntax spec is part of the kramdown website, so you need to run webgen to build it. Or if you just want that page converted to HTML, strip everything until and including the line "--- name:content" from `doc/syntax.page` and use kramdown to convert it to HTML.

**Comment by zaufi** [comment]
Thanks, this sounds better than inject one more build dependency to ebuild ;)
