### ISSUE TITLE
Docs 404 link

### ISSUE THREAD

**Issue by tmcw** [gettalong/kramdown#315]
On the landing page of Kramdown's docs, the link to Kramdown::Document is a 404:

![2016-02-19 at 9 59 am](https://cloud.githubusercontent.com/assets/32314/13178967/8d321ac8-d6ef-11e5-9034-630e5cb7e7b3.png)

The link goes to http://kramdown.gettalong.org/Kramdown/Document.html

**Comment by gettalong** [comment]
Thanks! This is an automatically created link, so it seems to be a problem with RDoc.

**Comment by gettalong** [comment]
I have worked around the issue - thanks for reporting. The fix will be live with the next release.
