### ISSUE TITLE
Code blocks inside lists are not rendered with pre tags

### ISSUE THREAD

**Issue by tomjohnson1492** [gettalong/kramdown#316]
When you have code blocks appearing within lists, the code blocks aren't set off with `pre` tags. Instead, they're getting set off with `code` tags. I elaborated in detail about this in this post: [Verifiable Bug with code blocks inside list items using Kramdown and Rouge on Github Pages](http://bit.ly/kramdownrougebug)

Here's a sample showing the issue: [https://github.com/tomjohnson1492/kramdowntest](https://github.com/tomjohnson1492/kramdowntest)

**Comment by gettalong** [comment]
See my answer at https://github.com/tomjohnson1492/kramdowntest/issues/1

**Comment by geraldb** [comment]
FYI: @tomjohnson1492  I've updated the example with the help of Thomas Leitner - the kramdown developer. It works!

All you have to fix is your indentation e.g. use three spaces max. for your code block (for level 1) and 3+4 e.g. 7 spaces max. for your code block (for level 2) and so on. See the sample [source](http://planetjekyll.github.io/sandbox-syntax-highlighter/lists.html) and [rendered with GitHub Pages](https://github.com/planetjekyll/sandbox-syntax-highlighter/blob/gh-pages/lists.md). Cheers.
