### ISSUE TITLE
Pipe characters in text creates table

### ISSUE THREAD

**Issue by bobrocke** [gettalong/kramdown#317]
A single `|` in a paragraph creates a table when it should not.

```
If you | have a number
```

or

```
**Edit | Edit All Selected Variants**
```

is enough to do it.

Escaping the `|` like this `\|` works around the bug.

**Comment by gettalong** [comment]
This is currently the intended behaviour.

**Comment by bobrocke** [comment]
Why would it be intended? When run through Babelmark, kramdown is the only implementation generating a table:

http://johnmacfarlane.net/babelmark2/?text=If+you+have+a+number+of+images+selected%2C+and+have+**Edit+%7C+Edit+All+Selected+Variants**+checked%2C+typing+metadata+into+a+metadata+field+in+the+Metadata+tool+does+not+apply+that+change+to+all+the+selected+images.+I+would+expect+to+be+able+to+select+images+and+apply+or+edit+metadata+for+them+all+at+once.

**Comment by gettalong** [comment]
Most other implementations don't support tables or support them in another way, so you wouldn't see that on Babelmark.

**Comment by bobrocke** [comment]
While it is certainly your call, I think you'll find that at least Parsedown, Markdown Extra, MultiMarkdown, RedCarpet, GFM, and probably, several others implement tables with `|`.

**Comment by bobrocke** [comment]
And kramdown documentation says the table implementation is based on Markdown Extra, which does not behave that way with a `|`:

```
This syntax feature is not part of the original Markdown syntax. The syntax is based on the one from the PHP Markdown Extra package.
```

**Comment by paulmenzel** [comment]
Also having the problem, I kind of agree with bobrocke.

Would it be possible to change the [syntax](http://kramdown.gettalong.org/syntax.html), so that the pipe character is required to be first on a line?

**Comment by gettalong** [comment]
The syntax could be changed but only for the 2.0 version of kramdown, see #151.

**Comment by whuwangyong** [comment]
> It seems to be a bug but it is actually a very bad decision on my part... I should have never allowed tables without leading pipe characters...

Even in version 2.x the syntax still not changed?

**Comment by gettalong** [comment]
@whuwangyong Version 2.0 was an intermediate release to extract some parts of kramdown, so what is meant here by 2.0 is now actually 3.0

**Comment by whuwangyong** [comment]
Thanks for your reply.
