### ISSUE TITLE
Language names, again

### ISSUE THREAD

**Issue by cabo** [gettalong/kramdown#318]
I'm sorry this is coming up again and again, but language names need to be even more flexible.

In the end, they turn up in an HTML5 class name, and the syntax for class names is extremely flexible:
https://www.w3.org/TR/2014/REC-html5-20141028/infrastructure.html#set-of-space-separated-tokens

So `language-русский` is as valid as is `language-c++` or `language-asn.1`.
This is not theoretical: It comes up in
https://tools.ietf.org/html/draft-iab-xml2rfc-03#section-2.48.4
which will soon be a standard that kramdown-rfc2629 is targeting.

Is there a reason the syntax for languages in fenced code blocks is restricted?
Shouldn't it be `[^\s]+`?

**Comment by cabo** [comment]
common mark seems to agree with русский:
http://johnmacfarlane.net/babelmark2/?normalize=1&text=~~~+русский%0Aeasel%0A~~~%0A
and with asn.1:
http://johnmacfarlane.net/babelmark2/?normalize=1&text=~~~+asn.1%0Aeasel%0A~~~%0A

But indeed few other implementations do.  Hmm.

(Note that I would require a space before the `[^\s]+` language name; the more restricted current one maybe is  useful when attached to the `~~~`.)

**Comment by gettalong** [comment]
@cabo Thanks for bringing this up.

In the kramdown specification I did exactly specify of what characters an ID name may be specified but didn't do the same for class names.

Keeping that in mind *not* allowing any character in class names would actually be a bug. However, the two characters I would not include are the dot and hash sign so as to make chaining class and ID names in attribute lists still possible.

Any thoughts on this?

And what do you mean by this:

> (Note that I would require a space before the [^\s]+ language name; the more restricted current one maybe is useful when attached to the ~~~.)

**Comment by gettalong** [comment]
I have fixed this in a way that is hopefully futureproof!

**Comment by cabo** [comment]
Just tried it -- great!

(My comment about requiring a space was that maybe
```
~~~@$)(@#)($*(*&
```
should not be recognized as a code block start.  But then, the `~~~` is still pretty unique, so I'm happy with the way this is now.)

(If you really need a `#` or `.` in a class name specified in an IAL, use `class=...`. Allowing these in the language position of a code block is great for C# and ASN.1.)

Looking forward for a release, so I can start referencing the new version from kramdown-rfc2629.

**Comment by gettalong** [comment]
@cabo Already released version 1.10.0 :smile:
