### ISSUE TITLE
Fenced code block not rendering properly (with or without GFM)

### ISSUE THREAD

**Issue by briennakh** [gettalong/kramdown#319]
In Jekyll, when I set the markdown converter to kramdown, this fenced code block

```
'''javascript
function hey(name) {
	return 'Hey ' + name;
}

console.log(hey('Brienna'));
'''
```
_(note that I used ''' as a replacement for backticks to be able to show this example)_

renders like this:
![kramdown](https://cloud.githubusercontent.com/assets/9706870/13385355/dc8213c8-de6d-11e5-87b9-980ef5fefb14.png)

This happens no matter what I do. I've tried setting the `input: GFM` option, but it doesn't make a difference whether or not it's included.

However, when I set the markdown converter to redcarpet, the same code block renders like this:
![1 appearance](https://cloud.githubusercontent.com/assets/9706870/13385386/0eaefc9e-de6e-11e5-83b6-7fefc2a07b9d.png)

This is what I want to see! But I don't want to use redcarpet. I want to use kramdown. 

If it helps, I've included the HTML result from both markdown converters. 

Kramdown: 
![kramdown elements](https://cloud.githubusercontent.com/assets/9706870/13385428/81ca0d4a-de6e-11e5-8656-920325316af2.png)

Redcarpet: 
![1 elements](https://cloud.githubusercontent.com/assets/9706870/13385184/fdd3afb6-de6b-11e5-99f8-2eba1b3b7c8a.png)

**Comment by gettalong** [comment]
As you can see from the output of kramdown the code block **gets highlighted**. However, it seems that you are using wrong CSS definitions and therefore it doesn't work. Please post Jekyll related questions/bugs at the Jekyll bug tracker!
