### ISSUE TITLE
<em> inserted incorrectly inside a hyperlink

### ISSUE THREAD

**Issue by zxteloiv** [gettalong/kramdown#323]
Hi, actually I found the problem by converting my notes into markdown format.

I have a snippet like this
``` markdown
[Stochastic_Processes_-_1.4_analysis](Stochastic_Processes_-_1.4_analysis)
```
or for simplicity
``` markdown
[A-_B](A_-B)
```

Feed it to kramdown I got the following
``` bash
$ echo "[A-_B](A_-B)" | kramdown
<p>[A-<em>B](A</em>-B)</p>
```
which should be `<p><a href="A_-B">A-_B</a></p>`.

I tried all the four, only the last one yields this problem:
- `[A_-B](A-_B)` ok
- `[A-_B](A-_B)` ok
- `[A_-B](A_-B)` ok
- `[A-_B](A_-B)` 

It works well in the javascript port of kramdown, i.e., the _kramed_.
``` bash
$ echo "[A-_B](A_-B)" | kramed
<p><a href="A_-B">A-_B</a></p>
```

My environment is
- OS X El Capitan
- ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
- gem 2.0.14
- kramdown 1.9.0

Thank you for reading this!

**Comment by gettalong** [comment]
Thanks for reporting, this is definitely a bug.
