### ISSUE TITLE
Inline links always become reference links

### ISSUE THREAD

**Issue by sfcgeorge** [gettalong/kramdown#324]
Is this deliberate? I'm not sure why I'd want this. A config option of `link_style: (:inline|:reference)` might be nice.

```ruby
kr = Kramdown::Document.new "Ok lets link to [Google](http://www.google.com/)"
kr.to_kramdown
# => "Ok lets link to [Google][1]\n\n\n\n[1]: http://www.google.com/\n"
```

It's the same with an html `a` tag too.

**Comment by gettalong** [comment]
Absolute URLs are converted to reference style links, all others to inline style links.

I would be okay with a pull request introducing this functionality.

**Comment by sfcgeorge** [comment]
Oh intriguing, thanks. Well that does make some sense. Hmm I'll have a think.

**Comment by gettalong** [comment]
@sfcgeorge I'm closing this for now since it seems you are the only one interested in this - but if you have a pull request, feel free to send it my way.
