### ISSUE TITLE
Escaping the pipe character (|) does not work

### ISSUE THREAD

**Issue by paulmenzel** [gettalong/kramdown#325]
With kramdown 1.10.0, converting `**test \| test**` does not work.

```
2.1.5 :001 > Kramdown::Document.new("**test \| test**").to_html
 => "<table>\n  <tbody>\n    <tr>\n      <td>**test</td>\n      <td>test**</td>\n    </tr>\n  </tbody>\n</table>\n"
```

Here is a test for GitHub Flavored Markdown.

*   **test | test**
*   **test \| test**

This is needed, so the workaround mentioned in #317 works.

**Comment by gettalong** [comment]
If you supply your test case in a Ruby string you have to use two backslashes because the first one is eaten by Ruby:

~~~
2.3.0 :002 > Kramdown::Document.new("**test \\| test**").to_html
 => "<p><strong>test | test</strong></p>\n" 
~~~

As you can see this works just fine.

**Comment by paulmenzel** [comment]
@gettalong, you are right. Sorry for the noise.

**Comment by paulmenzel** [comment]
… and thank you for the quick response.
