### ISSUE TITLE
tilde appending the language converts it to ordered list

### ISSUE THREAD

**Issue by xksteven** [gettalong/kramdown#326]
This displays fine
\~~~
myArray = ["Steven"]
\~~~

but this gets converted to an ordered list

\~~~ javascript
myArray = ["Steven"] 
\~~~

**Comment by gettalong** [comment]
The output from the second example is the following when using Rouge:

~~~ html
<div class="highlighter-rouge"><pre class="highlight"><code><span class="nx">myArray</span> <span class="o">=</span> <span class="p">[</span><span class="s2">"Steven"</span><span class="p">]</span> 
</code></pre>
</div>
~~~

Or without any syntax highlighter at all:

~~~ html
<pre><code class="language-javascript">myArray = ["Steven"] 
</code></pre>
~~~

Seems right to me.
