### ISSUE TITLE
Custom Indent Level

### ISSUE THREAD

**Issue by isaiahgrey93** [gettalong/kramdown#327]
Would be helpful to have an option specify the indent level for Code Block level indentation, or everywhere. If I understand correctly the standard for the indent level is 8 spaces for Kramdown. This is a lot when using a 3 column pane documentation layout, and the Code is only within a column.

We are getting by using spaces, but it is a huge hassle.

Thanks for the excellent work on Kramdown :+1:

**Comment by gettalong** [comment]
Please read the syntax documentation at http://kramdown.gettalong.org/syntax.html for information about how kramdown handles leading spaces.

Tl;dr:

* 1 tab equals 4 spaces in kramdown
* Indented code blocks need 4 spaces
* List item indentation is based on the column number of the first non-space character after the list item marker, or 4 spaces if only whitespace is used on the line with the list item marker.
