### ISSUE TITLE
Feature Request: Include CSS classname for language in syntax-highlighted code blocks

### ISSUE THREAD

**Issue by SLaks** [gettalong/kramdown#328]
RedCarpet includes <code>class="language-_blah_"</code> in the `<code>` tag for a syntax-highlighted code block with language specified.

This can be used to highlight and label code blocks by language, as I do [in my blog](http://blog.slaks.net/2015-06-30/code-snippets-impossible-code).

I'd like to add this classname to Kramdown too.

**Comment by gettalong** [comment]
Currently the `language-LANG` part is *removed* when using a syntax highlighter. So the easiest way would be to just leave the information there. It would then be on the outermost `<div>` tag that surrounds the highlighted code which should't be a problem.

Would this solve your issue?

**Comment by SLaks** [comment]
I did not realize that.
That should be fine too.

**Comment by SLaks** [comment]
Thanks!

Can you please release a version so I can get this in GitHub Pages?

**Comment by gettalong** [comment]
In time, yes. But also not that Github Pages has its own release schedule.

**Comment by SLaks** [comment]
I know; after you release, I'll need to bug them to release. (once they switch to Kramdown on May 1st, I won't be able to push my blog until they release this)

Thanks again!
