### ISSUE TITLE
Markdown left untouched in HTML Snippet

### ISSUE THREAD

**Issue by IanMitchell** [gettalong/kramdown#330]
I'm not sure if this is normal behavior or not, but it wasn't what I was expecting - if I have markdown in an html snippet, it's left untranslated. For instance:

```
<center>![Image](http://image.src.jpg)</center>
```

Centers the phrase `![Image](http://image.src.jpg)` rather than the image itself.

**Comment by gettalong** [comment]
1\. The `<center>` tag is deprecated, better use CSS to center your image, e.g.

~~~
![Image](http://image.src.jpg)
{: style="text-align: center"}
~~~

2\. The `<center>` tag is a block level HTML element and kramdown does not process Markdown contents in a block level tag. If you want it processed, you need to tell kramdown to do so:

~~~
<center markdown="span">![Image](http://image.src.jpg)</center>
~~~

**Comment by IanMitchell** [comment]
Oh, didn't know you could do that first style. Thank you!
