### ISSUE TITLE
Regression for underscore emphasis in version 1.11.0

### ISSUE THREAD

**Issue by stomar** [gettalong/kramdown#333]
Version 1.11.0 breaks parsing of underscore emphasis in some cases. This is most probably caused by commit c972cc2414296b5dbebb77966ee59b2d212586e0.

Below there are some examples for cases where parsing fails; note that especially for quotation marks there is a wide variety of used symbols, depending on language.

(Maybe some test cases should be added?)

Source:

``` markdown
ok:

- _test_
- '_test_'
- "_test_"
- ("_test_")

Not ok:

- (_test_)
- “_test_”
- \`_test_'
- „_test_“ (German style)
```

With 1.11.0 this results in:

``` html
<p>ok:</p>

<ul>
  <li><em>test</em></li>
  <li>‘<em>test</em>’</li>
  <li>“<em>test</em>”</li>
  <li>(“<em>test</em>”)</li>
</ul>

<p>Not ok:</p>

<ul>
  <li>(_test_)</li>
  <li>“_test_”</li>
  <li>`_test_’</li>
  <li>„_test_“ (German style)</li>
</ul>
```

With 1.10.0 everything is fine:

``` html
<p>ok:</p>

<ul>
  <li><em>test</em></li>
  <li>‘<em>test</em>’</li>
  <li>“<em>test</em>”</li>
  <li>(“<em>test</em>”)</li>
</ul>

<p>Not ok:</p>

<ul>
  <li>(<em>test</em>)</li>
  <li>“<em>test</em>”</li>
  <li>`<em>test</em>’</li>
  <li>„<em>test</em>“ (German style)</li>
</ul>
```

**Comment by gettalong** [comment]
Thanks for reporting and the additional test cases - I have just released a bug fix version.

**Comment by stomar** [comment]
Thanks for the fast fix, the new release works fine!
