### ISSUE TITLE
<main> not processed with parse_block_html

### ISSUE THREAD

**Issue by jmlacroix** [gettalong/kramdown#334]
Hi!

I was messing around with middleman and kramdown and I stumbled upon a weird behavior: it seems like kramdown won't parse content inside `<main>` html blocks.

Here's the markdown I'm trying to process:

```
title
=====

{::options parse_block_html="true" /}

<main class="hi">

### level 3

text [link](http://google.com)

</main>
```
Here's it's output using kramdown 1.11.1:

```
<h1 id="title">title</h1>

<main class="hi">

### level 3

text [link](http://google.com)

</main>
```

If I change the `<main>` tag to a `<div>`, it works:

```
title
=====

{::options parse_block_html="true" /}

<div class="hi">

### level 3

text [link](http://google.com)

</div>
```

Output:

```
$ kramdown test.html.md
<h1 id="title">title</h1>

<div class="hi">

  <h3 id="level-3">level 3</h3>

  <p>text <a href="http://google.com">link</a></p>

</div>
```

Is there anything else I can provide you with ?

Thanks for your help.

**Comment by gettalong** [comment]
Thanks for the report!

The reason is that `<main>` is not recognized as a valid HTML element, yet, so block parsing defaults to raw. You can force block parsing in the meantime by using `<main markdown="block">`.

**Comment by gettalong** [comment]
The fix for this will be in the next release.
