### ISSUE TITLE
Strip when generating IDs

### ISSUE THREAD

**Issue by IvanUkhov** [gettalong/kramdown#335]
I’m curious if there is any particular reason for not stripping when generating IDs (like those that appear in HTML tags). Currently, the code [looks](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/base.rb#L232) as follows:

```ruby
def generate_id(str)
  # ...
  gen_id = str.gsub(/^[^a-zA-Z]+/, '')
  gen_id.tr!('^a-zA-Z0-9 -', '')
  gen_id.tr!(' ', '-')
  gen_id.downcase!
  # ...
end
```

It would be nice to `gen_id.strip!` before replacing spaces with dashes so that IDs don’t end up containing a bunch of dashes at the end.

My primary motivation is as follows. Consider `README.md` of repositories hosted on GitHub. Sometimes people put build, version, etc. badges in the header. For instance:

```markdown
# My Project [![a][b]][c] [![d][e]][f]
``` 

In this case, the header gets assigned an ID whose value is `my-project--`, which is a bit ugly.

Regards,
Ivan

**Comment by gettalong** [comment]
Changing this would break existing sites, so this is a no-go for 1.x, sorry. You can always use manual header IDs for such cases.
