### ISSUE TITLE
Kramdown in YARD, generated HTML is treated as text to display in some cases.

### ISSUE THREAD

**Issue by aef** [gettalong/kramdown#337]
When using Kramdown with [YARD](http://yardoc.org/), when using blocks surrounded with `~~~~~`, I get fixed-width code blocks. However, when I use `~~~~~ ruby` as the starting line, it seems the same markup is generated, but it is then escaped, so that I see a bunch of HTML tags in the generated documentation.

Is there anything I am doing wrong? Why is this happening?

I am using `kramdown` gem version 1.11.1 with the `yard` gem version 0.8.7.6.

I used the following to configure YARD:

~~~~~
--output-dir=doc/api
--embed-mixins
--protected
--no-private
--markup-provider=kramdown
--markup=markdown
-
HISTORY.md
LICENSE.md
~~~~~

I am not sure if this is a problem in YARD, in Kramdown or in some kind of adapter inbetween. I just started my search here.

**Comment by gettalong** [comment]
When you have a situation like "kramdown with X" or "kramdown in Y" or similar, always try using kramdown with "X" or "Y". If the problem persists, it is a problem with kramdown, otherwise with "X" or "Y".

Therefore this is the wrong place to ask this question - you need to ask the YARD people.
