### ISSUE TITLE
Where to report issues with Kramdown and GitHub Pages?

### ISSUE THREAD

**Issue by oscarb** [gettalong/kramdown#338]
I have stumbled upon a few issues playing around with GitHub Pages that seem to be related to Kramdown (or rather GitHub Pages version of Kramdown). 

For example, using GitHub Pages I am unable to use the Kramdown feature [attribute list definitions](http://kramdown.gettalong.org/syntax.html#attribute-list-definitions). It simply renders as text, see https://github.com/oscarb/kramdown-options-test/commit/03d9b4737e9a372012f15b3989b1e5ebfb0160df

My questions are: Should this issue be reported here? If not, which repo is more suitable for me to report it to? Or should I contact the GitHub staff? 

Now that [Kramdown is _the_ parser for GitHub pages](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0), it's too bad that not all its features are available. Is there any way to see which Kramdown features that works?

Note: all my edits are done online directly at GitHub's webpage.

**Comment by arthurattwell** [comment]
In your [test commit](https://github.com/oscarb/kramdown-options-test/commit/03d9b4737e9a372012f15b3989b1e5ebfb0160df) you use this:

~~~
## Parse markdown in html block {:.class}
~~~

The ALD there won't work because you've applied it inline, but it isn't attached (touching with no spaces) a span-level element. 

You need to do either this, to apply `.class` to the block-level heading:

~~~
## Parse markdown in html block
{:.class}
~~~

or this, to apply `.class` to a span (here, an `<em>` span) within the heading:

~~~
## *Parse markdown in html block*{:.class}
~~~

**Comment by oscarb** [comment]
@arthurattwell I see now, thanks! :+1: From the [example in the documentation](http://kramdown.gettalong.org/syntax.html#block-ials), it is clear that the IAL for a block element needs to be below the element. I guess I must have misunderstood the following:

> A block IAL [...] has to be put _directly_  before or _after_ the block-level element [my emphasis]

In that case then so far I've only found [an issue](https://github.com/sjk15/sjk15.github.io/issues/2) with the feature [transliterate header ids](http://kramdown.gettalong.org/options.html#option-transliterated-header-ids), but that's already been reported to GitHub staff.

If I find anything else that seems to be related to GitHub pages, do I report it here or contact GitHub?

**Comment by gettalong** [comment]
@oscarb If you find something that looks like it is related to kramdown, you can report it here. However, if it is related to an application or library using kramdown, report it at the respective issue tracker.

It is fairly easy to check if a problem is in kramdown itself by using the kramdown binary to verify the wrong behaviour. I.e.

~~~ shell
$ kramdown -i GFM <<EOF
some input
EOF
<p>some text</p>
$
~~~
