### ISSUE TITLE
Leave math alone entirely

### ISSUE THREAD

**Issue by sampsyo** [gettalong/kramdown#342]
When `math_engine` is disabled, it appears that Kramdown wraps display math (like `$$this$$`) in `<pre>` blocks:

```sh
$ kramdown --version
1.11.1
$ echo '$$x$$' | kramdown
<script type="math/tex; mode=display">x</script>
$ echo '$$x$$' | kramdown --math-engine nil
<pre>$$
x
$$</pre>
```

This is quite surprising—I imagined that this option would disable the feature entirely, letting me keep my $$s exactly as they were in the source. Is there any option to turn off this extension entirely?

This happens in the [`convert_math` method in the HTML converter](https://github.com/gettalong/kramdown/blob/2cd02dfacda041d3108a039e085f804645a9d538/lib/kramdown/converter/html.rb#L315-L323). The `format_math` call returns nil when this is disabled, so the `if` falls through to the second arm, which wraps the value in a `<pre>` block.

**Comment by gettalong** [comment]
You are probably right. I have looked through the previous version of the conversion function and it didn't use `<pre>` or `<span>` there. So if the math_engine is turned off, it really should just output the input string.

Thanks for letting me know!

**Comment by gettalong** [comment]
@sampsyo So, looking at the code and the previous versions in more detail, it seems the best way to go forward when no math engine is selected, is to output LaTeX style inline/block delimiters, i.e. `$` for inline and `$$` for block, wrapped in `<div>` and `<span>`.

The `<div>` and `<span>` tags won't do anything to the styled output but allows us to preserve possibly set attributes and to assign `class="kdmath"` to allow for easy selection via CSS or Javascript.

So this input:

~~~
Some $$inline=math$$ is here

$$
And some
block math here
$$
~~~

would yield the following output:

~~~ html
<p>Some <span class="kdmath">$inline=math$</span> is here</p>

<div class="kdmath">$$
And some
block math here
$$</div>
~~~

Would that satisfy your needs?

**Comment by sampsyo** [comment]
Absolutely! Thanks for looking into it.

**Comment by gettalong** [comment]
Okay, then I will do that.

**Comment by gettalong** [comment]
Will be in the next version.

**Comment by sampsyo** [comment]
Woohoo! Thank you!

**Comment by 9peppe** [comment]
@gettalong, having the same syntax for inline and display math conflicts with usual math-writing use, where display math is usually inside paragraphs (text after starts in lowercase and all), and there is no way to do that with kramdown second guessing the writer's intentions. Please consider a math_engine that truly ignores everything between single and double dollars, leaving all the config to a MathJax config block.

**Comment by gettalong** [comment]
@9peppe Sorry, I don't understand your statement. Could you please be more specific to what kramdown should do? Best would be to include sample input, current output and preferred output.

You can already disable the math_engine by setting it to null. Then the output just consists of `<div>` plus `$$` for block math elements and `<span>` plus `$` for inline math elements.

**Comment by 9peppe** [comment]
@gettalong Well, if I do that, single dollars get rightly ignored. But double dollars do not.

Inputs like 

    This is a paragraph $$with a display equation inside\text{.}$$

and 

    This is a paragraph.
    
    $$followed by display math in another paragraph\text{.}$$

Give outputs like: 

    <p>This is a paragraph <span class="kdmath">$with a display equation inside\text{.}$</span></p>
 
and 

    <p>This is a paragraph.</p>
    
    <div class="kdmath">$$followed by display math in another paragraph\text{.}$$</div>

I have no problems with the second example, but in the first my equation becomes an inline equation, when I expected it to be a display math piece inside `<p>`, or at least a raw source piece with both dollars left alone. Like:

    <p>This is a paragraph $$with a display equation inside\text{.}$$</p> 

The main problem is that while I can use single and double dollars to let MathJax decide what to do, kramdown converts all double-dollar display math inside paragraphs to single-dollar inline math, even with math_engine set to null or nil.

**Comment by gettalong** [comment]
kramdown distinguishes between inline and block elements. Block elements like math blocks cannot be used as inline elements. This means that inside a paragraph math elements are treated as inline math and otherwise as block elements.

So what you want is not directly possible with kramdown. *However*, you can tell kramdown to ignore dollar signs by escaping them. Then it will not treat the dollar signs as the start of a math element.

**Comment by 9peppe** [comment]
Uhm, [display math isn't really a block element](https://github.com/mathjax/MathJax/issues/1707#issuecomment-282902454) according to MathJax people, and is traditionally used inside paragraphs.

Escaping dollar signs kinda works, but I am worried the underscores in the equation contents might end up interpreted as emphasis, and other conflicts like that (and every authoring tool not expecting escaped dollars to mean anything). Isn't there a way to tell kramdown to treat dollars, double dollars, and everything in between like raw text?

**Comment by gettalong** [comment]
Please remember that we are talking about kramdown, not MathJax here. In kramdown there is a difference between block and span elements. And therefore there are two different forms of math elements, one block math element and one span math element. And only the span math element may be used inside a paragraph. This has nothing to do with how MathJax sees things.

You can use the [nomarkdown extension](https://kramdown.gettalong.org/syntax.html#extensions) to tell kramdown to not parse part of the source as kramdown source but raw text.

Modifying the parsing behaviour of kramdown is not possible and will not be implemented. If you want to change how kramdown parses things, you can easily subclass the parser and modify it. See the GFM or Markdown parser implementations for that.

**Comment by 9peppe** [comment]
Ok. I found a solution that might work for me. I'll use the second group of delimiters:

```
<script type="text/x-mathjax-config">
   MathJax.Hub.Config({
       tex2jax: {
           inlineMath: [ ['$','$'], ['\\(', '\\)'] ],
           displayMath: [ ['$$','$$'], ['\\[', '\\]'] ],
           processEscapes: true
       }
   });
</script>
```
