### ISSUE TITLE
Kramdown escapes all the symbols in emails

### ISSUE THREAD

**Issue by anton-tsyganenko** [gettalong/kramdown#343]
```
$ echo "<me.example@example.com>" | kramdown
<p><a href="&#109;&#097;&#105;&#108;&#116;&#111;:&#109;&#101;&#046;&#101;&#120;&#097;&#109;&#112;&#108;&#101;&#064;&#101;&#120;&#097;&#109;&#112;&#108;&#101;&#046;&#099;&#111;&#109;">&#109;&#101;&#046;&#101;&#120;&#097;&#109;&#112;&#108;&#101;&#064;&#101;&#120;&#097;&#109;&#112;&#108;&#101;&#046;&#099;&#111;&#109;</a></p>
$ kramdown --version
1.11.1

```

**Comment by gettalong** [comment]
Could you describe the problem?

**Comment by anton-tsyganenko** [comment]
I want it to give result without escaping ascii-characters, like this:
`<p><a href="mailto:me.example@example.com">me.example@example.com</a></p>`
but it escapes everything. It is shown correct in the browser, but it increases source code length and size and decreases its readability.

**Comment by gettalong** [comment]
Okay, that is by design and to be compatible in this regard with the original Markdown.pl implementation.

**Comment by anton-tsyganenko** [comment]
In another way of setting email links the results differ:

```
$ echo "[a@b.c](mailto:a@b.c)" | markdown
<p><a href="mailto:a@b.c">a@b.c</a></p>
$ echo "[a@b.c](mailto:a@b.c)" | kramdown 
<p><a href="&#109;&#097;&#105;&#108;&#116;&#111;:&#097;&#064;&#098;&#046;&#099;">&#097;&#064;&#098;&#046;&#099;</a></p>
```

**Comment by gettalong** [comment]
Don't know that `markdown` executable, so I can't say. Fact of the matter is: It is how it is. And if there is no good reason to change it (and you have provided none), I won't change it.

**Comment by anton-tsyganenko** [comment]
> Don't know that markdown executable, so I can't say.

That one: https://www.archlinux.org/packages/community/any/markdown/

**Comment by gettalong** [comment]
Thanks, since it seems that most other implementations don't obfuscate the email links anymore, kramdown should probably follow suit in this case.

**Comment by gettalong** [comment]
The obfuscation will be removed in the next release.
