### ISSUE TITLE
& rewritten to &amp; in URLs in tag attributes

### ISSUE THREAD

**Issue by fginter** [gettalong/kramdown#348]
I need the following inline HTML

```
<span property="owl:imports" resource="https://www.w3.org/2012/pyRdfa/extract?uri=http://universaldependencies.org/docs/u/pos/all.html&format=xml&rdfagraph=output&vocab_expansion=false&rdfa_lite=false&embedded_rdf=true&space_preserve=false&vocab_cache=true&vocab_cache_report=false&vocab_cache_refresh=false" />
```

Try as I might, the `&` characters always get rewritten to `&amp;` by kramdown in the resource attribute. I tried all thinkable combinations of `markdown="0"` and `--no-parse-*` options, to no avail. Is this a bug, or am I doing something wrong?

**Comment by gettalong** [comment]
If you run your provided sample through kramdown, you are correct that ampersands are entity-encoded. However, this is done to be compatible to HTML as well as XHTML and adds no problems.
