### ISSUE TITLE
Rouge 2.0 compatibility

### ISSUE THREAD

**Issue by 5t111111** [gettalong/kramdown#350]
The recently released Rouge 2.0 has [breaking changes with its formatters](https://github.com/jneen/rouge#formatters).

I've checked the compatibility by providing those new formatters to Kramdown options and found some incompatibilities/strange behavior.

The issues I've found so far are:
- `Rouge::Formatters::HTMLLegacy` which should provide backwards-compatibility add `<pre>` tag to only the first code block.
- It seems you cannot specify formatters other than the default `Rouge::Formatters::HTML` because they require to be instantiated with base formatters.

Although I don't know if these issues are related Rouge internals rather than Kramdown at the moment, I just want to paste the test code before I can give it further investigation.

``````
require 'kramdown'
require 'rouge'

source = <<EOS
# Rouge 2.0 compatibility check

code block 1:

```ruby
def foo
  puts 'foo'
end
```

code block 2:

```ruby
def bar
  puts 'bar'
end
```

one liner:

```
def baz; puts 'baz'; end
```
EOS

# Without specifying a formatter
# It won't wrap code block with pre tag

puts Kramdown::Document.new(source, input: 'GFM', syntax_highlighter: 'rouge').to_html

# Specify Rouge::Formatters::HTML as a formatter
# It won't wrap code block with pre tag

puts Kramdown::Document.new(
  source,
  input: 'GFM',
  syntax_highlighter: 'rouge',
  syntax_highlighter_opts: {
    formatter: Rouge::Formatters::HTML
  }
).to_html

# Specify Rouge::Formatters::HTMLLegacy as a formatter
# It wrap only the first code block with pre tag

puts Kramdown::Document.new(
  source,
  input: 'GFM',
  syntax_highlighter: 'rouge',
  syntax_highlighter_opts: {
    formatter: Rouge::Formatters::HTMLLegacy
  }
).to_html

# Specify Rouge::Formatters::HTMLPygments as a formatter
# It causes an error

puts Kramdown::Document.new(
  source,
  input: 'GFM',
  syntax_highlighter: 'rouge',
  syntax_highlighter_opts: {
    formatter: Rouge::Formatters::HTMLPygments # => Causes an error because of missing base formatter
  }
).to_html
``````

**Comment by gettalong** [comment]
kramdown supports rouge ~> 1.8 (see the Rakefile), so there is no real problem for kramdown because of rouge 2.x.

If the changes in the rouge API are not that drastic, it would probably be possible to handle them in the current implementation of the rouge syntax highlighter. Otherwise it would be best to create another syntax highlighter "rouge2" that depended on rouge 2.x.

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1

**Comment by dentarg** [comment]
> kramdown supports rouge ~> 1.8 (see the Rakefile), so there is no real problem for kramdown because of rouge 2.x.

Ah, just leaving a note here if someone else ends up as confusing as I was until I figured out things. kramdown gemspec having (note **development_dependency**)

    s.add_development_dependency 'rouge', '~> 1.8'

doesn't help your project when adding rouge to your Gemfile, you need to limit the version yourself.

**Comment by gettalong** [comment]
@dentarg The reason for the development dependency is that it is an optional dependency for kramdown.

**Comment by dentarg** [comment]
Sure, I understand that. 

Might be worth mentioning in the readme/documentation what rouge version is currently supported.

**Comment by andrew8712** [comment]
Hey guys! I tried to use `kramdown` with `rouge` v2.0.7, but the dependency didn't met: 

> Could not find 'rouge' (~> 1.7) - did find: [rouge-2.0.7,rouge-2.0.0]

Is the support of latest `rouge` version in plans? The latest version meeting the dependency (1.11.1) is a bit outdated.

**Comment by gettalong** [comment]
@andrew8712 I will work on it when I have time. Pull requests are welcome!
