### ISSUE TITLE
GFM mode does not support  Emoji

### ISSUE THREAD

**Issue by imkean** [gettalong/kramdown#351]
like `:ok_hand:`
👌 

support  [GFM](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) completely, please

**Comment by gettalong** [comment]
I think implementing this for the GFM parser would be rather easy if there was a mapping available that showed which colon-name-colon combination is mapped to which emoji Unicode character.

**Comment by imkean** [comment]
Here is the [emoji cheat sheet](http://www.emoji-cheat-sheet.com), and [this mapping](https://github.com/muan/emoji/blob/gh-pages/javascripts/emojilib/emojis.json) may be helpful.

**Comment by gettalong** [comment]
@imkean These may be cheat sheets but if the GFM parser should be more like Github's GFM parser, we would need the mapping from Github, not some random mappings.

**Comment by gettalong** [comment]
For anyone wanting to implement this: https://github.com/github/gemoji

**Comment by Arnie97** [comment]
Before emojis are supported by Kramdown, in case you just want emojis within Jekyll or GitHub pages, you could simply add the `jemoji` gem to your site's `_config.yml`:
```yaml
gems:
  - jemoji
```
Reference: https://help.github.com/articles/emoji-on-github-pages/

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1

**Comment by tech4him1** [comment]
Is this going to be implemented or added to the feature project?

**Comment by gettalong** [comment]
@tech4him1 This is part of the "Feature Requests" project and needs a pull request.

**Comment by gettalong** [comment]
@imkean The GFM parser has been extracted from the main kramdown distribution. If this issue should be resolved, please create a ticket at https://github.com/kramdown/parser-gfm/issues since I can't transfer this issue there. Thank you!
