### ISSUE TITLE
python syntax highlighting cases page build failure on github pages on @ symbol

### ISSUE THREAD

**Issue by CatherineH** [gettalong/kramdown#352]
I think this is probably not the place to post this, but I'm not sure where else.

I have some python code with decorators in my github pages jekyll blog, such as:

```
class myclass:
    @property
    def myproperty(self):
         return "myvalue"
```

This builds fine with kramdown 1.11.1 with the --safe tag in jekyll on my local machine.

However, running this on github pages, I get:

```
The page build failed with the following error:

Page build failed.
```

Removing the @ symbol causes the page to build without error.

**Comment by gettalong** [comment]
Please test without Jekyll, i.e. with only kramdown. If it is still a problem, comment on this issue. Otherwise please ask at the appropriate Jekyll issue tracker or forum since I don't know much about Jekyll.
