### ISSUE TITLE
Surprising behaviour when nesting ordered lists with two spaces

### ISSUE THREAD

**Issue by robbertbrak** [gettalong/kramdown#353]
When I try create a nested ordered list with two space indent:

```
1. A
  1. B
```

it does not produce a nested list. Instead, both A and B are rendered at the same level.

```
<ol>
  <li>A</li>
  <li>B</li>
</ol>
```

It seems that the minimum indentation level is three spaces. While this makes sense in retrospect (after all, the first item starts after three characters), it took me a while to figure it out, as the documentation on this point is rather hard to understand. It doesn't help that Github itself seems to have no problems with two space indents, or even one space:

1. A
  1. B

Perhaps the documentation could be clarified with a few examples? E.g. something like http://spec.commonmark.org/0.25/#example-270.

**Comment by robbertbrak** [comment]
Yes, I do think that more examples would clarify things. I especially think that it would help to:

* add a few more examples of _ordered_ lists (most current examples use unordered lists) and show what happens if the numbers get to multiple digits;
* make the examples _shorter_ and more to the point. Currently the examples are both example and explanation, which I find distracting. I find it much easier to read examples such as the one I provided above: 'this' input leads to 'that' output. 

NB. The reason I was surprised that Github works differently, is that I was under the impression that Github itself also uses Kramdown (e.g., https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/).

**Comment by gettalong** [comment]
I have updated the documentation and there are now some more examples regarding the list indentation. Will be online at kramdown.gettalong.org once the new version is released.

**Comment by Dholmblad** [comment]
@gettalong I've noticed when attempting to use similar syntax with jeykll which uses kramdown that the second nested list will use letters as markers as opposed to numbers. 

`1. first level
    1. second level
        1. third level
`

Will result in 

`1. first level
    a. second level
        a. third level
`
