### ISSUE TITLE
Create unique IDs for definition terms

### ISSUE THREAD

**Issue by gvwilson** [gettalong/kramdown#355]
It's common to use a definition list for a glossary, in which case it is helpful to be able to link directly from a term's use to its definition:

~~~
<p>
  The <a href="#fnord">fnordification</a> of blazwhup is...
</p>
...
<dl>
  <dt id="fnord">fnord</dt>
  <dd>...definition...</dd>
</dl>
~~~

Creating the link is easy in Kramdown-flavored Markdown:

~~~
The [fnordification](#fnord) of blazwhup is...
~~~

but there's no easy way to create the `id` for the `dt`.  It would be very helpful if Kramdown auto-generated IDs, and better yet if it was possible to provide a prefix for the whole `dl` so that if there are several `dl`'s in a single page, the IDs for the `dt`s in that `dl` will have prefixed (unique) IDs.

**Comment by gettalong** [comment]
@gvwilson This feature will be in the next release.

Actually, there are two changes to definition lists:

1. It will now be possible to assign attributes using an IAL to definition terms like it is possible already for definitions themselves.

2. Additionally, one can assign the reference name `auto_ids` to a definition (similar to how footnotes and the TOC work). Definition lists having such a reference name will automatically generate an ID using the same algorithm as for header IDs (but without the additional stuff for headers and without double ID checking). And using a name like `auto_ids-prefix` one can assign a prefix to be used for the auto IDs.

**Comment by gvwilson** [comment]
Excellent - thanks very much.  Do you have a target date for the release?

**Comment by gettalong** [comment]
Yes, next release will be end of next week.

**Comment by gvwilson** [comment]
Thanks Thomas - any idea how quickly GitHub will deploy?

**Comment by gettalong** [comment]
@gvwilson This is a question for @benbalter but I think it will not be long after the kramdown release. For reference, Github pages was updated to kramdown 1.11.1 about a month after the kramdown release.

**Comment by gvwilson** [comment]
Thanks,
Greg
