### ISSUE TITLE
GFM inconsistency for list after paragraph without blank line

### ISSUE THREAD

**Issue by MattiSG** [gettalong/kramdown#359]
Copying https://github.com/github/markup/issues/900 in here:

- - - - -

The following renders as a list in previews of markdown (.md) files, but renders as a single paragraph on Github pages:

```
This is a list:
- or is it
```
Compare https://github.com/Morendil/md-inconsistency/blob/gh-pages/index.md and http://morendil.github.io/md-inconsistency/

This results in errors and frustration when we encourage our users to change or submit content via Github for our site hosted on Github Pages and rendered with Jekyll.

(via @Morendil)

- - - - -

Opening it here as I sent https://github.com/github/markup/issues/900 to GitHub support, here was their answer through @danayel:

> Jekyll is an Open Source project and thus uses a similarly Open Source markdown engine - kramdown.
> 
> GitHub itself uses it's own markdown engine, which hasn't been released publically yet. 
> 
> Getting consistency across the two is something we are interested in and investigating, but for now the best option is to post an issue on the kramdown repository[1] and see if they are able to sort this out on their end.

**Comment by gettalong** [comment]
There is no spec for GFM and therefore hard to implement it right. Pull requests for adding better compatibility to GFM are welcome.

**Comment by gettalong** [comment]
This issue is solved by the pull request #358.
