### ISSUE TITLE
Add support for multi-line tables

### ISSUE THREAD

**Issue by geraldb** [gettalong/kramdown#361]
Hello Thomas,
   First thanks for the great work on kramdown. 

> Anything that should go into the next kramdown release?

Might be bit of a stretch - I'd like to see support for simple tables with multi-line rows. pandoc has a great syntax, see http://pandoc.org/MANUAL.html#tables  Basically multi-line table rows are separated by blank lines. Example:

```
-------------------------------------------------------------
 Centered   Default           Right Left
  Header    Aligned         Aligned Aligned
----------- ------- --------------- -------------------------
   First    row                12.0 Example of a row that
                                    spans multiple lines.

  Second    row                 5.0 Here's another one. Note
                                    the blank line between
                                    rows.
-------------------------------------------------------------
```

Cheers.

**Comment by gettalong** [comment]
A small stretch ;-) Since this would change the parsing in a non-backwards-compatible way, this can only be done for the next major release.

**Comment by geraldb** [comment]
No worries.  Would be a great addition for 2.x. Thanks for the consideration. Keep it up. Cheers.

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1

**Comment by itcarroll** [comment]
The blank line in the pandoc syntax seems like a very big stretch to me. Is there a syntax that would cause text in what otherwise looks like a new row to simply be concatenated to text in the "cell" above, before conversion to HTML? I imagine a `:` could replace the pipe in such cases, as in

```
| Lorem          | Ipsum                          |
|----------------+--------------------------------|
| dolor sit amet | consectetur adipiscing elit,   |
|                : sed do eiusmod tempor          |
|                : incididunt ut labore et dolore |
|                : magna aliqua.                  |
| Ut enim ad     | minim veniam                   |
```

Creation of headers, footers and other separators would persist as is. Would it break backwards compatibility?

**Comment by gettalong** [comment]
Yep, it would break compatibility because currently colons are nothing special inside a table cell.
