### ISSUE TITLE
Ability to disable indented code blocks

### ISSUE THREAD

**Issue by drdaemos** [gettalong/kramdown#364]
Thanks for the great work at Kramdown.

I have a Jekyll-powered site and looking for the way to disable automatically invoked code blocks on indented text. 

The reason to have this are custom Jekyll plugins, which utilize Liquid to provide markup extensions like wrapping some text in colored block or tabs etc. These plugins use HTML for outputting advanced content, and it is very hard to control the whitespace on output HTML + Markdown when Liquid tags appear in lists (that's because lists use the indentation too).

I can write pure HTML without any Liquid preprocessing, but this looks terrible and I'd like to have some sort of snippet system.

**Comment by gettalong** [comment]
Indented code blocks are part of the Markdown syntax, so the kramdown and GFM parsers are using them. If you don't want them, the easiest way would be to create a custom parser based on the kramdown (or GFM) parser and remove the indented code block parsing routine. Have a look at https://github.com/gettalong/kramdown/blob/master/lib/kramdown/parser/markdown.rb to see how to create such a custom parser.
