### ISSUE TITLE
How can I set the location of the image?

### ISSUE THREAD

**Issue by triffic-tang** [gettalong/kramdown#365]
As described in the Syntax Reference of Kramdown, we can set the height and width size of the image, like the below:
`Here is an inline ![smiley](smiley.png){:height="36px" width="36px"}.`

But how can I set the location of the image, like `set align=center`?

**Comment by gettalong** [comment]
The height and width are just attributes set on the `img` tag, nothing magical done here by kramdown. If you want to center the image, you have to set the style attribute on the paragraph, see #145.
