### ISSUE TITLE
[syntax highlighter] Missing <pre> & <code> after highlighting code with rouge

### ISSUE THREAD

**Issue by GregOnNet** [gettalong/kramdown#367]
Hi,

I use rouge as syntax highlighter together with kramdown.

**Problem**

When I run kramdown I get the highlighted code blocks.
Unfortunately this code-block is not wrapped in `<pre><code>`.

_Expected_

```html
<div class="language-ruby highlighter-rouge"><span class="c1"># Gemfile</span>
  <pre>
    <code>
      <span class="n">group</span> <span class="ss">:web</span> <span class="k">do</span>
      <!-- more code-->
    <code>
  <pre>
</div>
```

_Actual_

```html
<div class="language-ruby highlighter-rouge"><span class="c1"># Gemfile</span>
  <span class="n">group</span> <span class="ss">:web</span> <span class="k">do</span>
  <!-- more code-->
</div>
```

**Origin**

I think the problem is located in `html.rb` line `98..`.

```ruby
# html.rb
def convert_codeblock(el, indent)
# ...
  highlighted_code = highlight_code(el.value, el.options[:lang] || lang, :block, hl_opts)

  if highlighted_code
    add_syntax_highlighter_to_class_attr(attr, lang || hl_opts[:default_lang])
    "#{' '*indent}<div#{html_attributes(attr)}>#{highlighted_code}#{' '*indent}</div>\n"
  else
# ...
```

When `highlighted_code` is present the highlighted code is returned wrapped in a `div`.
The tags `<pre>` and `<code>` are missing.

**Fix**

I think the fix would be:

```ruby
# html.rb
highlighted_code = highlight_code(el.value, el.options[:lang] || lang, :block, hl_opts)

if highlighted_code
  add_syntax_highlighter_to_class_attr(attr, lang || hl_opts[:default_lang])
  "#{' '*indent}<div#{html_attributes(attr)}><pre><code>#{highlighted_code}#{' '*indent}</code></pre></div>\n"
else
...
```

I applied this fix locally and the syntax highlighting works as expected.

Can you please check if my solution would also work even if other syntax highlighters are used?

Thanks in advance
Greg

**Comment by gettalong** [comment]
If I use

    ~~~ ruby
    class New
    end
    ~~~

as input and invoke the kramdown binary like `kramdown --syntax-highlighter rouge`, I get the following result:

~~~ html
<div class="language-ruby highlighter-rouge"><pre class="highlight"><code><span class="k">class</span> <span class="nc">New</span>
<span class="k">end</span>
</code></pre>
</div>
~~~

So the rouge syntax highlighter already seems to use `<pre>`.

Can you provide more details for the problem, like the input and how you invoke the kramdown binary on it?

**Comment by GregOnNet** [comment]
Hi,

my code is here on GitHub: [https://github.com/GregOnNet/blog](gregonnet/blog)
I use [Nanoc](https://github.com/nanoc/nanoc) which calls the kramdown library.
Nanoc provides a filter for [kramdown](http://nanoc.ws/doc/reference/filters/#kramdown). This filter calls kramdown:

``` ruby
module Nanoc::Filters
  # @api private
  class Kramdown < Nanoc::Filter
    requires 'kramdown'

    # Runs the content through [Kramdown](http://kramdown.gettalong.org/).
    # Parameters passed to this filter will be passed on to Kramdown.
    #
    # @param [String] content The content to filter
    #
    # @return [String] The filtered content
    def run(content, params = {})
      document = ::Kramdown::Document.new(content, params)

      document.warnings.each do |warning|
        $stderr.puts "kramdown warning: #{warning}"
      end

      document.to_html
    end
  end
end
```

---

The Input is a markdown file and looks like the following:

     ## Install bundle guard

     # Gemfile
     
     ~~~ ruby
     group :web do
       gem 'nanoc', '~> 4.3'
     end

     group :development do
       gem 'guard'
       gem 'adsf'
     end
    ~~~
([view file](https://raw.githubusercontent.com/GregOnNet/blog/master/content/posts/articles/2016-08-27-How-to-setup-Nanoc-with-Guard.md))

I hope this helps.
If there is any thing else I can help with, please let me know.

**Comment by gettalong** [comment]
I get the following result with `kramdown --syntax-highlighter rouge`:

~~~ html
<h2 id="install-bundle-guard">Install bundle guard</h2>

<div class="language-ruby highlighter-rouge"><pre class="highlight"><code><span class="c1"># Gemfile</span>

<span class="n">group</span> <span class="ss">:web</span> <span class="k">do</span>
  <span class="n">gem</span> <span class="s1">'nanoc'</span><span class="p">,</span> <span class="s1">'~&gt; 4.3'</span>
<span class="k">end</span>

<span class="n">group</span> <span class="ss">:development</span> <span class="k">do</span>
  <span class="n">gem</span> <span class="s1">'guard'</span>
  <span class="n">gem</span> <span class="s1">'adsf'</span>
<span class="k">end</span>
</code></pre>
</div>
~~~

As you can see the HTML output includes the `<pre>` tag.

Please test purely with kramdown and not via a third party library/application - if the problem persists, I will reopen the issue.

**Comment by GregOnNet** [comment]
Yes, it seems that the issue seems to be related to Nanoc than.
Thanks for your support.

**Comment by gettalong** [comment]
You may also want to look at the "syntax_highlighter_opts" option of kramdown - maybe it has been changed in your environment and therefore the output is different.

**Comment by zerocool4u2** [comment]
I believe this one is the option you where looking for syntax_highlighter_opts: { formatter: Rouge::Formatters::HTMLLegacy }, you should be able to use it as a param to run

**Comment by amree** [comment]
Hi guys

I think this might be related, so, I'm just going to post it here. As you can see from the example below, I'm not getting the `<pre>` tag when I use kramdown with rouge (compared to what I get when I just use the default).

```bash
$ kramdown -i GFM --syntax-highlighter rouge code.txt
<h1 id="header">Header</h1>

<div class="language-ruby highlighter-rouge"><span class="k">def</span> <span class="nf">hello</span>
  <span class="nb">puts</span> <span class="s2">"hello world"</span>
<span class="k">end</span>
</div>

$ kramdown -i GFM code.txt
<h1 id="header">Header</h1>

<div class="language-ruby highlighter-coderay"><div class="CodeRay">
  <div class="code"><pre><span class="line-numbers"><a href="#n1" name="n1">1</a></span><span style="color:#080;font-weight:bold">def</span> <span style="color:#06B;font-weight:bold">hello</span>
<span class="line-numbers"><a href="#n2" name="n2">2</a></span>  puts <span style="background-color:hsla(0,100%,50%,0.05)"><span style="color:#710">&quot;</span><span style="color:#D20">hello world</span><span style="color:#710">&quot;</span></span>
<span class="line-numbers"><a href="#n3" name="n3">3</a></span><span style="color:#080;font-weight:bold">end</span>
</pre></div>
</div>
</div>
```

Content of `code.txt`

```
# Header

```ruby
def hello
  puts "hello world"
end
    ```
```

p/s: Ignore the extra spaces in the last line

**Comment by gettalong** [comment]
@amree Are you using a compatible rouge version? I.e. <2.0.0?

**Comment by amree** [comment]
@gettalong I missed that information somehow and now it's working (by locking the `rogue` gem to `1.11.1`. Thanks a lot.
