### ISSUE TITLE
fenced code in blockquote

### ISSUE THREAD

**Issue by Sequoia** [gettalong/kramdown#374]
> # Header
> Content
> Here's some code:
> ```js
> function random(){
>     return 5;
> }
> ```

## Expected
*(this is github but basically I expect a `<pre>` tag in there somewhere)*

```html
<blockquote>
<h1>Header</h1>

<p>Content<br>
Here's some code:</p>

<div class="highlight highlight-source-js"><pre><span class="pl-k">function</span> <span class="pl-en">random</span>(){
    <span class="pl-k">return</span> <span class="pl-c1">5</span>;
}</pre></div>
</blockquote>
```

## Actual

```html
<blockquote>
  <h1 id="header">Header</h1>
  <p>Content
Here s some code:
<code>js
function random(){
    return 5;
}
</code></p>
</blockquote>
```

**Comment by gettalong** [comment]
You have to make sure that you follow kramdown's syntax:

* The problem you most likely have is that you need to use tildes for fenced code blocks with kramdown. Only the GFM flavour of kramdown supports the GFM style fenced code blocks with backticks.

* Make sure that you use blank lines between block elements. I.e. before the fenced code block needs to be a blank line.
