### ISSUE TITLE
Running the tests

### ISSUE THREAD

**Issue by agriffis** [gettalong/kramdown#377]
To get the tests running, I used this sequence. I didn't see anything like this in the README or docs so I'd like to know if this is the best formula or if I should be doing something else. If this looks good, I can provide a pull request to add it to the README

```
$ rake gemspec  # makes kramdown.gemspec
$ cat > Gemfile <<EOF
source 'https://rubygems.org'
gemspec
EOF
$ bundle  # installs the dev deps
$ rake  # runs the tests
```

**Comment by agriffis** [comment]
Additionally I needed #378 to run without latex, alternatively on Fedora:

```
dnf groupinstall -y 'Authoring and Publishing'
```

On Ubuntu it would be either `apt-get install texlive` or `apt-get install texlive-full`, not sure which is required.

**Comment by agriffis** [comment]
Additionally required for the test suite to run through cleanly

```
$ sudo dnf install nodejs npm
$ npm install mathjax-node
$ PATH=$PATH:$PWD/node_modules/.bin
```

and to include the latex tests (though these won't make the suite fail if missing)

```
$ sudo dnf group install 'Authoring and Publishing'   # Fedora
$ sudo apt-get install texlive-full  # Debian/Ubuntu
```

**Comment by agriffis** [comment]
Hmm, this would have been easier if I'd noticed `.travis.yml` effectively laying out the requirements.

**Comment by gettalong** [comment]
Yes, the travis configuration file nicely shows what is needed. I will probably make a notice about this in the readme file.

**Comment by gettalong** [comment]
I have added some info to the README.md file - thanks for making me aware of this!
