### ISSUE TITLE
GFM Code Blocks in lists work with 3 spaces but not with 4

### ISSUE THREAD

**Issue by connorshea** [gettalong/kramdown#381]
I believe I found a bug in the GFM parser. The problem is that GitHub's codeblocks need to be indented when inside of an ordered list (if they're not, the ordered list is interrupted and the "counter" resets), but Kramdown only allows 3 space indentation in the GFM parser where it should allow 3 or 4.

### Three spaces of indentation

I can't embed the example markdown within this issue due to the limitations of the GitHub issue tracker's code block support. 

Input: See `markdown_3_spaces.txt` in this Gist for the input Markdown: https://gist.github.com/connorshea/904bcb25216dc85ec6b3653f5bed17d3

Then we run this command: `puts Kramdown::Document.new(File.read('markdown_file.text'), {:input => 'GFM', :syntax_highlighter => 'rouge', :hard_wrap => false}).to_html`

**HTML output:**

<details>
```html
<ol>
  <li>
    <p>Lorem ipsum dolor sit amet.</p>

    <div class="language-ruby highlighter-rouge"><span class="n">ruby</span> <span class="n">code</span>
    </div>
  </li>
  <li>
    <p>Lorem ipsum dolor sit amet.</p>

    <div class="language-ruby highlighter-rouge"><span class="n">ruby</span> <span class="n">code</span>
    </div>
  </li>
  <li>
    <p>Lorem ipsum dolor sit amet.</p>
  </li>
  <li>
    <p>Find the <code class="highlighter-rouge">incoming_email</code> section in <code class="highlighter-rouge">config/gitlab.yml</code>, enable the feature
  and fill in the details for your specific IMAP server and email account:</p>

    <div class="language-yaml highlighter-rouge"><span class="c1"># Configuration for Gmail / Google Apps, assumes mailbox gitlab-incoming@gmail.com</span>
<span class="na">incoming_email</span><span class="pi">:</span>
  <span class="na">enabled</span><span class="pi">:</span> <span class="s">true</span>
    </div>
  </li>
  <li>
    <p>Enable <code class="highlighter-rouge">mail_room</code> in the init script at <code class="highlighter-rouge">/etc/default/gitlab</code>:</p>

    <div class="language-sh highlighter-rouge">sudo mkdir -p /etc/default
<span class="nb">echo</span> <span class="s1">'mail_room_enabled=true'</span> | sudo tee -a /etc/default/gitlab
    </div>
  </li>
</ol>
```
</details>

**Screenshot and GitHub Interpretation**:

<details>
<img width="977" alt="screen shot 2016-10-17 at 5 33 15 pm" src="https://cloud.githubusercontent.com/assets/2977353/19459403/dc5f9356-948f-11e6-85a4-5c02b844ce5b.png">

<img width="784" alt="screen shot 2016-10-17 at 5 30 54 pm" src="https://cloud.githubusercontent.com/assets/2977353/19459362/8355fc5a-948f-11e6-8902-4d1de7e9de58.png">

</details>

### Four spaces of indentation

Input: See `markdown_4_spaces.txt` in this Gist: https://gist.github.com/connorshea/904bcb25216dc85ec6b3653f5bed17d3

Then we run this command: `puts Kramdown::Document.new(File.read('markdown_file.text'), {:input => 'GFM', :syntax_highlighter => 'rouge', :hard_wrap => false}).to_html`

**HTML output:**

<details>
```html
<ol>
  <li>
    <p>Lorem ipsum dolor sit amet.</p>

    <p><code class="highlighter-rouge">ruby
 ruby code
</code></p>
  </li>
  <li>
    <p>Lorem ipsum dolor sit amet.</p>

    <p><code class="highlighter-rouge">ruby
 ruby code
</code></p>
  </li>
  <li>
    <p>Lorem ipsum dolor sit amet.</p>
  </li>
  <li>
    <p>Find the <code class="highlighter-rouge">incoming_email</code> section in <code class="highlighter-rouge">config/gitlab.yml</code>, enable the feature
  and fill in the details for your specific IMAP server and email account:</p>

    <p><code class="highlighter-rouge">yaml
 # Configuration for Gmail / Google Apps, assumes mailbox gitlab-incoming@gmail.com
 incoming_email:
  enabled: true
</code></p>
  </li>
  <li>
    <p>Enable <code class="highlighter-rouge">mail_room</code> in the init script at <code class="highlighter-rouge">/etc/default/gitlab</code>:</p>

    <p><code class="highlighter-rouge">sh
 sudo mkdir -p /etc/default
 echo 'mail_room_enabled=true' | sudo tee -a /etc/default/gitlab
</code></p>
  </li>
</ol>
```
</details>

**Screenshot and GitHub Interpretation**:

<details>
<img width="993" alt="screen shot 2016-10-17 at 5 33 23 pm" src="https://cloud.githubusercontent.com/assets/2977353/19459402/dc5e84f2-948f-11e6-9420-a84d7152cec9.png">

<img width="778" alt="screen shot 2016-10-17 at 5 29 49 pm" src="https://cloud.githubusercontent.com/assets/2977353/19459347/60316f52-948f-11e6-82de-2947e74ad17f.png">
</details>

**Note** that while the screenshot for 3 spaces has monospace code, it is not actually being parsed properly by the Rouge syntax highlighter. The language isn't being passed to Rouge correctly and thus the syntax highlighting doesn't work. Rouge outputs HTML that is compatible with Pygments, and thus uses `<div>` and `<span>` tags rather than a code block. The issue could also be a combination of Rouge and the GFM parser, I can look into that more.

### Conclusion

The point is, GitHub renders code blocks inside of an ordered list the same whether the code blocks are indented using 3 spaces or 4. Kramdown does not.

The reason I'm reporting this rather than ignoring it like a sane person and using 3 spaces of indentation is that we have two places where our Markdown docs need to go: One where we parse it with Kramdown, which works with 3 spaces, and one – embedded inside the Help section of the application – where we parse it with the GitLab markdown pipeline (complicated and unimportant right now), which does not work with 3 spaces. Because of this, I can't just make the documentation use 3 spaces of indentation without breaking the latter.

Also this is still a bug in the implementation regardless if the goal is to match GitHub's markdown output exactly, so I figured I'd open this issue anyway.

Best,
Connor

**Comment by gettalong** [comment]
Thanks for this bug report but this has nothing to do with fenced code blocks themselves and is the intended behaviour.

The reason for this behaviour is how list indentation works - see http://kramdown.gettalong.org/syntax.html#lists - and that list indentation behaves differently than in the Github parser.

So if you don't want or can't use the normal indentation and need 4 spaces, you have to make sure that the text on the line with the list item marker starts at column 4, i.e.

~~~
1. The letter 'T' is in column 3, so three spaces of indentation is needed

   Other block elements inside this list item need three spaces of indentation.

Some other text because standard Markdown doesn't allow us to interrupt a list...

1.  The letter 'T' here is in the column 4 (preceded by two spaces), so an indentation of four spaces is needed.

    Other block elements inside *this list item* need **four** spaces of indentation.
~~~
