### ISSUE TITLE
Heading IDs Not Outputting With UTF-8 Characters

### ISSUE THREAD

**Issue by bradonomics** [gettalong/kramdown#382]
I'm using kramdown on a multi-lingual Jekyll site. The English headings are producing ids as you'd expect:

![jekyll-english-heading-ids](https://cloud.githubusercontent.com/assets/5723185/19634691/68a169d2-99e7-11e6-88bc-424b604cc940.png)

But for Thai language pages, I'm getting "section," "section-1," etc.:

![jekyll-thai-heading-ids](https://cloud.githubusercontent.com/assets/5723185/19634725/8224daf6-99e7-11e6-94d4-32aab0b52bc4.png)

Expected result:
```html
<h2 id="ต่อให้-ทุ่มเท-ด้วย">ต่อให้ ทุ่มเท ด้วย</h2>
```

Actual result:
```html
<h2 id="section">ต่อให้ ทุ่มเท ด้วย</h2>
```

**Comment by gettalong** [comment]
This is just how the automatic section ID generation works by default, see http://kramdown.gettalong.org/converter/html.html#auto-ids. You can try the option ['transliterated_header_ids'](http://kramdown.gettalong.org/options.html#option-transliterated-header-ids) and see if this produces results that work better for you.
