### ISSUE TITLE
Newpage / pagebreak support for LaTeX

### ISSUE THREAD

**Issue by dato** [gettalong/kramdown#384]
Hi!

I searched the documentation and I couldn’t find support for issuing a command _only_ in LaTeX output. In particular, I’m interested in `\newpage` and `\pagebreak`. Though generic support would be welcome as well.

Is there a way that I have missed? Thx.

**Comment by gettalong** [comment]
See http://kramdown.gettalong.org/syntax.html#extensions and look for the "nomarkdown" extension.

You can do something like this with this extension:

~~~
{::nomarkdown type="latex"}
\pagebreak
{:/}
~~~

**Comment by dato** [comment]
Excellent. I had missed that exception. Thanks for your help. :+1:
