### ISSUE TITLE
Is there a way to truncate auto id length?

### ISSUE THREAD

**Issue by huphtur** [gettalong/kramdown#385]
example (perhaps a bit extreme, but you get the idea 😉)

`#### Bacon ipsum dolor amet turducken flank boudin filet mignon pork belly kielbasa. Fatback tenderloin cow short ribs beef ribs shankle ribeye pork shank tongue. Ball tip pork belly t-bone frankfurter shoulder shankle pork loin tri-tip jerky salami pork pancetta tongue ham hock picanha. Biltong cow chuck chicken shoulder cupim sirloin, pastrami rump tenderloin corned beef tongue flank leberkas pork chop.`

results in: 

`<h4 id="bacon-ipsum-dolor-amet-turducken-flank-boudin-filet-mignon-pork-belly-kielbasa-fatback-tenderloin-cow-short-ribs-beef-ribs-shankle-ribeye-pork-shank-tongue-ball-tip-pork-belly-t-bone-frankfurter-shoulder-shankle-pork-loin-tri-tip-jerky-salami-pork-pancetta-tongue-ham-hock-picanha-biltong-cow-chuck-chicken-shoulder-cupim-sirloin-pastrami-rump-tenderloin-corned-beef-tongue-flank-leberkas-pork-chop">Bacon ipsum dolor amet turducken flank boudin filet mignon pork belly kielbasa. Fatback tenderloin cow short ribs beef ribs shankle ribeye pork shank tongue. Ball tip pork belly t-bone frankfurter shoulder shankle pork loin tri-tip jerky salami pork pancetta tongue ham hock picanha. Biltong cow chuck chicken shoulder cupim sirloin, pastrami rump tenderloin corned beef tongue flank leberkas pork chop.</h4>`

is there a way to set the auto id character limit via options?

**Comment by gettalong** [comment]
There is no way to do this via an option but in such cases it is best to just manually set an ID.
