### ISSUE TITLE
Using span-level kramdown syntax within HTML tables

### ISSUE THREAD

**Issue by jmarshall** [gettalong/kramdown#386]
I have a kramdown-using GitHub Pages document that contains several HTML tables — these are done as HTML tables because many of the cells contain several paragraphs and even a nested table, and I understand kramdown table syntax is basically for tables with simple single-line cell contents.

It would be nice to be able to use kramdown syntax within the table cells, as in this much-reduced example:

```markdown
---
layout: default
title: foo
---

This is **bold**.

{::options parse_block_html="true" /}

<p>
I want this to be **bold** too!
</p>

<table>
<tr><td>
And **this**.
</td></tr>
</table>
```

However the bold within `<p>` works, but the bold within the `<table>` does not.

If I use `<tr markdown="block">` then the bolding within the nested `<td>` works, but the tables in my document have enough rows that adding this for every row is fairly painful.  I would settle for needing to use `<table markdown="block">` once for each table, but that isn't effective.

Looking at the code, it seems that if `table` and/or `tr` were in [`HTML_CONTENT_MODEL_BLOCK`](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/parser/html.rb#L37-L39) then kramdown syntax would work in table cells without markdown attributes on every cell or row.

This was the case before 39f8add015bf37b7d6490bcd345708d23bf546d3 but I guess I don't understand the comment (_The following elements are also parsed as raw since they need child elements that cannot be expressed using kramdown syntax: colgroup table tbody thead tfoot tr ul ol_) that was added in that commit.

**Comment by gettalong** [comment]
If `<tr>` was treated as an HTML element with content model :block, it would be able to contain block elements like `<blockquote>` or `<p>` which is not allowed. This is the reason why it is parsed as raw.

I'm afraid that the only thing that you can do is using `markdown="block"` or `markdown="span"` on the `<td>` elements in which you want to use kramdown syntax.
