### ISSUE TITLE
Unable to display a list inside a table cell

### ISSUE THREAD

**Issue by IdanAdar** [gettalong/kramdown#387]
I've been unsuccessful in displaying a list inside a table cell.  
I've tried with the list in HTML as well as in markdown.

How do I get this working in Kramdown?

For example, take this line:

```
| GET requests <ul><li>Get a list of all the devices that use push notification for an application</li><li>Get the details of a specific device</li><li>Get the list of subscriptions</li><li>Get the subscription information that is associated with a subscription ID.</li><li>Get the details of a GCM configuration</li><li>Get the details of an APNS configuration</li><li>Get the list of tags that are defined for the application</li><li>Get details of a specific tag</li></ul>            | Yes           | Yes         | Yes         | Yes        | 
```

It renders like this in Kramdown: 

<img width="931" alt="screen shot 2016-11-08 at 14 22 31" src="https://cloud.githubusercontent.com/assets/7255583/20098936/d526db9a-a5be-11e6-9d7b-4f3a5ebed827.png">

And like this in Redcarpet: 

<img width="929" alt="screen shot 2016-11-08 at 14 19 38" src="https://cloud.githubusercontent.com/assets/7255583/20098846/6c45b6aa-a5be-11e6-8655-9ac702efe505.png">

**Comment by IdanAdar** [comment]
The solution is to use Kramdown exntesions, namely: `{::nomarkdown} .. {:/}`.

**Comment by mstanleyjones** [comment]
Is this still the case? I end up with really terrible code doing it this way:

```
The type of mount, can be either `volume`, `bind`, or `tmpfs`. Defaults to `volume` if no type is specified.{::nomarkdown}<ul><li>{:/}`volume`: mounts a [managed volume](volume_create.md) into the container.{::nomarkdown}</li><li>{:/}`bind`: bind-mounts a directory or file from the host into the container.{::nomarkdown}</li><li>{:/} `tmpfs`: mount a tmpfs in the container.{::nomarkdown}</li></ul>{:/}
```

**Comment by johndmulhausen** [comment]
Why wouldn't Kramdown assume the inverse - that instances of < and > are denoting HTML? It's bad enough not supporting multiline table cells, but apparently Kramdown thinks we're all out here struggling with typing `&lt;` and `&gt;` and you're making it easier by converting to HTML entities for us? Can you describe your understanding of our use cases that leads to implementations like this, @IdanAdar?

**Comment by johndmulhausen** [comment]
Please reopen this issue, this is an extremely poor solution of a frequent use case.

**Comment by gettalong** [comment]
Please read the syntax specification for kramdown at https://kramdown.gettalong.org/syntax.html, especially the section regarding table support. There you will find that the kramdown table syntax only allows span-level elements inside a table, which is a design decision and not a bug.

If you want to use tables containing block level elements like paragraphs or lists, please just use standard HTML tables.

**Comment by johndmulhausen** [comment]
@gettalong Calling bad ideas "design decisions" doesn't really fly when you fail basic use cases, and the fact that a bad idea is written down doesn't mean that it trumps user feedback. 

Pandoc, for example, doesn't obstinately insist that this is some kind of impossible task, having implemented mutli-line cells some time ago, like this:

```
+---------------+---------------+--------------------+
| Fruit         | Price         | Advantages         |
+===============+===============+====================+
| Bananas       | $1.34         | - built-in wrapper |
|               |               | - bright color     |
+---------------+---------------+--------------------+
| Oranges       | $2.10         | - cures scurvy     |
|               |               | - tasty            |
+---------------+---------------+--------------------+
```

I'm sure your syntax specification is very interesting, but I care about it even less than you seem to care about the fact that people can't do basic things with your converter.

**Comment by gettalong** [comment]
@johndmulhausen It is okay to voice your opinion but the design decisions are not "bad ideas". Pandoc clearly went with a more elaborate table syntax, I chose a simple one for kramdown. Note that Markdown itself doesn't have *any* table syntax - is that a bad idea too? There are always benefits and trade-offs when designing something.

And the system is not breaking down, some people just want to use it in a way it wasn't designed for. If it doesn't fulfill your use case you're welcome to make changes to the parser. After all, it's open source.

**Comment by johndmulhausen** [comment]
I'm sorry to see a response largely arguing the semantics around whether things are "bad ideas" or "breaking down." I'm also sorry to see responses like "we documented our design decision, go read that," and "implement it yourself." I guess we'll have to do some thinking about whether putting up with this level of support for this limited a tool is actually a good idea. Thank you for getting back to me.

**Comment by gettalong** [comment]
I think you don't quite understand how open source works. And you also might wanna read one or all of

* http://jlongster.com/Why-Frequently-Absent-Open-Source
* http://writing.jan.io/2017/03/06/sustainable-open-source-the-maintainers-perspective-or-how-i-learned-to-stop-caring-and-love-open-source.html
* https://nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/ ...

**Comment by johndmulhausen** [comment]
If you say so. :)

Thank you again for getting back to me.

**Comment by MischaDeNola** [comment]
Sorry I'm late to the party, but if you're using Kramdown tables, you can write a "grid style" table and use the bodies for rows.

```
| Column 1      | Column 2   | Column 3  | Column 4   |
|---------------|:-----------|:---------:|:-----------|
| First Row     | Some value | Another   | 1. yoyo    |
|               |            |           | 2. baz     |
|               |            |           | 3. bar     |
|---------------|------------|-----------|------------|
| Second row    | hey yo     | I'm cool  | Totally    |
|---------------|------------|-----------|------------|
| Third  row    | asdf       | andmore   | sweet      |
{:.altTableClass}
```

Then, with an alternate table class, you only draw borders for the bodies.

However, just like the Pandoc grid table, it's obnoxious to maintain--if you don't constantly jiggle your spacing for nice visual alignment, they can quickly become hard to read with all the empty cells (though, not as bad as the pandoc simple tables).

The easiest solution, if you aren't a purist about HTML, is to simply put a `<br>` wherever you want to break the line within the cell (much simpler solution).

And, if you are really married to bullets (which don't render in Kramdown tables), you could just put the HTML in there. I like the other solutions more, though, 'cause I want our source to be as readable as possible (otherwise, why bother with markdown to begin with?)

On a related note, while multi-lines in a table cell is nice and all, I feel like being able to merge table cells is a feature more worth kicking up a fuss over.

**Comment by milipili** [comment]
Well, regardless of side talks, it is a quite annoying limitation nonetheless. The `altTableClass` trick simply does not work with many themes. And actually, without looking for more complex syntax, it would be awesome if the example given by @MischaDeNola was working out of the box. Simple and intuitive.

That said, it is ambigous with the current used features. So the "box" must be explicitly defined to let the parser apply the traditional rules on this paricular region (the "1. 2. 3. bar"). A simple flag disabled by default to enforce the definition of borders (with `-----`) would not be enough?

**Comment by gettalong** [comment]
I get it that it is a limitation due to the way tables are designed in kramdown. And it might also be an annoying limitation for some people. However, I won't break compatibility in kramdown 1.x by changing how tables are parsed.

**Comment by milipili** [comment]
Oh of course, definitely. It would not make sense.

I was more thinking of an option before the table or after it to change the behavior (and thus to preserve the current default behavior). But perhaps not so easy to do as it is. But anyway, if there is a 2.x, maybe something to think about it :)

**Comment by stevewells20** [comment]
I think the feature of lists inside of tables would be a great feature to add; that being said, @johndmulhausen is acting a bit like an incendiary troll. Thank you @gettalong for responding to his comments in such a professional and correct manner. I think the solution proposed by @milipili of setting a table specific flag to parse markdown inside of the table is a winning one, and I might be keen on trying to implement it myself. If you do end up having time for this, it would really expand the content display capabilities!

**Comment by johndmulhausen** [comment]
@stevewells20 A troll is someone who is acting in bad faith. Having maintained open-source projects, I think referring someone to blog articles about open source philosophy while summarily shutting down FR discussions for basic use cases is pretty bad faith compared to a poster showing a) syntactical examples of other solutions who got it right, and b) syntactical examples of how cumbersome the current workarounds are. 

As for the concerns about "breaking compatibility" - there are easy solutions there; for example, a `block-level-table-cells` option/flag that is "true" by default, but can be overridden if someone wants the old behavior.

Table-specific flags to enable markdown inside tables are probably a little heavy-handed; that is clearly coming from a world where one assumes people *don't* want to use markdown by default, all the time. But, in the real world, of course they do.

**Comment by stevewells20** [comment]
I appreciate you trying to educate me @johndmulhausen, but this is not the right place for such an out of scope tangent. Feel free to email me! I agree with your example of a solution as being a possible option, and this might be a great project to become more comfortable with Ruby on! When you can't beat it, fork it.
