### ISSUE TITLE
Question: possible to implement table enhancement?

### ISSUE THREAD

**Issue by sixtyfive** [gettalong/kramdown#388]
Since it allows non-technical users to easily put together complex tables, I've written a parser for the ASCII tables produced by [tablesgenerator.com](http://www.tablesgenerator.com/text_tables) which I'm figuring out now out how to package up as a Gem.

Right now the best way I can think of to include them in a Markdown document goes something like this:

```
[ASCIITABLE_START]
+----------------+-----------+-------------+
|                | Blah      | Blah        |
+----------------+-----------+-------------+
| Blah | Blah  | Blah | Blah | Blah | Blah |
+------+-------+------+------+      +      |
| Blah | Blah  | Blah | Blah |      |      |
+----------------+------+----+------+------+
| Blah                | Blah | Blah | Blah |
+---------------------+------+------+------+
[ASCIITABLE_STOP]
```

If the processor leaves the table alone, now the resulting HTML can be searched for them again and they can be replaced by proper HTML tables.

My questions is: are the better ways of accomplishing the same result, perhaps by extending Kramdown ? (I understand you do not want to include more complex tables than are currently possible and I would only want to write such an extension for myself or perhaps another Gem). If Kramdown can't be made to recognize a table of the above style, would it be possible to abuse the code highlighting feature (`\`\`\`asciitable`?) towards this end, and how would one have to go about that?

**Comment by gettalong** [comment]
Have a look at the code for the [fenced codeblock parser](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/parser/kramdown/codeblock.rb#L38), there you will find an example on how to write a block parser which would be needed for this. And then have a look at the [GFM parser implementation](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/parser/gfm.rb) to see how to remove or add additional block parsers.

As you correctly said the kramdown parser won't be extended to support something like this. However, you could write a syntax highlighter that recognizes the 'asciitable' format and falls back to rouge/coderay if an other format is specified. This would probably the easiest way and packaging your code this way other people would be able to use it as well. See the [syntax highligher documentation](http://kramdown.gettalong.org/rdoc/Kramdown/Converter/SyntaxHighlighter.html) for more information.

**Comment by sixtyfive** [comment]
@gettalong Thank you so much for your answer, and *especially* for linking to the proper jump-in point in the code! I had to learn a number of new things, but finally have something that works now. It's "good enough" for my personal needs but it'd be a shame not to make this little project my first attempt as a Gem. Could you take a look at my monkey patching code? Is there anything particularly bad or stupid in it, or perhaps some non-obvious improvement one could make?

```
#!/usr/bin/env ruby

require 'bundler/setup'
require 'kramdown'
require_relative 'asciitable'

module Kramdown
  module Parser
    class Kramdown
      THIRDPARTY_PARSERS = %w{asciitable table}

      def parse_codeblock_fenced
        if @src.check(self.class::FENCED_CODEBLOCK_MATCH)
          start_line_number = @src.current_line_number
          @src.pos += @src.matched_size
          lang = @src[3].to_s.strip
          puts lang
          if thirdparty = THIRDPARTY_PARSERS.include?(lang)
            cat = :raw
            case lang.to_sym
              when :asciitable, :table then
                src = ASCIITable.parse(@src[5])
            end
          else
            cat = :codeblock
            src = @src[5]
          end
          el = new_block_el(cat, src, nil, location: start_line_number)
          unless thirdparty || lang.empty?
            el.options[:lang] = lang
            el.attr['class'] = "language-#{@src[4]}"
          end
          @tree.children << el
          true
        else
          false
        end
      end
    end
  end

  class Element
    def to_s
      @value
    end

    def value=(string)
      @value = string
    end
  end
end

unless ARGV.length == 1
  puts "Usage: fencing-test.rb <file>"
  exit
end
puts Kramdown::Document.new(File.read(ARGV.first), parse_block_html: true).to_html
```

**Comment by gettalong** [comment]
@sixtyfive If it works for you, it's fine but I wouldn't publish the code in its current state because of the monkey-patching and because there is probably a nicer way to do this.

As for monkey-patching: You shouldn't do it if you intend to release the code to the public, especially in a library. If you want to directly change the `#parse_codeblock_fenced` method, create a proper subclass and override the method. This is much cleaner and doesn't change existing, relied-on behaviour. It is also not clear why you override anything in the `Kramdown::Element` class...

As for the nicer way: Implement a new syntax highlighter (see the [rouge highlighter](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/syntax_highlighter/rouge.rb) for an example) and do the parsing of the ASCII tables there, falling back to the Rouge/Coderay highlighter if necessary. In this way your code is using an extension interface of kramdown and will work nicer in more environments and situations.

**Comment by sixtyfive** [comment]
The answer is: I simply don't know to program at a level better than the code I posted. That's part of the why I requested for you to comment. That said, I do know that monkey patching is not a technique intended to be kept in place indefinitely. Thank you for linking to the rouge highlighter! I'll read it and try to change the code accordingly!
