### ISSUE TITLE
Html tags escaped when added after text

### ISSUE THREAD

**Issue by daralbrecht** [gettalong/kramdown#390]
When I try to parse a string with text & html tags in html parser I'm getting proper result:
```
pry(main)> Kramdown::Document.new('test <p>paragraph</p>', input: 'html').to_html
=> "test <p>paragraph</p>\n"
```
But when I try to use default kramdown parser html tags are escaped in the result:
```
pry(main)> Kramdown::Document.new('test <p>paragraph</p>').to_html
=> "<p>test &lt;p&gt;paragraph&lt;/p&gt;</p>\n"
```
Is it intended?

**Comment by gettalong** [comment]
Yeah, because in HTML you can't nest paragraphs. And since the kramdown parser would identity the line as a paragraph it would parse it as such. If you put the `<p>paragraph</p>` on a separate line, it will work.
