### ISSUE TITLE
custom auto-id code

### ISSUE THREAD

**Issue by nvoynov** [gettalong/kramdown#395]
Hi,

I need provide custom method for auto-id generation. Is is possible? 

Auto-id is awesome, but I have some problems in headers in UTF-8 international encodings. For example for the text.

```markdown
# [f.1] First requirement
# [f.2] Second requirement
# [f.3] Общие требования по работе с таблицами
```

I have the next output and I would like to get rid of the extra dash of headers like `<a href="#f3------" id="markdown-toc-f3------">`

```html
<ul id="markdown-toc">
  <li><a href="#f1-first-requirement" id="markdown-toc-f1-first-requirement">[f.1] First requirement</a></li>
  <li><a href="#f2-second-requirement" id="markdown-toc-f2-second-requirement">[f.2] Second requirement</a></li>
  <li><a href="#f3------" id="markdown-toc-f3------">[f.3] Общие требования по работе с таблицами</a></li>
</ul>
```

And then I accept then next id generate function.

```ruby
def get_header_id(header)
  header.downcase
    .gsub(/[^A-Za-z0-9\s]/, ' ')
    .strip
    .gsub(/(\s){2,}/, ' ')
    .gsub(/\s/, '-')
end
```

**Comment by gettalong** [comment]
Yes, this is easily possible. Just create a new class based on the HTML converter and override the `#generate_id(str)` method.

Also see if the options [auto_id_stripping](https://kramdown.gettalong.org/options.html#option-auto-id-stripping) and [transliterated_header_ids](https://kramdown.gettalong.org/options.html#option-transliterated-header-ids) would help in your case.
