### ISSUE TITLE
strange indent for code block output

### ISSUE THREAD

**Issue by nvoynov** [gettalong/kramdown#396]
Hi,

I have strange output for code blocks. First line is OK, the others have a strange indent.  

Source:
```markdown
#### [core.req.file] Reading requirement from a file {#core-req-file}
The System shall provide the ability to read Requirement from the formatted Markdown file. An example of this formatted Markdown file is provided below.

~~~markdown
# [<requirement id>] <requirement title>
{{
<attribute1>: value1
<attribute2>: value2  
}}
<body>

## [<child requirement id>] <child requirement title>
<child requirement body>
~~~
```

Html output seems to be OK

<img width="532" alt="code_block_output_html" src="https://cloud.githubusercontent.com/assets/103741/21084201/65cdb0d4-c008-11e6-9e2f-9718893cbb99.png">

But Firefox and Chrome show me the same indent for first string of each code block. 

<img width="356" alt="code_block_output" src="https://cloud.githubusercontent.com/assets/103741/21083948/9988529e-c003-11e6-96cf-c5ee0c88582d.png">

Can you help me? Where does these leading spaces appear, and may be I'm missing some important options?

Thanks for great product!

**Comment by nvoynov** [comment]
Today I tried to play with Rouge syntax highlighter as [described](https://kramdown.gettalong.org/syntax_highlighter/rouge.html), mostly because of mardkown support. 

I install Rouge and add the following options:

```ruby
OPTIONS = {
   syntax_highlighter: 'rouge',
   syntax_highlighter_opts: { line_numbers: true }
}
```

But there is a strange output also. In does not provide line breaks ...

Source document excerpt

```markdown
~~~shell
# serve minireq project in current directory
$ minireq-site serve

# serve minireq project in 'home/user/minireq-site' directory on port 9000
$ minireq-site serve home/user/minireq-site -p 9000
~~~
```
Html output

```html
<div class="language-shell highlighter-rouge"><span class="c"># serve minireq project in current directory</span>
          <span class="gp">$ </span>minireq-site serve
          
          <span class="c"># serve minireq project in 'home/user/minireq-site' directory on port 9000</span>
          <span class="gp">$ </span>minireq-site serve home/user/minireq-site -p 9000
          </div>
```

**Comment by gettalong** [comment]
Run you files through the plain kramdown parser using the kramdown binary and see if the problem persists. If not, then it is a problem in how you use kramdown.

I get the following result when using `kramdown --syntax-highlighter null`:

~~~ html
<h4 id="core-req-file">[core.req.file] Reading requirement from a file</h4>
<p>The System shall provide the ability to read Requirement from the formatted Markdown file. An example of this formatted Markdown file is provided below.</p>

<pre><code class="language-markdown"># [&lt;requirement id&gt;] &lt;requirement title&gt;
{{
&lt;attribute1&gt;: value1
&lt;attribute2&gt;: value2  
}}
&lt;body&gt;

## [&lt;child requirement id&gt;] &lt;child requirement title&gt;
&lt;child requirement body&gt;
</code></pre>
~~~



As for your rouge example: This is what I get when I run it through the kramdown binary:

~~~ html
<div class="language-shell highlighter-rouge"><pre class="highlight"><code><span class="c"># serve minireq project in current directory</span>
<span class="gp">$ </span>minireq-site serve

<span class="c"># serve minireq project in 'home/user/minireq-site' directory on port 9000</span>
<span class="gp">$ </span>minireq-site serve home/user/minireq-site -p 9000
</code></pre>
</div>
~~~

Make sure you use a supported rouge version, i.e. < 2.0.
