### ISSUE TITLE
Request: issue warning when footnote is made but unused

### ISSUE THREAD

**Issue by kylebarbour** [gettalong/kramdown#400]
I could be wrong, but I have a distinct memory of kramdown issuing a warning when footnotes are defined but not cited. Apologies if that memory is incorrect --- but either way, I think this would save me frequently, because I write long documents with occasionally > 100 citations and it's easy to write a long footnote and forget to cite it, and the software doesn't provide a way to help remind you. For example, in the following code,

    Lorem ipsum.

    [^foo]:
        bar

which produces

    <p>Lorem ipsum.</p>

with no footnote, it would be really nice if a warning was issued saying something like "Warning: footnote 'foo' on line baz unreferenced - ignoring" so you can go check and make sure you actually wanted to do that. Presently, warnings are issued for duplicate footnotes (Warning: Duplicate footnote name 'foo' on line baz - overwriting) and for footnotes with no definition (Warning: Footnote definition for 'foo' not found on line baz), so I think there may already be some infrastructure that would allow checking this.

Thanks for considering!

**Comment by gettalong** [comment]
Thanks, this is a good idea - will do this for the next release if easily possible!

**Comment by gettalong** [comment]
Done! :smile:

**Comment by kylebarbour** [comment]
You are, as always, the best :) Thanks!

**Comment by gettalong** [comment]
:smile: Thanks!
