### ISSUE TITLE
double (or internal) emphasis ignored with GitHub Pages

### ISSUE THREAD

**Issue by ousia** [gettalong/kramdown#402]
@gettalong, I get an issue with the following Markdown code:

``` markdown
_double *emphasis*_
```

GitHub parses it fine into HTML as:

``` html
<em>double <em>emphasis</em></em>
```

But kramdown parses it as:

``` html
<em>double *emphasis*</em>
```

Besides the issue with the proper CSS selector (`em em { font-style: normal; }`}, kramdown should be parsing the inner emphasis.

Even [Markdown strict](http://pandoc.org/try/?text=_double+*emphasis*_&from=markdown_strict&to=html) allows internal emphasis.

I’m afraid this might be a bug.

Happy New Year.

**Comment by gettalong** [comment]
This is by design and also the behaviour of the original Markdown.pl implementation - see <https://johnmacfarlane.net/babelmark2/?normalize=1&text=_double+*emphasis*+some_>
