### ISSUE TITLE
Headings conversion issue

### ISSUE THREAD

**Issue by n4to4** [gettalong/kramdown#404]
This seems to be a bug

```
puts Kramdown::Document.new("# aaa\n# bbb").to_html
# <h1 id="aaa">aaa</h1>
# <p># bbb</p>

puts Kramdown::Document.new("# aaa\n\n# bbb").to_html
# <h1 id="aaa">aaa</h1>
#
# <h1 id="bbb">bbb</h1>
```

CommonMark spec says blank lines are not required: http://spec.commonmark.org/0.27/#example-47

**Comment by gettalong** [comment]
Please note that the kramdown parser is based on the kramdown specification, available at kramdown.gettalong.org/syntax.html which predates CommonMark by years.

If you read that document you will find that headings need to start a block boundary, e.g. a blank line, to be recognized to avoid ambiguities.
