### ISSUE TITLE
How to write custom math engine?

### ISSUE THREAD

**Issue by JensKMueller** [gettalong/kramdown#405]
I defined my own math engine following the example of existing math engines. But I find no information on how to make the engine available. I found `configurable(:math_engine)` and used `add_math_engine` but this does not work.
Can you outline the steps to integrate a custom math engine?

**Comment by gettalong** [comment]
You may wanna look at https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter.rb#L52 and the module where the `add_math_engine` method comes from: https://github.com/gettalong/kramdown/blob/master/lib/kramdown/utils/configurable.rb#L16.

Basically you need to call `Kramdown::Converter.add_math_engine(:your_engine_name, YourEngineClass)`.

**Comment by glebm** [comment]
Here is a full example with KaTeX:

https://github.com/thredded/thredded-markdown_katex/blob/master/lib/thredded/markdown_katex/kramdown/katex_converter.rb
