### ISSUE TITLE
Unable to add {:toc} to every page in Jekyll site

### ISSUE THREAD

**Issue by mstanleyjones** [gettalong/kramdown#406]
I'm trying to parse the {:toc} macro as part of our Liquid template, and it is silently not working. You can see the commit where I try to do this here:

https://github.com/mstanleyjones/docker.github.io/commit/0d06da40efefdf3c5b1ac03b86606c6814bb739c

## Version-specific stuff:

We are using the Github Pages gem at version 105, which pulls in Kramdown 1.11 and Jekyll 3.3.1
I'm walking up the version of the Github Pages gem one at a time, and it's not making a difference so far. I've tested 106, 107, 108, and 109 so far.

## What I did:

1.  Added the following into the `_layouts/docs.html`. Included `markdown="1"` so that the block would get interpreted by Kramdown.

    ```html

    {% unless page.notoc %}
    <div id="inline_toc" markdown="1">

    * TOC
    {:toc}

    </div>
    {% endunless %}

    ```

    All the blanks are because I read in a few issues that you need blank lines.

    This all hugs the left-hand side to make sure that spacing is not causing the problem.

2.  Here is the relevant part of the `_config.yml`:

    ```yaml
    markdown: kramdown
    kramdown:
       input: GFM
       html_to_native: true
       hard_wrap: false
       syntax_highlighter: rouge
       toc_levels: 2..2
    ```

    I tried adding `parse_block_html: true` but it didn't make a difference.

    By the way, if I just specify `toc_levels: 2` I get an error. This syntax works great if I throw the `{:toc}` in an individual Markdown file before generation but not if I try to put it in Liquid.

3.  Clean and build the site, then browse to a page.

## What I get: The Kramdown is just rendered as plain text. Screenshot attached:

<img width="820" alt="screen shot 2017-01-30 at 5 06 36 pm" src="https://cloud.githubusercontent.com/assets/7674613/22448478/98893a8e-e70e-11e6-933e-c3b0c3b7e3cd.png">

(updated the description after I stopped trying to include it from a separate file)

**Comment by mstanleyjones** [comment]
I also filed a Jekyll bug in case the problem is not with Kramdown: https://github.com/jekyll/jekyll/issues/5843

**Comment by mstanleyjones** [comment]
I got some advice that I couldn't use an include to do this, so I moved the whole div into the `_layouts/docs.html` file, and amended the commit. This didn't fix the problem or change the symptoms in any way that I can tell. :(

**Comment by gettalong** [comment]
Please test out everything using just kramdown.

When using the command line client `kramdown -i GFM` with your example, it works as expected:

Input:
~~~
<div id="inline_toc" markdown="1">

* TOC
{:toc}

</div>

# test
~~~

Output:

~~~html
<div id="inline_toc">

<ul id="markdown-toc">
  <li><a href="#test" id="markdown-toc-test">test</a></li>
</ul>

</div>

<h1 id="test">test</h1>
~~~

So I will close this issue since the problem doesn't seem to be on kramdown's side.

**Comment by mstanleyjones** [comment]
Thanks for your quick response. I didn't realize I could test it using Kramdown directly. I'll keep pursuing it from the Jekyll side. Thanks!
