### ISSUE TITLE
Superscripts and subscripts in Kramdown?

### ISSUE THREAD

**Issue by nybblr** [gettalong/kramdown#41]
I love the extra power kramdown gives me, so I was surprised not to find any syntax for superscripts and subscripts other than the inelegant `<sup>` html injection. Are there any particular reasons support isn't built in?

The most natural syntax I've seen uses carets for super and tilde for sub:

```
October 31^st^
H~2~O
```

Are there any plans to add this to the kramdown spec/parser?

~ Jonathan Martin

**Comment by reitzig** [comment]
FWIW, using `<sup>` and `<sub>` is possible.

**Comment by docsteveharris** [comment]
Thanks!

**Comment by eneko** [comment]
:+1: for superscript and subscript support. There are many characters in English and other languages, like Spanish, that should be written as super/sub script. We've gotten a bit used to see things like "2nd" and "3rd" because of the computer age, but that is not proper English.

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1

**Comment by smithtimmytim** [comment]
Wanted to add my vote to this one.

**Comment by jfallows** [comment]
I'm 👍 for adding superscript and subscript support too please.

**Comment by gettalong** [comment]
Superscript and subscript are available in VersaDok, the spiritual successor to kramdown: https://github.com/gettalong/versadok

**Comment by ahamelers** [comment]
If anyone needs it, I've written a kramdown parser extension for `^superscript^` and `~subscript~` that doesn't interfere with gfm strikethrough

```ruby
require 'kramdown'
require 'kramdown-parser-gfm'

class Kramdown::Parser::SubSup < Kramdown::Parser::GFM
  def initialize(source, options)
    super
    @span_parsers |= %i[superscript subscript]
  end

  SUPTAGSTART = /\^([^^]*)\^/
  SUBTAGSTART = /(?<!~)~(?!~)([^~]*)(?<!~)~(?!~)/

  def subsupparse(regex)
    line = @src.current_line_number

    if @src[1].blank?
      add_text(@src.scan(regex))
    else
      @src.pos += 1
      el = Kramdown::Element.new(:html_element, 'sup', {}, category: :span, line: line)
      parse_spans(el, regex)
      @tree.children << el
      @src.pos += 1
    end
  end

  def parse_superscript
    subsupparse(/\^/)
  end

  def parse_subscript
    subsupparse(/~/)
  end

  define_parser(:superscript, SUPTAGSTART, '\^') unless has_parser?(:superscript)
  define_parser(:subscript, SUBTAGSTART, '(?<!~)~(?!~)') unless has_parser?(:subscript)
end
```
