### ISSUE TITLE
The behaviour of escaping backtick is different from GFM

### ISSUE THREAD

**Issue by Rokt33r** [gettalong/kramdown#410]
The below code should be rendered like <code>\`</code>.

```
<code>\`</code>
```

But, kramdown with GFM input option renders it like <code>\\`</code>.

**Comment by gettalong** [comment]
I don't understand the problem. Could you be more specific as to what the input, current output and your proposed output is? Thanks.

**Comment by Rokt33r** [comment]
I want to quote backtick(<code>\`</code>). I'm using kramdown on jekyll.

Sorry for being late.

#### Input

```
<code>\`</code>
```

#### Expected output(GFM)

<code>\`</code>

#### Actual output(Kramdown with GFM input option)

<code>\\`</code>

**Comment by gettalong** [comment]
The reason for this behaviour is that the contents of `<code>` tags should generally be left alone. This is document in the kramdown syntax guide at https://kramdown.gettalong.org/syntax.html#html-blocks (scroll down until you see "Parse as raw HTML" in bold).

If GFM handles this differently, as it seems to be the case, then this needs to be fixed.

Thanks for the bug report!

You know that you can use

    `` ` ``

to quote the backtick? See https://kramdown.gettalong.org/syntax.html#code-spans

**Comment by Rokt33r** [comment]
You're welcome. And, thanks for sharing the link. It is so helpful 👍

**Comment by gettalong** [comment]
@Rokt33r The GFM parser has been extracted from the main kramdown distribution. If this issue should be resolved, please create a ticket at https://github.com/kramdown/parser-gfm/issues since I can't transfer this issue there. Thank you!
