### ISSUE TITLE
Regression in nested unordered list parsing

### ISSUE THREAD

**Issue by cnmcavoy** [gettalong/kramdown#411]
I've noticed a regression in Kramdown, where 1.12.0 would parse a nested unordered list inside of an ordered list correctly, but 1.13.2 will not. For example, on 1.12.0, this markdown:

```
1. An ordered list item
  - A nested unordered list item
  - Another item
2. Another ordered list item
```

When passed to `Kramdown::Document.new(...).to_html` on 1.12.0, it produced the following html output:
```
"\n<ol>\n  <li>An ordered list item\n    <ul>\n      <li>A nested unordered list item</li>\n      <li>Another item</li>\n    </ul>\n  </li>\n  <li>Another ordered list item</li>\n</ol>\n"
```

However, on 1.13.2, the same markdown produced different output, without the nested unordered list is produced:
```
"\n<ol>\n  <li>An ordered list item\n  - A nested unordered list item\n  - Another item</li>\n  <li>Another ordered list item</li>\n</ol>\n"
```

I'm not completely certain, but I suspect the change that introduced the new behavior was here: https://github.com/gettalong/kramdown/commit/f7efbd74262b372c073f67087ec843a55aedbc1b

Is the new behavior intentional? From some manual testing, it seems that the 2-spaced indentation is no longer enough to detect a new list, however if the inner nested unordered list has 4-space indentation it is detected and parsed correctly. I don't see the 4-space requirement documented in the syntax guide: https://kramdown.gettalong.org/syntax.html .

**Comment by gettalong** [comment]
Please see the release notes for version 1.13.0 at https://kramdown.gettalong.org. There you will find that this is not a regression but a bug fix.

In your example, the indented unordered list is only indented two space but the indentation needed for the contents of the first item in the ordered list is three spaces. Just indent the nested unordered list correctly and you will get the intended behaviour.

You will find in the documentation at https://kramdown.gettalong.org/syntax.html#lists that the first non-whitespace character after the list marker determines indentation.

**Comment by cnmcavoy** [comment]
Ugh.

![](https://imgs.xkcd.com/comics/workflow.png)

Thanks though, I did not know the three spaces was important.

**Comment by cnmcavoy** [comment]
@gettalong I am actually still seeing odd behavior, even with triple spacing. You are right that the triple space works with nesting, but only if the ordered list has fewer than 10 items:

This is fine:
```
1. foo
   - bar
   - quz
```

This is broken:
```
1. foo
2. bar
...
10. quz
   - qaz
```
You have to _quadruple_ space items after items 10, and while I have not checked, I'd imagine lists that are > 99 need to be quintuple spaced. It definitely seems like the parser is demanding an extra space because it treats the 1-0 as a separate entity than `10`.

**Comment by gettalong** [comment]
No, this is not an odd behaviour. If you read my last sentence and the syntax documentation I pointed you to you will find that

> the first non-whitespace character after the list marker determines indentation.

So in the case of `1. foo` the first non-whitespace character is in column 4, therefore indentation is 3 spaces. In the case of `100. foo` the indentation is 5 space because foo starts in column 6.

**Comment by cnmcavoy** [comment]
That's very non-intuitive... but okay.

**Comment by gettalong** [comment]
Why? Just align the body of the list item with the text on the first line and it just works. You could formulate the rule as "use the indentation that makes the list item look correct".
