### ISSUE TITLE
Code Highlighter: GH Pages vs Jekyll/Kramdown 

### ISSUE THREAD

**Issue by henioStraszny** [gettalong/kramdown#415]
Recently I've started working with GitHub Pages mainly due to GitHub Flavored Markdown rich programming language support. I've understood that using GFM on GitHub and on GitHub Pages should provide exact experience, unfortunately in my case it is not, and I hope I can get some help here.

Example:

I've added yaml code as follows:

``` yaml
layout: post
title: "New post"
date: 2016-11-18 13:13:13 +0100
categories: general
```

It translates on GitHub as follows:

``` html
<div class="highlight highlight-source-yaml">
    <pre>
        <span class="pl-ent">layout</span>: 
        <span class="pl-s">post</span>
        <span class="pl-ent">title</span>: 
        <span class="pl-s">
            <span class="pl-pds">
                "
            </span>
            New post
            <span class="pl-pds">
                "
            </span>
        </span>
        <span class="pl-ent">
            date
        </span>
        : 
        <span class="pl-s">
            2016-11-18 13:13:13 +0100
        </span>
        <span class="pl-ent">
            categories
        </span>
        : 
        <span class="pl-s">
            general
        </span>
    </pre>
</div>
```

It translates in GitHub Pages into:

``` html
<div class="language-yaml highlighter-rouge">
    <pre class="highlight">
        <code>
            <span class="s">layout</span>
            <span class="pi">:</span> 
            <span class="s">post</span>
            <span class="s">title</span>
            <span class="pi">:</span> 
            <span class="s2">"</span>
            <span class="s">New</span>
            <span class="nv"> </span>
            <span class="s">post"</span>
            <span class="s">date</span>
            <span class="pi">:</span> 
            <span class="s">2016-11-18 13:13:13 +0100</span>
            <span class="s">categories</span>
            <span class="pi">:</span> 
            <span class="s">general</span>
        </code>
    </pre>
</div>
```

The problem is that this engine works different. If we take into account first line of given yaml file:

` layout: post`

GH renders layout and post with different classes leading to nice colors - result:

![image](https://cloud.githubusercontent.com/assets/9430861/23294803/9148ee6e-fa6d-11e6-8fd8-331b0499c025.png)

GHP renders layout and post with the same classes leading to the same colors - result:

![image](https://cloud.githubusercontent.com/assets/9430861/23294778/6d8ec6f6-fa6d-11e6-8c46-41f833c71c45.png)

My _config.yml

```yaml
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span: false
highlighter: rouge
theme: minima
```

I would appreciate any help.

**Comment by gettalong** [comment]
The GFM parser of kramdown is a "best effort" since there is no official specification for GFM. So you will not get the same experience on Github Pages and Github.

From your examples it seems that you just have to use the proper CSS classes to get the correct highlighting. So please check if your CSS style files include the necessary instructions.

**Comment by henioStraszny** [comment]
> The GFM parser of kramdown is a "best effort" since there is no official specification for GFM. So you will > not get the same experience on Github Pages and Github.

Thank you for your explanation and all the great work  👍 

> From your examples it seems that you just have to use the proper CSS classes to get the correct
> highlighting. So please check if your CSS style files include the necessary instructions.

Could you help me understand how can I do this?

If we will just analyse first line:

```yaml
layout: post
```

HTML generated by Kramdown looks like that:

```html
<span class="s">layout</span>
<span class="pi">:</span> 
<span class="s">post</span>
```

So as far as I understand, I actually cannot distinguish `layout` from `post` since they both have the same class.

On GitHub it looks like that:

```html
<span class="pl-ent">layout</span>
: 
<span class="pl-s">post</span>
```
Here we have two different classes what allows us to apply i.e. different colors.

**Comment by gettalong** [comment]
Ah, I misunderstood your problem. I thought it was about including the right CSS definitions but it is about the highlighter assigning the same class for YAML keys and values.

However, kramdown doesn't do highlighting itself but uses third-party libraries like coderay and rouge. So if they don't assign different classes, there is nothing kramdown can do, sorry.
