### ISSUE TITLE
<svg>...</svg> parsing bug?

### ISSUE THREAD

**Issue by gpakosz** [gettalong/kramdown#416]
Hello,

Given `test.md`, Kramdown believes there's a missing closing `</svg>` tag:
```
Some inline svg representing maths <svg xmlns:xlink="http://www.w3.org/1999/xlink" width="1.808ex" height="2.176ex" style="vertical-align: -0.505ex;" viewBox="0 -719.6 778.5 936.9" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg">
<defs>
<path stroke-width="1" id="E1-MJMAIN-2212" d="M84 237T84 250T98 270H679Q694 262 694 250T679 230H98Q84 237 84 250Z"></path>
</defs>
<g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)">
 <use xlink:href="#E1-MJMAIN-2212" x="0" y="0"></use>
</g>
</svg>
```

```
$ kramdown test.md > /dev/null
Warning: Found no end tag for 'svg' (line 1) - auto-closing it
Warning: Found invalidly used HTML closing tag for 'svg' on line 8
```

Should it be supported?

**Comment by gettalong** [comment]
The problem here is that kramdown does not know any of the SVG tags and therefore interprets them incorrectly. To use inline SVG make sure that there is no line break inside the SVG elements, i.e. everything on one line.

**Comment by gpakosz** [comment]
Yeah I figured using a single line would work around the problem, thanks.

**Comment by gettalong** [comment]
Another way would be to use more than four spaces of indentation for the continuing lines (i.e. every line except the first one).
