### ISSUE TITLE
Example of rouge

### ISSUE THREAD

**Issue by buschhardt** [gettalong/kramdown#418]
Hallo, can you please give a example to use rouge - your documentation is little bit irritating...

I try 
`
Kramdown::Document.new(mybody, {syntax_highlighter: :rouge, syntax_highlighter_opts:{line_numbers:true,formatter: Rouge::Formatters::HTMLPygments},parse_block_html: true}).to_html
`
How can I change the formatter? 
Or when I use the "standard rouge" then the css is 'highlighter-rouge' - how its possible to change this? I try:
`
Kramdown::Document.new(mybody, {syntax_highlighter: :rouge,syntax_highlighter_opts:{line_numbers:true,css_class:'codehilite'}, parse_block_html: true}).to_html
`
Please do more examples in the documentation or in testsuites.
And thank you for kramdown.

**Comment by gettalong** [comment]
Please have a look at https://kramdown.gettalong.org/syntax_highlighter/rouge.html for which options the rouge syntax highlighter supports.

You need to do something like this:

~~~ ruby
Kramdown::Document.new(text, parse_block_html: true, syntax_highlighter: :rouge, syntax_highlighter_opts: {line_numbers: true})
~~~

In your examples you provide three arguments whereas only two arguments are needed.

The CSS class `highlighter-rouge` can't be changed except by changing the HTML converter. But you may be able to use one of rouge's options to add a CSS class.
