### ISSUE TITLE
How to generate link targets?

### ISSUE THREAD

**Issue by buschhardt** [gettalong/kramdown#419]
Hallo,
if I look in the toc I find:
`<li><a href="#urheber--und-leistungsschutzrechte" id="markdown-toc-urheber--und-leistungsschutzrechte">§ 3 Urheber- und Leistungs­schutz­rechte</a></li>`

How is the name in the <a href generated? I try snake_case from Kramdown::Utils, but there must be a other method.

Thank You

**Comment by mstanleyjones** [comment]
You can add `{: id="foo" }` after the thing you want to give an ID to, and then just link to `#foo` in your href.  For example:

```
This is a paragraph with an ID.
{: id="bar" }

[This is a link to bar](#bar).
```

**Comment by gettalong** [comment]
Have a look at https://kramdown.gettalong.org/converter/html.html under the section "Automatic Generation of Header IDs". There you will find how text is converted to the ID. Also note that some options modify the behaviour, like `auto_id_stripping`.

The method that actually does the ID generation can be found at https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/base.rb#L232.
