### ISSUE TITLE
Codeblock output options

### ISSUE THREAD

**Issue by buschhardt** [gettalong/kramdown#420]
Hallo,

is there the posibility to change the output of codeblocks, when I use the `.to_kramdown` method?
E.g
Input:
```
~~~
mycode
~~~
```

Output :
(4 spaces)mycode

I want output like the input. Maybe a option exists for this?
Thank You

**Comment by gettalong** [comment]
No, there is currently no such option. You can customize the converter and override the `#convert_codeblock` method to change how codeblocks are output.
