### ISSUE TITLE
Generated Anchor IDs break when upgrading from 1.12.0 to 1.13.x

### ISSUE THREAD

**Issue by jpstroop** [gettalong/kramdown#424]
Given the Markdown:

```
# 5.5 Foo Bar
```

in 1.12.0 this the generated ID is `foo-bar`, and in 1.13.0 the generated ID is `55-foo-bar`. Is this known? Was it intentional?

**Comment by zimeon** [comment]
Seems that this should be caught by the testcase https://github.com/gettalong/kramdown/blob/master/test/testcases/block/04_header/with_auto_ids.text --> https://github.com/gettalong/kramdown/blob/master/test/testcases/block/04_header/with_auto_ids.html#L3 ... where heading "12. Another one-1-here" is supposed to generate id `another-one-1-here` as documented in https://kramdown.gettalong.org/converter/html.html#auto-ids

**Comment by gettalong** [comment]
With kramdown v1.13.1:

~~~
$ kramdown
<h1 id="foo-bar">5.5 Foo Bar</h1>
$ kramdown --auto-id-stripping
<h1 id="foo-bar">5.5 Foo Bar</h1>
$ kramdown --no-auto-id-stripping
<h1 id="foo-bar">5.5 Foo Bar</h1>
$ kramdown -i GFM
<h1 id="55-foo-bar">5.5 Foo Bar</h1>
~~~

Also see the release notes: https://kramdown.gettalong.org/news.html#kramdown-1130-released

**Comment by jpstroop** [comment]
Ah--missed that note. Thanks!

**Comment by jpstroop** [comment]
I'd point out that this could be considered a breaking change, since it's no longer possible to use GFM unless you're willing to accept broken IDs.

**Comment by gettalong** [comment]
@jpstroop You would be right if the GFM parser of kramdown was introducing something new, something not covered by the GFM spec (in this case I don't mean the new spec based on CommonMark but the non-existent spec for the original GFM). However, in this case the behaviour of kramdown's GFM parser was buggy and got fixed and people relying on the buggy behaviour got bitten.
