### ISSUE TITLE
How to escape @something for it NOT to get linked as a user-mention?

### ISSUE THREAD

**Issue by mbirth** [gettalong/kramdown#426]
If have a HTML with Markdown template in GitHub Pages with a LD+JSON section like this:

```
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "WebSite",
    "url": "{{ site.url }}/",
    "potentialAction": {
        "@type": "SearchAction",
        "target": "{{ site.url }}/?q={search_term_string}",
        "query-input": "required name=search_term_string"
    }
}
</script>
```

I can't seem to find a way to prevent Kramdown from trying to link the `@context` to a GitHub user, rendering the JSON into some invalid mess. When I escape it, e.g. `"\@context"`, I get `"\<a href="https://github.com/context" class="user-mention">@context</a>"`. Liquid `{% raw %}` tags also didn't help. And, for some reason, GitHub Pages doesn't seem to support the `{::nomarkdown}` extension. And I can't find any other way to prevent this from getting auto-linked.

How can I escape that properly?

**Comment by gettalong** [comment]
If you feed your short example to kramdown (either using the kramdown parser or the GFM parser), the script tag comes out as is. So there must be a problem somewhere else in your pipeline. Maybe the tool you are using does some additional processing.

**Comment by mbirth** [comment]
Problem is: I can't change anything as I'm using GitHub Pages. [Here](https://github.com/mbirth/wiki/blob/gh-pages/index.html)'s the source file and [this is](http://wiki.mbirth.de/) (see source) what GitHub Pages makes of it. Can be reproduced locally with [this Jekyll setup](https://github.com/mbirth/wiki/blob/gh-pages/Gemfile) (based on [these instructions](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/)).

**Comment by gettalong** [comment]
If it is a problem with Github Pages, please ask the Github Pages or Jekyll guys and gals as I'm not involved in that project - thanks!
