### ISSUE TITLE
Add option to render footnotes as inline spans

### ISSUE THREAD

**Issue by pron** [gettalong/kramdown#427]
An option to render footnotes as spans at the point of their reference rather than at the end of the text would allow presenting them as sidenotes with proper styling as in [here](https://edwardtufte.github.io/tufte-css/).

**Comment by gettalong** [comment]
You can do that by creating a custom HTML converter that changes how footnotes are displayed.

**Comment by pron** [comment]
Any links to an explanation on how to write such a custom converter?

**Comment by gettalong** [comment]
See the API docs as usual: https://kramdown.gettalong.org/rdoc/Kramdown/Converter/Base.html and the implementation of the HTML converter at https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/html.rb for an example.

**Comment by idmyn** [comment]
Hi, I've started writing a custom converter for this and I think I'm really close but I'm not sure how to render the footnote content:

```ruby
class Kramdown::Converter::Html
  def convert_footnote(el, _indent)
    name = @options[:footnote_prefix] + el.options[:name]
    if (footnote = @footnotes_by_name[name])
      number = footnote[2]
    else
      number = @footnote_counter
      @footnote_counter += 1
      @footnotes << [name, el.value, number, 0]
      @footnotes_by_name[name] = @footnotes.last
    end

    span = Kramdown::Element.new(:span)
    span.children = Marshal.load(Marshal.dump(el.value.children))

    # not sure what the last arg should be: I've tried el, el.value, span, convert(span)
    sidenote_content = format_as_span_html('span', {class: "sidenote"}, span)

    "<span class=\"sidenote-wrapper\"><label for=\"sn-#{name}\" class=\"margin-toggle sidenote-number\"></label>" \
      "<input type=\"checkbox\" id=\"sn-#{name}\" class=\"margin-toggle\">" \
      "#{sidenote_content}</span>"
  end
end
```

I'm sure it's just a small change that I'm missing but I'm an inexperienced rubyist so I'm struggling to debug it and any help would be massively appreciated 😅

**Comment by gettalong** [comment]
* There is no element type named `:span`. So defining the `span` element doesn't work as you would expect.
* The last element of `format_as_span_html` needs to be the rendered body of the element.
* You can directly render the children of an element using the `#inner` method. So in you case you would provide `inner(el.value, _indent)` as last element to the `format_as_span_html` call.

**Comment by idmyn** [comment]
Thanks @gettalong! `inner` is what I needed :)

for anybody finding this in the future, this is what ended up working for me (for jekyll, I added a file called `sidenotes.rb` with the following code in the `_plugins` directory and it was picked up automatically)

```ruby
class Kramdown::Converter::Html
  def footnote_content()
    ""
  end

  def convert_footnote(el, _indent)
    name = @options[:footnote_prefix] + el.options[:name]
    if (footnote = @footnotes_by_name[name])
      number = footnote[2]
    else
      number = @footnote_counter
      @footnote_counter += 1
      @footnotes << [name, el.value, number, 0]
      @footnotes_by_name[name] = @footnotes.last
    end

    sidenote_content = format_as_span_html('span', {class: "sidenote"}, inner(el.value.children[0], _indent))

    "<span class=\"sidenote-wrapper\"><label for=\"sn-#{name}\" class=\"margin-toggle sidenote-number\"></label>" \
      "<input type=\"checkbox\" id=\"sn-#{name}\" class=\"margin-toggle\">" \
      "#{sidenote_content}</span>"
  end
end
```
