### ISSUE TITLE
Is there anything that can be done about the ordered list reset problem?

### ISSUE THREAD

**Issue by meygerjos** [gettalong/kramdown#428]
People are talking about this with respect to jekyll, but it seems like it's also a kramdown problem:

http://stackoverflow.com/questions/35858704/jekyll-kramdown-code-in-ordered-list-number-reset#41917631
https://github.com/jekyll/jekyll/issues/588

The issue is that liquid tags within ordered lists cause the ordered lists to start over after the liquid tags.

A possible solution: the liquid tag could be wrapped in something (i.e. `{_ {% [liquid tag] %} _}`), and `kramdown` could interpret the wrapper `{_..._}` as "don't break up the ordered list for the sake of me!"  In other words, `kramdown` would ignore all the whitespace and newlines from the first non-whitespace before `{_` to the last non-whitespace after `_}` when making its judgements about starting or ending block elements.

**Comment by gettalong** [comment]
This is no problem for kramdown to solve but for the tool that uses kramdown. Consider: Should kramdown know the whims of each and every template language? The definitive answer is: no.

If the input that kramdown gets is not well formatted, be it a user input error or the error of another library/application, kramdown can nothing do to correct this problem.
