### ISSUE TITLE
Redefined method warning from kramdown

### ISSUE THREAD

**Issue by zenspider** [gettalong/kramdown#429]
When running my tests (that always run with `-w`:

```
[...]/kramdown-1.12.0/lib/kramdown/compatibility.rb:43: warning: method redefined; discarding old <=>
```

This is because the check is wrong:

```
if !Symbol.instance_methods.include?("<=>")

  class Symbol
    def <=>(other)
      self.to_s <=> other.to_s
    end
  end

end
```

Since `Symbol.instance_methods` returns an Array of Symbols.

A better/safer check might be:

```
10001 % ruby -e 'p :<=>.respond_to? :<=>'
true
```

Happy to send a PR, but let me know what direction you'd like to go in first.

**Comment by gettalong** [comment]
Thanks for letting me know! I will fix this for the next release - your mentioned solution doesn't work for Ruby 1.8.7 (yeah, I know, it's EOL).

**Comment by zenspider** [comment]
It doesn't? I figured behavior testing would be safer.

**Comment by zenspider** [comment]
The other way is to always map in one direction.

**Comment by gettalong** [comment]
Yep, I will probably do something along these lines - or maybe just throw compatibility with Ruby < 2.0 out since those versions are not officially supported anymore.

**Comment by lloeki** [comment]
@gettalong we're on a warning hunting spree over there, checking everything we find against upstream, and this one came up on our radar, care to give some status update?

BTW, what's the rationale behind [this line](https://github.com/gettalong/kramdown/blob/e9714d87e842831504503c7ed67f280873d98908/Rakefile#L99)? It may be a good target to make it true (the default starting with rake 11), what do you think?

**Comment by gettalong** [comment]
@lloeki This will be fixed in the next release, probably be removing Ruby <2.0 support.

**Comment by gettalong** [comment]
@lloeki One reason for not enabling warnings is that rouge throws myriads of them, littering the output.

**Comment by gettalong** [comment]
Done.

**Comment by lloeki** [comment]
Thanks a lot!

Should the rouge warnings be reported upstream?

**Comment by gettalong** [comment]
Possibly, yes.
