### ISSUE TITLE
Whitespace between divs

### ISSUE THREAD

**Issue by passsy** [gettalong/kramdown#430]
```
<div>
<div markdown="1" style="display: inline-block">
Box1
</div>
<div markdown="1" style="display: inline-block">
Box2
</div>
<div markdown="1" style="display: inline-block">
Box3
</div>
</div>
```

Results in 

`Box1<whitespace>Box2<whitespace>Box3`

Added whitespace for a newline

### Workaround:
remove newline between divs

```
<div>
<div markdown="1" style="display: inline-block">
Box1
</div><div markdown="1" style="display: inline-block">
Box2
</div><div markdown="1" style="display: inline-block">
Box3
</div>
</div>
```

Results correctly in 

`Box1Box2Box3`

### Screenshot:

![screen shot 2017-05-10 at 20 25 34](https://cloud.githubusercontent.com/assets/1096485/25914522/dceb2c88-35be-11e7-902b-350f83560617.png)

**Comment by gettalong** [comment]
So... what is the question here? In the first example *you* put whitespace between the `<div>` tags which is reflected in the output, whereas in the second example you *removed* the whitespace and so doesn't show anymore...

Could you show the current output and how it should be changed in your opinion? Or is there another issue?

**Comment by passsy** [comment]
I was expecting that a newline doesn't add a whitespace to the html output when the next entry after the newline is another html tag.

**Comment by passsy** [comment]
Another workaround to remove the whitespace between HTML tags are comments

```
<div>
<div markdown="1" style="display: inline-block">
Box1
</div><!--

--><div markdown="1" style="display: inline-block">
Box2
</div><!--

--><div markdown="1" style="display: inline-block">
Box3
</div>
</div>
```

**Comment by gettalong** [comment]
Yeah, but a newline *is* whitespace. This has nothing to do with kramdown but everything with HTML. You might wanna read up on how HTML handles whitespace and how the white-space CSS property can be used to manipulate the default setting for elements.

As for comments: Note that there isn't any space between the end of the div and the start of the comment and also none between the end of the comment and the start of the next div. If there was, you would have the same problem.
