### ISSUE TITLE
Bug - pipe character in Markdown link creates a table

### ISSUE THREAD

**Issue by CarlKing5019** [gettalong/kramdown#431]
Inline link contains a pipe character was converted to a table, which is different to GFM.
The bug reported in <https://github.com/jekyll/jekyll/issues/2818> is still existing.
If it's convenient, could you fix it? Many thanks!

**Comment by gettalong** [comment]
This has nothing to do with convenience.

You need to escape the pipe character as stated in the syntax documentation.

Yes, I know, this is cumbersome but that's the way it is for now until version 2.x.

**Comment by CarlKing5019** [comment]
Thanks for your kindly reply.

**Comment by Lin-Buo-Ren** [comment]
@gettalong 

> You need to escape the pipe character as stated in the syntax documentation.

Would you mind specifying where it is stated?  <https://daringfireball.net/projects/markdown/syntax#autoescape> doesn't mention that the pipe symbol is required to be escaped.

Currently I escaped it using `&#124;` but I really think that it is unnecessary.

**Comment by Lin-Buo-Ren** [comment]
Nevermind, I noticed that it is mentioned in <https://kramdown.gettalong.org/syntax.html#automatic-and-manual-escaping>

**Comment by whuwangyong** [comment]
> 

And now the version is 2.3, but the bug still exists. Or anything I missed?

**Comment by gettalong** [comment]
@whuwangyong There is no bug, it works as stated. You need to escape the pipe character as per the syntax documentation - see https://kramdown.gettalong.org/syntax.html#tables
