### ISSUE TITLE
It is possible to make kramdown ToC work outside content block?

### ISSUE THREAD

**Issue by tu5** [gettalong/kramdown#432]
I'm trying to put ToC inside the sidebar, instead of in content block. Is it possible with kramdown?

site url: https://tu5.github.io/toc/
repo: https://github.com/tu5/toc
sidebar: https://github.com/tu5/toc/blob/master/_includes/sidebar.html

**Comment by gettalong** [comment]
You can put the placeholder for the ToC anywhere in the kramdown document, see https://kramdown.gettalong.org/converter/html.html#toc for an example.

**Comment by tu5** [comment]
Do you have an idea why it doesn't render on my site? Maybe I'm missing something oblivious.

**Comment by gettalong** [comment]
I don't know which tools you use to create your website, so better ask the creators of those tools since this doesn't seem to be a problem with kramdown itself but with its usage.

**Comment by tu5** [comment]
It's just pure html+css and jekyll from github pages

**Comment by gettalong** [comment]
So you need to ask the Jekyll community since you are using Jekyll to create HTML from Markdown documents via kramdown.
