### ISSUE TITLE
{:toc} leaves links

### ISSUE THREAD

**Issue by nate-wernimont** [gettalong/kramdown#434]
Hello, I am making a website using jekyll, and I am using a table of contents. My problem is that I am linking to websites with my headers, but I want the table of contents to link to where that header is on the page, not to the same website that the header links to.

So, my markdown document looks something like this:

---
layout: page
---

1. TOC
{:toc}

## [Header](link to website)
information
...
...

## [Header](link to website)
...
...

Is there anyway to remove that link when I generate my table of contents so that the table of contents can function correctly?

**Comment by gettalong** [comment]
You could you a post-processor to remove the inner `<a>` tags.

However, according to the [HTML 5 spec](http://w3c.github.io/html/single-page.html#the-a-element) nested `<a>` tags are not allowed. So the better solution would be for kramdown to strip all `<a>` tags from the content of a TOC entry itself.

Marking this as a bug - thanks for reporting!

**Comment by nate-wernimont** [comment]
As an update, I looked at the generated HTML code, and it doesn't even nest the <a>. It leaves them as completely separate, which is weird to me. So, it does the following when it is trying to make a table of contents that has links:

<a href="#example" id="markdown-toc-example"></a>
<a href="https://link.to.example.com">Example</a>

**Comment by gettalong** [comment]
Hmm... if I run your example through kramdown I get the following output for the TOC:

~~~ html
<ol id="markdown-toc">
  <li><a href="#headerlink-to-website" id="markdown-toc-headerlink-to-website"><a href="link to website">Header</a></a></li>
  <li><a href="#headerlink-to-website-1" id="markdown-toc-headerlink-to-website-1"><a href="link to website">Header</a></a></li>
</ol>
~~~

As you can see, the `<a>` tags *are* nested. Maybe some postprocessing recognizes the invalid nesting and closes the first tag?

**Comment by nate-wernimont** [comment]
You are right. When I view the actual source, it is nested, but it appears that Safari un nests it in the inspect element box.

**Comment by gettalong** [comment]
Done - will be in the next release.
