### ISSUE TITLE
{: #myid} does not work on td or tr table elements

### ISSUE THREAD

**Issue by axelfontaine** [gettalong/kramdown#436]
{: #myid} does not work on td or tr table elements. This is however quite useful to be able to define anchors on large tables.

Proposal:

```
Col 1 | Col 2
----- | -----
abc | def
{: #myid}xyz | 123
```

Should result in the row with `xyz` being rendered as `<tr id="myid"><td>xyz</td><td>123</td></tr>`

**Comment by gettalong** [comment]
You are right, this is not possible right now. Pull request are welcome!

**Comment by gettalong** [comment]
@axelfontaine I'm closing this since feature requests needing a pull request are closed and tracked through the "Feature Request" project.
