### ISSUE TITLE
Option to automatically add one or more classes globally

### ISSUE THREAD

**Issue by skinless8** [gettalong/kramdown#437]
newb question here....

Looking for a way to automatically add one or more class to a set of tags; mainly for bootstrap purposes.

For example, would like to see all `<img ...>` to be `<img class="img-fluid" ...>`, without having to add `{:.img-fluid}` to each image in my kramdown docs.

**Comment by gettalong** [comment]
You have several options to achieve this:

* Transform the AST (abstract syntax tree) returned by the kramdown parser and change the elements and their data before the AST is sent to the HTML converter.
* Create a new converter class based on the standard HTML converter and adapt any or all elements as you need.
* Post-process the output of kramdown's HTML converter with a tool that does what you need.
