### ISSUE TITLE
New release to support Rouge 2

### ISSUE THREAD

**Issue by Crunch09** [gettalong/kramdown#439]
Hi,
unfortunately Rouge 2 support has only been added after the last release of kramdown in Rubygems [in January](https://rubygems.org/gems/kramdown). Is there any possibility that we could have a new release, please?
Please let me know if i can help with any blockers which are postponing a release.

**Comment by gettalong** [comment]
There you go: https://kramdown.gettalong.org/news.html :smile:

**Comment by Crunch09** [comment]
Wonderful! 🎉  Thank you!!
