### ISSUE TITLE
Abbreviations don't work in footnotes

### ISSUE THREAD

**Issue by thomasleese** [gettalong/kramdown#440]
It looks like abbreviations don't work in footnotes, with the following Markdown input I would expect to see an `abbr` tag in both the paragraph at the beginning and then in the footnote paragraph as well, but it doesn't appear in the footnote.

Input:

```markdown
There is a TXT file here. [^1]

*[TXT]: Text File

[^1]: A TXT file.
```

Output:

```html
<p>There is a <abbr title="Text File">TXT</abbr> file here. <sup id="fnref:1"><a href="#fn:1" class="footnote">1</a></sup></p>

<div class="footnotes">
  <ol>
    <li id="fn:1">
      <p>A TXT file.&nbsp;<a href="#fnref:1" class="reversefootnote">&#8617;</a></p>
    </li>
  </ol>
</div>
```

**Comment by gettalong** [comment]
Thanks for reporting - it certainly seems that abbreviation substitution should also be done in the footnotes.

Will fix that for the next release.

**Comment by gettalong** [comment]
Done.
