### ISSUE TITLE
[feature request] SVG output with mathjax-node

### ISSUE THREAD

**Issue by luc-j-bourhis** [gettalong/kramdown#443]
Considering how lacking is the support of MathML in browsers, the mathjax-node converter would be far more useful if it could output SVG. This could be done by using `tex2svg` instead of `tex2mml`.

**Comment by gettalong** [comment]
Thanks for the idea - you are welcome to provide a pull request for this feature.

I will close this feature request since feature requests needing a pull request are tracked through a project.
