### ISSUE TITLE
Non-English smart quotes render typographically wrong apostrophes

### ISSUE THREAD

**Issue by michaelfranzl** [gettalong/kramdown#445]
Example in German:

```
txt = "\"He said: 'Einstein'sche Relativitätstheorie.'\""
opts = { :smart_quotes => %w{sbquo lsquo bdquo ldquo} } # configure german quotes
latex = Kramdown::Document.new(txt, opts).to_html
```

Outputs: 
„He said: ‚Einstein‘sche Relativitätstheorie.‘“

Should be:
„He said: ‚Einstein’sche Relativitätstheorie.‘“

Maybe the `smart_quotes` option could take a fifth element which configures the entity to be used for mid-word apostrophes. Correct example for German would be:

    opts = { :smart_quotes => %w{sbquo lsquo bdquo ldquo rsquo} }

**Comment by gettalong** [comment]
I'm not that keen on changing things in the `smart_quotes` parser. The example you mention is just one thing that is not done correctly since the parser itself is more or less English-centric. I don't think there is a good and easy solution for this - any ideas?

**Comment by michaelfranzl** [comment]
No problem. Just thought I'd mention it. I've monkey patched it to suit my needs. Issue can be closed, thanks.

**Comment by gettalong** [comment]
Thanks for your understanding!

If your fix is of a general nature, you might wanna upon a pull request.
