### ISSUE TITLE
Visual Studio Code (VSCode) plugin

### ISSUE THREAD

**Issue by ohadschn** [gettalong/kramdown#447]
It would be great to have a kramdown plugin in VSCode.
Preview would be the most important feature IMHO, followed by syntax highlighting and auto completion.

**Comment by gettalong** [comment]
Certainly a nice idea and I'm open for a pull request if this needs to be implemented inside the kramdown repo. But I have a feeling that it would be better to create a new repo for this plugin.

As with other enhancements that need a pull request, I will close this issue and file it in the "Feature Requests" project. Comments are still open for discussing.
