### ISSUE TITLE
Arabic numbers in non-European digits form do not produce a numbered list

### ISSUE THREAD

**Issue by mehdisadeghi** [gettalong/kramdown#450]
kramdown produces numbered lists only if one uses [Arabic numerals](https://en.wikipedia.org/wiki/Arabic_numerals) with their European digits form. This is fine by kramdonw:

    1. One
    2. Two and so on

But the following example - which is using Persian digits - will produce a normal paragraph and not a numbered list:

    ۱. one
    ۲. two and so on

How could one possibly fix this?

P.S. Another Unicode related issue is #281

**Comment by gettalong** [comment]
If we would follow that logic, we would need to implement different list parsers for every language out there... which is neither useful nor efficient.

In kramdown the syntax for unordered lists uses `*`, `+` or `-`, and the ASCII characters `0` to `9` for ordered lists. That's just how the syntax was designed. If I were to design kramdown now, I still would *only* use these characters.

This means that there is nothing to "fix". So if you want to change the symbols used for ordered lists, feel free to implement a parser based on the main kramdown parser that uses an alternate set of characters for ordered lists.

**Comment by mehdisadeghi** [comment]
> If we would follow that logic, we would need to implement different list parsers for every language out there... which is neither useful nor efficient.

I think one unicode-aware parser would suffice. Probably based on gems such as [twitter-cldr](https://github.com/twitter/twitter-cldr-rb).

> If you want to change the symbols used for ordered lists, feel free to implement a parser based on the main kramdown parser.

By this I would assume you mean creating a new library with a custom parser such as `kramdown-unicode` or something similar and keeping kramdown ASCII-oriented.

As a side note for future visitors, once can easily change HTML presentation of ordered-lists to their language by setting `list-style-type` CSS property. For example `list-style-type:persian` will cause the digits to be displayed with Persian numerals.

**Comment by gettalong** [comment]
Yes, kramdown is open source and if you need something that doesn't really make sense for kramdown itself you can easily create something upon it.
