### ISSUE TITLE
Feature request: mechanism to ignore newlines

### ISSUE THREAD

**Issue by kylebarbour** [gettalong/kramdown#452]
In `bash` and many other languages, you can use the escape character to ignore newlines:

    $ echo "You are in a maze of \
    > twisty little passages, all alike."
    You are in a maze of twisty little passages, all alike.
    $

It would be excellent to be able to do the same thing in kramdown. Generally, the [lazy syntax](https://kramdown.gettalong.org/syntax.html#line-wrapping) renders this unnecessary. However, there are some situations (like tables) where this would be really nice, such as having

    | You are in a maze of \
      twisty little passages, all alike. | xyzzy | plugh |

be parsed the same as

     | You are in a maze of twisty little passages, all alike. | xyzzy | plugh |

This would enhance the readability of very long table lines while using syntax that is already familiar.

Thanks for considering!

**Comment by gettalong** [comment]
First note that using two backslashes at the end of a line already has a defined meaning in kramdown syntax, creating a line break.

As for introducing something like this for tables: It may possibly be not difficult to implement, however, I question whether such syntax is generally useful for tables. kramdown's table syntax was only designed for very *simple* tables...

**Comment by kylebarbour** [comment]
I hear what you're saying --- I like that kramdown does what it does well and isn't trying to be a complete replacement for HTML, and feature creep can be bad. This wouldn't change anything about the kind of tables you can have, though, it would just allow for lines that are easier to read in an editor. No functionality that doesn't already exist would be created --- after all, you can just have them be on one line at the moment.

Two backslashes are defined as creating a `<br />`, but one I think doesn't produce any output, and the `\\` syntax is ignored inside tables anyhow (just creating a single backslash).

**Comment by gettalong** [comment]
Okay, I get your point. Another question: Should this new feature be just available for tables, or also for other elements?

Implementation-wise for tables I would probably just check if a table line ends with a single backslash, and then unconditionally append the following line to it, dropping the backslash in the process.

I will also need to check/think about if this new feature will change general processing of a file in a bad backwards-incompatible way.

**Comment by kylebarbour** [comment]
I haven't run into this issue with any other environment, so while there might be a need for it I think the lazy syntax obviates the need for this anywhere else. So I think just in tables in fine unless you'd like to generalize it more.

I think your implementation idea is great - that's exactly what I was thinking.

**Comment by ccorn** [comment]
Some observations:
* TeX math uses the combination of backslash and white space (including linefeed) as an actually typeset horizontal space (of about 1ex width if I recall correctly). From Math SE I recall that this works as expected with MathJax (whereas current KaTeX signals a parse error when I try that). So I'd like to see a change like that restricted to table parsing.
* I have tried whether `<!-- NL -->` does the trick (with `NL` representing the newline): No.
* However, my template engine (Liquid) swallows `{{ ''NL}}` reliably before the text gets passed to kramdown. So there might be an alternative already.

**Comment by gettalong** [comment]
@kylebarbour Sorry for taking so long!

I really think that this won't be a good change for kramdown. It complicates the table syntax and makes thinking about table rows more complicated than necessary. The proper way to implement something like this would probably be to allow table rows with multiple lines in the source text.

So this won't be implemented.
