### ISSUE TITLE
Feature request: markdown stripper / plaintext converter

### ISSUE THREAD

**Issue by riffraff** [gettalong/kramdown#456]
I have a use case where I want to render some markdown as HTML in some places, and as plain text in others.

When rendering to plaintext  I don't want to keep the `**stuff**`  around.

Redcarpet has an utility converter that [does this](http://www.rubydoc.info/github/vmg/redcarpet/Redcarpet/Render/StripDown), but I could not find an equivalent for Kramdown.

So, I am currently first rendering into HTML and then stripping tags and unencoding entities, but this is obviously very wasteful and it would be cool if we had native support for this (or maybe there is, but I couldn't find it).

Also, notice `remove_span_html_tags` and `remove_block_html_tags` are not enough, as entities are escaped.

**Comment by gettalong** [comment]
For this feature we would first need to define which kramdown syntax markers should be stripped, e.g. `#` for headings?, `*` and `_` for  emphasis?, all markers? What about list item markers? Or blockquote markers? Or table indicators?

Such things need to be clarified first. The implementation itself should be rather straight forward, most things could probably just be copied from the kramdown converter.

As with all feature requests that need a pull request, I have filed this under the "Feature Requests" project and will close this issue.

**Comment by riffraff** [comment]
sorry I'm not familiar with the process, am I supposed to still reply here even though the feature is closed? I don't see a way to interact with the project entry otherwise.

So forgive me if this is not the right way, but I'll reply here.
My point of reference is https://github.com/vmg/redcarpet/blob/e3a1d0b00a77fa4e2d3c37322bea66b82085486f/lib/redcarpet/render_strip.rb

So, span-ish, block-ish, list-ish, and footonote-ish elements are rendered with markers stripped (other than newlines), tables are rendered as tab-formatted, links are rendered as `text (url)` (title stripped) and images are `title http://example.org/picture.png`. 
Horizontal rules are dropped.

This of course arbitrary and incomplete and I'm mostly interested in removing inline markers, so it would be fine _for me_ to error out ("this kind of markdown cannot be stripped") or passthrough if things other than basic markers are used.

I can try to put together a PR if this seems reasonable.

**Comment by gettalong** [comment]
Yes, just use this issue for further discussion. Once there is someone willing to do a PR, I will reopen the issue.

If you implement something very specific, it would be best to put it into a separate Rubygem. If there is a general solution, usable by many people, it probably makes sense to include it into kramdown itself.

For the general solution, we would need to discuss the handling of all entities. E.g. I wouldn't drop horizontal rules completely but output something useful because horizontal rules are often used for separating parts of some text.
