### ISSUE TITLE
[GFM] wrong ID generation for headers containing --

### ISSUE THREAD

**Issue by kolyshkin** [gettalong/kramdown#459]
Consider the following fragment of an `.md` file on github:

```md
...
see [--foobar](#option---foobar) option below.
...
## Option --foobar
```

The above gets rendered by GitHub to the following:

...
see [--foobar](#option---foobar) option below.
...
## Option --foobar

Now, if we use kramdown GFM to convert this .md, we'll have the following two problems:

1. Double dash gets replaced by ndash, which is bad at least in this particular case, and maybe in general, as GitHub's own parser doesn't do it.
2. The link to "Option --foobar" will not work, as ID for the intralink will be `option-foobar` rather than github's `option---foobar`. The reason is the above double-dash -> ndash conversion.

While the first issue is only bad in some specific cases, the second one is really bad as it breaks some intralinks in the resulting document. Perhaps it makes sense to disable double-dash and triple-dash conversion for GFM (say, another option to gfm_quirks)?

**Comment by gettalong** [comment]
If we change the way link generation works for the GFM parser, it might break existing documents. However, since it is GFM we are talking about and the implementation in kramdown is not quite complete, I would consider such a change a bug fix and not a feature change.

A pull request for the this is welcome.

**Comment by kolyshkin** [comment]
OK, I have a PR with a patch that apparently works. I'm just not sure about it as my Ruby knowledge is totally non-existent, to say at least.

**Comment by gettalong** [comment]
Pull request #462 is applied.
