### ISSUE TITLE
Angle-bracketed URL right after a linebreak is rendered without the linebreak

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [gettalong/kramdown#461]
## Input
```markdown
First line  
<https://example.com/second-line-url>  
Third line <https://example.com/with-an-url>
```

Note: 2 trailing space characters after `First line` and `/second-line-url>`

## Current Output
```html
<p>First line
<a href="https://example.com/second-line-url">https://example.com/second-line-url</a><br />
Third line <a href="https://example.com/with-an-url">https://example.com/with-an-url</a></p>

```

## Expected Output
```html
<p>First line<br />
<a href="https://example.com/second-line-url">https://example.com/second-line-url</a><br />
Third line <a href="https://example.com/with-an-url">https://example.com/with-an-url</a></p>
```

## Commandline
`kramdown --input kramdown --output html <kramdown-issue-461-reproduction-sample.markdown >kramdown-issue-461-reproduction-sample.html` in GNU Bash

## Additional Info
Here's the output when `--input` is set to `GFM`

```html
<p>First line<br />
<a href="https://example.com/second-line-url">https://example.com/second-line-url</a>  <br />
Third line <a href="https://example.com/with-an-url">https://example.com/with-an-url</a></p>
```

Notice the re-appeared expected line break at line 1 and redundant 2 spaces before the line break of line 2

## Kramdown
1.15.0 from RubyGems

## Ruby
2.3.1p112 (2016-04-26) from Ubuntu 16.04 archive

**Comment by Lin-Buo-Ren** [comment]
Another mismatch render result [here](https://lin-buo-ren.github.io/#%E6%88%91%E7%9A%84%E8%81%AF%E7%B5%A1%E6%96%B9%E5%BC%8Fmy-contact-info)

![_326](https://user-images.githubusercontent.com/13408130/31585502-2026bafa-b1f5-11e7-825b-e16ce0af3bf7.png)

**Comment by gettalong** [comment]
Please edit your issue text so that it is clear what the difference is, showing the input, the current HTML output and the, in your opinion, correct HTML output. Images are not really useful.

**Comment by Lin-Buo-Ren** [comment]
@gettalong Updated.  Thanks for pointing out.

**Comment by gettalong** [comment]
Thanks for updating the issue - now I know what you mean :+1: And it seems to be a bug.

**Comment by gettalong** [comment]
I have identified the problem - the fix will be in the next release!
