### ISSUE TITLE
Markdown bidi Links (issue with RTL), add dir=auto

### ISSUE THREAD

**Issue by laukstein** [gettalong/kramdown#463]
The issue reported also in https://github.com/jekyll/jekyll/issues/6293
Test-case https://output.jsbin.com/capezil/quiet

When `<url>` contains RTL characters it is rendered wrongly, 'broken' especially when parent dir=rlt,
see the example of `<https://domain.com/dir/קישור-למאמר/1>` ( to be clear is `https://domain.com/dir` + `/קישור-למאמר` and **only in the end** `/1` )

**current result**

![grabilla g10032](https://user-images.githubusercontent.com/183966/29195911-c5e4f140-7e39-11e7-82fe-81a8933bc93d.png)

the **expected result**

![grabilla uh2448](https://user-images.githubusercontent.com/183966/29195991-523b9234-7e3a-11e7-858e-faf6b0886815.png)

This issue can be **safely and easily fixed** by adding `dir=auto` to `<a>` Markdown generated links `<url>` and `[text](url)`.

Lets say we have today

    <a href="http://domain.com/page">Link</a>

it needs to be changed to 

    <a href="http://domain.com/page" dir=auto>Link</a>

**Comment by gettalong** [comment]
You can use an IAL if you need to set the `dir` attribute on either kind of links, like this for example:

~~~ 
<https://domain.com/dir/קישור-למאמר/1>{: dir="auto"}
~~~

If you need this on all links, please subclass the HTML converter class and override the link generation methods.

**Comment by laukstein** [comment]
@gettalong, can you please explain me how I apply it to all links when using [Github Pages](https://github.com/github/pages-gem) [Jekyll](https://github.com/jekyll/jekyll) ? It probably needs to be done in **_config.yml**?

**Comment by laukstein** [comment]
@gettalong, please reopen this issue! Your suggestion wouldn't work in Github Pages. The fix needs to be made in Kramdown globally or trough _config.yml

**Comment by gettalong** [comment]
@laukstein As I wrote, if you want to apply this on all links you should subclass the HTML converter to implement what you need.

**Comment by laukstein** [comment]
@gettalong this issue is a feature request to do it trough _config.yml or to apply it to all links by default.

**Comment by gettalong** [comment]
_config.yaml is something Jeykyll specific, you need to ask there for that. As for applying it to all links by default: As I said you need to writer a custom converter.

**Comment by pathawks** [comment]
Let’s forget about `_config.yml`, I think that’s distracting from the issue.

Is there any way that kramdown could detect when a URL includes RTL characters and set the `dir` accordingly? Could an option be added to kramdown to toggle this behavior? If that happened, this could easily be turned on by Jekyll.

Or is that not something that kramdown can support? If that is the case, a custom converter would be needed.

**Comment by gettalong** [comment]
If this functionality is needed, it is easy to create a new converter or parser. I just don't think it is a good fit for the kramdown parser or the main HTML converter.
