### ISSUE TITLE
Feature Request: Render inside Div blocks?

### ISSUE THREAD

**Issue by st4rdog** [gettalong/kramdown#467]
https://github.com/chjj/marked/issues/488

I'm trying to add pagination to individual pages, like so:
```html
---
---
<div class="page-break">
## Introduction
Paragraph.
</div>

<div class="page-break">
## Setup
Paragraph.
</div>
```

But it displays the headings as raw text. Using span will fix the headings, but displays a ```</span>``` as raw text.

It's mentioned in the linked issue that some markdown implementations do it this way:
```html
<div markdown="1">
# Heading
</div>
```

If there's no solution, do you know of any way supported by github pages?

**Comment by gettalong** [comment]
I don't see the problem since kramdown already supports the `markdown="1"` attribute. Your sample will result in the following output:

~~~html
<div>
  <h1 id="heading">Heading</h1>
</div>
~~~
