### ISSUE TITLE
Feature request: option to disable smart punctuation other than quotes

### ISSUE THREAD

**Issue by kylebarbour** [gettalong/kramdown#472]
kramdown currently has a simple mechanism to disable smart quotes (double and single):

    $ kramdown --smart-quotes apos,apos,quot,quot file.txt

However, kramdown additionally generates ellipses (U+2026, …) from three periods (...). I think a number of folks like me who opt to preserve ASCII quotes would prefer to retain the three periods as well. This could be as simple as a `--no-ellipsis` option. I currently remove them with `sed`.

I think this addresses all the "smart" punctuation. The other main ones are en-dashes (U+2013, –) and em-dashes (U+2014, —), but those are easily avoided if desired by just typing a single hyphen, although I think it would be great to have an option to suppress those as well so one can use `--` and `---` as preferred.

Thanks for considering!

**Comment by gettalong** [comment]
kramdown currently converts `---`, `--`, `...`, `<<` and `>>`. If we create a new option, it should probably be similar to `--smart-quotes` in that each "smart punctuation" conversion should be switchable.

Something along the lines `--typographic-syms "{mdash: ---, ndash: --, hellip: ...}"`.

Would that make sense to you? And would this solve your problem?

**Comment by kylebarbour** [comment]
That makes sense to me and would solve my problem as well!

**Comment by gettalong** [comment]
Thanks for your contribution - I have implemented this and it will be in the next release.
