### ISSUE TITLE
Feature request: recognize backtick as math delimiter (AsciiMath syntax)

### ISSUE THREAD

**Issue by gioele** [gettalong/kramdown#474]
The AsciiMath syntax (supported by MathJax 2.x) delimits inline and display mathematical expressions using the backtick character (entered as "backslash" + "backtick" in markdown). It would be nice if kramdown could recognize this delimiter as it does with other delimiters like `$$`.

My current workaround is to style those paragraphs with explicit classes. Example:

```
\` f(x,n) = sqrt(x/n) - cos(x) \`
{: .kdmath}
```

**Comment by gettalong** [comment]
I'm sorry but math expressions in kramdown are delimited by `$$` and nothing else. It isn't really useful to provide alternate ways to specify math expressions.

Additionally, the backtick is already used for code spans, so this would confuse users.
