### ISSUE TITLE
Kramdown treats valid HTML as invalid and converts to entities.

### ISSUE THREAD

**Issue by envygeeks** [gettalong/kramdown#475]
When a document with raw HTML uses valid HTML syntax that doesn't include quotes of any kind, Kramdown treats it as invalid HTML and converts it to entities and rewraps it, resulting in raw HTML being displayed upon conversion.

Works:

```ruby
html = "<p class='hello'>world</p>"
Kramdown::Document.new(html).to_html
# => "<p class=\"hello\">world</p>\n"
```

Doesn't Work:

```ruby
html = "<p class=hello>world</p>"
Kramdown::Document.new(html).to_html
# => "<p>&lt;p class=hello&gt;world&lt;/p&gt;</p>\n"
```

**Comment by gettalong** [comment]
It is stated in the [syntax documentation](https://kramdown.gettalong.org/syntax.html#html-blocks) that kramdown only supports correct XHTML, with a few common exceptions. I really don't want to implement a fully compliant HTML parser given all the allowed variances...

So, no bug but a documented implementation choice.
