### ISSUE TITLE
`{:toc}` doesn't strip links from headlines

### ISSUE THREAD

**Issue by janpio** [gettalong/kramdown#478]
I am using `kramdown` 1.13.2 via `github pages` (163) in Jekyll. I use `{:toc}` to create a table of contents at the start of a long page.

I noticed a problem:

A markdown headline like

```
## [Install](install.md)
```

will get converted into the ToC as this:

```
<li><a href="#install" id="markdown-toc-install"></a><a href="/install">Install</a></li>
```

This means the actual ToC entry is not clickable to go to the internal headline anchor, but the external link gets triggered when you click the headline text. The ToC is not usable.

Is this a bug?
Or even expected behavior?
Did this get fixed in one of the newer releases?

**Comment by gettalong** [comment]
You will find your information at https://kramdown.gettalong.org/news.html.

**Comment by janpio** [comment]
Thanks.

Found it here: https://kramdown.gettalong.org/news.html#kramdown-1150-released

Created an issue with Github Pages to update kramdown so Github Pages gets this fix (and others):
https://github.com/github/pages-gem/issues/505
