### ISSUE TITLE
figure element

### ISSUE THREAD

**Issue by iNerdier** [gettalong/kramdown#48]
I’ve been trying to write lately with kramdown's markdown parser and I’ve come across two problems that seem to unsolvable in the current release.

One is that there seems to be no way to stop kramdown from wrapping image links in <p> tags. This is often fine but when paired with something like

``` css
p + p {
    text-indent: 1em;
}
```

the results are less than happy, images inherit unwanted text stylings and go all over the shop.

Markdown is smart enough not to add tags to existing block level elements, could the same method be used to allow specifying of stand-alone images?

If this is unfeasible or undesirable, could it be possible to allow it via an option ( say :image_block => true )

The second problem is attempting to use html5's new <figure> and <figcaption> elements. According to [can I use it](http://caniuse.com/#feat=html5semantic) all major browsers now support them and they’re certainly a great help in writing articles with images that need citations or have direct references to text.

Looking through google to see if anyone has attempted it I found https://github.com/michelf/php-markdown/wiki/HTML5-update which seems to have a pretty useful starting point for working out a syntax to use them.

Would either of these problems be something we might be able to do something about?

**Comment by 9peppe** [comment]
I'm probably late to this, but I like *a lot* how Pandoc handles this: if an image is in a paragraph on its own, it becomes a figure, and its alt-text is used as caption.

**Comment by RoyiAvital** [comment]
Any chance having syntax for Figure?

Something like using the `alt-text` as caption as suggested by @9peppe ?

Thank You.

**Comment by gettalong** [comment]
I can imagine providing a new option for changing the behaviour of how paragraphs with only an image are converted, similar to how the LaTeX converter currently does it - see https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/latex.rb#L71

@9peppe / @RoyiAvital What should the output for the following kramdown fragment should be if the option to convert standalone images is activated?

~~~ markdown
This is a para with an ![image](some.jpg).

![standalone image](some.jpg)
~~~

Note that the alternative text of the image *cannot* contain markup, it is just text.

**Comment by 9peppe** [comment]
I'd say

    <p>This is a para with an <img alt="image" src="some.jpg" /></p>

    <figure id="someid">
      <img alt="standalone image" src="some.jpg" />
      <figcaption>standalone image</figcaption>
    </figure>

**Comment by RoyiAvital** [comment]
3 Remarks (Though I'm not sure possible).

 1. Could we have a flag of some kind to whether use Figure or regular Image element?  
     Maybe something like `![standalone image figure="true"](some.jpg)`.
 2. Currently `kramdown` allows adding HTML using `![standalone image](some.jpg){:class="center-img"}`. It should be kept.
 3. In Pandoc they created reference system using `\tag`. Is there an option doing so here as well?

**Comment by gettalong** [comment]
@9peppe If the image had an ID assigned, should it then be on the `figure` tag or on the `img` tag?

@RoyiAvital 

ad 1) No. If the new option to process a paragraph with a single item being an image is activated, the output is changed. The only way this would be doable would be via the option value itself.

ad 2) The parser is not touched, only the output is changed.

ad 3) I don't know what you mean. If you set an id on the image, you can use that id later.

**Comment by 9peppe** [comment]
I don't know. It think it will depend on individual use cases. But if we apply it to `figure`, then we can use css selectors like `#id img`.

**Comment by gettalong** [comment]
That's what I was thinking, i.e. class and id attributes are transferred to the `figure` tag, all others stay with the image.

**Comment by RoyiAvital** [comment]
@gettalong ,
First thank you for the answer and the openness.
Could you explain:
> ad 1) No. If the new option to process a paragraph with a single item being an image is activated, the output is changed. The only way this would be doable would be via the option value itself.

Thank You.

**Comment by gettalong** [comment]
@RoyiAvital I'm against changing the kramdown parser. Therefore the way to specify *how* a paragraph with only an image should be rendered is via the new option that changes how the converter works. E.g. if the option's value is "figure", then a figure tag is rendered, if it is "image" than just the image without enclosing paragraph tags is rendered.

**Comment by RoyiAvital** [comment]
I see.
How could one which uses GitHub Pages could control this?

**Comment by gettalong** [comment]
I don't really know Github Pages nor use it, but since it is based on Jekyll I guess it provides the ability to define kramdown options and through this facility one could also set the new option.

**Comment by mb21** [comment]
In pandoc, when its [implicit figure extension is enabled](extension-implicit_figures), you can append a newline to mark individual images as non-figures.

About where to put the class and id, there's an [issue open about that](https://github.com/jgm/pandoc/issues/3928).

**Comment by gettalong** [comment]
So, to sum up:

~~~
![standalone image](some.jpg){:#id .class}
~~~

will be rendered into

~~~ html
<figure id="id" class="class">
  <img alt="standalone image" src="some.jpg" />
  <figcaption>standalone image</figcaption>
</figure>
~~~

iff the new option 'standalone_image' is true. If it is not (the default value for the option), then the current behaviour doesn't change.

@9peppe @RoyiAvital Any comments?

**Comment by RoyiAvital** [comment]
@gettalong ,
It looks great!

2 edge cases I thought about
What happens when:

```
![standalone image](some.jpg)
```

Could we have:
```
<figure>
  <img alt="standalone image" src="some.jpg" />
  <figcaption>standalone image</figcaption>
</figure>
```

Or even farther, for:
```
![standalone image](some.jpg){:#id}
```

Having:

```
<figure id="id">
  <img alt="standalone image" src="some.jpg" />
  <figcaption>standalone image</figcaption>
</figure>
```

**Comment by RoyiAvital** [comment]
@gettalong ,
Any update on that?

**Comment by gettalong** [comment]
I'm rather busy right now, so this change together with a new release will probably be in August.

**Comment by gettalong** [comment]
@RoyiAvital I have implemented this now with a slight change of functionality: If you want to have a standalone image, use the special `standalone` IAL reference on the image, ie.

~~~
![standalone image](some.jpg){:standalone}
~~~

**Comment by Faegy** [comment]
@gettalong Any commit to reference in order to track this feature's availability?

**Comment by AvverbioPronome** [comment]
>  use the special `standalone` IAL reference on the image, ie.

I don't understand this. Why are we introducing a behavior not seen in any markdown parser? (a big part of my initial request had to do with using the same source with multiple parsers, even if I did not make that clear)

**Comment by gettalong** [comment]
To make it possible to have both worlds. This new functionality is backwards compatible, so no problem. And if you use another library that supports kramdown, it will also just work, using the default output of that library.

**Comment by gettalong** [comment]
Actually, `<img />` is an inline *and* a block tag. So in Markdown one has to choose and in case of kramdown, `<img />` is treated as an inline tag. This means that internally an image is always wrapped inside a paragraph.

Now, with these changes one can choose how a standalone image is shown: either as a paragraph with an image (default) or as a figure element. This has nothing to do with a doctype.

**Comment by gettalong** [comment]
The doctype is not known by kramdown. It just outputs valid HTML. With the current implementation, the user can choose how to display standalone images regardless of the doctype, on a case-by-case basis.

**Comment by mb21** [comment]
So either you use the global `standalone_image` option, or you can use `{:standalone}` on a image by image basis, correct? If so, that seems sensible to me (although I would be mostly interested in the global option).

**Comment by gettalong** [comment]
There is no global `standalone_image` option, currently. As I mentioned before I decided to go with the IAL reference. If a global option is still needed, this would have to wait for another release.

**Comment by pmpinto** [comment]
> @RoyiAvital I have implemented this now with a slight change of functionality: If you want to have a standalone image, use the special `standalone` IAL reference on the image, ie.
> 
> ```
> ![standalone image](some.jpg){:standalone}
> ```

@gettalong Was this ever released?
I'm on v1.14 and I'm still seeing the `img` inside a `p` with the following:
```markdown
![placeholder image](https://via.placeholder.com/1920x1080){:standalone}
```

**Comment by gettalong** [comment]
@pmpinto See https://kramdown.gettalong.org/converter/html.html#standalone-images and the [release notes for 2.0.0](https://kramdown.gettalong.org/news.html#kramdown-200-released)

**Comment by pmpinto** [comment]
> @pmpinto See https://kramdown.gettalong.org/converter/html.html#standalone-images and the [release notes for 2.0.0](https://kramdown.gettalong.org/news.html#kramdown-200-released)

For some reason I was on Jekyll 3.8.6.
4.0.0 comes with kramdown 2.1.0 already.
Thanks!

**Comment by RoyiAvital** [comment]
@pmpinto , I think you can also do something similar [using the `include` trick in Jekyll](https://jekyllrb.com/docs/includes).

This is a temporary solution.

For instance, GitHub Pages still uses Jekyll 3.85 and kramdown `1.17`.

**Comment by codingthat** [comment]
A more flexible solution would be better, in my opinion.  When `alt` and `caption` are equal, this means people who actually need the accessibility feature of `alt` have to pay the penalty of sifting through (or hear, as the case may be) the exact same text twice.  As far as I'm aware, `alt` should describe the picture in detail for those who cannot see it, whereas a caption is more of an additional commentary for everyone, whether they can see it or not—for example, it might cite the source the image was borrowed from.

**Comment by AvverbioPronome** [comment]
> When `alt` and `figcaption` are equal, this means people who actually need the accessibility feature of `alt` have to pay the penalty of sifting through (or hear, as the case may be) the exact same text twice.

True, but flexibility is not the point of markdown, human-readability is.

I guess the way to address your concern would be to just leave `alt` empty when `figcaption` is identical. (nb: 'empty' doesn't mean "remove the attribute," that would make invalid html).

For flexibility, there's always raw html :/

**Comment by codingthat** [comment]
Well...sort of.  It addresses the double-content issue.  But actually both sets of content have different purposes, and this is would simply eliminate the possibility of people who can't see the graphic (whether due to vision issues or a poor Internet connection) from understanding what it shows.  (And if you include such descriptions in captions, well, that becomes its own double-content issue.  A picture's worth a thousand words sometimes, and people who _can_ see the image won't want those specific thousand words.)

Indeed, we currently use raw HTML in this case, which certainly makes it less readable.  I wonder if there could be a special attribute in this case, to allow for separate setting of `alt` and `figcaption` that still leaves it useful for the consumers of the rendered result, while maintaining Kramdown's additional human-readability.

**Comment by AvverbioPronome** [comment]
Also realize that `alt` is not `longdesc` (that's not implemented in any browser at all)

**Comment by mrshannonyoung** [comment]
> Well...sort of. It addresses the double-content issue. But actually both sets of content have different purposes, and this is would simply eliminate the possibility of people who can't see the graphic (whether due to vision issues or a poor Internet connection) from understanding what it shows. (And if you include such descriptions in captions, well, that becomes its own double-content issue. A picture's worth a thousand words sometimes, and people who _can_ see the image won't want those specific thousand words.)
> 
> Indeed, we currently use raw HTML in this case, which certainly makes it less readable. I wonder if there could be a special attribute in this case, to allow for separate setting of `alt` and `figcaption` that still leaves it useful for the consumers of the rendered result, while maintaining Kramdown's additional human-readability.

This is the way forward. There does need to be a clear distinction between the alternate text for the image and figcaption if they are different.
