### ISSUE TITLE
Unique IDs for footnotes with the same names

### ISSUE THREAD

**Issue by pjpoole** [gettalong/kramdown#483]
This author highlighted a problem I am currently having: https://github.com/gettalong/kramdown/issues/56

His answer was different than mine. I prefer to use numbers, and even if I do use custom footnote names, I don't trust myself to never re-use a single name for multiple footnotes that may show up in the same view.

It looks like one solution would be to keep track of a global context and manually advance the starting footnote number as I render posts in a blog index page, but I don't see a way to query a Kramdown document to ask how many footnotes it sees. (i.e., something like:

```ruby
total_footnotes = 0

documents.each do |document|
  rendered = Kramdown::Document.new(document, { footnote_nr: total_footnotes + 1 })
  total_footnotes += renderered.footnote_count
end
```

but an easier solution would be the option to add in some sort of nonce into each footnote reference so that the ids would be like `fn:1-adf123`.

**Comment by pjpoole** [comment]
A third option I can think of is to offer a switch for removing footnotes completely. It looks like someone already did this [using hand-rolled nokogiri][nokogiri] to remove footnotes from excerpted posts, which is similar to what I'm trying to do.

[nokogiri]: http://penguindreams.org/blog/removing-footnotes-from-excerpts-in-jekyll/

**Comment by gettalong** [comment]
Thank you for pointing out this problem!

I can imagine a solution similar to what is done with the [`auto_id_prefix` option](https://kramdown.gettalong.org/options.html#option-auto-id-prefix), i.e. a new option called `footnote_prefix` that gets used on conversion. Would this solve your problem?

**Comment by pjpoole** [comment]
It certainly would!

**Comment by gettalong** [comment]
@pjpoole This will be implemented for the next release.

**Comment by gettalong** [comment]
@pjpoole This will be in the release coming out today. I.e. there is a new option `footnote_prefix` that allows you to avoid duplicate IDs.

Additionally, I have added the footnote count of the document to the options of the root element.

Together with the option `footnote_nr` it is now possible to output multiple documents together with consecutively number footnotes and unique IDs:

~~~ ruby
require 'kramdown/document'
total_footnotes = 0
documents = [
  "footnote[^a][^a]\n\n[^a]: My note\n[^b]: another (ignored) note",
  "footnote[^a][^a]\n\n[^a]: My note\n[^b]: another (ignored) note",
  "footnote[^a][^a]\n\n[^a]: My note\n[^b]: another (ignored) note",
]

documents.each do |document|
  document = Kramdown::Document.new(document, {footnote_nr: total_footnotes + 1, footnote_prefix: total_footnotes + 1})
  puts document.to_html
  total_footnotes += document.root.options[:footnote_count]
end
~~~

results in:

~~~ html
<p>footnote<sup id="fnref:1a"><a href="#fn:1a" class="footnote">1</a></sup><sup id="fnref:1a:1"><a href="#fn:1a" class="footnote">1</a></sup></p>

<div class="footnotes">
  <ol>
    <li id="fn:1a">
      <p>My note <a href="#fnref:1a" class="reversefootnote">&#8617;</a> <a href="#fnref:1a:1" class="reversefootnote">&#8617;<sup>2</sup></a></p>
    </li>
  </ol>
</div>
<p>footnote<sup id="fnref:2a"><a href="#fn:2a" class="footnote">2</a></sup><sup id="fnref:2a:1"><a href="#fn:2a" class="footnote">2</a></sup></p>

<div class="footnotes">
  <ol start="2">
    <li id="fn:2a">
      <p>My note <a href="#fnref:2a" class="reversefootnote">&#8617;</a> <a href="#fnref:2a:1" class="reversefootnote">&#8617;<sup>2</sup></a></p>
    </li>
  </ol>
</div>
<p>footnote<sup id="fnref:3a"><a href="#fn:3a" class="footnote">3</a></sup><sup id="fnref:3a:1"><a href="#fn:3a" class="footnote">3</a></sup></p>

<div class="footnotes">
  <ol start="3">
    <li id="fn:3a">
      <p>My note <a href="#fnref:3a" class="reversefootnote">&#8617;</a> <a href="#fnref:3a:1" class="reversefootnote">&#8617;<sup>2</sup></a></p>
    </li>
  </ol>
</div>
~~~
