### ISSUE TITLE
Underscores being removed from URL

### ISSUE THREAD

**Issue by 8vius** [gettalong/kramdown#488]
I use markdown on some emails that are sent out of my system, when these have any text between underscores it's being processed as well into `<em>` is there any way to selectively ignore processing of underscores or a way around this?

**Comment by gettalong** [comment]
Can you provide some sample input, current output and output that you want?

**Comment by gettalong** [comment]
@8vius I will close this issue since I didn't get an answer and reopen it once there is something to do.
