### ISSUE TITLE
Enable/disable specific markdown feature

### ISSUE THREAD

**Issue by schneems** [gettalong/kramdown#494]
First of, thanks for this library. It's great!

I'm curious if it's possible to disable a specific markdown feature. I want to disable markdown turning lines that start with spaces into a code block

My use case is this: I have a library that lets you write Rails emails in markdown https://github.com/schneems/maildown/

It works great, except for it requires all of your loops to be un-indented, otherwise it assumes the beginning spaces mean it should be interpreted as a code block. So you end up with code that looks like this:

```erb
<% if @write_docs.present? %>
## Write Docs

<% @write_docs.sort_by {|d| d.repo.full_name }.each do |doc| %>
**<%= doc.repo.full_name %>** ([source](<%= doc.to_github %>)): [<%= doc.path %>](<%= doc_method_url doc %>)

<% end %>
<% end %>
```

I added an experimental option to remove all leading whitespace. Unfortunately it's too broad of a hammer, and doesn't work for when I actually want to use a code block (via github style backticks) to show code. 

I'm curious if you've got any ideas or if I could turn off the "indent to make code blocks" feature all together. Any help or ideas are appreciated.

**Comment by gettalong** [comment]
The standard way to approach this is to subclass the kramdown parser and adjust the used block parsing methods. See for example https://github.com/gettalong/kramdown/blob/master/lib/kramdown/parser/markdown.rb#L32 where the `@span_parsers` and `@block_parsers` are changed to remove features not found in plain Markdown.

**Comment by gettalong** [comment]
@schneems Did my comment help you? Or do you need more information/help?

**Comment by schneems** [comment]
I haven’t had the chance to dig deeper. Got sidetracked in my paternity leave. Thanks, I think this is what I’m looking for though.
