### ISSUE TITLE
Javascript parser doesn't handle certain regex flags correctly

### ISSUE THREAD

**Issue by bradarv90** [gettalong/kramdown#496]
I'm assuming that this is the correct repo to report this to. I'm using Jekyll for my blog and from what I can tell, it uses this repo to do the markdown to HTML conversion. 

I found that my javascript code blocks that use the flags `gim` get highlighted properly, but using the `u` flag doesn't get highlighted. I'm assuming the parser just isn't updated for the new flags that were introduced in ES6. I've attached two pictures to show you what I'm seeing. 

![correctflags](https://user-images.githubusercontent.com/1361788/36567349-1a46df74-17f4-11e8-940b-c5bda3901c7e.png)

![incorrectflag](https://user-images.githubusercontent.com/1361788/36567358-22df1d36-17f4-11e8-9a97-c34837788144.png)

Note in the images above that the whole expression `/a.a/gim` is the same color, while in the second example the `u` is not the same color as the rest of the expression. 

If you can point me to where I should be checking, I can attempt to fix this, but I have no idea what I should be looking to fix this.

**Comment by gettalong** [comment]
Highlighting is not done by kramdown itself but by other tools used by kramdown, for example coderay or rouge ([see the sidebar](https://kramdown.gettalong.org/documentation.html)). So you will have to ask at the issue tracker of the highlighting library this question.
