### ISSUE TITLE
How to prevent Kramdown from removing &nbsp;?

### ISSUE THREAD

**Issue by bfontaine** [gettalong/kramdown#504]
Hello,

I use Kramdown for my Jekyll blog, and I’m trying to find a way to disable the removal of special spaces such as `&nbsp;` and `&thinsp;`. I write in French and non-breaking spaces are a lot more used in this language than in English.

```ruby
# Expected
Kramdown::Document.new("hi&nbsp;here").to_html # "<p>hi&nbsp;here</p>\n"
# Actual
Kramdown::Document.new("hi&nbsp;here").to_html # "<p>hi here</p>\n"
```

I’ve read the docs and dug in the code but I can’t find any option to disable this behavior.

~~Is using `\u00a0` or `\u202F` the only way to go?~~
Update: unfortunately using `\u00a0` in a file doesn’t work because when read it becomes `\\u00a0`. I tried using `&#x00a0;` but it gets stripped just like `&nbsp;`.

Thanks.

**Comment by bfontaine** [comment]
It seems that it does preserve those spaces; but using the true character and not the HTML entity. Sorry for the disturbance.

**Comment by gettalong** [comment]
@bfontaine No problem, you can change how you want to output entities by setting the option [entity_output](https://kramdown.gettalong.org/options.html#option-entity-output).
