### ISSUE TITLE
Performance issue when rendering a lot of space

### ISSUE THREAD

**Issue by krasnoukhov** [gettalong/kramdown#505]
Here's a pretty comprehensive example:

```ruby
note = "1"+" "*20000+"2"
Benchmark.measure { Kramdown::Document.new(note) }.real
```

This takes around 3 seconds on my machine. A DOS vulnerability potentially?

**Comment by gettalong** [comment]
Thanks for reporting and the test. The culprit is the setext header parser, will have to investigate a bit more why its regexp is slow.

**Comment by gettalong** [comment]
The problem exists not only for the setext header parser but at least also for the atx header parser, i.e. these two regexp have bad behaviour when used on very long lines:

~~~ ruby
SETEXT_HEADER_START = /^(#{OPT_SPACE}[^ \t].*?)#{HEADER_ID}[ \t]*?\n(-|=)+\s*?\n/
ATX_HEADER_MATCH = /^(\#{1,6})(.+?(?:\\#)?)\s*?#*#{HEADER_ID}\s*?\n/
~~~

I have tried a few things but haven't yet come up with a viable solution.

**Comment by gettalong** [comment]
When removing everything after the first occurence of `\n` in each regexp, they get fast. So I guess that the regexp has to backtrack much more because of them. However, I haven't come across a solution yet.

**Comment by glebm** [comment]
Some of the instances of `*?` look unnecessary, e.g. `\s*?\n` can be replaced with `[ \t\r\f\v]*\n`. https://ruby-doc.org/core-2.5.1/Regexp.html#class-Regexp-label-Character+Classes

**Comment by gettalong** [comment]
Thanks but I have already tried that. And also changing lazy to possessive quantifiers or vice versa. Didn't find a combination that was fast and didn't break the tests...

**Comment by glebm** [comment]
I've managed to reduce the time by 50% with this but of course it doesn't solve the issue:

```ruby
HEADER_ID = /[ \t]*?(?:[ \t]{#([A-Za-z][\w:-]*)})?/
SETEXT_HEADER_START = /^#{OPT_SPACE}(.*?)(?<=[^ \t])#{HEADER_ID}[ \t]*\n([-=])[-=]*[ \t\r\f\v]*\n/
ATX_HEADER_MATCH = /^(\#{1,6})(.+?(?:\\#)?)\s*?#*#{HEADER_ID}[ \t\r\f\v]*\n/
```

The command I used for measuring:

```bash
ruby -e "$:.unshift('lib'); require 'kramdown'; require 'benchmark'; puts Benchmark.measure { Kramdown::Document.new('1'+' '*20000+'2') }.real.round(3)"
```

By the way, `ATX_HEADER_MATCH` is OK as is, only `SETEXT_HEADER_START` is problematic.

Since solving it with a single regex appears impossible, we could match only the `===` line (`/^([-=])[-=]*[ \t\r\f\v]*$/`) and then check the previous line within `parse_setext_header`.
