### ISSUE TITLE
Differentiate between indented and fenced code block in the AST

### ISSUE THREAD

**Issue by mojavelinux** [gettalong/kramdown#507]
It would be helpful when converting to other output formats if the parser added information to the AST to differentiate between an indented codeblock and a fenced codeblock. The use of these two forms often imply a different meaning (esp when both occur in the same document). At the moment, these two block types are indistinguishable in the AST.

I'm proposing a hint such as `fenced: true` in the options map for the parsed element (in the parse_codeblock_fenced method)

I'd be happy to provide a PR if this idea receives approval.

**Comment by gettalong** [comment]
Thanks for this proposal - I'm okay with adding such a hint. And would gladly accept a PR :smile: :+1:

**Comment by mojavelinux** [comment]
Fantastic! Thanks Thomas.
