### ISSUE TITLE
Is there a way to use LaTeX packages on Kramdown GitHub pages?

### ISSUE THREAD

**Issue by Purpzie** [gettalong/kramdown#511]
Hi! I apologize if I should ask somewhere else, but I just wanted to check if Kramdown already supports this first.

I'm running a site using GitHub pages, Jekyll,  and of course Kramdown (along with the [hpstr](https://github.com/mmistakes/hpstr-jekyll-theme) theme). Hpstr comes with a handy [scripts.html](https://github.com/madisonfrede/madisonfrede.github.io/blob/master/_includes/scripts.html#L2) in *_includes*, which is then used in every layout. I've already added the required [script](https://jekyllrb.com/docs/extras/#math-support) for normal latex to work, and have confirmed that it is indeed functioning correctly.

Recently I discovered that there are extra packages that can improve latex functionality. For example, [tikz](https://www.sharelatex.com/learn/TikZ_package) allows you to create geometric figures. However, these packages must be specified using `\usepackage` in the preamble of a latex document, and Kramdown doesn't allow you to use a preamble (unless I am mistaken).

If it is supported, could you help me out? If not, I'll go ask this on a more latex-centered forum or repo.

**Comment by gettalong** [comment]
If you need this functionality, you should use a [custom LaTeX template](https://kramdown.gettalong.org/converter/latex.html#option-template). With the template you can define anything you need. Have a look at the [default template](https://github.com/gettalong/kramdown/blob/master/data/kramdown/document.latex) to see how it is done.
