### ISSUE TITLE
Parser crashes if empty tag is found in table cell when html_to_native option is enabled

### ISSUE THREAD

**Issue by mojavelinux** [gettalong/kramdown#514]
If the html_to_native option is enabled, and an empty tag is found in a table cell, the parser crashes because the value of the node is nil.

Here's a test case:

```
| abc    | def |
| ------ | --- |
| a<br>b | c   |
```

The error occurs in Table#parse_table

```rb
while (c = root.children.shift)
  lines = c.value.split(/\n/)
  ...
end
```

A simple nil check will fix the problem. I also recommend using a string instead of a regexp to split.

I'd be happy to submit a PR to correct this problem.

**Comment by mojavelinux** [comment]
PR available. See #515.

**Comment by gettalong** [comment]
Thank you for the bug report and fix!

**Comment by mojavelinux** [comment]
I'm glad to help! Thanks for reviewing and merging, @gettalong!

**Comment by mojavelinux** [comment]
@gettalong would you be willing to do a patch release that includes this fix? I'm processing a large number of Markdown documents and this bug is being triggered, which is preventing the conversion from running to completion. Thanks!

**Comment by gettalong** [comment]
I'm in the process of going through all commits and issues/pull request since the last release - release will be today or in the next few days.

**Comment by mojavelinux** [comment]
Thanks @gettalong! I really appreciate it.
