### ISSUE TITLE
Make collected link refs available to converters

### ISSUE THREAD

**Issue by mojavelinux** [gettalong/kramdown#516]
When converting back to a lightweight markup syntax (such as Markdown to Markdown) it would be helpful if the link defs found by the parser were made available to the converter (either via the AST or converter options). This would allow references to be restored. Currently, this information is dropped once parsing is complete and all signs of these link refs vanish from the parsed tree.

I'd be happy to work on a proposed change if this idea is accepted.

**Comment by gettalong** [comment]
Thanks for the proposal!

Some thoughts:

* How would you want to store the link ID? In normalized form?

* There can be multiple different link IDs for one normalized link ID - how would you handle this case?

* What would be the advantage of storing this information in the options? I think it would better go into the root node of the AST.

**Comment by gettalong** [comment]
> > How would you want to store the link ID? In normalized form?
>
> I'd probably go with the same form that is used to pass links to the :link_defs option. That way, it's consistent and expected.

Okay, so the normalized form than since the link IDs passed via the `:link_defs` option get normalized.

> > There can be multiple different link IDs for one normalized link ID - how would you handle this case?
>
> Personally, I'm only interested in the last one that wins. But I understand that others might want to have all of them. If we go down that path, then I would assume each ID would be mapped to an array.

Since we will use the normalized link ID, this won't be a problem.

> > What would be the advantage of storing this information in the options? I think it would better go into the root node of the AST.
>
> That works for me!

Great! Then the root node of the AST it is.

**Comment by mojavelinux** [comment]
I'll proceed with preparing a PR as soon as I get a chance.

**Comment by gettalong** [comment]
@mojavelinux Did you by change prepare a PR for this? Is this still of interest to you?

**Comment by gettalong** [comment]
I'm closing this issue since there doesn't seem to be interest in this functionality.

**Comment by mojavelinux** [comment]
Unfortunately, this is just not something I have time to focus on now or in the near future. I'm certain it would still be useful, otherwise I wouldn't have taken the time to file the issue. But I cannot pursue it.
