### ISSUE TITLE
Certain characters not lowercased by auto_ids on Windows

### ISSUE THREAD

**Issue by arthurattwell** [gettalong/kramdown#517]
On Windows, the letter É is not lowercased in automatic header ID generation.

For example, on OSX and Ubuntu, this heading:

```
# Équilibre
```

correctly generates as

```
<h1 id="équilibre">Équilibre</h1>
```

but on Windows 10 using Ruby 2.3.3 I get

```
<h1 id="Équilibre">Équilibre</h1>
```

I'm not able to test newer versions of Ruby on Windows at the moment, but I will when I can in case that's an issue.

**Comment by gettalong** [comment]
Have you tested on OS X and Ubuntu with the same Ruby version? There was a [change](https://bugs.ruby-lang.org/issues/10085) in Ruby 2.4 that makes `#downcase` Unicode aware.

**Comment by arthurattwell** [comment]
@gettalong Sorry for the delay. I've now tested this on several Ruby versions on Ubuntu and Windows 10. You're quite right, thanks: Ruby 2.4 fixes this.

**Comment by gettalong** [comment]
@arthurattwell No problem and thanks for getting back!
