### ISSUE TITLE
Add support for the backslash variant of a hard line break to GFM input

### ISSUE THREAD

**Issue by mojavelinux** [gettalong/kramdown#519]
GFM (as well as CommonMark) allow a hard line break to be defined using a single trailing backslash.

```
foo\
bar
```

This should produce:

```
[<kd:text "foo">, <kd:br>, <kd:text "\nbar">]
```

(See https://spec.commonmark.org/0.28/#hard-line-breaks)

I also think the parser should remove the newline from the start of the second line of text.

---

It's also interesting to note that GFM no longer interprets hard line breaks (hard_wrap) by default. It's easy enough to set this option to false, but it might be appropriate to reconsider it as the default option.

**Comment by gettalong** [comment]
Thanks - pull requests are welcome!

**Comment by mojavelinux** [comment]
Thanks for reviewing, @gettalong. Pull request sent!

**Comment by mojavelinux** [comment]
The good news is that this is a very low impact change. The backslash hard line break is only supported for GFM (which is true, since it's not in strict markdown) and it is only enabled when hard wrap is off.

**Comment by gettalong** [comment]
Thanks for your contribution!

**Comment by gettalong** [comment]
As for changing the default value of the hard_wrap option: I'm not sure whether this is a good idea since it may impact many people who depend on the current behaviour.

**Comment by mojavelinux** [comment]
You're welcome!

As for the hard_wrap option, I agree that could be a big change. Perhaps the right thing to do would be to note in the documentation / website that GFM with hard_wrap: false is technically the most true to GFM.

(The reason for the recommendation has to do with the fact that GFM is now based on CommonMark, so GFM isn't the same as it used to be).
