### ISSUE TITLE
setup.rb claims to be GPL licensed

### ISSUE THREAD

**Issue by iragsdale** [gettalong/kramdown#521]
I see that Kramdown was converted to be MIT licensed some time back, but the file setup.rb claims to be GPL licensed, which I think would require the entire project to be available under the terms of the GPL. Is this an oversight or intentional?

**Comment by gettalong** [comment]
The `setup.rb` file is LGPL licensed, so as far as I know it should be okay.

**Comment by iragsdale** [comment]
You are correct, sorry about that! It was flagged by our legal team and wanted to make sure you were aware. My apologies. :)
