### ISSUE TITLE
newline in fenced code block disappeared

### ISSUE THREAD

**Issue by siahuat0727** [gettalong/kramdown#524]
Hi, I'm new to github page, web and kramdown.

May I ask why the newline in the fenced code blocks after "// pruning" disappeared on github page ?

![image](https://user-images.githubusercontent.com/17688111/41605997-48b077d0-7415-11e8-9e48-1d1ea07fc4c1.png)

However, it works fine at my localhost (execute `bundle exec jekyll serve --watch`) and [open with github](https://github.com/siahuat0727/siahuat0727.github.io/blob/master/_posts/2018-06-19-sudoku.markdown) 

![image](https://user-images.githubusercontent.com/17688111/41606627-b28e50ea-7416-11e8-9854-9ec1432e417f.png)

![image](https://user-images.githubusercontent.com/17688111/41606783-124af9ca-7417-11e8-953b-fe08afd94de8.png)

Or where should I ask this question? I have no idea why

**Comment by gettalong** [comment]
I think you should better ask someone from Jekyll or Github pages for this, so I will close this for now.

However, if this is related to kramdown, please provide a sample source document, the output when running the kramdown binary with this sample document and your expected output. Then I can re-open the issue if this is really something kramdown related.
