### ISSUE TITLE
Can you please explain ![alt](<(src)>) syntax?

### ISSUE THREAD

**Issue by Convincible** [gettalong/kramdown#525]
Hi,

I have been delighting myself by combing through [the kramdown converter source](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/kramdown.rb) to understand it for the purpose of overriding in a custom converter. (Specifically, HTML to Kramdown – not the other way around!)

An interesting behaviour seems to be that if links or images in HTML have their `href` or `src` set to include brackets, e.g. `href="(foo)"` then the converter will treat it differently. Specifically:
* For links, it will treat `foo` as a reference link
* For images, it will spit out the kramdown: `![alt](<src>)` i.e. wrap the src in angle brackets

I can see no reference to what wrapping an image source in angle brackets does, in terms of Kramdown syntax. Can someone enlighten me as to what this means, and why this behaviour is used?

Thanks!

**Comment by gettalong** [comment]
See the syntax for [inline links](https://kramdown.gettalong.org/syntax.html#inline-links) - the image syntax is just an extension for the link syntax.

Basically, wrapping the URL in angle brackets avoids problems with invalidly nested parentheses.

**Comment by Convincible** [comment]
Thanks! I didn't spot this line in the docs:

> The link URL has to contain properly nested parentheses if no title is specified, or the link URL must be contained in angle brackets (incorrectly nested parentheses are allowed).

Could you just further clarify what this means?

Why is it the behaviour that any link containing parentheses is treated as a reference? ie. `<a href="/he)llo">` gets converted by `.to_kramdown` as `[title][/he)llo]` not `[title](/he\)llo)` or even `[title](</he)llo>)`?
