### ISSUE TITLE
add support for tabbed code blocks

### ISSUE THREAD

**Issue by tombradford** [gettalong/kramdown#527]
it would be nice to have support for [tabbed code blocks](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#tabbed-fences).

Currently, a sample markdown snippet throws a MD022 error:
```
```no-highlight tab="tabA"
#!/bin/bash
...
```

MD022 Headers should be surrounded by blank lines

**Comment by gettalong** [comment]
First, codeblocks are started with `~~~`, not with ` ``` `. The latter is only valid for the GFM parser.

If you need such a functionality, you need to write a custom syntax highlighter. Then this syntax highlighter could extract some information from the language spec provided on the codeblock starting line, probably some added `?tab=tabA` part, and then use another syntax highlighter to do the actual work.

So it could look something like this:

~~~~~~
~~~ no-highlight?tab=tabA
#!/bin/bash
~~~
~~~~~~~

You reference something called an "MD022 error", i don't know what it means.

I will close this issue and move it to the feature requests project. However, feel free to comment on this issue further.
