### ISSUE TITLE
Incorrect handling of info string in GFM

### ISSUE THREAD

**Issue by gvwilson** [gettalong/kramdown#530]
According to the spec for [GitHub Flavored Markdown](https://github.github.com/gfm/#info-string):

> The line with the opening code fence may optionally contain some text following the code fence; this is trimmed of leading and trailing whitespace and called the info string... The first word of the info string is typically used to specify the language of the code sample, and rendered in the class attribute of the code tag. However, this spec does not mandate any particular treatment of the info string.

If I used this script:

```ruby
require "kramdown"
require "json"

markdown = STDIN.read()
doc = Kramdown::Document.new(markdown, :input=>'GFM')
tree = doc.to_hash_a_s_t
puts JSON.pretty_generate(tree)
```

to process this input:

~~~
```python
code
```
~~~

I get the correct AST:

```
{
  "type": "root",
  "options": {
    "encoding": "UTF-8",
    "location": 1,
    "options": {
    },
    "abbrev_defs": {
    },
    "abbrev_attr": {
    }
  },
  "children": [
    {
      "type": "codeblock",
      "attr": {
        "class": "language-python"
      },
      "value": "code\n",
      "options": {
        "location": 1,
        "lang": "python"
      }
    }
  ]
}
```

However, if I add anything after the language identifier in the info block:

~~~
```python this=that
code
```
~~~

the code block is incorrectly identified:

```
{
  "type": "root",
  "options": {
    "encoding": "UTF-8",
    "location": 1,
    "options": {
    },
    "abbrev_defs": {
    },
    "abbrev_attr": {
    }
  },
  "children": [
    {
      "type": "p",
      "options": {
        "location": 1
      },
      "children": [
        {
          "type": "codespan",
          "value": "python this=that\ncode\n",
          "options": {
            "location": 1
          }
        }
      ]
    }
  ]
}
```

The second AST should be structured just like the first; the extra `this=that` should either be an extra element in the AST or ignored.

**Comment by gettalong** [comment]
@gvwilson The GFM parser has been extracted from the main kramdown distribution. If this issue should be resolved, please create a ticket at https://github.com/kramdown/parser-gfm/issues since I can't transfer this issue there. Thank you!
