### ISSUE TITLE
<center> not recognized as a block level tag

### ISSUE THREAD

**Issue by moll** [gettalong/kramdown#532]
Hey,

While `<center>` may be deprecated from HTML proper, it's still semantically useful tag once restyled for more appropriate behavior. I noticed the `parse_block_html` option of Kramdown however ignores contents inside `<center>` as it's missing from the block level tag constant in https://github.com/gettalong/kramdown/blob/790e2514c4075cc48542000923e33c61ee169147/lib/kramdown/parser/html.rb#L37.

**Comment by gettalong** [comment]
I would rather not add deprecated HTML things to kramdown, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center for how to do the same with a standard paragraph and IALs (for the CSS).

**Comment by moll** [comment]
That's a pity. Fortunately this workaround seemed to do the trick:
```ruby
require "kramdown"
Kramdown::Parser::Html::Constants::HTML_CONTENT_MODEL_BLOCK.push "center"
Kramdown::Parser::Html::Constants::HTML_CONTENT_MODEL["center"] = :block
```

As said, I'm not using `<center>` for its stylistic, but its slightly repurposed semantic meaning. Beats doing the longer `<div class="something">` in my op.

**Comment by moll** [comment]
Actually, with Web Components and all those fancy shenanigans with custom elements getting popularity, how _should_ one extend Kramdown to have it parse Markdown for tags it's not familiar with? Both for my deprecated `<center>` desire and entirely new tags?

**Comment by gettalong** [comment]
There is currently no standardized way to do this because when kramdown was designed there were no custom elements. Updating the constants, as you did, is probably the best way to do it for now.
