### ISSUE TITLE
Block attribute after math block not consistently handled

### ISSUE THREAD

**Issue by luc-j-bourhis** [gettalong/kramdown#533]
The following code

```ruby
require 'kramdown'

text = <<END
This is an example of math

$$\\nabla\\cdot E = \\rho$$
{: .autotag}

and the rest follows.
END

math_eng = 'mathjax'
#math_eng = 'katex'
puts Kramdown::Document.new(text, :math_engine => math_eng).to_html
```

produces the following output when  `math_eng == 'mathjax'`

```html
<p>This is an example of math</p>

<script type="math/tex; mode=display">\nabla\cdot E = \rho</script>

<p>and the rest follows.</p>
```

and the following output when `math_eng = 'katex'`

```html
<p>This is an example of math</p>

<div class="autotag kdmath">$$
\nabla\cdot E = \rho
$$</div>

<p>and the rest follows.</p>
```
I do realise that a `class` can't be set for a `<script>` tag in the Mathjax case but still I find it a problem that the class just disappears like that. Anything would be better than the current situation really!

This is with Kramdown version 1.17.0

**Comment by gettalong** [comment]
Any suggestions?

**Comment by luc-j-bourhis** [comment]
Actually, to my surprise, the [HTML Living Standard](
https://html.spec.whatwg.org/multipage/dom.html#global-attributes) specify that «The WHATWG DOM standard defines the user agent requirements for the class, id, and slot attributes for any element in any namespace.». [HTML5](
https://www.w3.org/TR/html50/scripting-1.html#script), again through [global attributes](
https://www.w3.org/TR/html50/dom.html#global-attributes). So `<script>` could get passed  the class and the id set by kramdown attributes. Then both with KaTeX and Mathjax, one could select particular equations at will.

**Comment by gettalong** [comment]
Cool, thanks for the update. So just adding the class and id attributes, if specified, to the `<script>` tag of the mathjax math engine would be sufficient for you?

**Comment by luc-j-bourhis** [comment]
Yes, id and class would suit me. Note that I opened issue [#2041](
https://github.com/mathjax/MathJax/issues/2041) on Mathjax repo, suggesting that class and id on the script tag are passed to the tags created by Mathjax to actually display the equation. That would nicely fit with this present issue. Thanks!

**Comment by gettalong** [comment]
@luc-j-bourhis Took a while but with the next release the MathJax engine adds `<div>` and `<span>` tags around the math (which incidentally also changed to use the standard syntax instead of `<script>` tags).
