### ISSUE TITLE
Math block, LaTeX environment and equation numbering

### ISSUE THREAD

**Issue by luc-j-bourhis** [gettalong/kramdown#534]
The best automatic equation numbering with Mathjax is 
```javascript
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
```
because it numbers the environment `equation`, `align`, etc but not their starred versions, and it act upon the presence of `\notag`. However that presumes every equation is at least in the `equation` environment. By default, kramdown does not put displayed equations in any environment. Being forced to type `\begin{equation| ... \end{equation|` for every math block is no fun. So it would be nice if there was an option in `math_engine_opts` to tell kramdown to do that for us.

**Comment by luc-j-bourhis** [comment]
KaTeX does not accept `\begin{equation}` unfortunately. So this suggested option shall be disabled for KaTeX for the time being.

**Comment by gettalong** [comment]
It would need to be disabled by default anyway because it would change the appearance of current documents. And furthermore, the math engine options are engine specific, so if one engine doesn't recognize an option it is not used.

**Comment by gettalong** [comment]
@luc-j-bourhis I will close the issue and move it into the "Feature Requests" project where all issues are collected that need contributed pull requests.
