### ISSUE TITLE
Incorrect handling of multi-line code blocks

### ISSUE THREAD

**Issue by dblock** [gettalong/kramdown#536]
<img width="424" alt="screen shot 2018-08-13 at 7 32 47 pm" src="https://user-images.githubusercontent.com/542335/44063699-b0a34e54-9f2f-11e8-964c-204764e3ef51.png">

results in (notice the incorrect "two" header)

<img width="447" alt="screen shot 2018-08-13 at 7 33 06 pm" src="https://user-images.githubusercontent.com/542335/44063708-ba337354-9f2f-11e8-9241-7f24e81039ff.png">

https://gist.github.com/dblock/51a087689e5dc24fb986da47bd36ec30

From https://github.com/dblock/danger-toc/issues/7

**Comment by dblock** [comment]
I can try to fix this if someone can point me a bit into the right direction.

**Comment by gettalong** [comment]
I'm sorry but I can see nothing wrong with the code in the picture (please post the code itself the next time, it is better than a picture for an issue).

You are using the kramdown parser which supports the standard `~~~` fenced codeblock syntax. If you want to use the GFM triple backtick syntax, you have to use the GFM parser.

**Comment by dblock** [comment]
Picture because github won't let me past a bunch of back quotes without screwing up the formatting. Code in gist linked. Sorry :) Looking at the rest ...

**Comment by dblock** [comment]
Using `Kramdown::Document.new(md, input: 'GFM')` fixed the problem. Thanks.

**Comment by gettalong** [comment]
If you need to paste code with fenced code block syntax, just use more of the characters. You will get this:

~~~~~
~~~
fenced codeblock
~~~
~~~~~
if you use this:

~~~~~~
~~~~~
~~~
fenced codeblock
~~~
~~~~~
~~~~~~
