### ISSUE TITLE
GFM strikethrough seemingly broken when there's only one character inside

### ISSUE THREAD

**Issue by taoky** [gettalong/kramdown#539]
The syntax `~~content~~` does not seem to work when "content" is only one character. But the GFM actually supports it like this:

~~a~~

Here is my test:
```
> kramdown -i GFM
~~a~~
<p>~~a~~</p>
> kramdown -i GFM
~~aa~~
<p><del>aa</del></p>
```

And I notice that this weird behavior also exists when "content" is only a CJK character.
```
> kramdown -i GFM
~~中~~
<p>~~中~~</p>
> kramdown -i GFM
~~中文~~
<p><del>中文</del></p>
```

My kramdown version is 1.17.0, ruby version is 2.5.1p57 (2018-03-29 revision 63029), and OS is macOS 10.13.6.

The testcase for [GFM strikethrough](https://github.com/gettalong/kramdown/blob/master/test/testcases_gfm/strikethrough.text) does not contain this situation, so I believe that this is a bug rather than an intended behavior.

**Comment by gettalong** [comment]
Thank you for your report - this is indeed a bug in the regular expression needed for parsing the strikethrough.

**Comment by gettalong** [comment]
@taoky The GFM parser has been extracted from the main kramdown distribution. If this issue should be resolved, please create a ticket at https://github.com/kramdown/parser-gfm/issues since I can't transfer this issue there. Thank you!
