### ISSUE TITLE
Incomplete instructions: setting options within a document

### ISSUE THREAD

**Issue by antoineco** [gettalong/kramdown#545]
_following-up on #418_

The [_options_](https://kramdown.gettalong.org/options.html) page provides an example for setting flat options (bool, string, int) directly inside a kramdown document. But how about nested options?

Things I've tried unsuccessfully:

```
{::options syntax_highlighter_opts={ line_numbers="true"} /}
{::options syntax_highlighter_opts={ line_numbers: "true"} /}
{::options syntax_highlighter_opts={"line_numbers" => "true"} /}
```

**Comment by gettalong** [comment]
You need to use something like this:

~~~
{::options syntax_highlighter_opts="{line_numbers: table\}" /}
~~~

Make sure that you quote the value like with HTML attributes. And you need to escape closing parentheses.

**Comment by antoineco** [comment]
@gettalong thanks for the example, much appreciated :+1:

I'd like to keep this issue open until I add a working example to the existing documentation. Would you be open to that?

**Comment by gettalong** [comment]
I don't think that this issue needs to be kept open since the question is answered. If you like to add an example to the documentation, feel free to go ahead and open a pull request once done.
