### ISSUE TITLE
Document how to pass lexer options

### ISSUE THREAD

**Issue by antoineco** [gettalong/kramdown#546]
Looking at the kramdown code for [the `rouge` integration](https://github.com/gettalong/kramdown/blob/00550a5f5a61e2f6b894db359b6b63e9ace80713/lib/kramdown/converter/syntax_highlighter/rouge.rb#L27) I was expecting to be able to pass [lexer options](https://github.com/jneen/rouge/blob/c5f4288162e2e6218180779c7f6ac1735bb56eab/lib/rouge/lexer.rb#L36) in my markdown documents as follows:

    ```console?comments=true
    # comment
    some command ...
    ```

    ~~~console?comments=true
    # comment
    some command ...
    ~~~

However lexer options are ignored. What is the correct way to do this?

**Comment by gettalong** [comment]
You need to use the correct syntax for Rouge. For example, for using the `start_inline` option for the `php` lexer you need can do the following:

~~~~~~~
~~~ php?start_inline=0
echo "Hello World!";
~~~
~~~~~~~

**Comment by antoineco** [comment]
@gettalong thank you for the answer, but how does it differ from the example I posted?

Besides, I'd like to keep this issue open until I add a working example to the existing documentation. Would you be open to that?

**Comment by gettalong** [comment]
It doesn't really differ from your example (except you need to make sure to use tildes) but as I said you need to use the correct syntax that Rouge needs. So you have to look up the `console` lexer in Rouge and find out which options (and their values) are supported.

**Comment by antoineco** [comment]
Yes, I did exactly that.

**Comment by antoineco** [comment]
Yes, I did [exactly that](https://github.com/jneen/rouge/blob/c5f4288162e2e6218180779c7f6ac1735bb56eab/lib/rouge/lexers/console.rb#L21), which is the reason for my ticket.

Using the latest rouge and kramdown versions.

**Comment by gettalong** [comment]
Okay, I don't think that this is a kramdown issue. Please provide an example that uses only Rouge that works correctly and depends on a lexer option.

**Comment by antoineco** [comment]
@gettalong you were absolutely right. Of all lexer options it looks like I picked the only confusing one (`:prompt` was shadowing my option).

I changed my fence to `console?prompt=$` and got the expected result.

Sending a PR your way nevertheless.
