### ISSUE TITLE
Should auto_ids strip to first alpha character?

### ISSUE THREAD

**Issue by COV-GIS** [gettalong/kramdown#547]
I ran into an issue when updating and reworking a project with up-to-date Jekyll with leading numbers in heading ids. While html5 spec allows for ids to start with a number, it can cause issues with JS, as when dynamically creating menus, etc. I'm not sure when this changed in kramdown but some time in the last year and a half. Here are examples of from the old and new project.

```html
<h2 id="introductory-provisions">3-01.01 [Introductory Provisions]</h2>
```
```html
<h2 id="3-0101-introductory-provisions">3-01.01 [Introductory Provisions]</h2>
```

Possibly an option to strip ids to first alpha character?

Additionally I don't know who is using html 4.01 anymore but starting an id with a number is invalid.

**Comment by gettalong** [comment]
Can you provide a complete example, specifying input, current output and expected output? Additionally specify which parser you are using - thank you!

**Comment by COV-GIS** [comment]
@gettalong I attempted to figure out what may have changed. Unfortunately I've updated ruby, jekyll and all other deps. As far as expected output, I'm more of just an end user of jekyll and kramdown, so I can't really speak to that. I was able to overcome my issue with js and ids with leading numbers. And as ids with leading numbers are valid in html5, it really isn't a kramdown issue. Thank you.
