### ISSUE TITLE
Create a table of content (toc) without html id attributes

### ISSUE THREAD

**Issue by Exagone313** [gettalong/kramdown#549]
Hi,

When creating a [table of content](https://kramdown.gettalong.org/converter/html.html#toc), it adds *id* attributes to the `ul` and `a` elements. I don't understand what's the idea behind this, these *id* attributes seem unnecessary to me.

In fact I'm very cautious to the HTML generated for my Jekyll blog and I really don't want to have *id* attributes that shouldn't be used as anchors. I'd like to find a way to disable the generation of these.

Example:
```
* toc
{:toc}
```

Wanted result:
```
<ul>
  <li><a href="#foo">Foo</a></li>
</ul>
```

Actual result:
```
<ul id="markdown-toc">
  <li><a href="#foo" id="markdown-toc-foo">Foo</a></li>
</ul>
```

How can I achieve this without forking/hacking Kramdown?

Thanks for your help.

**Comment by gettalong** [comment]
If you don't want these IDs created, you can create a custom converter based on the HTML converter and override the `#generate_toc_tree` method.

**Comment by Exagone313** [comment]
Yeah I could probably do that and maintain my overridden [method](https://kramdown.gettalong.org/rdoc/Kramdown/Converter/Html.html#method-i-generate_toc_tree) with your potential newer changes.

But I'd like to know if adding an option for my case would be accepted as a PR. (I don't know what's the  policy about contributions, it'll principally be just an `unless` in the concerned method anyway)

**Comment by gettalong** [comment]
I don't think an option is useful in this case because removing the ID from the elements doesn't provide any benefit. In fact, removing the IDs would make linking back to a TOC entry impossible.
