### ISSUE TITLE
Can't have bold and italic

### ISSUE THREAD

**Issue by DavidBiesack** [gettalong/kramdown#550]
` _italics_ or **bold**` work but combining as `_**bold and italic**_` or `**_bold and italic_**` (as in GFM **_bold and italic_**) does not work. I'm using kramdown via Jeklyll 3.4.3 and kramdown 1.17.0

**Comment by gettalong** [comment]
Please have a look at the [syntax documentation](https://kramdown.gettalong.org/syntax.html) for kramdown. Underscores may only be used on whole words whereas asterisks work inside words. So if you want to mark something as bold *and* italic, just use three asterisks, like this: `***bold and italic***`.
