### ISSUE TITLE
Double quotes are wrongly converted

### ISSUE THREAD

**Issue by fatjyc** [gettalong/kramdown#555]
the code is
```
 "abc"
```

converted result is 

```
<p>“abc”</p>
```

the double quotes are wrongly converted

**Comment by kecode** [comment]
The wrong place to convert in double quotes is Chinese double quotes.

**Comment by kecode** [comment]
> Can you explain a bit more _what exactly_ is wrong? You will find in the [syntax documentation](https://kramdown.gettalong.org/syntax.html) that quotes are converted automatically to "smart quotes".

The wrong place to convert in double quotes is Chinese double quotes.

**Comment by gettalong** [comment]
You can define how the quotes get converted by using the [smart_quotes option](https://kramdown.gettalong.org/converter/html.html#option-smart-quotes).

**Comment by kecode** [comment]
> You can define how the quotes get converted by using the [smart_quotes option](https://kramdown.gettalong.org/converter/html.html#option-smart-quotes).

Thank you！
