### ISSUE TITLE
LaTeX \maketitle

### ISSUE THREAD

**Issue by owm111** [gettalong/kramdown#556]
As far as I know, there is no way to have a LaTeX `\maketitle` with kramdown. With my knowledge of kramdown, the only thing I can think of would be a template to generate it.

Pandoc conatins this feature, however it requires processing a "frontmatter." 

Would something like this even be possible in kramdown?

(If it isn't obvious, I am very new to kramdown. So far, I like what I see, but this is a sort of "deal breaker" for me)

**Comment by owm111** [comment]
It may... something I will definitely play around with.

Is there documentation about variables, etc. available to in the templates?

**Comment by gettalong** [comment]
No but have a look at the [default tempate](https://github.com/gettalong/kramdown/blob/master/data/kramdown/document.latex)

**Comment by owm111** [comment]
I managed to make something that works---very rough, but it works. [See this gist](https://gist.github.com/owm111/6d8b50e48a7a135632cbdeb6c0c48643).

For a summary, I used the following to find the title:
```rb
body[/\\begin\{center}\n\\rule\{3in}\{0\.4pt}\n\\end\{center}\n(?:.|\n)*title: (.+)\n(?:.|\n)*---/, 1][/(.+)\\newline/, 1]
```
Similar regexps were used to find the author, date, and the document content.

(Ruby is far from my strongest language, so suggestions are welcome.)

**Comment by gettalong** [comment]
You have access to the whole abstract syntax tree in the converter (`@converter.root`). This could be used to get the element (probably a header?) and its text without resorting to Regexp. See https://kramdown.gettalong.org/rdoc/Kramdown/Element.html for how the elements are stored.

**Comment by owm111** [comment]
Nope, all's good. Sorry for not doing this earlier
