### ISSUE TITLE
")" not supported as ordered list marker

### ISSUE THREAD

**Issue by cup** [gettalong/kramdown#558]
> An ordered list marker is a sequence of 1–9 arabic digits (0-9), followed by
> either a `.` character or a `)` character.

http://spec.commonmark.org/0.28#ordered-list-marker

With this input:

~~~
1. alpha
2. beta
3. gamma

1) delta
2) epsilon
3) zeta
~~~

github.com produce this result:

~~~html
<ol>
<li>alpha</li>
<li>beta</li>
<li>gamma</li>
</ol>
<ol>
<li>delta</li>
<li>epsilon</li>
<li>zeta</li>
</ol>
~~~

However Kramdown produce this:

~~~html
<ol>
  <li>alpha</li>
  <li>beta</li>
  <li>gamma</li>
</ol>

<p>1) delta
2) epsilon
3) zeta</p>
~~~

**Comment by gettalong** [comment]
Please note that kramdown follows the [kramdown specification](https://kramdown.gettalong.org/syntax.html). Nowhere it says that kramdown provides an implementation of the CommonMark version of Markdown.

As for the issue at hand: The kramdown parser doesn't have this syntax. If there is enough interest, it may be implemented for the next big version of the kramdown parser.

**Comment by cup** [comment]
For anyone using GitHub Pages, you can simply add this to `_config.yml`:

~~~
markdown: CommonMarkGhPages
~~~

you dont even have to declare the plugin in `_config.yml` as its activated by
default:

http://github.com/github/pages-gem/blob/fb5c3f2/lib/github-pages/plugins.rb#L9

reference:

http://github.com/github/jekyll-commonmark-ghpages
