### ISSUE TITLE
Text highlight

### ISSUE THREAD

**Issue by luispuerto** [gettalong/kramdown#559]
Hey! 

It would be great if the next version kramdown support rendering `==highlighted text==` in html as `<mark>highlighted text</mark>`, so we can get a little bit more easy highlighted text more easily. 

it's the same idea as in #41

**Comment by gettalong** [comment]
Thank you for this idea. Since this is a feature request, it will be tracked by a separate project (see https://github.com/gettalong/kramdown/projects/1) and closed. Once somebody works on this issue, it will be re-opened.

**Comment by luispuerto** [comment]
really happy to hear that @gettalong. Do you have any date for the "next major version"?
