### ISSUE TITLE
Duplicate IDs

### ISSUE THREAD

**Issue by XhmikosR** [gettalong/kramdown#561]
Hello!

So, I've been hitting some cases with duplicate IDs on Bootstrap blog.

I'm not sure if this is an issue with kramdown or if Jekyll could work around this or something, but I thought I'd report this.

Source repo: https://github.com/twbs/bootstrap-blog

kramdown config:

```yml
kramdown:
  auto_ids: true
```

Jekyll 3.8.5 with kramdown 1.17

Basically we loop through the posts, and some of the posts might use the same header. Even if I work around this for one case specific case, there are more cases and it becomes tedious to keep track of all this manually :)

```
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/index.html":184.1-184.19: error: Duplicate ID "whats-new".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page12/index.html":296.1-296.14: error: Duplicate ID "tldr".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page2/index.html":437.1-437.20: error: Duplicate ID "highlights".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page4/index.html":235.1-235.28: error: Duplicate ID "download-bootstrap".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page4/index.html":243.1-243.23: error: Duplicate ID "bootstrap-cdn".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page5/index.html":216.1-216.28: error: Duplicate ID "download-bootstrap".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page5/index.html":224.1-224.23: error: Duplicate ID "bootstrap-cdn".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page5/index.html":287.1-287.28: error: Duplicate ID "download-bootstrap".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page5/index.html":295.1-295.23: error: Duplicate ID "bootstrap-cdn".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page5/index.html":337.1-337.28: error: Duplicate ID "download-bootstrap".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page5/index.html":345.1-345.23: error: Duplicate ID "bootstrap-cdn".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page5/index.html":399.1-399.28: error: Duplicate ID "download-bootstrap".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page7/index.html":236.1-236.20: error: Duplicate ID "whats-next".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page7/index.html":402.1-402.18: error: Duplicate ID "new-docs".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page7/index.html":455.1-455.28: error: Duplicate ID "download-bootstrap".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page7/index.html":474.1-474.24: error: Duplicate ID "full-changelog".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page8/index.html":244.1-244.21: error: Duplicate ID "key-changes".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page8/index.html":268.1-268.17: error: Duplicate ID "up-next".
"file:/C:/Users/xmr/Desktop/bootstrap-blog/_site/page8/index.html":484.1-484.17: error: Duplicate ID "up-next".
```

**Comment by gettalong** [comment]
You need to use the option [`auto_id_prefix`](https://kramdown.gettalong.org/options.html#option-auto-id-prefix) so that each rendered post gets a custom prefix.

**Comment by XhmikosR** [comment]
@gettalong: but this doesn't fix the error, it's just the IDs will be prefixed.

**Comment by XhmikosR** [comment]
Because I did try it before I opened the issue, and it's the same result as expected.

**Comment by gettalong** [comment]
All I can say is that the mentioned option is made for use-cases such as this. How and where you apply this option is up to you but you need to apply a **different `auto_id_prefix` option for each rendered kramdown page** if the pages all appear in the same HTML output file.

**Comment by gettalong** [comment]
It has to be handled by the code outputting multiple kramdown documents together into one file. That's the only appropriate place. kramdown provides everything needed for correct output but it has to be used correctly.

I guess you have to find the place where this happens and change the code there.

**Comment by XhmikosR** [comment]
That's what I was trying to figure out, I think it's Jekyll that should handle this since it has the page context.

I'll try raising an issue there but I don't have high hopes.
