### ISSUE TITLE
Options from extracted gems are not output via CLI

### ISSUE THREAD

**Issue by ashmaroli** [gettalong/kramdown#569]
After having installed `kramdown-2.0.0`, running `kramdown --help` doesn't surface `options` from the extracted gems.

```bash
kramdown --help
```

I also used a `Gemfile` and tried again with `bundle exec`. Still no success!
```ruby
# Gemfile

gem 'kramdown', '~> 2.0'
gem 'kramdown-parser-gfm'
```
```bash
$ bundle exec kramdown --help
```

What should a user do to surface `options` from `kramdown-parser-gem` gem in the `--help` output?

**Comment by gettalong** [comment]
kramdown automatically loads a parser if it is used. So `kramdown -i GFM` still works, as would `kramdown -o pdf` for the PDF converter.

I'm open to suggestions for making the options of third-party extensions available to the kramdown binary.

**Comment by ashmaroli** [comment]
A simple route would be a introducing a new flag say `-x, --extension [GEM-NAME, [GEM_NAME_2...]]`
Usage would be:

```bash
$ kramdown -x parser-gfm
# => kramdown options + GFM Parser options

$ kramdown -x parser-gfm, syntax-coderay
# => kramdown options + GFM Parser options + CodeRay options
```
The binary can abort with an error message if the given extension raises a `LoadError` exception

**Comment by gettalong** [comment]
I have [committed](https://github.com/gettalong/kramdown/commit/d7644907db9aa3d7240243a24cd4dd64d3b803a3) a change which allows specifying extensions. Once specified, the options from the extension can be used with the binary and are shown with the `--help` option.
