### ISSUE TITLE
Multi-line code blocks are not parsed correctly in details/summary

### ISSUE THREAD

**Issue by BalestraPatrick** [gettalong/kramdown#580]
Hello,

My issue is related to #155. That specific issue was solved since the code block only contained one line of code. If the code block contains more than one line of code, the syntax highlighting breaks.

You can see the issue with the following markdown document:
````
<details><summary markdown="span">markdown</summary>

```swift
public var markdown: String
```

</details>

<details><summary markdown="span">markdown</summary>

```swift
public var markdown: String
public var markdown: String
```

</details>

<details><summary markdown="span">markdown</summary>

```swift
public var markdown: String

public var markdown: String
```

</details>
````

By using the command-line executable in this way:
```
cat Test.md | kramdown --parse-block-html > index.html
```

The result is the following:
<img width="494" alt="screen shot 2019-02-17 at 7 20 39 pm" src="https://user-images.githubusercontent.com/3658887/52917211-1e61b780-32e9-11e9-9ddd-52b1bd43f1ae.png">

As you can see, the first code block is parsed correctly (even though `swift` is inserted there, but probably this is an issue with the fact that I am opening the raw html instead of rendering it in GitHub pages?). In the second example, the newline character between the two code blocks is completely ignored. In the third example, the syntax highlighting and code block is completely broken.

Am I doing something wrong or is this a bug? Any idea on how to get around it?

**Comment by gettalong** [comment]
You need to use the correct fenced code block syntax, ie.

~~~~~
~~~ swift
some code block
~~~
~~~~~

Changing your example to the correct syntax and running kramdown as you showed result in the following output for me which looks correct:

~~~ html
<details>
  <summary>markdown</summary>

  <div class="language-swift highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">public</span> <span class="k">var</span> <span class="nv">markdown</span><span class="p">:</span> <span class="kt">String</span>
</code></pre></div>  </div>

</details>

<details>
  <summary>markdown</summary>

  <div class="language-swift highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">public</span> <span class="k">var</span> <span class="nv">markdown</span><span class="p">:</span> <span class="kt">String</span>
<span class="kd">public</span> <span class="k">var</span> <span class="nv">markdown</span><span class="p">:</span> <span class="kt">String</span>
</code></pre></div>  </div>

</details>

<details>
  <summary>markdown</summary>

  <div class="language-swift highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">public</span> <span class="k">var</span> <span class="nv">markdown</span><span class="p">:</span> <span class="kt">String</span>

<span class="kd">public</span> <span class="k">var</span> <span class="nv">markdown</span><span class="p">:</span> <span class="kt">String</span>
</code></pre></div>  </div>

</details>
~~~

ps. Please note that images don't help the discussion, provide text input and text output where possible.

**Comment by BalestraPatrick** [comment]
That fixes it, I didn't know about `~~~`. Thanks a lot! 👍

**Comment by elder-n00b** [comment]
My two cents, but related to GitHub markdown (not tried with kramdown, no idea what version github is using):  

currently code formatting breaks within `<details>`, with \``` and ~~~, if the tag begins on a new line.  
It works, with \``` and ~~~, if the tag is attached to the previous line (no intervening newline).

Examples: <details><summary>This works</summary>
backtick:
```swift
let base : [String: Any] = ["name": "Rocket Skates", "price": 12.75, "color": "yellow"]
let update : [String: Any] = ["price": 15.25, "color": "red", "year": 1974]
let result = base.merging(update) { (_, new) in new }
print(result)
```
tilde:
~~~swift
let base : [String: Any] = ["name": "Rocket Skates", "price": 12.75, "color": "yellow"]
let update : [String: Any] = ["price": 15.25, "color": "red", "year": 1974]
let result = base.merging(update) { (_, new) in new }
print(result)
~~~
</details>

<details><summary>This doesn't</summary>
backtick:
```swift
let base : [String: Any] = ["name": "Rocket Skates", "price": 12.75, "color": "yellow"]
let update : [String: Any] = ["price": 15.25, "color": "red", "year": 1974]
let result = base.merging(update) { (_, new) in new }
print(result)
```
tilde:
~~~swift
let base : [String: Any] = ["name": "Rocket Skates", "price": 12.75, "color": "yellow"]
let update : [String: Any] = ["price": 15.25, "color": "red", "year": 1974]
let result = base.merging(update) { (_, new) in new }
print(result)
~~~
</details>

**Comment by MatthewCane** [comment]
@elder-n00b thank you for this, I've been pulling my hair out as to why my CI generated Github comments are coming out malformed!
