### ISSUE TITLE
Odd/Even number of underscores in markdown tags treated as emphasis/strong

### ISSUE THREAD

**Issue by askmrsinh** [gettalong/kramdown#582]
I am trying to convert the below markdown text to html.

Input Markdown Image and link tags with odd (3) number of `_`:
```
![alt-assets/Wetter___stats.jsp.png](https://gitlab.com/user501254/Wetter/raw/b80b165a57036319d80d3e59919c3fa1a4719eb7/assets/Wetter___stats.jsp.png)

[alt-assets/Wetter___stats.jsp.png](https://gitlab.com/user501254/Wetter/raw/b80b165a57036319d80d3e59919c3fa1a4719eb7/assets/Wetter___stats.jsp.png)
```

The above should ideally be convert to below HTML:
```
<p><img src="https://gitlab.com/user501254/Wetter/raw/b80b165a57036319d80d3e59919c3fa1a4719eb7/assets/Wetter___stats.jsp.png" alt="assets/Wetter___stats.jsp.png" /></p>

<p><a href="https://gitlab.com/user501254/Wetter/raw/b80b165a57036319d80d3e59919c3fa1a4719eb7/assets/Wetter___stats.jsp.png">assets/Wetter___stats.jsp.png</a></p>
```

However, output (`-o kramdown`) with incorrectly place  ` *`:

```
\[assets/Wetter\_\_*stats.jsp.png\](https://gitlab.com/user501254/Wetter/raw/b80b165a57036319d80d3e59919c3fa1a4719eb7/assets/Wetter*\_\_stats.jsp.png)

!\[assets/Wetter\_\_*stats.jsp.png\](https://gitlab.com/user501254/Wetter/raw/b80b165a57036319d80d3e59919c3fa1a4719eb7/assets/Wetter*\_\_stats.jsp.png)
```

Furthermore, instead of 3 (odd) underscores (`___`)  if there are 4 (even > 2) underscores (`____`) it's parsed as as  `**`. As we increase the count of underscores, both `<em>` and `<strong>` tags start showing up in the output without a corresponding closing tag (`</em>`, `</strong>`). 
Manually escaping the underscores in both the cases fixes the issues.

I have checked the same input in some other converters (including this GitHub markdown field) where they are converted perfectly. Since I have almost no experience with the ruby code base, I am unable to make a PR with the fix but will be adding the test cases.

**Comment by gettalong** [comment]
Thanks for reporting this behaviour and the test cases!

The opened link should probably take preference over the emphasis but I will have to take a deeper look at this.

**Comment by user501254** [comment]
I went through the CommonMark Spec on which GFM adds.

Under Rule 17 of [6.4 Emphasis and strong emphasis](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis), the specification states:
> Inline code spans, links, images, and HTML tags group more tightly than emphasis. So, when there is a choice between an interpretation that contains one of these elements and one that does not, the former always wins. Thus, for example, `*[foo*](bar)` is parsed as `*<a href="bar">foo*</a>` rather than as `<em>[foo</em>](bar)`.

[Example 473](https://spec.commonmark.org/0.29/#example-473) illustrates this nicely.

**Comment by gettalong** [comment]
@user501254 Thanks but the CommonMark spec doesn't apply to kramdown, only the kramdown specification.

**Comment by user501254** [comment]
I understand, but I could not find anything specific to this issue [here](https://kramdown.gettalong.org/syntax.html).
I have also tried the derivative `kramdown-parser-gfm` gem which gave same results.

```Ruby
require 'kramdown'
require 'kramdown-parser-gfm'

text1="![alt-assets/Wetter___stats.jsp.png](https://gitlab.com/user501254/Wetter/raw/b80b165a57036319d80d3e59919c3fa1a4719eb7/assets/Wetter___stats.jsp.png)"
puts Kramdown::Document.new(text1, input: 'GFM').to_html
#<p>![alt-assets/Wetter__<em>stats.jsp.png](https://gitlab.com/user501254/Wetter/raw/b80b165a57036319d80d3e59919c3fa1a4719eb7/assets/Wetter</em>__stats.jsp.png)</p>

text2="[alt-assets/Wetter___stats.jsp.png](https://gitlab.com/user501254/Wetter/raw/b80b165a57036319d80d3e59919c3fa1a4719eb7/assets/Wetter___stats.jsp.png)"
puts Kramdown::Document.new(text2, input: 'GFM').to_html
#<p>[alt-assets/Wetter__<em>stats.jsp.png](https://gitlab.com/user501254/Wetter/raw/b80b165a57036319d80d3e59919c3fa1a4719eb7/assets/Wetter</em>__stats.jsp.png)</p>
```

**Comment by gettalong** [comment]
I have committed a fix and this will be in the next release.

**Comment by askmrsinh** [comment]
Thank you!
