### ISSUE TITLE
CJK Line Breaks

### ISSUE THREAD

**Issue by fangyi-zhou** [gettalong/kramdown#587]
# Description
Input:
```
一
二
三
四
五
```

Expected Output:
```
<p>一二三四五</p>
```

Actual Output:
```
<p>一
二
三
四
五</p>
```

# Why is this an issue?
We usually don't have spaces in CJK characters (Chinese, Japanese, Korean characters), unlike English and a bunch of other languages. If line breaks are preserved, it will render as a space in HTML, which is unnatural.
See also:
https://github.com/zhangkaizhao/asciidoctor_cjk_breaks
https://github.com/markdown-it/markdown-it-cjk-breaks
https://github.com/jgm/pandoc/issues/2586
https://github.com/zbinlin/markdown-it-perfect-newline-for-cjk

If anyone would like to give some pointers to code changes, I can submit a PR

**Comment by gettalong** [comment]
Thanks for bringing this up - you will probably need to adapt `Kramdown::Converter::HTML#convert_text` for this to work.

**Comment by gettalong** [comment]
@fangyi-zhou Do you have a pull request that implements the needed changes?

**Comment by fangyi-zhou** [comment]
https://github.com/gettalong/kramdown/pull/588

**Comment by gettalong** [comment]
Ah, sorry, I overlooked that pull request. Your changes are now merged - thank you for your contribution!
