### ISSUE TITLE
[Documentation] Please consider adding an example to the main readme for .md to .pdf conversion

### ISSUE THREAD

**Issue by rubyFeedback** [gettalong/kramdown#589]
Hello Thomas,

I am using more and more .md markdown files locally here. Thus, I am searching for a way to convert them on the commandline (on linux).

I first had a look at pandoc, but this requires the whole haskell stack, and it also failed to install for me so I gave up. I then looked at npm and a npm module but the installation failed too. So next thing was to try to see if rubygems has support for this.

I already knew kramdown because I use it in one of my projects (to display local .md files from oldschool ruby .cgi files). I then wondered whether kramdown has support for .md -> .pdf conversion.

Looking at the main readme of kramdown, this seems to be the case, but I could not find an example for the conversion.

IF the conversion works, would it be possible to add a line or two to show how to do this? (It may also help people who quickly scan through the main readme to determine whether this conversion is possible or not).

Thanks for reading - feel free to close this issue at any moment in time.

**Comment by gettalong** [comment]
The PDF converter can be installed via `gem install kramdown-converter-pdf` (it was extracted in the 2.0.0 version). Then you can run `kramdown -x converter-pdf -o pdf my.md` to convert a document to PDF.

As the PDF converter is currently unmaintained, I hesitate to add an example to the main kramdown README file.
