### ISSUE TITLE
different comments?

### ISSUE THREAD

**Issue by grauschnabel** [gettalong/kramdown#592]
Hi there,

how can disable some content from the latex converter but not from the html converter?

nomarkdown with "type" is great for having something rendered there.

Is there a way to add this to comment too?  Would be greate to have
```
{::comment type="latex"}
Hide me from the latex converter.
{:/comment}
```
Is this possible or do I have to create my own preprocessing routines?

Thanks,
Martin

**Comment by gettalong** [comment]
You can use the [`nomarkdown`](https://kramdown.gettalong.org/syntax.html#extensions) extension for this.
