### ISSUE TITLE
Duplicate IDs in parsed block element

### ISSUE THREAD

**Issue by arthurattwell** [gettalong/kramdown#595]
In kramdown 1.17 (running in Jekyll on Windows with Ruby 2.5, Ubuntu with Ruby 2.4) when I use this markdown, I get duplicate IDs on the headings:

```md
## Heading

<div markdown="1">

## Heading

</div>
```

Output:

```html
<h2 id="heading">Heading</h2>
<div>
  <h2 id="heading">Heading</h2>
</div>
```

Could or should the processor avoid duplicate IDs in this case?

**Comment by gettalong** [comment]
Have you tried with the latest version of kramdown? Because I get the following output for your sample:

~~~html
<h2 id="heading">Heading</h2>

<div>

  <h2 id="heading-1">Heading</h2>

</div>
~~~

**Comment by ashmaroli** [comment]
@arthurattwell  Do note that you'll have to explicitly add the latest version of `kramdown` (`2.1.0`) in your Gemfile because Jekyll 3 is programmed to install just kramdown-1.x automatically.
```ruby
gem 'kramdown', '~> 2.1'

group :jekyll_plugins do
  # needed for Jekyll 3 to load the extension at runtime to
  # support GFM input.
  #
  # Jekyll 4 will do it automatically. So won't be needed in future.
  gem 'kramdown-parser-gfm'
end

**Comment by arthurattwell** [comment]
Thanks @gettalong and @ashmaroli.

In Jekyll 4.0.0 with kramdown 2.1.0, I still get the duplicate IDs on Windows and Ubuntu.

However, using kramdown directly I get the correct, sequentially numbered IDs.

So it looks like the problem is in Jekyll, not kramdown. Does that sound plausible? If you agree, you can close this issue and I'll open one at Jekyll.

**Comment by gettalong** [comment]
@arthurattwell I'm not really familiar with Jekyll to answer the question. However, if it works with standalone kramdown, it most probably is a problem with Jekyll.

**Comment by arthurattwell** [comment]
@gettalong Thanks. I've opened [an issue at Jekyll](https://github.com/jekyll/jekyll/issues/7810).
