### ISSUE TITLE
Substitute file extensions of relative links (.md -> .html)?

### ISSUE THREAD

**Issue by Simran-B** [gettalong/kramdown#599]
Assume there are two Markdown files which cross-reference each other using the standard link syntax:

File1.md

```md
# File 1

[Link to File2](File2.md)
```
File2.md

```md
# File 2

[Link to File1](File1.md)
```

If you convert them to HTML, e.g. through Jekyll, you get File1.html and File2.html, but the file extensions remain `.md` and thus you end up with broken links:
`<a href="File2.md">Link to File2</a>`

You could change the extensions to `.html` like `[Link to File2](File2.html)` and the links will work in the generated output, but then you break them for your code editor (e.g. Alt+LMB on a URL in VS Code to open the linked file).

What Jekyll expects you to do is to use a Liquid tag it seems: `{% link File2.md %}`
But this won't be clickable either unless you customize your code editor to understand the templating syntax...

Is there a way in Kramdown to process links in such a way that `.md` extensions of relative links get replaced by `.html`? Another use case of some kind of user-defined callback would be to add the attribute `target="_blank"` to `<a>` tags for all external links.

**Comment by gettalong** [comment]
This is not something that is useful in kramdown itself but has to be decided by the tool that uses kramdown.

You mention that Jekyll users have to use a special liquid tag, I solved this in [webgen](https://webgen.gettalong.org( (a static website generator) in [another way](https://github.com/gettalong/webgen/blob/master/lib/webgen/content_processor/kramdown.rb#L22).

**Comment by Simran-B** [comment]
Do I understand correctly that kramdown.rb of webgen overwrites kramdown's own `convert_a()` method, and that any other tool like Jekyll could also do this to control what kramdown will output if it encounters regular Markdown links?

**Comment by gettalong** [comment]
webgen doesn't override this method but uses a subclass which specializes this method. And yes, any tool that uses kramdown can do that.
