### ISSUE TITLE
Updating kramdown

### ISSUE THREAD

**Issue by seamusdemora** [gettalong/kramdown#604]
This is a question: 

I have `kramdown` v. 1.16.2 installed on my Mac (Mojave 10.14.5), an install that I performed using `gem` v. 2.5.2.3. I'd like to update to the latest now, but after a (brief) search, I can't find anything  explaining how this is done. Can you point me toward the docs for this?

**Comment by gettalong** [comment]
You just need to run `gem install kramdown` and it will install the latest version. If you then want to remove the older version, just run `gem uninstall kramdown` and select the old version to uninstall it.
