### ISSUE TITLE
Embedded local videos don't work with Chrome

### ISSUE THREAD

**Issue by PForet** [gettalong/kramdown#609]
Hi

I'm currently having some issues with embedded videos on github pages. When using the following code:

`![foo](/assets/videos/something.mp4)`

it works on Safari but not on Chrome. [A fix](https://stackoverflow.com/questions/48876911/embedded-local-mp4-not-playing-in-chrome-when-running-jekyll-serve-econnreset) seems to be to put the video on mute. Indeed, when embedding the video using html tags:

```
<video muted autoplay loop>
   <source src="/assets/videos/something.mp4" type="video/mp4" width="320" height="240">
</video>
```

then it works fine on both browsers.
My issue with that fix is that we loose all the responsiveness of the markdown embedding (impossible to put the videos correctly in tables, rescaling, etc...). Is there a way to keep the behaviour of the inline embedding while muting the video?

Thanks a lot

**Comment by gettalong** [comment]
The syntax you are using is for embedding images, i.e. it creates an `<img>` tag. There is no syntax for videos, so if you want to embed a video, you will have to use HTML tags.
