### ISSUE TITLE
Replace quotation marks with a dedicated HTML tag q

### ISSUE THREAD

**Issue by doktorbro** [gettalong/kramdown#61]
The current syntax provides the `smart_quotes` option to transform the simplified quotation marks `"` and `'` into typographically correct quote pairs (»«, „“, …). This is a step forward from default markdown, but away from semantic meaning of a quote.

The point is: a quote is a _markup_ like [emphasis](http://kramdown.rubyforge.org/syntax.html#emphasis). We should treat it like such. There is a dedicated HTML tag `q` for quotes you can design it with CSS whatever your language requires. German would write:

``` css
q:before { content: "»" }
q:after {  content: "«" }
```

What do you thing about introducing that way to parse quotation marks? Maybe as an option?

**Comment by kslstn** [comment]
> The problem is that currently quotation marks are not recognized in pairs. I.e. kramdown doesn't know when a quotation starts and when it ends. It just sees a straight quotation mark, does some checking and changes the quotation mark into the one it assumes is the correct one. Therefore it is not possible to utilize the `<q>` tag.

Is this still the case today? I (wrongly) submitted [this issue](https://github.com/jekyll/jekyll/issues/8441) to the Jekyll project. Having `<q>` tags would let site makers define quotation marks in CSS, based on the language of the text in which the quote appears. Because of how Jekyll and Kramdown work together, right now, there's no way to consistently apply smart quotation marks for more than one language on a site.

**Comment by gettalong** [comment]
@kslstn Yes, there is no algorithm in kramdown to detect correct pairs of quotes. If you don't want quotes turned into smart quotes automatically, use the `smart_quotes` option.

You either need to pre-process your source files and insert `<q>` tags there or post-process the output of kramdown.

**Comment by doktorbro** [comment]
@kslstn the irony is most developers don’t understand the importance of proper typography. for example https://github.com/jnvsor/jnvsor.github.io/pull/1

there is one very simple workaround without extra-processing mentioned by @gettalong: abuse the strong tag. it’s applicable if you 

1. do not use the real strong tag in your text;
1. do not use nested quote tags;
1. do not care about html semantics.

## example

### input markdown

```markdown
bob: **where are you, alice?**
alice: **i’m on the *titanic*.**
```
### input css

```css
strong:before { content: "«" }
strong:after {  content: "»" }
```

### output
> bob: «where are you, alice?»
alice: «i’m on the *titanic*.»
