### ISSUE TITLE
Initializing multiple Documents with the same options

### ISSUE THREAD

**Issue by ashmaroli** [gettalong/kramdown#610]
When given the following code:
```ruby
('A'..'Z').to_a.each do |name|
  (1..50).to_a.each do |section|
  source = File.read("folio/#{name}#{section}", mode: 'utf-8')
  Kramdown::Document.new(source, FOLIO_OPTIONS).to_html
end
```
Each of the `Document` instance generates a copy of the same `Options` hash (same `#hash` value but different `#object_id`). This involves consuming resources to parse and merge hashes at multiple levels to produce *the same output* from *the same input*.

Would be great if this could be optimized.

**Comment by gettalong** [comment]
I will have a look at it. This will probably have to be done by using some new methods...

**Comment by ashmaroli** [comment]
Thank you. I tried to approach this with a class-wide cache:
```ruby
def self.options_cache
  @options_cache ||= {}
end

def initialize(source, options = {})
  self.class.options_cache[options.hash] ||= Options.merge(options).freeze
  @options = self.class.options_cache[options.hash]
  . . .
end
```
But that felt a bit *off..*

**Comment by gettalong** [comment]
Yeah, that won't do since the options are also used by the parsers and converters, so this would only catch one place of initialization.

**Comment by gettalong** [comment]
We decided to leave this as it is.
