### ISSUE TITLE
Use CGI.escape_html instead of in-house implementation

### ISSUE THREAD

**Issue by ashmaroli** [gettalong/kramdown#611]
`CGI.escape_html` has been made [faster with Ruby 2.3](https://github.com/ruby/ruby/commit/ce7f7f5e3d6c288b140870fa87c4b11e9a744f62)

Additionally, more optimization can be [expected with Ruby 2.7](https://github.com/ruby/ruby/commit/0a29dc87e62c701db56816cb430daf07a4f02bea) if there's at least one escaped character.

Additional benefits over simple `gsub` with regexps is bypassing allocations of `Matchdata` objects.

**Comment by gettalong** [comment]
The current implementation does more than `CGI.escape_html`, so this would need to be taken into account for a potential pull request.

**Comment by gettalong** [comment]
@ashmaroli I will close this issue now due to inactivity. Feel free to comment if you have more input.
