### ISSUE TITLE
How can you convert a mutate `to_hash_ast` to `HTML`

### ISSUE THREAD

**Issue by teddynecsoiu** [gettalong/kramdown#613]
If you strip or modify some values of the AST from `to_hast_ast`, how can you then pass that back through a converted to get HTML? e.g.

```
class TabsTagBlock < Liquid::Block
    require "kramdown"
    def render(context)
      rawDoc= Kramdown::Document.new(super)
      rawAST = rawDoc.to_hash_ast
     
      # Method that removes all root lvl h2
      # Save new AST in cleanAST

      # Convert AST back to Kramdown::Document or HTML ??
      "<div class='clean'>#{Kramdown::Document.new(cleanAST).to_html}</div>"
    end

  end
```

**Comment by gettalong** [comment]
You don't use HashAST for such a purpose. If you want to change something in the AST and then convert it, you just need to walk the AST itself and perform the actions directly on the AST. The AST is stored in `document.root`.
