### ISSUE TITLE
Heading not parsed while using parse_block_html attribute

### ISSUE THREAD

**Issue by robbiejaeger** [gettalong/kramdown#616]
I'm trying out the `parse_block_html` attribute. I have a `section` with markdown:

![image](https://user-images.githubusercontent.com/17582916/60470575-2da12c00-9c1e-11e9-8be5-069fe82194a1.png)

The code snippet and paragraph text is working well, but the heading does not appear to be parsed since it still shows the `##`.

![image](https://user-images.githubusercontent.com/17582916/60470504-def39200-9c1d-11e9-8be9-8bbcfac91a57.png)

Is this expected? This is within a Jekyll static site.

**Comment by gettalong** [comment]
Your hashes for the heading are indented, i.e. even when wrapping kramdown text within HTML tags you need to start at the left side because indentation is important.

**Comment by robbiejaeger** [comment]
Ah, ok - I see that now. I was imagining the markdown as child elements in the section, which led me to want to nest them. Thank you for the quick response!
