### ISSUE TITLE
Unable to use custom Rouge formatter for highlighting

### ISSUE THREAD

**Issue by ashmaroli** [gettalong/kramdown#617]
Given that I have the following configuration:
```yaml
syntax_highlighter_opts:
  formatter: HTMLTable
```
However when I try to convert a code-block, I get the following error:
```
private method `format' called for #<Hash:0x000000000601f440>
```
On bisecting, the issue occurs due to the following:
https://github.com/gettalong/kramdown/blob/2ff9d43f660460e8f6b14624af0adc50731eaa41/lib/kramdown/converter/syntax_highlighter/rouge.rb#L33

The reason being that `Rouge::Formatters::HTMLTable` should be constructed by passing another "formatter" instance:
```ruby
Rouge::Formatters::HTMLTable.new(Rouge::Formatters::HTML.new, opts)
```

**Comment by gettalong** [comment]
It seems that the formatter subclasses don't share a common constructor interface. Some need the options, some another formatter, some yet another thing...

Any suggestions? The only way to solve this seems to be to specify the formatter as class and not as string.

**Comment by ashmaroli** [comment]
I did take this issue up [to Rouge](https://github.com/rouge-ruby/rouge/issues/1218)'s maintainers themselves, but there hasn't been a response till date.

> Any suggestions?

I would recommend to implement an *adapter* of sorts. But not sure, if that lies within the scope of `kramdown`. So, left it as is..

**Comment by gettalong** [comment]
The problem with the adapter route is that if a formatter takes another formatter, which one should it take?

**Comment by ashmaroli** [comment]
The basic idea is to emulate the implementation for [`Rouge::Formatters::HTMLLegacy`](https://github.com/rouge-ruby/rouge/blob/917b39d68de62296059623e6d532ef10f8fe734c/lib/rouge/formatters/html_legacy.rb#L27-L37)
That class is unofficially deprecated for Rouge. They told me that it wouldn't get updated to handle newer formatters.

**Comment by daenney** [comment]
I just ran into this issue trying to use `HTMLLinewise` from Jekyll. I'm curious if it's at all possible?

> Any suggestions? The only way to solve this seems to be to specify the formatter as class and not as string.

This seems to suggest it should already be possible, or am I misunderstanding the comment?

**Comment by gettalong** [comment]
@daenney I really can't remember why I wrote what you quoted but since the formatter class is first resolved, regardless of whether it is specified as class or string, and only then an object instantiated, it won't be possible in this way.

Writing an adapter would work but I don't want to complicate things on kramdown's end when rouge can do that better.

So as @ashmaroli said: We are leaving this as it is for now and see what rouge does.

**Comment by gettalong** [comment]
@ashmaroli @daenney I don't think that rouge will do something about this. So on kramdown's end I will document the requirements for the formatter option of rouge and the user will need to make sure that s/he provides a correct (wrapper) class.
