### ISSUE TITLE
Adding accessible table headers with scope

### ISSUE THREAD

**Issue by injms** [gettalong/kramdown#618]
Would adding the ability to use `th scope="row"` and `th scope="col"` in tables be good for kramdown? 

The use of table headers and the `scope` attribute has the benefit of making tables more accessible for people who use assistive technology, such as screen readers.

This was [first suggested for Govspeak](https://github.com/alphagov/govspeak/issues/110), which uses kramdown as a dependency, and I've been tasked with making it work. Rather than implementing it for just Govspeak, I wondered if this would be something that would benefit kramdown?

To quote the issue raised on Govspeak:
> A good syntax for a new implementation [for table headers] (either via a kramdown extension or a govspeak hack) I would like to propose is to add a # after the pipe. Using a # would be intuitive as it's already used for headings. 

```markdown
|                 |# Second Column  |# Third Column       |
| --------------- | --------------- | ------------------- |
|# First row      | Cell            | Cell                |
|# Second row     | Cell            | Cell                |
```

The result would be:
```html
<table>
  <thead>
    <tr>
      <th> </th>
      <th scope="col">Second Column</th>
      <th scope="col">Third Column</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">First row</th>
      <td>Cell</td>
      <td>Cell</td>
    </tr>
    <tr>
      <th scope="row">Second row</th>
      <td>Cell</td>
      <td>Cell</td>
    </tr>
  </tbody>
</table>
```

Using the `|#` to show that the cell is a `th` also means that this feature shouldn't break any previously written tables - `| #` is interpreted as part of a the cell's content so would give `<td>#</td>`.

Is this something that people would find useful, and should I raise it in a pull request when this is working?

**Comment by gettalong** [comment]
I think it is a good idea in general but not for kramdown itself. The table syntax is meant for very simple tables only. Best way forward would be implementing it on govspeak's side.
