### ISSUE TITLE
Request to support File Transclusion

### ISSUE THREAD

**Issue by ClausKlein** [gettalong/kramdown#622]
[File Transclusion](https://fletcher.github.io/MultiMarkdown-5/transclusion.html)

File transclusion is the ability to tell MultiMarkdown to insert the contents of another file inside the current file being processed. For example:
```
This is some text.

{{some_other_file.txt}}

Another paragraph
```

**Comment by gettalong** [comment]
This is more a templating feature than a markup feature, so if you want such a functionality you should use a pre-processor like ERB to gain the needed functionality.

Alternatively, you could write your on parser class based on the kramdown parser that supports this feature.

**Comment by ClausKlein** [comment]
It is a github problem, they use kramdown AFAIK

see [factory_function.cpp](https://github.com/ClausKlein/samples/blob/master/Discussion.md#discussion-use-a-factory-function-if-you-need-virtual-behavior-during-initialization)

**Comment by gettalong** [comment]
Github uses a pipeline of transformation functions, with GFM being one of them. kramdown is only used by Github Pages (Jekyll).

Even if it were used on Github itself, this functionality belongs in a pre-processor.
