### ISSUE TITLE
Incorrect underscore handling after --- for em-dash

### ISSUE THREAD

**Issue by codingthat** [gettalong/kramdown#624]
An underscore-wrapped phrase immediately after a `---` renders plainly instead of in italics.

E.g. `it---by design---_cannot have side-effects_.` renders like this:

![image](https://user-images.githubusercontent.com/26723818/64153602-7c8e5c00-ce2f-11e9-8d59-ebfc993afef2.png)

But if you replace the latter `---` with `&mdash;`, it works as intended.

So  `it---by design&mdash;_cannot have side-effects_.` renders like this:

![image](https://user-images.githubusercontent.com/26723818/64153713-b65f6280-ce2f-11e9-8581-dca901f1bc98.png)

**Comment by gettalong** [comment]
Thanks for reporting this bug!

**Comment by ashmaroli** [comment]
@codingthat This should resolve by inserting spaces around the underscores:
```
it---by design--- _cannot have side-effects_.
```

**Comment by codingthat** [comment]
@ashmaroli Thanks, but not quite: That adds an undesired space between the latter em-dash and the word following it:

![image](https://user-images.githubusercontent.com/26723818/64964768-fdbc0900-d89b-11e9-9849-cc04ad49af14.png)

As you can see, this is different from the `&mdash;` workaround.

**Comment by codingthat** [comment]
Thanks @ashmaroli !  =)

**Comment by gettalong** [comment]
@codingthat I have merged the pull request by @ashmaroli, so I will close this issue.
