### ISSUE TITLE
Incorrectly escape \ and & in inline math

### ISSUE THREAD

**Issue by CptGit** [gettalong/kramdown#627]
Input:
`For example, $A = \begin{bmatrix}1 & 3 \\ 2 & 3 \\ 4 & 1\end{bmatrix}$.`

Expected ouput:
`<p>For example, $A = \begin{bmatrix}1 & 3 \\ 2 & 3 \\ 4 & 1\end{bmatrix}$.</p>`

Actual output:
`<p>For example, $A = \begin{bmatrix}1 &amp; 3 \ 2 &amp; 3 \ 4 &amp; 1\end{bmatrix}$.</p>`

Why does kramdown not preserve `\` and `&` in inline math? I know it does in math blocks.

Version: 2.1.0

**Comment by gettalong** [comment]
Inline math in kramdown is delimited by two dollar signs, see https://kramdown.gettalong.org/syntax.html#math-blocks.

Changing your example to

~~~
For example, $$A = \begin{bmatrix}1 & 3 \\ 2 & 3 \\ 4 & 1\end{bmatrix}$$.
~~~

results in

~~~ html
<p>For example, <script type="math/tex">% <![CDATA[
A = \begin{bmatrix}1 & 3 \\ 2 & 3 \\ 4 & 1\end{bmatrix} %]]></script>.</p>
~~~

**Comment by CptGit** [comment]
> Inline math in kramdown is delimited by two dollar signs, see https://kramdown.gettalong.org/syntax.html#math-blocks.
> 
> Changing your example to
> 
> ```
> For example, $$A = \begin{bmatrix}1 & 3 \\ 2 & 3 \\ 4 & 1\end{bmatrix}$$.
> ```
> 
> results in
> 
> ```
> <p>For example, <script type="math/tex">% <![CDATA[
> A = \begin{bmatrix}1 & 3 \\ 2 & 3 \\ 4 & 1\end{bmatrix} %]]></script>.</p>
> ```

Thanks a lot! :)
