### ISSUE TITLE
Kramdown Support for Assembly

### ISSUE THREAD

**Issue by Merikanto** [gettalong/kramdown#632]
Hello,

Does Kramdown support syntax highlight for assembly?

I tried the keywords "asm", "x86asm", "armasm", and none of them works.

Thanks!

**Comment by gettalong** [comment]
kramdown itself doesn't do any syntax highlighting, it delegates this task to {Rouge](https://github.com/rouge-ruby/rouge) - please ask there!

**Comment by Merikanto** [comment]
Thanks!
