### ISSUE TITLE
HTML tag inside code block escaping incorrectly

### ISSUE THREAD

**Issue by jlsucar** [gettalong/kramdown#633]
The following Markdown is being rendered incorrectly by kramdown:

```
require 'kramdown'
  
text = %q(<table>
<tr>
<td>
<code>
    Input name of true model trajectory file;
    <cr> for perfect_output.nc
</code>
</td>
</tr>
</table>

This is additional text. *Some markdown stuff*.)

p(Kramdown::Document.new(text).to_html)
```

Note that <cr> is NOT meant to be an HTML tag but is meant to be escaped code (in this case, for a carriage return).

Kramdown returns the following:

```
<table>
<tr>
<td>
<code>
    Input name of true model trajectory file;
    <cr> for perfect_output.nc\n
&lt;/code&gt;
&lt;/td&gt;
&lt;/tr&gt;
&lt;/table&gt;

This is additional text. *Some markdown stuff*.
</cr></code></td></tr></table>
```

There are two reasonable things to do:

1) Escape the <> characters. From this markdown, Github generates the following HTML, which is desired: 

```
<table>
<tr>
<td>
<pre><code>
Input name of true model trajectory file;
&lt;cr&gt; for perfect_output.nc
</code>
</pre>
</td>
</tr>
</table>
<p>This is additional text. <em>Some markdown stuff</em>.</p>
```

2) Don't escape the <cr> which is what raw HTML does. In this case, <cr> would simply not show up as it is an invalid HTML tag. This would be acceptable.

```
<table>
<tr>
<td>
<pre><code>
    Input name of true model trajectory file;
    <cr> for perfect_output.nc
</code>
</pre>
</td>
</tr>
</table>

<p>This is additional text. <em>Some markdown stuff</em>.</p>
```

But what kramdown is doing is certainly a bug that causes the rest of the page to be escaped as code within the table.

**Comment by gettalong** [comment]
Your issue text is missing characters. Please provide a copy-able sample input text (just the input, no ruby code) so that I can reproduce the problem - thank you!

**Comment by jlsucar** [comment]
Hi @gettalong, thanks for looking into this.

The complete contents of my minimal-example markdown file is the following (from <table> to *Some markdown stuff*):

```
<table>
<tr>
<td>
<code>
    Input name of true model trajectory file;
    <cr> for perfect_output.nc
</code>
</td>
</tr>
</table>

This is additional text. *Some markdown stuff*.
```

Is that sufficient?

**Comment by gettalong** [comment]
Okay, thanks. It seems that you are using an unclosed tag `<cr>` inside the HTML part. You either need to close the tag somewhere or properly escape the angle brackets so that the HTML part is actually valid HTML.

**Comment by jlsucar** [comment]
Thanks @gettalong . So do you think that escaping all following tags and putting them in the table is the correct behavior for kramdown when an unescaped/unterminated HTML tag is encountered?

**Comment by gettalong** [comment]
When the `<cr>` tag is encountered, kramdown searches for a closing tag `</cr>` or another start tag/self-closed tag. However, there is none until the end of the document, only some odd closing tags like `</code>` that are not expected and are therefore escaped. Finally, on document end the HTML tree structure is properly closed (even if no valid end tags are found) to provide valid HTML output.

Since you provide invalid HTML input, you get some not expected but at least valid output (and it is easy to spot the problem). Relying on failure modes of certain HTML parsers to escape `<cr>` is not a good idea. Just provide valid HTML to avoid this situation.

**Comment by jlsucar** [comment]
Okay, thanks for your time @gettalong ! We will properly escape these "tags" in the code.
