### ISSUE TITLE
kramdown can't render a formula in some cases.

### ISSUE THREAD

**Issue by HugueLiu** [gettalong/kramdown#635]
kramdown can't render a formula properly which contains `}_  _{`, such as `${a}_1$ $b_{2}$`. It should be like this under normal conditoins.
![image](https://user-images.githubusercontent.com/18070541/71518308-2d43ce00-28ed-11ea-82b2-0007c9465064.png)
But It's like this in Jekyll.
![image](https://user-images.githubusercontent.com/18070541/71518335-4ea4ba00-28ed-11ea-89ca-8552b1ec184f.png)
The version of kramdown in 2.1.0. 

```md
# test

<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML" type="text/javascript"></script>
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
            displayMath: [['$$','$$']],
            inlineMath: [['$','$']],
        },
    });
</script>

$abc$

${a}_b - a_{b}$
```
For a markdown file above, it looks like this in chrome  after rendering by kramdown using `kramdown test.md`.

![image](https://user-images.githubusercontent.com/18070541/71537633-c01a5200-2959-11ea-95c2-520221c69145.png)

But It works  in other markdown editors like Markdown Preview Enhanced in VScode which also use Mathjax. So It should not be caused by Mathjax.

**Comment by gettalong** [comment]
You need to use two dollar signs for inline math in kramdown, ie. `$${a}_1$$ $$b_{2}$$`. Then it will work:

~~~ html
<p><script type="math/tex">{a}_1</script> <script type="math/tex">b_{2}</script></p>
~~~
