### ISSUE TITLE
Math conversion does not allow for linebreaks

### ISSUE THREAD

**Issue by the-rccg** [gettalong/kramdown#640]
Using Kramdown on GitHub-Pages, the conversion of math linebreaks dows not happen properly. 
Namely,  `$a + b = c \\ d + e = f$` does not create a linebrea, the \\ is still present in the markdown and html files in the end.

**Comment by gettalong** [comment]
Could you please provide a full example file with the current output and the output you think would be correct?

**Comment by gettalong** [comment]
@the-rccg I will close this issue since you didn't provide the needed information. However, as far as I know, you have to put a real line break after `\\` in LaTeX code so that it gets converted to a line break.
