### ISSUE TITLE
ToC generation?

### ISSUE THREAD

**Issue by seamusdemora** [gettalong/kramdown#643]
I noticed a [pull request re ToC generation](https://github.com/gettalong/kramdown/pull/641).

This is a feature I would like to use on my GFM documents. I've searched for it twice now ( a couple of months ago & earlier today) and cannot find any documentation or examples that cover it. 

If this is a feature of kramdown, could you please point me to the documentation, or some usage examples?

**Comment by gettalong** [comment]
Please see https://kramdown.gettalong.org/converter/html.html#toc for information on table on contents for HTML output.

**Comment by seamusdemora** [comment]
Sorry to be thick, but I was looking for a ToC that can be used in a GFM document. Apparently there's no way to generate a ToC in GFM?

**Comment by gettalong** [comment]
GFM is only a parser. If you have a GFM document that is parsed with kramdown, the standard HTML converter is used to produce the output. So with the following input:

~~~
# test

# test2

* toc
{:toc}
~~~

you get this output

~~~ html
<h1 id="test">test</h1>

<h1 id="test2">test2</h1>

<ul id="markdown-toc">
  <li><a href="#test" id="markdown-toc-test">test</a></li>
  <li><a href="#test2" id="markdown-toc-test2">test2</a></li>
</ul>
~~~

Meaning the TOC generation works as expected.
