### ISSUE TITLE
Backticks (```) do not generate data-lang on code blocks

### ISSUE THREAD

**Issue by benknoble** [gettalong/kramdown#645]
Copied from https://github.com/jekyll/jekyll/issues/8040, as they said it was an upstream issue.

## My Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Operating System | macOS 10.14.5 |
| `jekyll`         | Latest   |
| `github-pages`   | Latest   |

---

## Expected Behaviour

When enclosing code in triple backticks and specifying a language (<code>```lang</code>), I expect `data-lang` attributes to be generated, similar to using <code>{% highlight lang %}</code> but without the tedium.

## Current Behavior

What's actually generated: 

```
<div class="language-bash highlighter-rouge">
<div class="highlight">
<pre class="highlight">
<code>
...
```

I would prefer `data-lang="bash"` on one of these (`pre` or `code` if possible), rather than this approach. Again, using `{% highlight lang %}` "solves" this, but is not ideal. An example of this is found in, e.g., the source of [this site](https://www.bytedude.com/jekyll-syntax-highlighting-and-line-numbers/#language-display), which mentions using this attribute. (If this is a rouge issue, according to [https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll](https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll), I'm already using it rouge.)

## Code Sample

I'm using [benknoble/benknoble.github.io](https://github.com/benknoble/benknoble.github.io) for examples; any language-specific code block will do.

**Comment by gettalong** [comment]
Thank you for opening this issue!

Why would you want a `data-lang` attribute? Is there an official standard concerning this attribute as is with [class `language-LANG`](https://www.w3.org/TR/html52/textlevel-semantics.html#the-code-element)?

**Comment by benknoble** [comment]
@gettalong 

> Is there an official standard concerning this attribute

There appears to have been a practice, whether or not there was a standard: see the site I linked (and many others like it) which rely on it.

> Why would you want a data-lang attribute?

I would want it because I can grab the value in CSS with `attr()`. AFAIK, there isn't an easy way to do that with a class `language-LANG`—or at least, not with CSS. I'm sure JS could do it, but I don't want to write some custom JS to grab all the languages and create new DOM elements for each page (jQuery could do it, but I don't need it otherwise and don't want the bloat). With CSS, it's as easy as a `::before` and `content: attr('data-lang')`.

Again, as far as I can tell, this is what *used* to be done, and I can't figure out how to make it happen for me now. Worse, other folks (like the site I mentioned) seem to be making it work, but I don't know what markup/hosting they're using. With GitHub pages, I'm tied to Kramdown + Rouge (which I'm fine with). And I'm partial to triple backticks, because the `{% highlight lang %}` is a pain to type.

**Comment by gettalong** [comment]
I'm reluctant to add duplicate information. You can use the `[attr~=value]` selector to easily select nodes with a certain `language-LANG` class. A quick search reveals [this Q/A](https://stackoverflow.com/questions/34005627/css-content-substring-function) containing a small Javascript snippet for displaying some part of an attribute.

I look at the bytedude link - he thinks that rouge generates the `data-lang` attribute. However, I searched the source code for rouge and didn't find any reference to such an attribute. Maybe Jekyll did it some time ago?

If you really need the `data-lang` attribute, the best way forward would be to create a custom HTML converter for your use case. Or convince the Jekyll maintainers to implement it.

**Comment by benknoble** [comment]
Odd—jekyll basically said they don't do it, relying entirely on kramdown for the MD->HTML generation.

I don't want to only select certain classes, I want the language on any that have it :) slightly different problem.

I'll poke around in rouge and see if they used to do it.

**Comment by gettalong** [comment]
Since Jekyl uses kramdown they could modify the output of the HTML converter in any way they like, after kramdown did the MD->HTML conversion. This is what many tools using kramdown do.

**Comment by gettalong** [comment]
@benknoble See https://github.com/gettalong/webgen/blob/master/lib/webgen/content_processor/kramdown.rb for an example on how kramdown can be tightly integrated into a static website generator to provide additionally needed features (in case of webgen overriding link generation to use webgen's facilities).
