### ISSUE TITLE
Extreme slowdown on missing space after mail link

### ISSUE THREAD

**Issue by stgm** [gettalong/kramdown#647]
We have a document that takes forever to parse, because the author forgot to insert a space after an e-mail link. Have a look at the first link right below the `## Contact` heading in this document:

https://github.com/uva/ci/blob/67a288280e9f301664d4ae967ea7a4d8acd90654/info/Studiewijzer.md

It looks like this:

    Stuur een mail naar <progik@mprog.nl>stel een vraag

I noticed that the parser takes noticeably longer even when I cut off the document just 10-20 characters after that link. The more characters that follow the missing space, the longer the parser takes. For the whole document, it took 25 seconds to parse :-)

We're on the Kramdown 2.1.0 gem in a Rails project.

**Comment by gettalong** [comment]
I'm sorry, the link you gave says "404 not found" but I could reproduce the problem using your example and adding content after it. And it seems that the problem quickly escalates....

**Comment by gettalong** [comment]
So it seems that problem is the regex for detecting the link, will see what I can do about it.

**Comment by gettalong** [comment]
I looked at the regex. It tries to match an email address with some restrictions. However, if one uses `mailto:...`, then no such restrictions are checked. Therefore I will just relax the regex to allow a more arbitrary string of the form `...@...`.

**Comment by gettalong** [comment]
Fix will be in the next release!

**Comment by stgm** [comment]
Thanks, very cool! :-)
