### ISSUE TITLE
mathjax 3 compatibility

### ISSUE THREAD

**Issue by opeltre** [gettalong/kramdown#651]
Kramdown's output is not compatible with mathjax 3's defaults!

The `<script type="tex/math">` tags are not parsed anymore, although it was the recommended 
output in v2 :bomb: 

Having a markdown parser go along with mathjax can be a real mind breaker and it is a __huge relief__ that kramdown does its job at protecting equations properly. 

It took me a day to identify the problem and it turns out it's all mathjax's fault. 

Until an eventual fix, I still think it would be much appreciated, and save math users a lot of time, if kramdown advertised on this issue in its docs:  
- [kramdown + mathjax](https://kramdown.gettalong.org/math_engine/mathjax.html) should really mention this
- [math syntax](https://kramdown.gettalong.org/syntax.html#math-blocks) should also precise that kramdown does not ship with a math engine and link to the above page

I'd say this is all the more called for as the mathjax docs are completely uneatable, and the internet is full with misleading, outdated similar threads!

**Comment by opeltre** [comment]
Here are the [mathjax API changes](http://docs.mathjax.org/en/latest/upgrading/v2.html#changes-in-the-mathjax-api) one may run into after a lot of web wandering (last bullet). 

One could have math rendered with kramdown by including a distribution of mathjax __2__. If only. The cdn script tag for v2 I pasted from their landing page didn't work. 

To use mathjax __3__, one should include _before_ loading the mathjax script this complicated configuration object, which essentially supplies the function looking for the script tag v2 used. 
```
MathJax = {
  options: {
    renderActions: {
      find: [10, function (doc) {
        for (const node of document.querySelectorAll('script[type^="math/tex"]')) {
          const display = !!node.type.match(/; *mode=display/);
          const math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
          const text = document.createTextNode('');
          node.parentNode.replaceChild(text, node);
          math.start = {node: text, delim: '', n: 0};
          math.end = {node: text, delim: '', n: 0};
          doc.math.push(math);
        }
      }, '']
    }
  }
};
```
Hoping you will highlight these problems in the docs, 
Cheers!

**Comment by opeltre** [comment]
See also https://github.com/mathjax/MathJax/issues/2220

**Comment by gettalong** [comment]
This is already fixed in https://github.com/gettalong/kramdown/commit/c3acf8df1db49d2456050f4456f3f542294e2e8f and will be part of the next release. You could try the repository version of kramdown to see if that works for you.
