### ISSUE TITLE
Fenced Code blocks not coloring correctly

### ISSUE THREAD

**Issue by bannsec** [gettalong/kramdown#657]
I've been running into a weird situation where it appears kramdown is overriding my declaration of `python` to be `sql`. Trying to recreate it, it seems to happen in very specific situation.

Example:

The following uses (tilda, tilda, tilda python)

```python
from revenge import Process, common, types
p = Process("./pwn_constraint")

# Grab the function you want to call
func = p.memory["pwn_constraint:0x12cf"]

# Since this modifies in memory, allocate a string ahead of time
mem = p.memory.alloc_string(types.StringUTF8("ABCDEFG"))

# Run the string
func(mem.address)
# 70

# Read what it got permuted into
mem.string_utf8
# 'CEGAFBD'
```

Markdown on github parses this just fine, but my kramdown using rogue ends up declaring it "class="hljs sql"". If you remove the "Since this modifies" comment, then it will highlight it correctly as python again.

Since I'm explicitly declaring it python, i don't see why it should ever end up being highlighted as SQL.

**Comment by gettalong** [comment]
Please provide a complete sample input file that shows the problem.

**Comment by bannsec** [comment]
I'm rather new to kramdown and in my case building through jekyll, so not sure what all you need.

Here's the rendered jekyll page: https://bannsecurity.github.io/writeups/2020/04/29/patriotctf-2020-rev-give-nom-nom/
Here's the source: https://github.com/BannSecurity/BannSecurity.github.io/blob/master/_posts/2020-04-29-patriotctf-2020-rev-give-nom-nom.md

Any config that I'm using would be up a directory and in `_config.yml` i'm guessing?

**Comment by gettalong** [comment]
If I run your example code block through `kramdown -x parser-gfm -i GFM`, I get the correct output with `language-python` on the first line.

So it doesn't seem to be a kramdown problem. Please try your kramdown documents with just kramdown, for example, via the command line. If there is still a problem, I will re-open the issue.
