### ISSUE TITLE
Valid IDs

### ISSUE THREAD

**Issue by ioquatix** [gettalong/kramdown#658]
Hello.

HTML5 allows any character to be an ID.

So:

```
# Thing {#Bake-Types-self.Any}
```

should be valid.

**Comment by gettalong** [comment]
If we change this, I would make the ID [XML-compatible](https://html.spec.whatwg.org/multipage/infrastructure.html#xml) so that the XML syntax of HTML5 is also supported - what do you think?

**Comment by ioquatix** [comment]
I think that's fine.

What's the implications of making it XML-compatible? I couldn't tell from the linked documentation. My understanding HTML5 basically allows any character. I assume except `#`?

**Comment by gettalong** [comment]
Yes, HTML5 allows any character. However, there is also an XML syntax version of HTML5 (formerly known as XHTML) which might have a problem with that (didn't find anything on that, though).

The XML syntax has a special ID type with certain allowed values. I have changed kramdown to allow all characters that are also allowed for this ID type. See https://www.w3.org/TR/xml/#id and https://www.w3.org/TR/xml/#NT-Name.

**Comment by gettalong** [comment]
Implemented in https://github.com/gettalong/kramdown/commit/90954bc4916153d5ad03dc3538b243c48e24a9d1

**Comment by ioquatix** [comment]
Great, thanks for your quick response!
