### ISSUE TITLE
Configurable TOC with absolute URLs.

### ISSUE THREAD

**Issue by rbprogrammer** [gettalong/kramdown#666]
Would it be possible to have a configuration property (currently I'm using Jekyll) such that the generated TOC links have absolute URL paths?  The use case for this is when the layout uses the `<base href="..."/>` tag the generated TOC links no longer work.  Possibly a config option like: `toc.anchors.absolute: true|false`?

For example, if a Markdown document under `articles/subdirectory/mytopic.md` looked something like this:

```markdown
---
layout: default
---

* TOC
{:toc}

# Heading One
## Subheading One
# Heading Two
```

With the `default.html` layout as:

```html
<!doctype html>
<html>
<head>
    <base href="{{ site.baseurl | relative_url }}"/>
</head>
<body>
{{ content }}
</body>
</html>
```

The current behaviour generates page-local links, as one might expect.

- `<a href="#heading-one">Heading One</a>`
- `<a href="#subheading-one">Subheading One</a>`
- `<a href="#heading-two">Heading Two</a>`

However, if my Jekyll config contains a base url like: `baseurl: http://mysite.example.com/`, then the problem is the resulting links do not contain the full paths to the file.  The links become:

- `<a href="http://mysite.example.com/#heading-one">Heading One</a>`
- `<a href="http://mysite.example.com/#subheading-one">Subheading One</a>`
- `<a href="http://mysite.example.com/#heading-two">Heading Two</a>`

These links do not include any sub-directories between the site's root and the generated HTML from the Markdown.  Based my Markdown example above, I would have expected the links to take me to:

- `<a href="http://mysite.example.com/articles/subdirectory/mytopic.html#heading-one">Heading One</a>`
- `<a href="http://mysite.example.com/articles/subdirectory/mytopic.html#subheading-one">Subheading One</a>`
- `<a href="http://mysite.example.com/articles/subdirectory/mytopic.html#heading-two">Heading Two</a>`

I do not think what I am proposing should be the default behaviour.  The default behaviour should remain with page-local links, like Kramdown already generates.

My current _hack_ is to write some extra Javascipt that fixes the links after the page loads.  This is a bit of a hack since the code is fixing something every time a user accesses the site.  When I feel like the problem should be fixed when the site is built (when Kramdown converts MD to HTML).

I could do a fork+PR, but I wanted to first see if there was any appetite for something like this. (and selfishly if someone had the time to implement this faster than I :)

P.S. forgive me for being dim if this, or something like this, has been proposed before.  Or if I can solve my problem in a different way that Kramdown already supports.  I tried looking for previous GH Issue but didn't quickly find anything quite like this problem.

**Comment by gettalong** [comment]
Your problem is not caused by kramdown itself but by the tool that uses kramdown, ie. Jekyll.

Why would you want to put something like `http://mysite.example.com/` into the `<base>` tag? This would only be valid for files in the root directory but not in a sub-directory, if I read the documentation for it correctly.

I.e. if you have a file `http://mysite.example.com/subdir/myfile.html` and you want to link to `test.html` in the same sub-directory with a relative link `[link to test.html](test.html)`, it will be a wrong, dangling link! So this problem should also affect all relative links, not just in-page anchors.

Be that as it may, it is not kramdown's job to mangle links. If you want to specially process links, you should writer a custom HTML converter that does that. See, for example, the [custom HTML converter used by webgen (another static website generator)](https://github.com/gettalong/webgen/blob/master/lib/webgen/content_processor/kramdown.rb#L22).

**Comment by rbprogrammer** [comment]
I suppose a more general description of my use case is that all of my Markdown documents have relative references assuming the root can change.

For example, I have a private repo on GitLab that when I deploy to GitLab Pages it has a different URL than my second hosting site which is an internal company server.  One website, one code base, but hosted in two different places.  I need the `<base ...>` tag since the site hosting on GitLab Pages will have the root under a subdirectory.

I agree Kramdown's job is not to mangle links, but in the case of the ToC it is generating broken links.  What is generated is just not compatible with standard HTML when a base-tag is used..  Which is why I thought fixing Kramdown was the better approach.

**Comment by gettalong** [comment]
Hmm...

> I agree Kramdown's job is not to mangle links, but in the case of the ToC it is generating broken links. 

I don't think that this is correct: If we need to create an URL referring to an ID element on the page itself, we need to create a fragment URL as kramdown currently does. Since kramdown doesn't know the output file name nor the full URL of the page, this is the only way to go.
