### ISSUE TITLE
Blockquote tags

### ISSUE THREAD

**Issue by thromeaway** [gettalong/kramdown#669]
It seems like Blockquotes arent parsed correctly in jekyll. I have to put `</blockquote>` in a new line as it turns out as `&lt;/blockquote&gt;` elsewise. The other Tags around it like` <p>` and` </p> `get parsed correctly. Im not using any Plugins except defaults. Im also not sure if its an issue of how kramdown was used in jekyll or in kramdown in general:

https://github.com/jekyll/jekyll/issues/8197

**Comment by gettalong** [comment]
This is probably correct behaviour as far as kramdown is concerned, see https://kramdown.gettalong.org/syntax.html#html-blocks

Can you show an example that doesn't work for you?
