### ISSUE TITLE
```mermaid --> figure

### ISSUE THREAD

**Issue by fulldecent** [gettalong/kramdown#683]
Please allow

    ```mermaid

blocks to be rendered as

    <figure class="language-mermaid">

or some other configurable options, rather than the current

    <pre><code>

**Comment by gettalong** [comment]
Just a note: The ```` ``` ```` syntax is not supported in kramdown, only then `~~~` syntax.

If you need support for mermaid rendering, please write a custom syntax highlighter that does this. See https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/syntax_highlighter.rb for details. And/Or have a look at [the existing ones](https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/syntax_highlighter.rb).

You can then wrap your custom implementation in a Ruby gem and use it where you need it. See https://github.com/kramdown/syntax-coderay for such an example.
