### ISSUE TITLE
`refdef` space in documentation

### ISSUE THREAD

**Issue by AlexWayfer** [gettalong/kramdown#684]
Hello.

I've found `{: refdef}` in the [documentation](https://kramdown.gettalong.org/quickref.html#block-attributes).

It's incorrect: `{:refdef}` renders properly.

**Comment by gettalong** [comment]
Hm... I can't verify this because

~~~
{:refdef: .c1 #id .c2 title="title"}

paragraph
{: refdef}
~~~

renders as

~~~ html
<p class="c1 c2" id="id" title="title">paragraph</p>
~~~

which is how it should be.

Why do you think it renders incorrectly? Can you provide an example?

**Comment by AlexWayfer** [comment]
Sorry, I don't know what was wrong, I have an exact example, but now it's not reproducible. Sorry for bothering you.
