### ISSUE TITLE
Stash default options in a constant / memoized variable

### ISSUE THREAD

**Issue by ashmaroli** [gettalong/kramdown#685]
Currently when a Document is parsed and converted, the _default options hash_ are freshly generated:
https://github.com/gettalong/kramdown/blob/84e305c87c3f9c4926031e83fefde3c883e919cb/lib/kramdown/parser/base.rb#L54
https://github.com/gettalong/kramdown/blob/84e305c87c3f9c4926031e83fefde3c883e919cb/lib/kramdown/converter/base.rb#L102
https://github.com/gettalong/kramdown/blob/84e305c87c3f9c4926031e83fefde3c883e919cb/lib/kramdown/options.rb#L76-L79
https://github.com/gettalong/kramdown/blob/84e305c87c3f9c4926031e83fefde3c883e919cb/lib/kramdown/options.rb#L69-L74

When numerous Documents, say about 1000, are parsed and converted in a single process, there's a high probability of about 2k temporary hash objects getting allocated.

## Suggestion

Since `Options.merge` invariably generates a new Hash, it would be nice if the default options were a single object for the entire duration of the process.

**Comment by gettalong** [comment]
As can be seen in the last of your snippets, the `Kramdown::Options.defaults` method creates a new hash. You propose to make this method always return the same hash, am I right?

If we would do this, we would need to create a new hash in `Kramdown::Options.merge`:

~~~ ruby
    def self.merge(hash)
      temp = defaults
      hash.each do |k, v|
        k = k.to_sym
        temp[k] = @options.key?(k) ? parse(k, v) : v
      end
      temp
    end
~~~

As you can see, the first line just uses the return value of `::defaults`. Later in the method that hash is *modified* by assigning values to keys.

This means if we don't create a new hash in `::defaults`, we would need to use `#dup` in `::merge`. I don't see how we could avoid this.

**Comment by ashmaroli** [comment]
> This means if we don't create a new hash in `::defaults`, we would need to use `#dup` in `::merge`.

Yes, I realize the need to generate a new Hash object.

>  I don't see how we could avoid this.

I actually prefer using `Hash#dup` in `::merge` if the result is absolutely the same because then there wouldn't be repeated iteration through `@options` with additional computations in the enumerator's block only to return the same Hash
(contents-wise) repeatedly.

**Comment by gettalong** [comment]
Ah, thanks, yes, this makes sense. If we go this way, we will need to clear the cached value if new option definitions are added later on. I will let this sink in and do the appropriate changes in the next few days.

**Comment by ashmaroli** [comment]
Thank you very much :)

**Comment by gettalong** [comment]
Took a bit longer than a few days but is implemented now and will be in the next release.
