### ISSUE TITLE
div style spills out after div

### ISSUE THREAD

**Issue by csaid** [gettalong/kramdown#686]
I'm noticing that div style spills out into text after the `</div>` whenever markdown mode is on.

```
This text is not italicized.

<img src="https://i.imgur.com/EJOjIMC.jpeg">
<div style="font-style:italic" markdown="1"> My italicized figure caption </div>

This text should not be italicized either, but it is.
```

The issue only goes away if I set `markdown="0"`. However, I would like to be able to process markdown inside a `<div></div>`

I'm on Kramdown 2.3.0, as it is included in the latest version of Github Pages.

Thanks

**Comment by chrissaid** [comment]
Here's what gets produced:
```
<p>This text is not italicized.</p>

<p><img src="https://i.imgur.com/EJOjIMC.jpeg" /></p>
<div style="font-style:italic">
  <p>My italicized figure caption &lt;/div&gt;</p>

  <p>This text should not be italicized either, but it is.</p>
</div>
```

**Comment by chrissaid** [comment]
Update: I've solved my problem: I need needed to put the <div> tags on their own separate lines.

```
<div style="font-style:italic" markdown="1">
My italicized figure caption
</div>
```
This behavior seems surprising to me. Not sure if this counts as user error or not.

**Comment by gettalong** [comment]
Yes, this is expected behaviour, see https://kramdown.gettalong.org/syntax.html#html-blocks, the second list item "Parse as block-level elements:".
