### ISSUE TITLE
Question: how to automatically convert URLs into clickable links

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [gettalong/kramdown#691]
GFM automatically converts URLS, such as this: (https://google.com) into clickable links. Kramdown, however, does not. That would just remain plain text. Is it possible to set a setting to make Kramdown automatically convert these links into clickable links? 

Here's where Kramdown is being used (for a Jekyll website): https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml#L183

**Comment by gettalong** [comment]
No, there is no option to do that. However, you can surround the links with angle brackets, i.e. `<https://google.com/>`, see https://kramdown.gettalong.org/syntax.html#automatic-links. This should work with *all* Markdown parsers, making your document more portable.
