### ISSUE TITLE
Can't figure out how to correctly style code blocks in PDF output

### ISSUE THREAD

**Issue by jvacek** [gettalong/kramdown#697]
Hey there, I'm trying to basically render some notes for my courses from markdown and I'd like to have syntax-highlighted `java` blocks.

Right now, everything is basically colour-less and not indented properly. 

I'm mirroring the repo to github from the school git instance, which means that the actual pipelines run from this file https://github.com/jvacek/OS2md/blob/master/.gitlab-ci.yml

There is a config file in the root of the repo too, which from the following output I suppose is being ingested correctly..?

![image](https://user-images.githubusercontent.com/1302278/104076440-64460280-5216-11eb-8cf7-47e9c924d48d.png)

Currently, my PDFs render into this for example [week1.md-k.pdf](https://github.com/gettalong/kramdown/files/5789820/week1.md-k.pdf)
 
Any help or pointers would be appreciated!

**Comment by gettalong** [comment]
The PDF converter is just a very basic implementation, without support for syntax highlighting. If you need that functionality, you would need to extend the converter and implement it yourself.
