### ISSUE TITLE
Kramdown doesn't convert HTML tags to markdown if they contain leading or trailing whitespace

### ISSUE THREAD

**Issue by dvandersluis** [gettalong/kramdown#698]
If an HTML span element (`b`, `strong`, `em`, etc.) contains leading or trailing whitespace, Kramdown will not convert it to markdown, even with `html_to_native: true`:

```ruby
Kramdown::Document.new('<b> test </b>', html_to_native: true).to_kramdown
=> "<b> test </b>\n\n"
Kramdown::Document.new('<b>test </b>', html_to_native: true).to_kramdown
=> "<b>test </b>\n\n"
Kramdown::Document.new('<b> test</b>', html_to_native: true).to_kramdown
=> "<b> test</b>\n\n"
Kramdown::Document.new('<b>test</b>', html_to_native: true).to_kramdown
=> "**test**\n\n"
```

Only the final example, where both sides of the inner string are stripped, gets converted into markdown.

**Comment by gettalong** [comment]
The reason for this is that the em/strong markers need to be followed/preceded by whitespace as per the [syntax specification]*https://kramdown.gettalong.org/syntax.html#emphasis). If we were to convert the cases in your example, you wouldn't get the correct result when converting to HTML again.

**Comment by dvandersluis** [comment]
Would there maybe be a way to do it optionally? We’re using kramdown to convert HTML where any leftover HTML is unexpected and breaks, so I’ve had to write code to parse the html first and strip the tags, but it’d be preferable to have it all happen at once IMO.

**Comment by gettalong** [comment]
The way forward in such a case is that you subclass the kramdown converter and provide your own logic. In kramdown proper it makes no sense because, as I said before, the resulting kramdown document would not convert back to the same HTML.
