### ISSUE TITLE
Inline links changing to reference links

### ISSUE THREAD

**Issue by kalpitad** [gettalong/kramdown#699]
Either the default parser or the Kramdown converter is changing inline links into reference links. This seems to happen only when the URL protocol is included (e.g. https) as in Example 2 and not Example 1 below. I need inline links to stay as inline links and cannot seem to find a config option to turn it off. Is this possible?

Example 1:
```
puts "======================"
puts Kramdown::Document.new("The **quick** _grey_ dog napped on the [moon](www.google.com). And then he said: woof, woof, bark.", {input: 'markdown'}).to_kramdown
puts "======================"
```
Outputs:
```
======================
The **quick** *grey* dog napped on the [moon](www.google.com). And then
he said: woof, woof, bark.

======================
```

Example 2:
```
puts "======================"
puts Kramdown::Document.new("The **quick** _grey_ dog napped on the [moon](https://www.google.com). And then he said: woof, woof, bark.", {input: 'markdown'}).to_kramdown
puts "======================"
```
Outputs:
```
======================
The **quick** *grey* dog napped on the [moon][1]. And then he said:
woof, woof, bark.



[1]: https://www.google.com
======================
```

Thank you!

**Comment by gettalong** [comment]
This was a design decision when implementing the kramdown converter. If a link starts with `https?` it is generally very long and therefore it makes sense to use a reference link for it. Also, the internal AST has no notion of whether the link was created through the inline link or reference link syntax. So one needs to decide what to output in the kramdown converter.

If you need special handling for this, I recommend subclassing the converter and implementing the behaviour you need.

**Comment by kalpitad** [comment]
Thank you! I subclassed the Kramdown converter and it works well.
