### ISSUE TITLE
Incorrect smart quotes convert

### ISSUE THREAD

**Issue by sakkamade** [gettalong/kramdown#700]
Hello. I'm using jekyll and noticed that the quotes following directly after hyphen `-` render improperly.

**Examples**
```
"word-"  =>  “word-“  |  instead for “word-”
'word-'  =>  ‘word-‘  |  instead for ‘word-’

or just 
"-"  =>  “-“
'-'  =>  ‘-‘ 
```

**Comment by gettalong** [comment]
The smart quotes feature is just a very basic implementation which only covers the standard use case of (English) sentences. There are many such corner cases which are not handled well/correctly.
