### ISSUE TITLE
blockquotes shouldn't require a leading blank line

### ISSUE THREAD

**Issue by snan** [gettalong/kramdown#702]
Neither Gruber's Markdown, nor CommonMark, require leaving a leading blank line before blockquotes. Same goes for here on GitHub.

So you can do email style.

My friend wrote:
> some text to me
> the other day

This is [an option in pandoc](https://github.com/jgm/pandoc/issues/7069) (should've been default).

**Comment by gettalong** [comment]
This is a design decision to allow line wrapping of text without the fear of changes to the output. If the blank line is not required there would be the possibility that a `>` would end up at the start of a line (eg. when writing math like `5000 > 399`), leading to a block quote where none should be.
