### ISSUE TITLE
Blank code span inconsistency

### ISSUE THREAD

**Issue by cabo** [gettalong/kramdown#704]
```
$ kramdown
` `

a ` `
^D
<p><code> </code></p>

<p>a ` `</p>
```

**Comment by gettalong** [comment]
From the syntax spec: *"A single backtick surrounded by spaces is treated as literal backtick."*. This is the reason why the second example shows only backticks. 

As for the first example: No backtick is surrounded by whitespace because the first one is at the start of the line and the last one at the end. However, I *think* for consistency the first example should also be converted to `<p>` `</p>` - what do you think?

**Comment by cabo** [comment]
This was surprising to at least one user.
I believe the commonmark spec also allows code spans that are spaces only:
https://spec.commonmark.org/0.29/#code-spans

Anyway, picking up on the "single backtick" language, let's try a double backtick then:

```
$ kramdown
a `` ``
^D
<p>a <code></code></p>
```

This would do it for me, but the space goes away (a *pair* should go away, but then not for codespans that are solely spaces).

**Comment by gettalong** [comment]
If multiple backticks are used for code spans, a single space right after the opening backticks and right before the closing backticks are removed. So if you use:

~~~
``   ``
~~~

you will get

~~~
<p><code> </code></p>
~~~

**Comment by cabo** [comment]
There weren't two spaces to be removed, so why are you removing the one that is there?  :-)
The commonmark spec also makes an exception for spans that are entirely made up of spaces.

**Comment by gettalong** [comment]
The rule is just: If there is a space after the opening backticks, remove it. Then if there is one before the closing backticks, remove it. This is always done, so it doesn't depend on what exactly is inside the code span.

**Comment by gettalong** [comment]
I will update the parser so that the start of a line is also treated as whitespace. So for ``` ` ` ``` at the start of line the first backtick is then also surrounded by whitespace and therefore treated as text.

**Comment by gettalong** [comment]
The change mentioned in https://github.com/gettalong/kramdown/issues/704#issuecomment-787058282 will be in the next release.
