### ISSUE TITLE
Automatically add rel="footnote" to footnote links

### ISSUE THREAD

**Issue by xplosionmind** [gettalong/kramdown#706]
Hello, I have [a Jekyll website](https://github.com/xplosionmind/tommi.space "tommi.space") which uses kramdown as the default Markdown parser. I noticed that a footnote link contains code like the following:
```html
<sup id="fnref:1" role="doc-noteref">
    <a href="#fn:1" class="footnote">1</a>
</sup>
```

<br />

I believe that, in order to comply with [the semantic HTML philosophy](https://dev.to/eevajonnapanula/ode-to-semantic-html-38c3 "Ode to Semantic HTML - DEV"), it would be really important to ad to the generated `a` tag the `rel="footnote"` attribute:
```html
<sup id="fnref:1" role="doc-noteref">
    <a href="#fn:1" class="footnote" rel="footnote">1</a>
</sup>
```

<br />

Furthermore, in modern and developed RSS readers, if the `rel=footnote` attribute is present, the footnote is clickable and displayed as a pop-up window; in other words, it is better recognized and implemented.

Would it be possible to add this feature?

<br />

Thank you very much!   
Best,   
T

**Comment by gettalong** [comment]
This is documentedThanks for opening the issue! I will have to read up on `rel="footnote"` to give you an answer on whether we can/will add this feature.

**Comment by gettalong** [comment]
I think that this change is okay and I will add it to the next release.

**Comment by xplosionmind** [comment]
> I will add it to the next release.

This is awesome!   
Thank you very much for your work. I love kramdown!

Best,   
T
