### ISSUE TITLE
Highlighting single word within markdown code block

### ISSUE THREAD

**Issue by awa5114** [gettalong/kramdown#707]
I am trying to highlight a single word in a code block generated by `kramdown`. For reasons not worth explaining here, I would like to do this by explicitly embedding the html `span` element within the code block in the markdown file. The `kramdown` [docs][1] appear to support embedding html inside block and span level markdown but I can't quite seem to get this work. Here is my `content.md` markdown file:
    
    ~~~
    def <span style="color: red;" markdown="span">function</span>():
    	print('hello')
    ~~~

Once I compile using `kramdown content.md>content.html` on a windows machine, I expect to get the following:

    <pre><code>def <span style="color: red;" markdown="span">function</span>():
    	print('hello')
    </code></pre>

However what I get instead is something like this:
    
    <pre><code>def &lt;span style="color: red;" markdown="span"&gt;function&lt;/span&gt;():
    	print('hello')
    </code></pre>

Which is not what I want. I have tried using the `markdown` attribute with all of `"0"`, `"1"`, `"span"` and `"block"` as  values to no avail. What am I missing here?

  [1]: https://kramdown.gettalong.org/syntax.html#html-spans

**Comment by gettalong** [comment]
Code blocks and code spans are *always* parsed as verbatim text. So any special HTML characters inside them will be properly escaped. This means that you can't embed any HTML in them.

The exception to this rule is when a syntax highlighter is used since then the syntax highlighter defines how to handle the verbatim contents. So if you need such a functionality you could write a custom syntax highlighter.

**Comment by awa5114** [comment]
@gettalong thanks for your response. Would you please point to some resources which would enable me to write such a custom highlighter? Would be curious to see the level of effort required...

**Comment by gettalong** [comment]
@awa5114 A syntax highlighter can be as minimal as https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/syntax_highlighter/minted.rb which is a highlighter for use with LaTeX output.

For a more complex example have a look at https://github.com/kramdown/syntax-coderay which implements a syntax highlighter for coderay.
