### ISSUE TITLE
b tags are not parsed when there is a space in block

### ISSUE THREAD

**Issue by mwitek** [gettalong/kramdown#709]
Hello, I noticed an issue with `<b>` tags.  When a tag has space before the opening or closing tag, it does not covert properly. 

example:
```
require 'kramdown'
html = "<b>This one does not have a space</b> <b> This has a space after open tag</b> <b>This has a space before closing tag </b>"
doc = ::Kramdown::Document.new(html, input: "html")
doc.to_kramdown

=> "**This one does not have a space** <b> This has a space after open tag</b> <b>This has a space before closing tag </b>"
```

**Comment by gettalong** [comment]
This is correct behaviour since the conversion would lead to ` ** This...`, i.e. two asterisk surrounded by whitespace which can't be converted back to HTML.
