### ISSUE TITLE
HTML entities in hyperlink text

### ISSUE THREAD

**Issue by SomeWeekendReading** [gettalong/kramdown#710]
I'm using kramdown as the default markdown engine in jekyll.  Normally it renders entities correctly, even obscure ones like the capital Greek digamma (&Gammad; which in some fonts looks vaguely like a Roman capital F).  However, when the &Gammad; is part of a link, it does not.

__Example input:__ [spirit of &Gammad;&Tau;&Phi;](...url...)
__HTML output:__ <a href="...url...">spirit of &amp;Gammad;ΤΦ</a>

Note here that it has output the &Tau; and &Phi; entities as characters, but has escaped the ampersand in &Gammad; causing it not to render.

Live example on the web [here](https://www.someweekendreading.blog/pi-day/), near the bottom of the page.

Is jekyll perhaps using an older version by default?

**Comment by gettalong** [comment]
The reason for this is that the `Gammad` entity is not recognized by kramdown. I will fix this for the next release.

In the meantime you can do the following:

~~~
require 'kramdown/utils'
Kramdown::Utils::Entities::ENTITY_TABLE << [988, 'Gammad']
~~~

This adds the entity to the table where kramdown looks it up.

**Comment by SomeWeekendReading** [comment]
Thanks; that makes sense.  Maybe pick up all the legal HTML entities, if any others are missing?

**Comment by gettalong** [comment]
I have added `Gammad` and `gammad`. Another commit already added many HTML5 entities.
