### ISSUE TITLE
Broken code block + bold rendering after Github pages update to kramdown 2.3.1

### ISSUE THREAD

**Issue by ailin-nemui** [gettalong/kramdown#713]
Hi,

our Github Pages website was just broken slightly by the kramdown 2.3.1 update. We have the following code:

```
{:#completion_auto}
` completion_auto` **`OFF`**
```

Previously (kramdown 2.3.0 as used by github-pages 213), it was rendered (correctly) as

```
completion_auto OFF
```

but now it renders as
```
` completion_auto **OFF`**
```

Do you have any advice?

Reference to our page/sources:
https://irssi.org/documentation/settings/ 
https://github.com/irssi/irssi.github.io/tree/master/documentation/settings.markdown

**Comment by gettalong** [comment]
See https://github.com/gettalong/kramdown/issues/704 - This was an intentional change to make the behaviour more consistent.

If you need that space inside the code span, please use two backticks.

**Comment by ailin-nemui** [comment]
it does not match the rendering on github, which is a pity

**Comment by gettalong** [comment]
Github doesn't use kramdown for rendering but a different Markdown engine and Markdown dialect. It is expected that there are differences because there is no Markdown standard.
