### ISSUE TITLE
Producing valid HTML5 from details/summary blocks

### ISSUE THREAD

**Issue by pdmosses** [gettalong/kramdown#715]
When using the 'parse_block_html' option, kramdown converts `<summary>` blocks to invalid HTML5:

```sh
echo "<details>\n<summary>text\n</summary>\ntext\n</details>" | kramdown --parse_block_html
```
produces:
```html
<details>
  <summary>
    <p>text</p>
  </summary>
  <p>text</p>
</details>
```

<img width="633" alt="Screenshot" src="https://user-images.githubusercontent.com/18308236/116518402-7a182a00-a8d0-11eb-9a2b-11992ca0c4ae.png">

The kramdown documentation for [HTML blocks](https://kramdown.gettalong.org/syntax.html#html-blocks) doesn't mention how `<details>` and `<summary>` blocks are treated. The default conversion for `<summary>` should not produce invalid HTML5.

Kramdown converts the following blocks to valid HTML5 (independently of the 'parse_block_html' option):

```markdown
<details markdown="1">
  <summary markdown="span">
    Summary *text*
  </summary>
  - Details
</details>

<details markdown="1">
  <summary markdown="1">
# Summary *heading*
  </summary>
  - Details
</details>
```

When using the 'parse_block_html' option, kramdown converts also the following example correctly to HTML5:
```markdown
<details>
  <summary>
# Summary *heading*
  </summary>
  - Details
</details>
```

# Details

Using kramdown 2.3.1.

<details>
<summary>
Invalid HTML5
</summary>

```sh
echo "<details>\n<summary>Summary *text*\n</summary>\n- Details \n</details>" | kramdown --parse_block_html
```
produces:
```html
<details>
  <summary>
    <p>Summary <em>text</em></p>
  </summary>
  <ul>
    <li>Details</li>
  </ul>
</details>
```
</details>

<details>
<summary>
Valid HTML5
</summary>

```sh
echo "<details>\n<summary markdown='span'>Summary *text*\n</summary>\n- Details \n</details>" | kramdown --parse_block_html
```
and
```sh
echo "<details markdown='1'>\n<summary markdown='span'>Summary *text*\n</summary>\n- Details \n</details>" | kramdown
```
produce:
```html
<details>
  <summary>Summary <em>text</em>
</summary>
  <ul>
    <li>Details</li>
  </ul>
</details>
```

Also
```sh
echo "<details>\n<summary>\n### Summary heading\n</summary>\n- Details \n</details>" | kramdown --parse-block-html
```
produces:
```html
<details>
  <summary>
    <h3 id="summary-heading">Summary heading</h3>
  </summary>
  <ul>
    <li>Details</li>
  </ul>
</details>
```
</details>

<details>
<summary>
Unparsed content
</summary>

```sh
echo "<details markdown='block'>\n<summary markdown='span'>\n### Summary heading\n</summary>\n- Details \n</details>" | kramdown
```
produces:
```html
<details>
  <summary>
### Summary heading
</summary>
  <ul>
    <li>Details</li>
  </ul>
</details>
```
</details>

<details>
<summary>
Parsed content
</summary>

```sh
echo "<details markdown='block'>\n<summary markdown='1'>\n### Summary heading\n</summary>\n- Details \n</details>" | kramdown
```
produces:
```html
<details>
  <summary>
    <h3 id="summary-heading">Summary heading</h3>
  </summary>
  <ul>
    <li>Details</li>
  </ul>
</details>
```
</details>

When using details/summary tags on GitHub, it appears that the summary text is unparsed, and using heading tags produces poor layout. See also #155 and this [gist](https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f#lists).

**Comment by gettalong** [comment]
I guess this is rather hard to get right because the complex HTML content model can't be mapped to the simple content model in kramdown.

In this case, phrasing content *and* headers are allowed for `<summary>` tags. So if kramdown parses the content as span-level content, the example with `### heading` won't work. And if it parses the content as block-level content, the example with `some *em* text` won't work due to this being wrapped in a paragraph.

So either avoid `parse_block_html` or use the "markdown" attribute on `<summary>` appropriately.
