### ISSUE TITLE
Rendering GFM-documented emojis

### ISSUE THREAD

**Issue by SomeWeekendReading** [gettalong/kramdown#716]
I'm using kramdown as the default markdown engine in a blog generated by Jekyll.  For the most part, I'm sticking to Github-flavored Markdown (GFM) and that seems to be reasonable.

[GFM advertises certain emojis as being available](https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md), but some experiments show that kramdown does not render them.  In particular, I've been trying to use some flag icons for a blog post about language translation: :jp:, :fr:, :india:, :it:, :cn:, :ru:, :greece:, :romania:.  They get rendered as text.

There's an example in a blog post [here](https://www.someweekendreading.blog/google-translate-review/#assessments-by-native-speakers).

I realize emojis are pretty silly and may not be a priority.

**Comment by gettalong** [comment]
Please open an issue at https://github.com/kramdown/parser-gfm/issues - thanks!

**Comment by SomeWeekendReading** [comment]
Done.
