### ISSUE TITLE
Abbreviations are destroyed by line breaks

### ISSUE THREAD

**Issue by cabo** [gettalong/kramdown#717]
Input:

``` markdown
*[foo bar]: baz

hello foo bar babble.

hello foo
bar babble.
```

Output:

``` html
<p>hello <abbr title="baz">foo bar</abbr> babble.</p>

<p>hello foo
bar babble.</p>
```

This is bad if the markdown author uses a line-breaking editor.

**Comment by cabo** [comment]
The abbreviation scanner also doesn't like non-breaking spaces inside the abbreviation.

It should accept any kind of whitespace.

**Comment by gettalong** [comment]
Thanks for the issue!

I have now implemented this in kramdown (see commit 9ac9402), using your work-around as basis. The implementation should be backwards-compatible as far as I can determine (i.e. converters don't need to be changed).

**Comment by cabo** [comment]
Thank you! 

Looking forward to the impending release...

**Comment by gettalong** [comment]
Yes :) Release comes probably tomorrow.
