### ISSUE TITLE
Accessibility: incorrect use of ARIA role="doc-noteref"

### ISSUE THREAD

**Issue by LouiseSteward** [gettalong/kramdown#719]
PR #646 refers.

According to the Digital Publishing WAI-ARIA Module 1.0 [documentation](https://www.w3.org/TR/dpub-aria-1.0/#doc-noteref), `role="doc-noteref"` should be applied to a superclass of type `link` (i.e. the `<a>` in the footnote ref) rather than to the `<sup>`. 

This error has been picked up using the [axe](https://www.deque.com/axe/) extension for Chrome, as well as using [Ace by DAISY](https://daisy.github.io/ace/) on EPUBs.

**Comment by gettalong** [comment]
This is implemented and will be in the next release.
