### ISSUE TITLE
Can't apply inline attribute to markdown <li>

### ISSUE THREAD

**Issue by dabrahams** [gettalong/kramdown#730]
Say you have an `<ol>` ordered list of 3 items in markdown, and you want to add a `.class` to the middle one.  There's no way to use an IAL to do that, because it has to appear on a line following the element, and that ends up breaking up the markdown into two `<ol>`s.  Maybe there should be a rule that an IAL at the end of a line can apply to the inner block generated by that line or something.

**Comment by gettalong** [comment]
You mean something like this:

~~~
1. First item
2. {:.class} second item
3. Third item
~~~

Output:

~~~ html
<ol>
  <li>First item</li>
  <li class="class">second item</li>
  <li>Third item</li>
</ol>
~~~

**Comment by dabrahams** [comment]
Oh, cool; that should be documented!  Now is there a way to attach attributes to the `<code>` tag generated for this (or heck, the `<pre>` tag or the inner `<div>` that rouge wraps it in)?

    ```c++
    // Does the fragment get applied to pre or code?
    ```

**Comment by gettalong** [comment]
It is documented, see https://kramdown.gettalong.org/syntax.html#lists at the end of that heading, before the "Definition Lists" heading.

If you are using triple tildes for pre tags, the IAL is applied to the pre tag:

~~~~~
$ kramdown --syntax-highlighter nil
~~~
~~~
{:.cls}
^D
<pre class="cls"><code>
</code></pre>
~~~~~

If you are using a syntax highlighter, it is assigned to the outermost div tag:

~~~~~
$ kramdown
~~~ ruby
x = Class.new
~~~
{:.cls}
<div class="language-ruby cls highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">x</span> <span class="o">=</span> <span class="no">Class</span><span class="p">.</span><span class="nf">new</span>
</code></pre></div></div>
~~~~~

In the above cases you need to use a CSS sub-selector like `.cls code` or `.cls .highlight` to process the tags you want.

**Comment by dabrahams** [comment]
Thanks!
