### ISSUE TITLE
Can't specify footnote location

### ISSUE THREAD

**Issue by jajmo** [gettalong/kramdown#731]
Using Jekyll & kramdown, the footnote placement [test file](https://github.com/gettalong/kramdown/blob/8efa9c30c45014442970d5976dd0e0005682edf3/test/testcases/span/04_footnote/placement.text) puts the footnotes at the bottom of the page, and ignores the `{:footnotes}` marker.

**Comment by gettalong** [comment]
Please try with kramdown alone. If this is still a problem, I will re-open. Otherwise Jekyll is doing something and you need to ask there.

**Comment by jajmo** [comment]
It does appear to be a jekyll-specific issue. Appreciate the fast response.
