### ISSUE TITLE
Unable to decode HTML entities

### ISSUE THREAD

**Issue by asbjornu** [gettalong/kramdown#734]
I want to convert HTML to plain text within a Kramdown plugin I'm making and I'm unable to get HTML entities decoded no matter what I do. Here's one of many things I've tried:

```ruby
html = "<h1>&amp; &gt; &lt;</h1>"
doc = Kramdown::Document.new(html, input: :html, entity_output: :as_char)
puts doc.to_kramdown # Outputs: # &amp; &gt; &lt;
```

I expected the output to be `# & > <` and not `# &amp; &gt; &lt;`. What am I doing wrong here?

**Comment by gettalong** [comment]
If you still want to implement this, please go ahead and provide a pull request. I will close this issue now.
