### ISSUE TITLE
latex warning causing test failure with newer texlive

### ISSUE THREAD

**Issue by boutil** [gettalong/kramdown#744]
Hi,

In Debian, we got the following report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1002115
caused (I think) by an upgrade of texlive from a version in 2021/09 to 2021/11.

Looking more closely, it appears when the test `test_files.rb` treats the latex conversion of `tests/testcases/man/example.text`. The non UTF-8 character appears when compiling the text converted to latex in the following "missing character"
```
LaTeX Warning: Command \l invalid in math mode on input line 134.

Missing character: There is no � in font cmr10!
```
which was possibly not printed before. It is triggered by the fact that on line 83 of `example.text`, the command `\l` is not a correct math latex command (at least without previous definition).
Would you consider changing to simply `l` or `\lambda`, it it does not change the purpose of the test?

Thanks!

**Comment by gettalong** [comment]
Thanks for the report - I have changed `\l` to `\lambda`.

I will try to get a release out soon-ish.
