### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [gettalong/kramdown#745]
Hey there!

I belong to an open source security research community, and a member (@ltpordh27) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by gettalong** [comment]
I have set up a policy. Tl;dr: Contact me at <t_leitner@gmx.at> - thanks!

**Comment by JamieSlome** [comment]
@gettalong - amazing, thanks for the quick response! ⚡ 

You should receive an e-mail from us within the next 24 hours with a magic URL that allows you to view the report without having to sign-up.

Otherwise, you can view the report directly here:
https://huntr.dev/bounties/c86353a6-1563-41fa-b350-0cb7f9c741ce/

It is private and only accessible to you! 👍
