### ISSUE TITLE
Weird backslash insertion in kramdown writer

### ISSUE THREAD

**Issue by cabo** [gettalong/kramdown#751]

**Comment by cabo** [comment]
``` 
$ kramdown -o kramdown << HERE
AA: foo

*[AA]: bar
HERE
```

➔ 

```
AA\: foo

*[AA]: bar
```

I can't find the code that does this backslash insertion.
The inserted backslash is stable over further `kramdown -o kramdown` sequences, but other processors don't like a backslash there (i.e., show it).

**Comment by gettalong** [comment]
The backslash insert is done here: https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/kramdown.rb#L78-L80

I think the code should actually read:

~~~ ruby
          end.gsub(/\s+/, ' ').gsub(ESCAPED_CHAR_RE) do
            $1 || !opts[:prev] || opts[:prev].type == :br ? "\\#{$1 || $2}" : $&
          end
~~~

But have to think a bit more about it.

**Comment by cabo** [comment]
Ah.  I now understand the bug.

```
$ kramdown -o kramdown <<HERE
a:

*a*:

a*:*
HERE

➔

a:

*a*\:

a*\:*
```

So the code is trying to protect against spuriously generating definition lists?
But `^[ ]{0,3}(:)` is matching against the text item, so starting a new text item with a ":" triggers the backslash.
Instead, it needs to see whether the text item starting with a ":" lands on a new line on the *output*.

**Comment by cabo** [comment]
Couldn't a ":" start a new line in `convert_p` with :line_width set?

Yep:

```
kramdown -o kramdown <<HERE | kramdown
aa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa : aa aaaa aaaa aaaa
HERE

➔ 

<dl>
  <dt>aa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa aaaa</dt>
  <dd>aa aaaa aaaa aaaa</dd>
</dl>
```

It's really not that easy to generate markdown...

**Comment by cabo** [comment]
I'd probably do this two-pass:

1. generate markdown, but output a special sentinel instead of `: ` for the dt
2. * convert all leading `:` to `\:` and
   * convert all sentinels to `: `

**Comment by gettalong** [comment]
@cabo The latest commit contains the fixes for the bugs.

**Comment by cabo** [comment]
I can report that the fix works for my use case.  Thank you!

**Comment by cabo** [comment]
Now what I need is a release so this bug fix trickles into a few production servers...

**Comment by gettalong** [comment]
@cabo Will do when I have time, probably on the weekend

**Comment by gettalong** [comment]
@cabo Release follows shortly
