### ISSUE TITLE
Add support for `<mark>`?

### ISSUE THREAD

**Issue by jaredcwhite** [gettalong/kramdown#754]
Hello folks. I worked on adding custom support for highlighting text with `either ::double colons:: or ==double equals==` which converts to `<mark>` tags, but thought I'd raise the issue here if that's something Kramdown would like to add natively. It's something a lot of Markdown editors support, and it's super useful IMHO.

More info here: https://github.com/bridgetownrb/bridgetown/pull/551

**Comment by gettalong** [comment]
Hmm... I have never seen this syntax, so am unsure if this would be a good addition. Furthermore, adding a new syntax would break backwards compatibility, so this would only be possible in a new major version.

**Comment by jaredcwhite** [comment]
Thanks for the reply @gettalong — I figured it'd be something that maybe could arrive eventually…under no illusion that's anytime soon. 😄

**Comment by gettalong** [comment]
Since this would require a major version and the benefits of the syntax are doubtful, this feature should be implemented in a custom parser/converter.
