### ISSUE TITLE
<figcaption markdown="1"> escapes closing tags after backticks...

### ISSUE THREAD

**Issue by codingthat** [gettalong/kramdown#757]
Hi everyone!  Thanks for developing the lovely kramdown tech.  :)

I'm trying to include some kramdown within a `<figcaption>` element, because nesting it within a kramdown'd `<figure>` isn't sufficient:

```
<figure markdown="1">

~~~ cs
// some code here
~~~

<figcaption>My Caption With Inline `BackTicks`</figcaption>
</figure>
```

This renders as:

![image](https://user-images.githubusercontent.com/26723818/170967205-9de02b69-ad58-44e5-b322-71f4f631b7c9.png)

But if we add `markdown="1"`:

```
<figure markdown="1">

~~~ cs
// some code here
~~~

<figcaption markdown="1">My Caption With Inline `BackTicks`</figcaption>
</figure>
```

...something breaks, as it doesn't seem to close off either element correctly:

![image](https://user-images.githubusercontent.com/26723818/170967441-4d3a957b-985d-486c-bfa4-a32957f8cea2.png)

Turns out it's because it's escaping the closing tags for some reason:

```
<figcaption>
    <p>My Caption With Inline <code>BackTicks</code>&lt;/figcaption&gt;
&lt;/figure&gt;</p>
```

Now, I thought it might be because it's two `markdown="1"` elements nested within each other, but if I use `div` and `span` instead of `figure` and `figcaption`, it works fine:

```
<div markdown="1">

~~~ cs
// some code here
~~~

<span markdown="1">My Caption With Inline `BackTicks`</span>
</div>
```

![image](https://user-images.githubusercontent.com/26723818/170968110-92659a4c-06a8-4226-b250-d96255af8934.png)

So it's specific to `figcaption`.

**Comment by gettalong** [comment]
The `<figcaption>` element may contain any flow content items, so also paragraphs, headers and such. Therefore it is marked in kramdown as being an element containing block elements and the rule for such HTML block elements is that the closing tag needs to be on a separate line:

~~~~~
<figure markdown="1">

~~~ cs
// some code here
~~~

<figcaption markdown="1">My Caption With Inline `BackTicks`
</figcaption>
</figure>
~~~~~

Alternatively, you can use `markdown='span'` to force handling the contents as inline contents.
