### ISSUE TITLE
diff is not work if i add a languge name

### ISSUE THREAD

**Issue by qiudaoermu** [gettalong/kramdown#763]
```diff js
++ i' am apple
-- i' am apple
```

<img width="279" alt="image" src="https://user-images.githubusercontent.com/13454418/187175481-a9e74937-5483-4292-ada2-983bd85ed4bb.png">

**Comment by gettalong** [comment]
Please provide more details (e.g. whether and how this works with rouge) and don't use three exclamation marks.

**Comment by qiudaoermu** [comment]
if i add js after diff, the code color don't change in kramdown, but it  works in github markdown.

**Comment by gettalong** [comment]
Github doesn't use kramdown, so you can't compare them. kramdown uses rouge syntax highlighter behind the scenes and therefore only supports those language names that are available there. Please ask there how to do what you want.
