### ISSUE TITLE
latex error with /testcases/block/04_header/with_auto_ids.text

### ISSUE THREAD

**Issue by boutil** [gettalong/kramdown#770]
Hi,

With a very recent version of latex, I see a test failure with the testcase `block/04_header/with_auto_ids.text`. The latex file produced is
```
\documentclass{scrartcl}

\usepackage[utf8x]{inputenc}

\usepackage[T1]{fontenc}
\usepackage{listings}

\usepackage{hyperref}





\setcounter{footnote}{0}

\hypersetup{colorlinks=true,urlcolor=blue}

\begin{document}
\section*{This is a header}

\subsection*{12. Another one-1-here}

\subsubsection*{Do \^{}\& it now}

\section*{Hallo}

\subsection*{Not now}

\section*{Hallo}

\section*{23232}

\section*{33333}

\subsection*{hallO}

\section{Header without ID}\hypertarget{}{}\label{}

\section*{Transliterated: Đây-là-ví-dụ}


\end{document}

```
which seems correct. When compiled with pdflatex 3.141592653-2.6-1.40.24 (TeX Live 2022/Debian), I get the following error
```
[...]
! LaTeX Error: Unicode character ụ (U+1EE5)
               not set up for use with LaTeX.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
```
There were no issue with versions of latex from Texlive 2021 and earlier.
Let me know if you need more information.

**Comment by boutil** [comment]
Something which is certainly relevant to the issue at hand: the log says
```
(/usr/share/texlive/texmf-dist/tex/latex/ucs/utf8x.def
  File: utf8x.def 2022/08/07 UCS: Input encoding UTF-8
  
  
  Package ucs Info: utf8x disabled, assuming standard utf8 processing
  (ucs)             load ucs package to force utf8x processing.
```
apparently, since August of this year, utf8x falls back to standard utf8 inputenc, which might be the reason for the change of behaviour.

**Comment by gettalong** [comment]
I'm not entirely sure how to make this test case work. Since this is not a kramdown issue itself (the user provided LaTeX document template needs to address this), I have blacklisted that single test.
