### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by andrewtbiehl** [gettalong/kramdown#771]
Hi! I was wondering if there is interest in enabling [the GitHub Discussions feature](https://docs.github.com/en/discussions) for this project, or if an alternative forum already exists for starting conversations about this project that aren't strictly issues.

My own interest for doing this is admittedly a bit self-serving. I would love to share a Kramdown plugin that I recently built with the larger community, but I don't want to abuse GitHub's Issues feature or anything else to do so.

If this is not possible, no worries! Regardless, thanks for an awesome and extensible tool!

**Comment by gettalong** [comment]
Show work now!
