### ISSUE TITLE
html_to_native: use normal links instead of reference-style links

### ISSUE THREAD

**Issue by collimarco** [gettalong/kramdown#775]
I need to convert some HTML to markdown.

I use `html_to_native: true`, however the links are all listed at the bottom of the page instead of inline.

Is it possible to have normal, inline links without foot notes?

**Comment by gettalong** [comment]
See https://github.com/gettalong/kramdown/blob/master/lib/kramdown/converter/kramdown.rb#L291-L306 - some links are converted to inline but not all (e.g. full URLs are always converted to reference style links). This is currently not configurable.
