### ISSUE TITLE
Pure Ruby PDF converter based on prawn

### ISSUE THREAD

**Issue by gettalong** [gettalong/kramdown#78]
I'm currently investigating how much effort it would take to create a pure Ruby PDF converter based on the [prawn](http://prawn.majesticseacreature.com) PDF library.

Any input, ideas, etc. are appreciated, especially on the following items:
- Expectations for such a converter
- How to handle customization of individual element output?
- Other libraries than prawn that are better suited for this task
- Is there need for such a converter?

**Comment by arivero** [comment]
![image](https://user-images.githubusercontent.com/43174/154158587-58b153b5-ba24-42dd-bc7d-1b65560b64e7.png)

**Comment by arivero** [comment]
The documentation pages imply that a direct pdf output is already envisioned, is it?

**Comment by gettalong** [comment]
On 2022-02-15 22:16 +0000 Alejandro Rivero wrote:
> The documentation pages imply that a direct pdf output is already
> envisioned, is it?

Yes, there is already kramdown-converter-pdf, see
https://github.com/kramdown/converter-pdf. It is currently unmaintained
but functional.
