### ISSUE TITLE
handling `br` inside formatting tags

### ISSUE THREAD

**Issue by directionless** [gettalong/kramdown#780]
I'm trying to convert html to markdown. Playing with Kramdown, it's pretty cool. But, I found a bit of a corner case. If there are `br` tags inside formatting, it comes out a bit funny. Honestly I'm not really sure what correct should be, but:

```ruby
[78] pry(main)> Kramdown::Document.new('<h1>foo<br>bar</h1>', :input => 'html').to_kramdown
=> "# foo  \nbar\n\n"
```

**Comment by gettalong** [comment]
Thanks for the report! From a cursory look at it I think this is a bug in the HTML to AST conversion scheme.

**Comment by gettalong** [comment]
After having a more in-depth look at this, I have adapted the kramdown converter  to correctly handle such cases.
