### ISSUE TITLE
Code block language not parsing in details/summary following math expression

### ISSUE THREAD

**Issue by b0nes164** [gettalong/kramdown#785]
### Example:
<details open>
  
  <summary>
  A spoiler
  </summary>
  
```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```
</details>

$1 + 1 = 2$

<details open>
  
  <summary>
  A spoiler
  </summary>
  
```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```
</details>

### Raw markdown:
````
<details open>
  
  <summary>
  A spoiler
  </summary>
  
```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```
</details>

$1 + 1 = 2$

<details open>
  
  <summary>
  A spoiler
  </summary>
  
```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```
</details>
````

**Comment by gettalong** [comment]
Please provide a sample input document, the output when running it through the kramdown binary with your desired options, and the desired output - thanks!

**Comment by b0nes164** [comment]
I apologize, I thought that all kramdown was the primary parser for GitHub, not an option, so this issue isn't relevant for you.

But to give a  rundown for posterity, the problem is that once you make a LaTeX-like expression with the '$' symbol, code blocks within detail/summaries are no longer colored properly with respect to their language attribute.
