### ISSUE TITLE
Custom Parser Support

### ISSUE THREAD

**Issue by aahn33** [gettalong/kramdown#786]
Hey looking into customizing the parser that the Kramdown Document class uses to parse markdown to document format. Basically want to add new element types that the parser can parse when constructing the document. I saw that the parser in the document initialization method can be customized via the options, but the possible options are checked via the parser.rb file. Is adding a new parser that extends the kramdown parser a supported feature?

**Comment by gettalong** [comment]
Yes, you can do that and it is actually the recommended way to add features. See https://github.com/kramdown/parser-gfm/blob/master/lib/kramdown/parser/gfm.rb for an example.
