### ISSUE TITLE
Add an extension for parsing Mermaid syntax to the libraries extending the functionality of kramdown

### ISSUE THREAD

**Issue by 38tter** [gettalong/kramdown#788]
Hi, folks!
Currently I have been working on [kramdown-mermaid](https://github.com/38tter/kramdown-mermaid), an extension of kramdown for parsing [Mermaid](https://mermaid.js.org/) syntax, and now some of the syntax ([ER Diagram](https://mermaid.js.org/syntax/entityRelationshipDiagram.html) ) can be parsed with this extension.

Can I add this to the list of kramdown extensions below?

https://github.com/gettalong/kramdown/wiki/Libraries-extending-the-functionality-of-kramdown

**Comment by gettalong** [comment]
Sure!
