### ISSUE TITLE
Select whether an HTML tag is parsed as block or span level

### ISSUE THREAD

**Issue by EtienneMiret** [gettalong/kramdown#793]
According to the [WHATWG](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element), the `img` element is both [flow content](https://html.spec.whatwg.org/multipage/dom.html#flow-content) and [phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content). I might be wrong on that one, but I understand “flow content” from the WHATWG spec as meaning “block level” while “phrasing content” would be “span level”.

In any case, there is no doubt `img` elements are allowed as direct children of the `body` element. Which seems currently impossible to achieve with kramdown.

So, could that feature be added? I’m thinking about something like:

```md
<img alt="" src="foo" level="span"/>

<img alt="" src="foo" level="block"/>
```

that would translates to:

```html
<p><img alt="" src="foo"></p>

<img alt="" src="foo">
```

Also, I took `img` as an example, but I expect that new `level` attribute to work on any tag.

**Comment by gettalong** [comment]
You can already achieve this with kramdown:

~~~
{::nomarkdown}
<img alt="" src="foo" />
{:/}
~~~

will result in

~~~ html
<img alt="" src="foo" />
~~~

**Comment by EtienneMiret** [comment]
Oh, OK, cool! Not sure why I didn’t see that in the doc. Thank-you!
