### ISSUE TITLE
Void elements should not use trailing slashes.

### ISSUE THREAD

**Issue by Raza403** [gettalong/kramdown#795]
Trailing slashes on void elements [have no effect](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing) and [interact badly with unquoted attribute values](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-directly-preceded-by-unquoted-attribute-values). Suggest removing trailing slashes from void elements such as `img`, `hr`, or `br`.

**Comment by gettalong** [comment]
kramdown outputs valid XHTML, so the trailing slash is needed.

**Comment by fulldecent** [comment]
Related discussion for cross reference:

https://groups.google.com/g/kramdown-users/c/m8I_hHFALk0?pli=1
