### ISSUE TITLE
Can I remove the image parsing method?

### ISSUE THREAD

**Issue by clickworkorange** [gettalong/kramdown#800]
I've rolled my own Kramdown::Parser as a very restricted subset of the GFM parser, for use in a publicly accessible comment section, and it works very well. But the list of removable parser methods does not seem to include anything related to parsing of image markdown, which I also want to remove. Is this possible?

**Comment by clickworkorange** [comment]
Actually, I just realised my CSP will block external images anyway, so this isn't super important.

**Comment by gettalong** [comment]
Images are parsed with the same parser method as links, see https://github.com/gettalong/kramdown/blob/master/lib/kramdown/parser/kramdown/link.rb#L67
