### ISSUE TITLE
parse failure on empty tables

### ISSUE THREAD

**Issue by gsar** [gettalong/kramdown#802]
`Kramdown::Document.new('<table></table>', input: 'html').to_kramdown` provokes an `undefined method 'type'` error:

![image](https://github.com/gettalong/kramdown/assets/6981812/f2e63b0d-9d20-4572-a1eb-c39cb1409dbe)

**Comment by gettalong** [comment]
Thanks for reporting! I have fixed this - new version will be released within a week.
