### ISSUE TITLE
[bug] Kramdown converter fails with NoMethodError: undefined method `type' for nil

### ISSUE THREAD

**Issue by honzasterba** [gettalong/kramdown#809]
Steps to reproduce:

```ruby
html = File.read("example.html")
doc, = Kramdown::Parser::Html.parse(html)
Kramdown::Converter::Kramdown.convert(doc)
```

will submit a PR with a fix

**Comment by honzasterba** [comment]
Attaching the example HTML file

[example.html.zip](https://github.com/user-attachments/files/16279917/example.html.zip)

**Comment by gettalong** [comment]
This is fixed and will be in the next release.
