### ISSUE TITLE
While converting tables from mark down to html it adds an extra <td> which makes table distorted

### ISSUE THREAD

**Issue by saisivaram7299** [gettalong/kramdown#812]

**Comment by gettalong** [comment]
Please add an example - thank you!

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by gettalong** [comment]
Without more details from you I cannot work on this.
