### ISSUE TITLE
Output is mangled if HTML includes newlines inside a tag

### ISSUE THREAD

**Issue by fulldecent** [gettalong/kramdown#815]
Test case working:

```sh
bundle exec ruby -e 'require "kramdown"; puts Kramdown::Document.new("<i></i>").to_html' 
<p><i></i></p>
```

Test case failing:

```sh
bundle exec ruby -e 'require "kramdown"; puts Kramdown::Document.new("<i><\n/i>").to_html'
<p><i>&lt;
/i&gt;</i></p>
```

Please note that `<i></i>` is valid HTML, with or without the newline after the `<` in the closing tag. And Prettier which is a very popular software, running [in many projects' workflows](https://github.com/search?q=prettier+path%3A.github%2Fworkflows%2F*&type=code) by default will generate code like this. (It modifies HTML files for style reasons but keeps them semantically equivalent.)

*Originally reported at https://github.com/jekyll/jekyll/issues/9691*

**Comment by gettalong** [comment]
kramdown expects HTML to be formatted in a certain way. Many things that are allowed with HTML5 don't work with kramdown as kramdown is not a full HTML5 parser/processor. So if you use kramdown, you need to provide the input as kramdown expects it.
