### ISSUE TITLE
Incorrect comment parsing while in the middle of list

### ISSUE THREAD

**Issue by numberisnan** [gettalong/kramdown#818]
## Issue

Kramdown doesn't handle multi-line ```<!-- -->``` style comments properly while being included in the middle (or end) of a list. This particular situation arose when hiding items from a roadmap/todo list. 

The issue does not occur when the list markup is removed from any one of the visible and commented text in the below example.

## Instance
```markdown
- Bananas
<!--
- Apples
-->
```
#### Output (running ```kramdown test.md```)
```html
<ul>
  <li>Bananas
&lt;!–</li>
  <li>Apples
–&gt;</li>
</ul>
```
The commented item is clearly not hidden.
![image](https://github.com/user-attachments/assets/3cd4cd30-93b5-4073-b621-521c355c5cbd)
## Versions
kramdown: 2.4.0 (latest)
ruby: 3.0.2p107

#### Edit
- Simplified example

**Comment by gettalong** [comment]
You need to use the correct syntax, i.e. insert a blank line (otherwise the line with `<!--` is seen as continuation of the line with `Bananas`):

~~~ 
- Bananas

<!--
- Apples
-->
~~~
