### ISSUE TITLE
Advanced tables (colspan / rowspan / multi-paragraph)? 

### ISSUE THREAD

**Issue by Tuckie** [gettalong/kramdown#87]
Is colspan or rowspan supported?
Is there any way to make a multi-paragraph cell?

Or any ideas as to how we could go about adding it? (cell-level IAL?)

Tables are one of my remaining headaches preventing me from going going full markdown (no html).

**Comment by dolfandringa** [comment]
> A detailed tutorial about HTML Tables...[HTML Table help](http://www.corelangs.com/html/tables/default.html)
> 
> nick

Sorry, but he didn't ask about HTML tables. He even said that he was looking for a non-html solution.

**Comment by jeffreytse** [comment]
As we known, kramdown only supports simple tables with no block elements inside cells, no colspan/rowspan or anything else. We have to use an HTML table for more complex tables.

To support col-span and row-span even more table features, I think the below Jekyll plug can help you:

> jekyll-space - 🚀 A Jekyll plugin to provide powerful supports for table, mathjax, plantuml, etc.

[https://github.com/jeffreytse/jekyll-spaceship](https://github.com/jeffreytse/jekyll-spaceship)

**For now, these extended features are provided:**

* Cells spanning multiple columns
* Cells spanning multiple rows
* Cells text align separately
* Table header not required
* Grouped table header rows or data rows
