### ISSUE TITLE
Support Minted for LaTeX Code Block Conversion

### ISSUE THREAD

**Issue by gettalong** [gettalong/kramdown#93]
[from Rubyforge]

It's excellent that Kramdown already supports a solid, separate package like Listings for formatting code blocks whenconverting to LaTeX. However, I'd like to request that Minted be supported as well.

Minted uses the Pygmentize library for its conversion, and was built in response to some of the shortcomings of Listings.Tools like Emacs' Org mode provide a configuration option when exporting to LaTeX to choose between exporting code blocks as Listing environments or Minted environments.

Thank you for an excellent open source project.

**Comment by l3kn** [comment]
I would like to try my hand at this, but I am not sure what would be the best way.

Currently all converters in `converter/syntax_highlighter` seem to be html only.
Is there a way to guarantee a syntax_highlighter is called from the correct converter
(e.g. setting :syntax_highlighter to minted would not mess up html conversion)?

**Comment by gettalong** [comment]
That would be great!

No, there is currently no such provision. Providing a correct value to the syntax highlighter option is the job of the user.

However, I toying around with the idea of introducing mime types for the parsers and converters. If this is done, it should be possible to set a preferred syntax highlighter for a mime type instead of a specific converter.

So for the time being, this issue would just need a new syntax highlighter and the adaption of the LaTeX converter.

**Comment by l3kn** [comment]
I forked this repo and changed the LaTeX converter use the highlight_code function (like the html converter).

But this way running `kramdown test.md -o latex` without specifying a `--syntax-highlighter` falls back to the default highlighter (coderay) and outputs a mix of LaTeX and html.

The best fix I could come up with would be to add a optional constant
`SUPPORTED_CONVERTERS = [:Html] # or [:Latex, :Html, ...]`
to the syntax highlighters and let `converter.rb` check if the current converter is supported*.

Should I open up a pull request with this changes first?

*
``` ruby
add_syntax_highlighter(kn_down) do |converter, text, lang, type, opts|
  require "kramdown/converter/syntax_highlighter/#{kn_down}"
  klass = ::Kramdown::Utils.deep_const_get("::Kramdown::Converter::SyntaxHighlighter::#{klass_name}")
  converter_name = converter.class.name.split('::').last.to_sym # maybe use strings?
 
  # Use || because SUPPORTED_CONVERTERS should be optional
  supported = klass::SUPPORTED_CONVERTERS.nil? || klass::SUPPORTED_CONVERTERS.member?(converter_name)
    
  if klass::AVAILABLE && supported
    add_syntax_highlighter(kn_down, klass)
  else
    add_syntax_highlighter(kn_down) {|*args| nil}
  end
    syntax_highlighter(kn_down).call(converter, text, lang, type, opts)
end
```

**Comment by gettalong** [comment]
The problem with using a constant like `SUPPORTED_CONVERTERS` is that custom HTML converters can't be used anymore with the syntax highlighters. The mime type approach I mentioned would circumvent this problem but I have to think a bit more about this.

Until such a facility is ready I think the best option would be to allow the LaTeX converter to optionally use exactly one specific syntax_highlighter, namely the one for minted. I.e. when `syntax_highlighter` is `minted`, the LaTeX converter should use the highlighting facility and otherwise should do its default thing.

**Comment by gettalong** [comment]
Thanks for your contribution, the changes are now in master.
