### ISSUE TITLE
Do not wrap img in paragraph

### ISSUE THREAD

**Issue by lu-zero** [gettalong/kramdown#98]
Wrapping images in paragraphs is normally less than ideal and short of falling down to html is not possible to use it in kramdown.

**Comment by Fastidious** [comment]
> This is a good idea but it will have to wait for the 2.0.0 release so that existing documents created for 1.x are not affected.

Was this ever done? If so, how to eliminate the `<p>`s around the `<img>`?

**Comment by gettalong** [comment]
Status is "open", so no. And milestone is set to 2.0.0, so again, no, since the current version is 1.9.0.

**Comment by gettalong** [comment]
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1

**Comment by AlexWayfer** [comment]
> Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1

They can be tracked and opened at the same time.

**Comment by cup** [comment]
I agree

**Comment by gettalong** [comment]
Standalone images using the `<figure>` tag will be possible with the next release.

**Comment by bouk** [comment]
For those that want to have standalone images in jekyll, just put this in `_plugins/kramdown-image.rb`:

```ruby
require 'kramdown/converter/html'

module StandaloneImages
  def convert_p(el, indent)
    return super unless el.children.size == 1 && (el.children.first.type == :img || (el.children.first.type == :html_element && el.children.first.value == "img"))
    convert(el.children.first, indent)
  end
end

Kramdown::Converter::Html.prepend StandaloneImages
```

And any `![]()` or `<img` that's on its own line anywhere in your markdown won't be wrapped in a paragraph.
